// modulesLock.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// The module-cache dependency lock (DESIGN-multi-package-modules D5, ruled 2026-09-29).
//
// A dependency converts to the VERSION-FREE `<outRoot>/pkg/<importPath>`, which is correct because
// Go's minimal version selection puts exactly one version of each module in a build. Across
// conversions into one output root, though, nothing recorded WHICH version is there: a second
// module needing another version of the same dependency silently overwrote the first's output,
// leaving every earlier consumer compiled against code it never selected. The lock is that record:
// one line per module-cache dependency converted into the root, and a conversion needing a
// DIFFERENT version of a locked module is refused, naming both, before anything is written.
//
// Only module-cache dependencies are locked. A `replace` onto a local directory has no version to
// record (the directory IS the identity), and the main module is the root, not a dependency.

const modulesLockFileName = "go2cs.modules.lock"

// moduleLockEntry is one locked dependency: the module, the version converted, the main module's
// go.sum hash for it (empty when the go.sum does not list it), and the converter that wrote it.
type moduleLockEntry struct {
	path      string
	version   string
	sum       string
	converter string
}

func modulesLockPath(outRoot string) string {
	return filepath.Join(outRoot, modulesLockFileName)
}

// readModulesLock reads the output root's lock; a root with no lock yet reads as empty.
func readModulesLock(outRoot string) (map[string]moduleLockEntry, error) {
	entries := make(map[string]moduleLockEntry)
	file, err := os.Open(modulesLockPath(outRoot))

	if os.IsNotExist(err) {
		return entries, nil
	}

	if err != nil {
		return nil, err
	}

	defer file.Close()

	scanner := bufio.NewScanner(file)

	for lineNo := 1; scanner.Scan(); lineNo++ {
		line := strings.TrimSpace(scanner.Text())

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)

		if len(fields) != 4 {
			return nil, fmt.Errorf("%s:%d: want `<module> <version> <go.sum hash|-> <converter>`, got %q", modulesLockPath(outRoot), lineNo, line)
		}

		sum := fields[2]

		if sum == "-" {
			sum = ""
		}

		entries[fields[0]] = moduleLockEntry{path: fields[0], version: fields[1], sum: sum, converter: fields[3]}
	}

	return entries, scanner.Err()
}

// writeModulesLock writes the lock sorted by module path, LF-terminated, so the file is stable
// across runs and platforms.
func writeModulesLock(outRoot string, entries map[string]moduleLockEntry) error {
	paths := make([]string, 0, len(entries))

	for path := range entries {
		paths = append(paths, path)
	}

	sort.Strings(paths)

	var lock strings.Builder

	lock.WriteString("# go2cs.modules.lock -- GENERATED by go2cs: one version per module per output root.\n")
	lock.WriteString("# <module> <version> <go.sum h1 hash, or - when the main module's go.sum does not list it> <converter>\n")

	for _, path := range paths {
		entry := entries[path]
		sum := entry.sum

		if sum == "" {
			sum = "-"
		}

		lock.WriteString(fmt.Sprintf("%s %s %s %s\n", entry.path, entry.version, sum, entry.converter))
	}

	if err := os.MkdirAll(outRoot, 0o755); err != nil {
		return err
	}

	return os.WriteFile(modulesLockPath(outRoot), []byte(lock.String()), 0o644)
}

// checkModulesLock refuses a conversion whose dependency versions disagree with the root's lock,
// naming every clash (module, locked version, requested version) and the lock file.
func checkModulesLock(outRoot string, locked map[string]moduleLockEntry, requested map[string]moduleLockEntry) error {
	var clashes []string

	for path, want := range requested {
		if have, ok := locked[path]; ok && have.version != want.version {
			clashes = append(clashes, fmt.Sprintf("  %s: locked at %s, this conversion needs %s", path, have.version, want.version))
		}
	}

	if len(clashes) == 0 {
		return nil
	}

	sort.Strings(clashes)

	return fmt.Errorf("refusing to convert into %s: the output root already holds a different version of %d module(s), "+
		"and its version-free pkg/<import-path> layout can hold only one per module (see %s):\n%s\n"+
		"Convert into a different output root, or remove the root's converted output and its lock first",
		outRoot, len(clashes), modulesLockPath(outRoot), strings.Join(clashes, "\n"))
}

// goSumHashes reads the `<module> <version> h1:...` lines of the main module's go.sum (not the
// `/go.mod` lines), keyed by "module version". A module without a go.sum reads as empty.
func goSumHashes(moduleDir string) map[string]string {
	hashes := make(map[string]string)
	data, err := os.ReadFile(filepath.Join(moduleDir, "go.sum"))

	if err != nil {
		return hashes
	}

	for _, line := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n") {
		fields := strings.Fields(line)

		if len(fields) == 3 && !strings.HasSuffix(fields[1], "/go.mod") {
			hashes[fields[0]+" "+fields[1]] = fields[2]
		}
	}

	return hashes
}

// goModDownloadPreflight runs `go mod download` in the module before anything is loaded, read-only
// against the module's own go.mod and go.sum (-mod=readonly), so a dependency missing from the cache
// or failing verification is ONE refusal naming it, instead of a load warning per package that
// imports it.
func goModDownloadPreflight(moduleDir string) error {
	cmd := exec.Command("go", "mod", "download")
	cmd.Dir = moduleDir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=readonly")

	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("go mod download preflight failed in %s -- a dependency is missing from the module cache "+
			"or fails go.sum verification, and nothing was converted:\n%s", moduleDir, strings.TrimSpace(string(output)))
	}

	return nil
}
