// solutionProjectPaths_test.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package main

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// THE CLASS THIS GUARDS, and it cost a step-5 wall on 2026-09-14.
//
// There are two solution files over one tree and they fail DIFFERENTLY:
//
//	src/go2cs-stdlib.slnx   GENERATED by the converter from the packages it converted, so it HEALS
//	                        ITSELF at the next reconvert -- 14 stale entries vanished at the H5 hop
//	                        without anyone removing them. C2's instrument guards that one.
//	src/go2cs.slnx          HAND-MAINTAINED. Nothing regenerates it, so a package that moves or
//	                        disappears leaves a dangling <Project Path> behind FOREVER.
//
// ⚠ A DANGLING ENTRY IS NOT A COSMETIC DEFECT: the solution does not LOAD. MSBuild fails at
// evaluation with MSB3202 before compiling a single file, so the build that would have reported the
// real state of the tree never runs. That is the shape that hid two stale entries across an entire
// release hop -- `runtime/internal/{math,sys}` moved to `internal/runtime/{math,sys}` and the
// vendored `x/crypto/sha3` package lost its last file, and nothing said so, because the solution
// never loaded far enough to be asked.
//
// ⚠ AND NOTHING ROUTINELY BUILDS THIS SOLUTION (CLAUDE.md's own warning), which is exactly why a
// TEXT guard is the right instrument: it needs no MSBuild, no .NET SDK and no restore, so it runs in
// the plain `go test ./...` every lane already runs, on every platform, including the boxes that
// cannot build the solution at all.
//
// ⚠ HOP-INDEPENDENT. It compares the solution against the working tree beside it and never against a
// Go release or a converted corpus, so it holds on master and on a version branch alike. Measured at
// master: 825 <Project Path> entries, 0 dangling.

// slnxProjectRe captures the path of every <Project Path="..."> entry. Anchored on the ELEMENT and
// not on `Path=` alone: a .slnx also carries <File Path="..."> rows (deploy-core.bat and friends),
// which are not projects and whose absence is not this guard's business.
var slnxProjectRe = regexp.MustCompile(`<Project\s+Path="([^"]+)"`)

// solutionProjectPaths returns every project path the solution names, in file order.
func solutionProjectPaths(slnxPath string) ([]string, error) {
	raw, err := os.ReadFile(slnxPath)
	if err != nil {
		return nil, err
	}
	var paths []string
	for _, m := range slnxProjectRe.FindAllStringSubmatch(string(raw), -1) {
		paths = append(paths, m[1])
	}
	return paths, nil
}

// danglingSolutionProjects returns the entries whose file is not on disk, resolved relative to the
// solution's own directory.
func danglingSolutionProjects(slnxPath string, paths []string) []string {
	base := filepath.Dir(slnxPath)
	var dangling []string
	for _, p := range paths {
		if _, err := os.Stat(filepath.Join(base, filepath.FromSlash(p))); err != nil {
			dangling = append(dangling, p)
		}
	}
	sort.Strings(dangling)
	return dangling
}

// TestSolutionProjectPathsExist is the guard.
func TestSolutionProjectPathsExist(t *testing.T) {
	root := repoRootFromPackageDir(t)
	slnx := filepath.Join(root, "src", "go2cs.slnx")
	if _, err := os.Stat(slnx); err != nil {
		t.Fatalf("hand-maintained solution not found at %s: %v", slnx, err)
	}

	paths, err := solutionProjectPaths(slnx)
	if err != nil {
		t.Fatalf("reading %s: %v", slnx, err)
	}

	// A zero that could not have been anything else is not a measurement: an .slnx whose schema
	// changed, or a regex that stopped matching, reports "no dangling entries" over a file it never
	// read. Both look exactly like a clean solution.
	if len(paths) == 0 {
		t.Fatalf("VACUOUS: %s yielded 0 <Project Path> entries; the guard cannot fail in this state "+
			"— check the .slnx element spelling before believing a clean reading", slnx)
	}
	t.Logf("hand-maintained solution names %d project(s)", len(paths))

	if dangling := danglingSolutionProjects(slnx, paths); len(dangling) > 0 {
		var b strings.Builder
		for _, p := range dangling {
			b.WriteString("\n  " + p)
		}
		t.Fatalf("%d <Project Path> entr(y|ies) in src/go2cs.slnx name a file that does not exist. "+
			"Nothing regenerates this solution, so each one is permanent, and MSBuild fails the whole "+
			"solution at evaluation with MSB3202 before compiling anything — the build that would "+
			"report the real state of the tree never runs:%s", len(dangling), b.String())
	}
}

// TestSolutionProjectPathScannerFiresAndAdmits is the positive control, in BOTH directions.
//
// ⚠ IT PLANTS INTO A COPY, NEVER INTO src/go2cs.slnx. A control that edits the real solution and
// restores it is one interrupted run away from leaving a dangling entry in the tree it guards.
func TestSolutionProjectPathScannerFiresAndAdmits(t *testing.T) {
	dir := t.TempDir()
	live := filepath.Join(dir, "live.csproj")
	if err := os.WriteFile(live, []byte("<Project/>\n"), 0o600); err != nil {
		t.Fatalf("planting a project file: %v", err)
	}

	slnx := filepath.Join(dir, "planted.slnx")
	body := `<Solution>
  <Folder Name="/x/">
    <Project Path="live.csproj" />
    <Project Path="gone/missing.csproj" />
  </Folder>
  <File Path="deploy-core.bat" />
</Solution>
`
	if err := os.WriteFile(slnx, []byte(body), 0o600); err != nil {
		t.Fatalf("planting the solution: %v", err)
	}

	paths, err := solutionProjectPaths(slnx)
	if err != nil {
		t.Fatalf("reading the planted solution: %v", err)
	}

	// The <File> row must NOT be collected: a guard that counts it would report a dangling project
	// for every non-project row the solution legitimately carries.
	if len(paths) != 2 {
		t.Fatalf("expected 2 <Project Path> entries (the <File> row must be skipped), got %d: %v", len(paths), paths)
	}

	dangling := danglingSolutionProjects(slnx, paths)
	if len(dangling) != 1 || dangling[0] != "gone/missing.csproj" {
		t.Fatalf("expected exactly the planted dead entry to fire, got %v", dangling)
	}

	// ADMIT: with the dead entry removed the same scanner must read clean, or "fires" only tells you
	// it refuses everything.
	clean := filepath.Join(dir, "clean.slnx")
	if err := os.WriteFile(clean, []byte("<Solution>\n  <Project Path=\"live.csproj\" />\n</Solution>\n"), 0o600); err != nil {
		t.Fatalf("planting the clean solution: %v", err)
	}
	cleanPaths, err := solutionProjectPaths(clean)
	if err != nil {
		t.Fatalf("reading the clean solution: %v", err)
	}
	if len(cleanPaths) != 1 {
		t.Fatalf("expected 1 entry in the clean plant, got %d", len(cleanPaths))
	}
	if got := danglingSolutionProjects(clean, cleanPaths); len(got) != 0 {
		t.Fatalf("the clean plant must read clean, got %v", got)
	}
}

// TestSolutionProjectPathScannerRefusesAnUnreadableSolution pins the vacuity arm's own trigger: a
// file the regex cannot match must yield ZERO paths, so the refusal above can actually be reached.
// Without this, "0 dangling" and "0 read" are the same reading.
func TestSolutionProjectPathScannerRefusesAnUnreadableSolution(t *testing.T) {
	dir := t.TempDir()
	odd := filepath.Join(dir, "schema-changed.slnx")
	if err := os.WriteFile(odd, []byte("<Solution>\n  <ProjectReference Include=\"x.csproj\" />\n</Solution>\n"), 0o600); err != nil {
		t.Fatalf("planting: %v", err)
	}
	paths, err := solutionProjectPaths(odd)
	if err != nil {
		t.Fatalf("reading: %v", err)
	}
	if len(paths) != 0 {
		t.Fatalf("a solution using a different element must yield 0 paths so the vacuity arm fires, got %d: %v", len(paths), paths)
	}
}
