// stdlibMetadata.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package main

import (
	_ "embed"
	"strings"
	"sync"

	"go2cs/internal/stdlibmeta"
)

//go:generate go run ./internal/genstdlibmeta

// stdLibMetadataAsset is the committed record of every converted standard-library package's
// exported cross-package metadata — the `[assembly: GoTypeAlias(…)]` and
// `[assembly: GoImplement<…>]` lines it publishes in its package_info.cs.
//
// The converter normally reads those lines from the referenced package's package_info.cs in
// the converted-source tree ($(go2csPath)core\<pkg>, staged by deploy-core). Under
// -recurse=nuget there is no converted-source tree at all: the standard library is consumed
// as pre-compiled go.<pkg> NuGet packages. Without these facts the converter cannot tell
// that, say, syscall's own assembly already implements `error` on syscall.Errno, so it
// re-declares the pair locally in the CONSUMING package — and go2cs-gen then generates a
// second, duplicate `syscall_Errnoᴠerror` adapter (CS0102/CS0111/CS8646). The record travels
// with the converter so a NuGet-referencing conversion sees exactly what a source-referencing
// one sees.
//
// Generated by ./internal/genstdlibmeta from src/core — the same tree
// push-nuget.ps1 packs — so the embedded record and the published assemblies are always one
// commit's output. TestStdLibMetadataInSync fails if the two drift.
//
//go:embed stdlib-metadata.txt
var stdLibMetadataAsset string

var (
	stdLibMetadataOnce     sync.Once
	stdLibMetadataSections map[string][]string
)

// stdLibExportedMetadata returns the recorded package_info.cs metadata lines for a converted
// standard-library package, keyed by its dotted name (PackageInfo.PackageName, e.g.
// `math.rand.v2` — also the `go.<name>` NuGet package id). The second result reports whether
// the package is recorded at all; an unrecorded package (a Go release newer than the one this
// converter was built from) falls back to the existing derive-from-declarations path.
func stdLibExportedMetadata(packageName string) ([]string, bool) {
	stdLibMetadataOnce.Do(func() {
		stdLibMetadataSections = parseStdLibMetadata(stdLibMetadataAsset)
	})

	lines, ok := stdLibMetadataSections[packageName]

	return lines, ok
}

// parseStdLibMetadata splits the embedded asset into its per-package sections. A `##<name>`
// line opens a section and runs to the next one; any other line outside a section (the file
// header) is a `#` comment and is ignored.
func parseStdLibMetadata(asset string) map[string][]string {
	sections := map[string][]string{}

	var current string

	for _, line := range strings.Split(asset, "\n") {
		line = strings.TrimRight(line, "\r")

		if after, found := strings.CutPrefix(line, stdlibmeta.SectionPrefix); found {
			current = after
			sections[current] = nil
			continue
		}

		if current == "" || strings.TrimSpace(line) == "" {
			continue
		}

		sections[current] = append(sections[current], line)
	}

	return sections
}
