// xsysDarwinLibc_test.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package main

import (
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/ritchiecarroll/hashset"
)

// golang.org/x/sys/unix reaches libc on darwin in two halves (darwin-xsys-libc, 2026-10-03). The README
// walkthrough's converted app died in fatih/color's type initializer on both mac legs of release-smoke
// 37136808066 with "syscall_syscall: no implementation reached this compilation", raised from
// unix.ioctlPtr. These fixtures are copied from x/sys v0.25.0 (the version fatih/color v1.18.0 pins):
// syscall_darwin_libSystem.go's seven pulls, and one of zsyscall_darwin_arm64.go's 154 address variables
// with the assembly that fills it.
const xsysDarwinLibcFixtureGo = `package main

import (
	"syscall"
	"unsafe"
)

type Errno = syscall.Errno

// Implemented in the runtime package (runtime/sys_darwin.go)
func syscall_syscall(fn, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)
func syscall_syscall6(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
func syscall_syscall6X(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
func syscall_syscall9(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr) (r1, r2 uintptr, err Errno) // 32-bit only
func syscall_rawSyscall(fn, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)
func syscall_rawSyscall6(fn, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
func syscall_syscallPtr(fn, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)

//go:linkname syscall_syscall syscall.syscall
//go:linkname syscall_syscall6 syscall.syscall6
//go:linkname syscall_syscall6X syscall.syscall6X
//go:linkname syscall_syscall9 syscall.syscall9
//go:linkname syscall_rawSyscall syscall.rawSyscall
//go:linkname syscall_rawSyscall6 syscall.rawSyscall6
//go:linkname syscall_syscallPtr syscall.syscallPtr

func ioctlPtr(fd int, req uint, arg unsafe.Pointer) (err error) {
	_, _, e1 := syscall_syscall(libc_ioctl_trampoline_addr, uintptr(fd), uintptr(req), uintptr(arg))
	if e1 != 0 {
		err = e1
	}
	return
}

var libc_ioctl_trampoline_addr uintptr

//go:cgo_import_dynamic libc_ioctl ioctl "/usr/lib/libSystem.B.dylib"

// A variable whose DATA points at a trampoline that does more than jump: no proof, no initializer.
var libc_notjump_trampoline_addr uintptr

//go:cgo_import_dynamic libc_notjump notjump "/usr/lib/libSystem.B.dylib"

// A variable with the assembly but NO pragma: nothing names a symbol, so nothing is resolved.
var libc_nopragma_trampoline_addr uintptr

func main() {
	_ = ioctlPtr(0, 0, nil)
}
`

const xsysDarwinLibcFixtureAsm = `// go run mkasm.go darwin arm64
// Code generated by the command above; DO NOT EDIT.

#include "textflag.h"

TEXT libc_ioctl_trampoline<>(SB),NOSPLIT,$0-0
	JMP	libc_ioctl(SB)
GLOBL	·libc_ioctl_trampoline_addr(SB), RODATA, $8
DATA	·libc_ioctl_trampoline_addr(SB)/8, $libc_ioctl_trampoline<>(SB)

TEXT libc_notjump_trampoline<>(SB),NOSPLIT,$0-0
	MOVD	R0, R1
	JMP	libc_notjump(SB)
GLOBL	·libc_notjump_trampoline_addr(SB), RODATA, $8
DATA	·libc_notjump_trampoline_addr(SB)/8, $libc_notjump_trampoline<>(SB)

TEXT libc_nopragma_trampoline<>(SB),NOSPLIT,$0-0
	JMP	libc_nopragma(SB)
GLOBL	·libc_nopragma_trampoline_addr(SB), RODATA, $8
DATA	·libc_nopragma_trampoline_addr(SB)/8, $libc_nopragma_trampoline<>(SB)
`

// xsysDarwinTwins is the expected forward for each pull: the public syscall twin that is the same libc
// call under the same failure rule in the darwin flavor (syscall_darwin_impl.cs).
var xsysDarwinTwins = map[string]string{
	"syscall_syscall":     "Syscall",
	"syscall_syscall6":    "Syscall6",
	"syscall_syscall6X":   "GoSyscall6X",
	"syscall_syscall9":    "Syscall9",
	"syscall_rawSyscall":  "RawSyscall",
	"syscall_rawSyscall6": "RawSyscall6",
	"syscall_syscallPtr":  "GoSyscallPtr",
}

// TestXSysDarwinLibcPullsForwardToTwins drives the recognizer over the seven pulls as x/sys declares
// them, under x/sys's own package path and its vendored copy's, and refuses them anywhere else:
// internal/syscall/unix declares five of the same pulls and answers them with its hand-owned
// net_darwin_impl.cs, which a forwarder would duplicate.
func TestXSysDarwinLibcPullsForwardToTwins(t *testing.T) {
	file, err := parser.ParseFile(token.NewFileSet(), "syscall_darwin_libSystem.go", xsysDarwinLibcFixtureGo, parser.ParseComments)

	if err != nil {
		t.Fatal(err)
	}

	// The directives sit in a block of their own after the declarations, exactly as x/sys writes them, so
	// no declaration's doc comment carries its directive: the recognizer must find it in the file.
	decls := map[string]*ast.FuncDecl{}

	for _, d := range file.Decls {
		if funcDecl, isFunc := d.(*ast.FuncDecl); isFunc && funcDecl.Body == nil {
			decls[funcDecl.Name.Name] = funcDecl
		}
	}

	saved, savedPulls := currentPackagePath, linknamePullDirectives
	defer func() { currentPackagePath, linknamePullDirectives = saved, savedPulls }()

	// The package-wide pre-pass records the directives, wherever they sit.
	linknamePullDirectives = nil
	collectLinknameHandles([]*ast.File{file})

	for _, pkgPath := range []string{"golang.org/x/sys/unix", "vendor/golang.org/x/sys/cpu"} {
		currentPackagePath = pkgPath

		for local, twin := range xsysDarwinTwins {
			v := &Visitor{importQueue: hashset.HashSet[string]{}, importPathAliases: map[string]string{"syscall": "syscall"}}
			alias, targetFunc, ok := v.funcLinknameForward(decls[local])

			if !ok {
				t.Errorf("%s: %s does not forward; it converts to a throwing stub (the walkthrough's darwin death)", pkgPath, local)
				continue
			}

			if alias != "syscall" || targetFunc != twin {
				t.Errorf("%s: %s forwards to %s.%s, want syscall.%s", pkgPath, local, alias, targetFunc, twin)
			}
		}
	}

	// The control: the same declarations in internal/syscall/unix must NOT forward.
	currentPackagePath = "internal/syscall/unix"

	for local := range xsysDarwinTwins {
		v := &Visitor{importQueue: hashset.HashSet[string]{}, importPathAliases: map[string]string{"syscall": "syscall"}}

		if _, _, ok := v.funcLinknameForward(decls[local]); ok {
			t.Errorf("internal/syscall/unix: %s forwards, which would duplicate net_darwin_impl.cs's hand-owned body", local)
		}
	}
}

// TestParseAsmTrampolineAddrs reads the DATA proof: a variable binds to the libc local its trampoline
// jumps to only when the trampoline's ONLY instruction is that jump.
func TestParseAsmTrampolineAddrs(t *testing.T) {
	got := parseAsmTrampolineAddrs(xsysDarwinLibcFixtureAsm)

	if got["libc_ioctl_trampoline_addr"] != "libc_ioctl" {
		t.Errorf("libc_ioctl_trampoline_addr binds to %q, want libc_ioctl (all: %v)", got["libc_ioctl_trampoline_addr"], got)
	}

	if local, bound := got["libc_notjump_trampoline_addr"]; bound {
		t.Errorf("libc_notjump_trampoline_addr bound to %q, but its trampoline does more than jump", local)
	}

	if got["libc_nopragma_trampoline_addr"] != "libc_nopragma" {
		t.Errorf("libc_nopragma_trampoline_addr binds to %q, want libc_nopragma (the asm proof alone; the pragma is checked at emission)", got["libc_nopragma_trampoline_addr"])
	}

	// The vendored x/sys/cpu in GOROOT carries the same shape: the real file must bind both of its variables.
	goRoot := build.Default.GOROOT

	if goRoot == "" {
		goRoot = runtime.GOROOT()
	}

	if goRoot != "" {
		path := filepath.Join(goRoot, "src", "vendor", "golang.org", "x", "sys", "cpu", "syscall_darwin_x86_gc.s")

		if content, err := os.ReadFile(path); err == nil {
			real := parseAsmTrampolineAddrs(string(content))

			for _, name := range []string{"libc_sysctl_trampoline_addr", "libc_sysctlbyname_trampoline_addr"} {
				if real[name] != strings.TrimSuffix(name, "_trampoline_addr") {
					t.Errorf("GOROOT %s: %s binds to %q, want %s", path, name, real[name], strings.TrimSuffix(name, "_trampoline_addr"))
				}
			}
		}
	}
}

// TestXSysDarwinLibcEmission drives the conversion of the fixture for darwin/arm64 under x/sys's module
// path: the pull emits a forwarder to syscall's public twin, the proven variable an initializer that
// resolves its symbol, and the two unproven variables stay bare fields.
func TestXSysDarwinLibcEmission(t *testing.T) {
	root := t.TempDir()
	appDir := filepath.Join(root, "app")

	writeModuleFile(t, filepath.Join(appDir, "go.mod"), "module golang.org/x/sys\n\ngo 1.23\n")
	writeModuleFile(t, filepath.Join(appDir, "main.go"), xsysDarwinLibcFixtureGo)
	writeModuleFile(t, filepath.Join(appDir, "zsyscall_darwin_arm64.s"), xsysDarwinLibcFixtureAsm)

	goRoot := build.Default.GOROOT

	if goRoot == "" {
		goRoot = runtime.GOROOT()
	}

	options := Options{
		goRoot:              goRoot,
		goPath:              build.Default.GOPATH,
		go2csPath:           filepath.Join(root, "out"),
		recurse:             true,
		targetPlatform:      "darwin/arm64",
		indentSpaces:        4,
		preferVarDecl:       true,
		useChannelOperators: true,
	}

	build.Default.GOROOT = options.goRoot
	build.Default.GOPATH = options.goPath

	if err := NewModuleConverter(options).ConvertModule(appDir); err != nil {
		t.Fatalf("ConvertModule: %v", err)
	}

	mainCs := strings.ReplaceAll(readGenerated(t, filepath.Join(options.go2csPath, "src", "golang.org", "x", "sys", "main.cs")), "\r\n", "\n")

	if forwarder := emittedFunction(t, mainCs, "syscall_syscall"); !strings.Contains(forwarder, "syscall.Syscall(") {
		t.Errorf("syscall_syscall is not a forwarder to syscall.Syscall:\n%s", forwarder)
	}

	resolve := `global::go.GoCgoDynamicImports.ResolveOrZero("ioctl", "/usr/lib/libSystem.B.dylib")`

	if !strings.Contains(mainCs, "libc_ioctl_trampoline_addr = (uintptr)"+resolve+";") {
		t.Errorf("libc_ioctl_trampoline_addr has no resolving initializer (want = (uintptr)%s):\n%s", resolve, fieldLine(mainCs, "libc_ioctl_trampoline_addr"))
	}

	for _, name := range []string{"libc_notjump_trampoline_addr", "libc_nopragma_trampoline_addr"} {
		if line := fieldLine(mainCs, name); strings.Contains(line, "ResolveOrZero") {
			t.Errorf("%s is unproven, yet it resolves: %s", name, line)
		}
	}
}

// fieldLine returns the emitted line declaring the named static field, or "" when there is none.
func fieldLine(cs string, name string) string {
	for _, line := range strings.Split(cs, "\n") {
		if strings.Contains(line, " static ") && strings.Contains(line, " "+name) && !strings.HasPrefix(strings.TrimSpace(line), "//") {
			return line
		}
	}

	return ""
}
