import io, sys, time
NL = chr(10)
M = "~/.claude/projects/C--Projects-go2cs/memory/"
tip, old = sys.argv[1], sys.argv[2]
t = time.strftime('%H:%M')
L = M + "train14-seat-ledger.md"; g = io.open(L, encoding='utf-8', newline='').read()
g += NL + "**" + t + " SUB-Q43 COMPLETE (a5833d1bd; claude/sub-q43 733f8a5e9, 2 files: CENSUS-runtime-pprof-doors.md + pprof go2cs_test_disclosures.json; markers 0; census 0):** runtime/pprof 2 -> 147 verdicts, 120 agreeing, 48 s; host-fatal 7 entries (6 crashes + 1 HANG TestGoroutineProfileLabelRace); P1/P2/P4 met, P3 wrong in the good direction (matched 120 vs 35, stub 2 vs 60); CPU-profile class = 13 rows ONE root getg (A/B proven). RULED (posted " + tip + "): seventh entry RATIFIED; class definition amended crash-or-hang + retirement trigger as a 2nd commit (fresh SHA announce-then-push) -> seat train 27 as SUBQ43 (SHA pending); Q51 queued (runtime/pprof BANK after Q47+Q44). C2's Q49 diff READ (4c0bc1cce): wrapper 22/23/21 (10/12/10 predicted + 9 alias-retained + 3 FromBox), darwin funnel 116+12 vs 101+1 (instrument spelling blindness; converter predicate go/types), third funnel package macos, placement fix (drain after every stmt; for-clause refused; literal isolation), footprint 14 files +152 KeepAlives by hunk; CNR running; ACCEPTED -> seat train 27 on announce." + NL
io.open(L, 'w', encoding='utf-8', newline='').write(g)
D = M + "doctrine-batch3-accumulator.md"; d = io.open(D, encoding='utf-8', newline='').read()
d += NL + "495. (C2, 2026-09-05, Q49) A census of an emitted SPELLING under-reports by every spelling it did not enumerate -- FromPinnedBox( counted, FromBox( (the reference-bearing spelling, exactly the token-route boxes where retention matters most) and pointer-typed VARIABLES invisible -- while the converter's own predicate is go/types' and reached them all: the alias-census rule one spelling over, and a guard that shares the census's blind spot (ARM 3 keyed on the same spellings) is not a second derivation." + NL
d += "496. (C2, 2026-09-05, instrument) A two-seeded diff NAMES the toolchain that built EACH arm (`go version <binary>`): a `go build` in a shell without the GOROOT pin stamped one arm go1.24.7 against the other's go1.23.12, caught only by byte-comparing a pinned rebuild against the running binary. And `setsid nohup ... &` leaves `$!` naming the setsid parent -- pid-record a detached run from inside (`echo $$; exec`), and kill by exact `bash <path>` excluding `$$`." + NL
d += "497. (SUB-Q43 + COORD, 2026-09-05) The host-fatal class is crash OR deadline-consuming HANG -- both lose every test after the member in its phase -- and a widening of a ruled class is asked, not assumed; an entry states a fact about TODAY's host and carries its own retirement trigger. Companion: a package priced 'mostly stub' from its names read mostly MATCHED once run (120 vs 35) -- the phantom-divergence shape; and thirteen rows can be ONE root when the package's own ordering leaks a flag (StartCPUProfile sets cpu.profiling before the throw), proven by skipping one test and watching exactly one row move." + NL
io.open(D, 'w', encoding='utf-8', newline='').write(d)
H = M + "coordinator-handoff-state.md"; h = io.open(H, encoding='utf-8', newline='').read()
io.open(H, 'w', encoding='utf-8', newline='').write(h.replace(old, tip))
print("ledger + doctrine 495-497 + anchor ->", tip)
