#!/bin/bash
# coord-train30-union-rebaseline.sh -- AFTER train 30's chain has ENDED (no live chain): re-baseline CompositeLiteralElements' golden from the sixteen-seat union converter,
# commit it on the assembly head as a UNION commit, then re-run CNR and the filtered runner. Justification measured 16:59 in the dry-run: Compile PASS, Output 1 compared / 0 failed; only Target failed (golden).
set -u
S=/c/Projects/go2cs/.claude/coord-scripts; SC=$HOME/AppData/Local/Temp/claude/C--Projects-go2cs--claude-worktrees-go2cs-fleet-train-19-7d1cc7/388822cf-bade-49e8-96a9-7ab378101ad4/scratchpad
W=/c/Projects/go2cs/.claude/worktrees/musing-moser-d4552c; cd $W || exit 2
chains=$(powershell -NoProfile -Command "(Get-CimInstance Win32_Process | Where-Object { \$_.CommandLine -like '*coord-train30-assemble.sh*' -and \$_.Name -eq 'bash.exe' -and \$_.CommandLine -notlike '*Get-CimInstance*' }).Count"); [ "$chains" = 0 ] || { echo "chain still alive ($chains) -- the worktree is frozen; not touching it"; exit 1; }
[ "$(git status --porcelain | wc -l)" = 0 ] || { echo "worktree dirty -- read before re-baselining"; git status --porcelain | head; exit 1; }
export GOROOT='$HOME\sdk\go1.23.12' DOTNET_ROOT='$HOME\dotnet10' MSBUILDDISABLENODEREUSE=1; export PATH="$HOME/sdk/go1.23.12/bin:$HOME/dotnet10:$PATH"
go version | grep -q go1.23.12 || { echo "GO PIN FAILED"; exit 1; }
cd $W/src/tests/Behavioral && powershell -NoProfile -ExecutionPolicy Bypass -File ./run-behavioral.ps1 --filter CompositeLiteralElements --update-targets > $SC/coord-t30-cle-rebaseline.log 2>&1; rc=$?
grep -aE 'Transpile|Compile|Target|Output|PASS|FAIL' $SC/coord-t30-cle-rebaseline.log | tail -7 | cut -c1-160
cd $W; echo "changed: $(git status --porcelain | tr '\n' ' ')"; n=$(git status --porcelain | wc -l)
[ "$n" -ge 1 ] && [ "$n" -le 2 ] && git status --porcelain | grep -qE 'CompositeLiteralElements/main\.cs(\.target)?$' || { echo "unexpected change set -- not committing"; exit 1; }
git diff --stat | tail -2; echo "stamp lines added: $(git diff | grep -c '^+.*GoArrayDims(2, 3)')"
git add src/tests/Behavioral/CompositeLiteralElements/main.cs src/tests/Behavioral/CompositeLiteralElements/main.cs.target
git commit -S -q -m "train 30 union: CompositeLiteralElements golden re-baselined from the sixteen-seat converter -- 'type nn [2][3]int' gains [GoArrayDims(2, 3)] on its wrapper, R's union read (f0fc24836): ONE rule fires, SUB-Q60's namedArrayElemDimsAttr in visitArrayType, when goArrayDims(underlying) returns more than one dimension -- a named array whose element is an unnamed fixed array -- and R's 7g arm (visitTypeSpec's StarExpr case, nilArrayPtrDims) cannot fire on an ArrayType at all; the stamp is the FIX for a measured defect (Q60's own record shows `var d nn` printing `2 0 [[] []]` where Go prints `2 3 [[0 0 0] [0 0 0]]`), and the one interaction is benign (7g's GoReflect.TypeStampedDims now fills a named nested array's descriptor dims from Q60's stamp, agreeing with ArrayDimsOfValue, the stamp-decides refusal silent). Q60's stdlib-scoped census (zero of 59 wrappers) could not see a shape that lives only in a behavioral guard. Q73 CLOSED by measurement (17:21): SUB-Q60's exact converter, built at 16d1943ac in scratch, emits this guard byte-identical to the committed 124 lines -- no nn struct at all, so no stamp -- and main.go differs between 16d1943ac and b91684991 by +93/-9: SUB-Q57's rows exercising nn (588a01aaa, train 29). Both seats' CNRs were honest; the second input is new SOURCE, not a second rule -- Q57's rows make the struct exist and Q60's rule stamps it -- and this union is the first tree holding both. Measured before re-baselining (dry-run at the union, 16:59): Transpile PASS, Compile PASS, Output 1 compared / 0 failed vs go run, Target the only failure (the golden). A golden is the converter's emission and no lane owns it; the union commit carries it.

Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>" && echo "COMMITTED $(git rev-parse --short=9 HEAD)"
if [ "${SKIP_CNR:-0}" = "1" ]; then echo "=== CNR re-run SKIPPED by flag (the re-battery runs it as leg 1 at the final tree)"; exit 0; fi
echo "=== CNR re-run"; powershell -NoProfile -ExecutionPolicy Bypass -File $W/src/tests/Behavioral/check-no-regression.ps1 > $SC/coord-t30-cnr-rerun.log 2>&1; c=$?; grep -aE 'NO REGRESSION|CHANGED|NOT MEASURED|byte-identical|skipped' $SC/coord-t30-cnr-rerun.log | tail -3 | cut -c1-200; echo "CNR rerun exit=$c"; git checkout -q -- src/tests/Behavioral 2>/dev/null; echo "worktree dirty after: $(git status --porcelain | wc -l)"; exit $c
