// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go.text;

partial class template_internal_test_package {
    static template_internal_test_package() {
        initᴛtVal();
        initᴛiVal();
        initᴛexecTests();
        initᴛmultiExecTests();
    }
} // end template_internal_test_package
