// GoWrapperAttribute.cs - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// Use of this source code is governed by an MIT-style license
// that can be found in the LICENSE file.

using System;

namespace go;

/// <summary>
/// Marks a converted lambda that stands where Go's compiler emits an autogenerated WRAPPER: a method
/// expression the converter renders as a lambda (<c>I.M</c> on an interface, and <c>(*T).M</c> for a
/// value-receiver method), carrying the wrapper's Go name.
/// </summary>
/// <remarks>
/// <para>
/// Go names such a wrapper after the method expression (<c>runtime_test.I.M</c>,
/// <c>runtime_test.(*structWithMethod).nop</c>) and reports its position as <c>&lt;autogenerated&gt;:1</c>.
/// The runtime's frame naming reads <see cref="GoName"/> from the lambda's generated method, which is
/// what <c>Delegate.Method</c> returns, so a PC for the value (<c>reflect.ValueOf(I.M).Pointer()</c>)
/// resolves to Go's name.
/// </para>
/// <para>
/// Go ELIDES a wrapper frame from a traceback when the wrapper called an ordinary function, and keeps
/// it when its callee is the panic machinery (gopanic, sigpanic, panicwrap). A live walk only ever
/// sees the first case, so runtime.Callers skips a marked frame. This differs from
/// <see cref="GoTwinForwarderAttribute"/>, whose lambda is go2cs machinery and has no Go frame at all.
/// </para>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, Inherited = false)]
public sealed class GoWrapperAttribute(string goName, string? packagePath = null) : Attribute
{
    /// <summary>The wrapper's Go name within its package: <c>I.M</c> or <c>(*T).M</c>.</summary>
    public string GoName { get; } = goName;

    /// <summary>
    /// The import path of the package that declares the receiver type, where Go places the wrapper, or
    /// <c>null</c> when it is the package the lambda is emitted in.
    /// </summary>
    public string? PackagePath { get; } = packagePath;
}
