// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// This file implements a custom generator to create various go/types
// source files from the corresponding types2 files.
namespace go.go;

using bytes = bytes_package;
using flag = flag_package;
using fmt = fmt_package;
using ast = global::go.go.ast_package;
using format = global::go.go.format_package;
using parser = global::go.go.parser_package;
using token = global::go.go.token_package;
using diff = global::go.@internal.diff_package;
using os = os_package;
using filepath = global::go.path.filepath_package;
using runtime = runtime_package;
using strings = strings_package;
using testing = testing_package;
using fs = io.fs_package;
using global::go.@internal;
using global::go.go;
using global::go.path;
using io = io_package;
using static global::go.go.types_internal_test_package;
using ꓸꓸꓸstring = Span<@string>;

partial class types_test_package {

internal static ж<@string> filesToWrite = flag.String("write"u8, ""u8, @"go/types files to generate, or ""all"" for all files"u8);

internal static readonly @string srcDir = "/src/cmd/compile/internal/types2/"u8;
internal static readonly @string dstDir = "/src/go/types/"u8;

// TestGenerate verifies that generated files in go/types match their types2
// counterpart. If -write is set, this test actually writes the expected
// content to go/types; otherwise, it just compares with the existing content.
public static void TestGenerate(ж<testing.T> Ꮡt) {
    // If filesToWrite is set, write the generated content to disk.
    // In the special case of "all", write all files in filemap.
    var write = filesToWrite.Value != ""u8;
    slice<@string> files = default!;             // files to process
    if (filesToWrite.Value != ""u8 && filesToWrite.Value != "all"u8){
        files = strings.Split(filesToWrite.Value, ","u8);
    } else {
        foreach (var (@file, _) in filemap) {
            files = append(files, @file);
        }
    }
    foreach (var (_, filename) in files) {
        generate(Ꮡt, filename, write);
    }
}

internal static void generate(ж<testing.T> Ꮡt, @string filename, bool write) {
    // parse src (cmd/compile/internal/types2)
    @string srcFilename = filepath.FromSlash(runtime.GOROOT() + srcDir + filename);
    var (@file, err) = parser.ParseFile(fset, srcFilename, default!, parser.ParseComments);
    if (err != default!) {
        Ꮡt.Fatal(err);
    }
    // fix package name
    @file.Value.Name.Value.Name = strings.ReplaceAll((~(~@file).Name).Name, types2ˢ, typesˢ);
    // rewrite AST as needed
    {
        var action = filemap[filename]; if (action != default!) {
            action(@file);
        }
    }
    // format AST
    ref var buf = ref heap(new bytes.Buffer(), out var Ꮡbuf);
    var (rel, _) = filepath.Rel(dstDir, srcDir);
    fmt.Fprintf(new types_test_package.bytes_BufferжWriter(Ꮡbuf), "// Code generated by \"go test -run=Generate -write=all\"; DO NOT EDIT.\n"u8);
    fmt.Fprintf(new types_test_package.bytes_BufferжWriter(Ꮡbuf), "// Source: %s/%s\n\n"u8, filepath.ToSlash(rel), filename);
    {
        var errΔ1 = format.Node(new types_test_package.bytes_BufferжWriter(Ꮡbuf), fset, @file.OrTypedNil()); if (errΔ1 != default!) {
            Ꮡt.Fatal(errΔ1);
        }
    }
    var generatedContent = buf.Bytes();
    // read dst (go/types)
    @string dstFilename = filepath.FromSlash(runtime.GOROOT() + dstDir + filename);
    (var onDiskContent, err) = os.ReadFile(dstFilename);
    if (err != default!) {
        Ꮡt.Fatalf("reading %q: %v"u8, filename, err);
    }
    // compare on-disk dst with buffer generated from src.
    {
        var d = diff.Diff(filename + " (on disk in "u8 + dstDir + ")"u8, onDiskContent, filename + " (generated from "u8 + srcDir + ")"u8, generatedContent); if (d != default!) {
            if (write){
                Ꮡt.Logf("applying change:\n%s"u8, d);
                {
                    var errΔ2 = os.WriteFile(dstFilename, generatedContent, 420); if (errΔ2 != default!) {
                        Ꮡt.Fatalf("writing %q: %v"u8, filename, errΔ2);
                    }
                }
            } else {
                Ꮡt.Errorf("file on disk in %s is stale:\n%s"u8, dstDir, d);
            }
        }
    }
}

// type action is a methodless func type — rendered inline as its base delegate

// must happen before renaming identifiers
// must happen before renaming identifiers
// "initorder.go": fixErrErrorfCall, // disabled for now due to unresolved error_ use implications for gopls
// must happen before renaming identifiers
// TODO(gri) needs adjustments for TestObjectString - disabled for now
// "object_test.go": func(f *ast.File) { renameImportPath(f, `"cmd/compile/internal/types2"->"go/types"`) },
// must happen before renaming identifiers
// must happen before renaming identifiers
internal static map<@string, Action<ж<ast.File>>> filemap = new map<@string, Action<ж<ast.File>>>{
    ["alias.go"u8] = fixTokenPos,
    ["assignments.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8);
        renameSelectorExprs(f, "syntax.Name->ast.Ident"u8, "ident.Value->ident.Name", "ast.Pos->token.Pos");
        renameIdents(f, "syntax->ast"u8, "poser->positioner", "nopos->noposn");
    },
    ["array.go"u8] = default!,
    ["api_predicates.go"u8] = default!,
    ["basic.go"u8] = default!,
    ["builtins.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8);
        renameIdents(f, "syntax->ast"u8);
        renameSelectors(f, "ArgList->Args"u8);
        fixSelValue(f);
        fixAtPosCall(f);
    },
    ["builtins_test.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8, @"""cmd/compile/internal/types2""->""go/types""");
        renameSelectorExprs(f, "syntax.Name->ast.Ident"u8, "p.Value->p.Name");
        renameIdents(f, "syntax->ast"u8);
    },
    ["chan.go"u8] = default!,
    ["const.go"u8] = fixTokenPos,
    ["context.go"u8] = default!,
    ["context_test.go"u8] = default!,
    ["conversions.go"u8] = default!,
    ["errors_test.go"u8] = (ж<ast.File> f) => {
        renameIdents(f, "nopos->noposn"u8);
    },
    ["errsupport.go"u8] = default!,
    ["gccgosizes.go"u8] = default!,
    ["gcsizes.go"u8] = (ж<ast.File> f) => {
        renameIdents(f, "IsSyncAtomicAlign64->_IsSyncAtomicAlign64"u8);
    },
    ["hilbert_test.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/types2""->""go/types"""u8);
    },
    ["infer.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        fixInferSig(f);
    },
    ["initorder.go"u8] = default!,
    ["instantiate.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        fixCheckErrorfCall(f);
    },
    ["instantiate_test.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/types2""->""go/types"""u8);
    },
    ["literals.go"u8] = (ж<ast.File> f) => {
        insertImportPath(f, @"""go/token"""u8);
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8);
        renameSelectorExprs(f,
            "syntax.IntLit->token.INT"u8, "syntax.FloatLit->token.FLOAT", "syntax.ImagLit->token.IMAG",
            "syntax.Name->ast.Ident", "key.Value->key.Name", "atyp.Elem->atyp.Elt");
        renameIdents(f, "syntax->ast"u8);
        renameSelectors(f, "ElemList->Elts"u8);
    },
    ["lookup.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
    },
    ["main_test.go"u8] = default!,
    ["map.go"u8] = default!,
    ["mono.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        insertImportPath(f, @"""go/ast"""u8);
        renameSelectorExprs(f, "syntax.Expr->ast.Expr"u8);
    },
    ["named.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameSelectors(f, "Trace->_Trace"u8);
    },
    ["object.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameIdents(f, "NewTypeNameLazy->_NewTypeNameLazy"u8);
    },
    ["objset.go"u8] = default!,
    ["operand.go"u8] = (ж<ast.File> f) => {
        insertImportPath(f, @"""go/token"""u8);
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8);
        renameSelectorExprs(f,
            "syntax.Pos->token.Pos"u8, "syntax.LitKind->token.Token",
            "syntax.IntLit->token.INT", "syntax.FloatLit->token.FLOAT",
            "syntax.ImagLit->token.IMAG", "syntax.RuneLit->token.CHAR",
            "syntax.StringLit->token.STRING");
        renameIdents(f, "syntax->ast"u8);
    },
    ["package.go"u8] = default!,
    ["pointer.go"u8] = default!,
    ["predicates.go"u8] = default!,
    ["recording.go"u8] = (ж<ast.File> f) => {
        renameImportPath(f, @"""cmd/compile/internal/syntax""->""go/ast"""u8);
        renameSelectorExprs(f, "syntax.Name->ast.Ident"u8);
        renameIdents(f, "syntax->ast"u8);
        fixAtPosCall(f);
    },
    ["scope.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameIdents(f, "InsertLazy->_InsertLazy"u8);
    },
    ["selection.go"u8] = default!,
    ["sizes.go"u8] = (ж<ast.File> f) => {
        renameIdents(f, "IsSyncAtomicAlign64->_IsSyncAtomicAlign64"u8);
    },
    ["slice.go"u8] = default!,
    ["subst.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameSelectors(f, "Trace->_Trace"u8);
    },
    ["termlist.go"u8] = default!,
    ["termlist_test.go"u8] = default!,
    ["tuple.go"u8] = default!,
    ["typelists.go"u8] = default!,
    ["typeset.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameSelectors(f, "Trace->_Trace"u8);
    },
    ["typeparam.go"u8] = default!,
    ["typeterm_test.go"u8] = default!,
    ["typeterm.go"u8] = default!,
    ["typestring.go"u8] = default!,
    ["under.go"u8] = default!,
    ["unify.go"u8] = fixSprintf,
    ["universe.go"u8] = fixGlobalTypVarDecl,
    ["util_test.go"u8] = fixTokenPos,
    ["validtype.go"u8] = (ж<ast.File> f) => {
        fixTokenPos(f);
        renameSelectors(f, "Trace->_Trace"u8);
    }
};

[GoType("map[@string, @string]")] partial struct renameMap;

// TODO(gri) We should be able to make these rewriters more configurable/composable.
//           For now this is a good starting point.

// makeRenameMap returns a renameMap populates from renames entries of the form "from->to".
internal static renameMap makeRenameMap(params ꓸꓸꓸstring renamesʗp) {
    var renames = renamesʗp.sslice();

    var m = new renameMap(0);
    foreach (var (_, r) in renames) {
        var s = strings.Split(r, "->"u8);
        if (len(s) != 2) {
            throw panic("invalid rename entry: " + r);
        }
        m[s[0]] = s[1];
    }
    return m;
}

// rename renames the given string s if a corresponding rename exists in m.
internal static void rename(this renameMap m, ж<@string> Ꮡs) {
    ref var s = ref Ꮡs.DerefOrNull();

    {
        var (r, ok) = m[s, ꟷ]; if (ok) {
            s = r;
        }
    }
}

// renameSel renames a selector expression of the form a.x to b.x (where a, b are identifiers)
// if m contains the ("a.x" : "b.y") key-value pair.
internal static void renameSel(this renameMap m, ж<ast.SelectorExpr> Ꮡn) {
    ref var n = ref Ꮡn.DerefOrNull();

    {
        var (a, _) = n.X._<ж<ast.Ident>>(ᐧ); if (a != nil) {
            @string a_x = (~a).Name + "."u8 + (~n.Sel).Name;
            {
                var (r, ok) = m[a_x, ꟷ]; if (ok) {
                    var b_y = strings.Split(r, "."u8);
                    if (len(b_y) != 2) {
                        throw panic("invalid selector expression: " + r);
                    }
                    a.Value.Name = b_y[0];
                    n.Sel.Value.Name = b_y[1];
                }
            }
        }
    }
}

// renameIdents renames identifiers: each renames entry is of the form "from->to".
// Note: This doesn't change the use of the identifiers in comments.
internal static void renameIdents(ж<ast.File> Ꮡf, params ꓸꓸꓸstring renamesʗp) {
    var renames = renamesʗp.sslice();

    var m = makeRenameMap(renames.ꓸꓸꓸ);
    var mʗ1 = m;
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.Ident> nΔ1: {
            mʗ1.rename(nΔ1.of(ast.Ident.ᏑName));
            return false;
        }}
        return true;
    });
}

// renameSelectors is like renameIdents but only looks at selectors.
internal static void renameSelectors(ж<ast.File> Ꮡf, params ꓸꓸꓸstring renamesʗp) {
    var renames = renamesʗp.sslice();

    var m = makeRenameMap(renames.ꓸꓸꓸ);
    var mʗ1 = m;
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.SelectorExpr> nΔ1: {
            mʗ1.rename((~nΔ1).Sel.of(ast.Ident.ᏑName));
            return false;
        }}
        return true;
    });
}

// renameSelectorExprs is like renameIdents but only looks at selector expressions.
// Each renames entry must be of the form "x.a->y.b".
internal static void renameSelectorExprs(ж<ast.File> Ꮡf, params ꓸꓸꓸstring renamesʗp) {
    var renames = renamesʗp.sslice();

    var m = makeRenameMap(renames.ꓸꓸꓸ);
    var mʗ1 = m;
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.SelectorExpr> nΔ1: {
            mʗ1.renameSel(nΔ1);
            return false;
        }}
        return true;
    });
}

// renameImportPath is like renameIdents but renames import paths.
internal static void renameImportPath(ж<ast.File> Ꮡf, params ꓸꓸꓸstring renamesʗp) {
    var renames = renamesʗp.sslice();

    var m = makeRenameMap(renames.ꓸꓸꓸ);
    var mʗ1 = m;
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.ImportSpec> nΔ1: {
            if ((~(~nΔ1).Path).Kind != token.STRING) {
                throw panic("invalid import path");
            }
            mʗ1.rename((~nΔ1).Path.of(ast.BasicLit.ᏑValue));
            return false;
        }}
        return true;
    });
}

// insertImportPath inserts the given import path.
// There must be at least one import declaration present already.
internal static void insertImportPath(ж<ast.File> Ꮡf, @string path) {
    ref var f = ref Ꮡf.DerefOrNull();

    foreach (var (_, d) in f.Decls) {
        {
            var (g, _) = d._<ж<ast.GenDecl>>(ᐧ); if (g != nil && (~g).Tok == token.IMPORT) {
                g.Value.Specs = append((~g).Specs, (ast.Spec)(new ast.ImportSpecжSpec(Ꮡ(new ast.ImportSpec(Path: Ꮡ(new ast.BasicLit(ValuePos: g.End(), Kind: token.STRING, Value: path)))))));
                return;
            }
        }
    }
    throw panic("no import declaration present");
}

// fixTokenPos changes imports of "cmd/compile/internal/syntax" to "go/token",
// uses of syntax.Pos to token.Pos, and calls to x.IsKnown() to x.IsValid().
internal static void fixTokenPos(ж<ast.File> Ꮡf) {
    var m = makeRenameMap(@"""cmd/compile/internal/syntax""->""go/token"""u8, "syntax.Pos->token.Pos", "IsKnown->IsValid");
    var mʗ1 = m;
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.ImportSpec> nΔ1: {
            if ((~(~nΔ1).Path).Kind != token.STRING) {
                // rewrite import path "cmd/compile/internal/syntax" to "go/token"
                throw panic("invalid import path");
            }
            mʗ1.rename((~nΔ1).Path.of(ast.BasicLit.ᏑValue));
            return false;
        }
        case ж<ast.SelectorExpr> nΔ1: {
            mʗ1.renameSel(nΔ1);
            break;
        }
        case ж<ast.CallExpr> nΔ1: {
            {
                var (fun, _) = (~nΔ1).Fun._<ж<ast.SelectorExpr>>(ᐧ); if (fun != nil && len((~nΔ1).Args) == 0) {
                    // rewrite syntax.Pos to token.Pos
                    // rewrite x.IsKnown() to x.IsValid()
                    mʗ1.rename((~fun).Sel.of(ast.Ident.ᏑName));
                    return false;
                }
            }
            break;
        }}
        return true;
    });
}

// fixSelValue updates the selector x.Sel.Value to x.Sel.Name.
internal static void fixSelValue(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.SelectorExpr> nΔ1: {
            if ((~(~nΔ1).Sel).Name == "Value"u8) {
                {
                    var (selx, _) = (~nΔ1).X._<ж<ast.SelectorExpr>>(ᐧ); if (selx != nil && (~(~selx).Sel).Name == "Sel"u8) {
                        nΔ1.Value.Sel.Value.Name = "Name"u8;
                        return false;
                    }
                }
            }
            break;
        }}
        return true;
    });
}

// fixInferSig updates the Checker.infer signature to use a positioner instead of a token.Position
// as first argument, renames the argument from "pos" to "posn", and updates a few internal uses of
// "pos" to "posn" and "posn.Pos()" respectively.
internal static void fixInferSig(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.FuncDecl> nΔ1: {
            if ((~(~nΔ1).Name).Name == "infer"u8) {
                // rewrite (pos token.Pos, ...) to (posn positioner, ...)
                var par = (~(~(~nΔ1).Type).Params).List[0];
                if (len((~par).Names) == 1 && (~(~par).Names[0]).Name == "pos"u8) {
                    par.Value.Names[0] = newIdent((~par).Names[0].Pos(), "posn"u8);
                    par.Value.Type = new ast.IdentжExpr(newIdent((~par).Type.Pos(), "positioner"u8));
                    return true;
                }
            }
            break;
        }
        case ж<ast.CallExpr> nΔ1: {
            {
                var (selx, _) = (~nΔ1).Fun._<ж<ast.SelectorExpr>>(ᐧ); if (selx != nil) {
                    var exprᴛ1 = (~(~selx).Sel).Name;
                    if (exprᴛ1 == "renameTParams"u8) {
                        if (isIdent((~nΔ1).Args[0], // rewrite check.renameTParams(pos, ... ) to check.renameTParams(posn.Pos(), ... )
 "pos"u8)) {
                            ref var pos = ref heap<tokenꓸPos>(out var Ꮡpos);
                            pos = (~nΔ1).Args[0].Pos();
                            var fun = Ꮡ(new ast.SelectorExpr(X: new ast.IdentжExpr(newIdent(pos, "posn"u8)), Sel: newIdent(pos, "Pos"u8)));
                            var arg = Ꮡ(new ast.CallExpr(Fun: new ast.SelectorExprжExpr(fun), Lparen: pos, Args: default!, Ellipsis: token.NoPos, Rparen: pos));
                            nΔ1.Value.Args[0] = new ast.CallExprжExpr(arg);
                            return false;
                        }
                    }
                    else if (exprᴛ1 == "addf"u8) {
                        if (isIdent((~nΔ1).Args[0], // rewrite err.addf(pos, ...) to err.addf(posn, ...)
 "pos"u8)) {
                            tokenꓸPos pos = (~nΔ1).Args[0].Pos();
                            var arg = newIdent(pos, "posn"u8);
                            nΔ1.Value.Args[0] = new ast.IdentжExpr(arg);
                            return false;
                        }
                    }
                    else if (exprᴛ1 == "allowVersion"u8) {
                        if (isIdent((~nΔ1).Args[0], // rewrite check.allowVersion(pos, ...) to check.allowVersion(posn, ...)
 "pos"u8)) {
                            tokenꓸPos pos = (~nΔ1).Args[0].Pos();
                            var arg = newIdent(pos, "posn"u8);
                            nΔ1.Value.Args[0] = new ast.IdentжExpr(arg);
                            return false;
                        }
                    }

                }
            }
            break;
        }}
        return true;
    });
}

// fixAtPosCall updates calls of the form atPos(x) to x.Pos() in argument lists of (check).dump calls.
// TODO(gri) can we avoid this and just use atPos consistently in go/types and types2?
internal static void fixAtPosCall(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.CallExpr> nΔ1: {
            {
                var (selx, _) = (~nΔ1).Fun._<ж<ast.SelectorExpr>>(ᐧ); if (selx != nil && (~(~selx).Sel).Name == "dump"u8) {
                    foreach (var (i, arg) in (~nΔ1).Args) {
                        {
                            var (call, _) = arg._<ж<ast.CallExpr>>(ᐧ); if (call != nil) {
                                // rewrite xxx.dump(..., atPos(x), ...) to xxx.dump(..., x.Pos(), ...)
                                if (isIdent((~call).Fun, "atPos"u8)) {
                                    ref var pos = ref heap<tokenꓸPos>(out var Ꮡpos);
                                    pos = (~call).Args[0].Pos();
                                    var fun = Ꮡ(new ast.SelectorExpr(X: (~call).Args[0], Sel: newIdent(pos, "Pos"u8)));
                                    nΔ1.Value.Args[i] = new ast.CallExprжExpr(Ꮡ(new ast.CallExpr(Fun: new ast.SelectorExprжExpr(fun), Lparen: pos, Rparen: pos)));
                                    return false;
                                }
                            }
                        }
                    }
                }
            }
            break;
        }}
        return true;
    });
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string errˢ = "err"u8;
internal static readonly @string posˢ = "Pos"u8;

// fixErrErrorfCall updates calls of the form err.addf(obj, ...) to err.addf(obj.Pos(), ...).
internal static void fixErrErrorfCall(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.CallExpr> nΔ1: {
            {
                var (selx, _) = (~nΔ1).Fun._<ж<ast.SelectorExpr>>(ᐧ); if (selx != nil) {
                    if (isIdent((~selx).X, errˢ)) {
                        var exprᴛ1 = (~(~selx).Sel).Name;
                        if (exprᴛ1 == "errorf"u8) {
                            {
                                var (ident, _) = (~nΔ1).Args[0]._<ж<ast.Ident>>(ᐧ); if (ident != nil && (~ident).Name == "obj"u8) {
                                    // rewrite err.addf(obj, ... ) to err.addf(obj.Pos(), ... )
                                    ref var pos = ref heap<tokenꓸPos>(out var Ꮡpos);
                                    pos = (~nΔ1).Args[0].Pos();
                                    var fun = Ꮡ(new ast.SelectorExpr(X: new ast.IdentжExpr(ident), Sel: newIdent(pos, posˢ)));
                                    nΔ1.Value.Args[0] = new ast.CallExprжExpr(Ꮡ(new ast.CallExpr(Fun: new ast.SelectorExprжExpr(fun), Lparen: pos, Rparen: pos)));
                                    return false;
                                }
                            }
                        }

                    }
                }
            }
            break;
        }}
        return true;
    });
}

// fixCheckErrorfCall updates calls of the form check.errorf(pos, ...) to check.errorf(atPos(pos), ...).
internal static void fixCheckErrorfCall(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.CallExpr> nΔ1: {
            {
                var (selx, _) = (~nΔ1).Fun._<ж<ast.SelectorExpr>>(ᐧ); if (selx != nil) {
                    if (isIdent((~selx).X, "check"u8)) {
                        var exprᴛ1 = (~(~selx).Sel).Name;
                        if (exprᴛ1 == "errorf"u8) {
                            {
                                var ident = asIdent((~nΔ1).Args[0], // rewrite check.errorf(pos, ... ) to check.errorf(atPos(pos), ... )
 "pos"u8); if (ident != nil) {
                                    ref var pos = ref heap<tokenꓸPos>(out var Ꮡpos);
                                    pos = (~nΔ1).Args[0].Pos();
                                    var fun = newIdent(pos, "atPos"u8);
                                    nΔ1.Value.Args[0] = new ast.CallExprжExpr(Ꮡ(new ast.CallExpr(Fun: new ast.IdentжExpr(fun), Lparen: pos, Args: new ast.Expr[]{new ast.IdentжExpr(ident)}.slice(), Rparen: pos)));
                                    return false;
                                }
                            }
                        }

                    }
                }
            }
            break;
        }}
        return true;
    });
}

// fixGlobalTypVarDecl changes the global Typ variable from an array to a slice
// (in types2 we use an array for efficiency, in go/types it's a slice and we
// cannot change that).
internal static void fixGlobalTypVarDecl(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.ValueSpec> nΔ1: {
            if (len((~nΔ1).Names) == 1 && (~(~nΔ1).Names[0]).Name == "Typ"u8 && len((~nΔ1).Values) == 1) {
                // rewrite type Typ = [...]Type{...} to type Typ = []Type{...}
                (~(~nΔ1).Values[0]._<ж<ast.CompositeLit>>()).Type._<ж<ast.ArrayType>>().Value.Len = default!;
                return false;
            }
            break;
        }}
        return true;
    });
}

// fixSprintf adds an extra nil argument for the *token.FileSet parameter in sprintf calls.
internal static void fixSprintf(ж<ast.File> Ꮡf) {
    ast.Inspect(new ast.FileжNode(Ꮡf), (ast.Node n) => {
        switch (n.type()) {
        case ж<ast.CallExpr> nΔ1: {
            if (isIdent((~nΔ1).Fun, "sprintf"u8) && len((~nΔ1).Args) >= 4) {
                /* ... args */
                nΔ1.Value.Args = insert((~nΔ1).Args, 1, new ast.IdentжExpr(newIdent((~nΔ1).Args[1].Pos(), "nil"u8)));
                return false;
            }
            break;
        }}
        return true;
    });
}

// asIdent returns x as *ast.Ident if it is an identifier with the given name.
internal static ж<ast.Ident> asIdent(ast.Node x, @string name) {
    {
        var (ident, _) = x._<ж<ast.Ident>>(ᐧ); if (ident != nil && (~ident).Name == name) {
            return ident;
        }
    }
    return default!;
}

// isIdent reports whether x is an identifier with the given name.
internal static bool isIdent(ast.Node x, @string name) {
    return asIdent(x, name) != nil;
}

// newIdent returns a new identifier with the given position and name.
internal static ж<ast.Ident> newIdent(tokenꓸPos pos, @string name) {
    var id = ast.NewIdent(name);
    id.Value.NamePos = pos;
    return id;
}

// insert inserts x at list[at] and moves the remaining elements up.
internal static slice<ast.Expr> insert(slice<ast.Expr> list, nint at, ast.Expr x) {
    list = append(list, (ast.Expr)(default!));
    copy(list.slice(at + 1), list.slice(at));
    list[at] = x;
    return list;
}

} // end types_test_package
