// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/termlist_test.go
// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.go;

using strings = strings_package;
using testing = testing_package;
using static global::go.go.types_package;

partial class types_internal_test_package {

// maketl makes a term list from a string of the term list.
internal static global::go.go.types_package.termlist maketl(@string s) {
    s = strings.ReplaceAll(s, " "u8, ""u8);
    var names = strings.Split(s, "|"u8);
    var r = new global::go.go.types_package.termlist(len(names));
    foreach (var (i, n) in names) {
        r[i] = testTerm(n);
    }
    return r;
}

public static void TestTermlistAll(ж<testing.T> Ꮡt) {
    if (!allTermlist.isAll()) {
        Ꮡt.Errorf("allTermlist is not the set of all types"u8);
    }
}

public static void TestTermlistString(ж<testing.T> Ꮡt) {
    foreach (var (_, want) in new @string[]{
        "∅"u8,
        "𝓤"u8,
        "int"u8,
        "~int"u8,
        "myInt"u8,
        "∅ | ∅"u8,
        "𝓤 | 𝓤"u8,
        "∅ | 𝓤 | int"u8,
        "∅ | 𝓤 | int | myInt"u8
    }.slice()) {
        {
            @string got = maketl(want).String(); if (got != want) {
                Ꮡt.Errorf("(%v).String() == %v"u8, want, got);
            }
        }
    }
}

public static void TestTermlistIsEmpty(ж<testing.T> Ꮡt) {
    foreach (var (test, want) in new map<@string, bool>{
        ["∅"u8] = true,
        ["∅ | ∅"u8] = true,
        ["∅ | ∅ | 𝓤"u8] = false,
        ["∅ | ∅ | myInt"u8] = false,
        ["𝓤"u8] = false,
        ["𝓤 | int"u8] = false,
        ["𝓤 | myInt | ∅"u8] = false
    }) {
        var xl = maketl(test);
        var got = xl.isEmpty();
        if (got != want) {
            Ꮡt.Errorf("(%v).isEmpty() == %v; want %v"u8, test, got, want);
        }
    }
}

public static void TestTermlistIsAll(ж<testing.T> Ꮡt) {
    foreach (var (test, want) in new map<@string, bool>{
        ["∅"u8] = false,
        ["∅ | ∅"u8] = false,
        ["int | ~string"u8] = false,
        ["~int | myInt"u8] = false,
        ["∅ | ∅ | 𝓤"u8] = true,
        ["𝓤"u8] = true,
        ["𝓤 | int"u8] = true,
        ["myInt | 𝓤"u8] = true
    }) {
        var xl = maketl(test);
        var got = xl.isAll();
        if (got != want) {
            Ꮡt.Errorf("(%v).isAll() == %v; want %v"u8, test, got, want);
        }
    }
}

internal partial struct TestTermlistNorm_type /*dyn*/ {
    internal @string xl, want;
}

public static void TestTermlistNorm(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistNorm_type[]{
        new("∅"u8, "∅"u8),
        new("∅ | ∅"u8, "∅"u8),
        new("∅ | int"u8, "int"u8),
        new("∅ | myInt"u8, "myInt"u8),
        new("𝓤 | int"u8, "𝓤"u8),
        new("𝓤 | myInt"u8, "𝓤"u8),
        new("int | myInt"u8, "int | myInt"u8),
        new("~int | int"u8, "~int"u8),
        new("~int | myInt"u8, "~int"u8),
        new("int | ~string | int"u8, "int | ~string"u8),
        new("~int | string | 𝓤 | ~string | int"u8, "𝓤"u8),
        new("~int | string | myInt | ~string | int"u8, "~int | ~string"u8)
    }.slice()) {
        var xl = maketl(test.xl);
        var got = maketl(test.xl).norm();
        if (got.String() != test.want) {
            Ꮡt.Errorf("(%v).norm() = %v; want %v"u8, xl, got, test.want);
        }
    }
}

internal partial struct TestTermlistUnion_type /*dyn*/ {
    internal @string xl, yl, want;
}

public static void TestTermlistUnion(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistUnion_type[]{
        new("∅"u8, "∅"u8, "∅"u8),
        new("∅"u8, "𝓤"u8, "𝓤"u8),
        new("∅"u8, "int"u8, "int"u8),
        new("𝓤"u8, "~int"u8, "𝓤"u8),
        new("int"u8, "~int"u8, "~int"u8),
        new("int"u8, "string"u8, "int | string"u8),
        new("int"u8, "myInt"u8, "int | myInt"u8),
        new("~int"u8, "myInt"u8, "~int"u8),
        new("int | string"u8, "~string"u8, "int | ~string"u8),
        new("~int | string"u8, "~string | int"u8, "~int | ~string"u8),
        new("~int | string | ∅"u8, "~string | int"u8, "~int | ~string"u8),
        new("~int | myInt | ∅"u8, "~string | int"u8, "~int | ~string"u8),
        new("~int | string | 𝓤"u8, "~string | int"u8, "𝓤"u8),
        new("~int | string | myInt"u8, "~string | int"u8, "~int | ~string"u8)
    }.slice()) {
        var xl = maketl(test.xl);
        var yl = maketl(test.yl);
        @string got = xl.union(yl).String();
        if (got != test.want) {
            Ꮡt.Errorf("(%v).union(%v) = %v; want %v"u8, test.xl, test.yl, got, test.want);
        }
    }
}

internal partial struct TestTermlistIntersect_type /*dyn*/ {
    internal @string xl, yl, want;
}

public static void TestTermlistIntersect(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistIntersect_type[]{
        new("∅"u8, "∅"u8, "∅"u8),
        new("∅"u8, "𝓤"u8, "∅"u8),
        new("∅"u8, "int"u8, "∅"u8),
        new("∅"u8, "myInt"u8, "∅"u8),
        new("𝓤"u8, "~int"u8, "~int"u8),
        new("𝓤"u8, "myInt"u8, "myInt"u8),
        new("int"u8, "~int"u8, "int"u8),
        new("int"u8, "string"u8, "∅"u8),
        new("int"u8, "myInt"u8, "∅"u8),
        new("~int"u8, "myInt"u8, "myInt"u8),
        new("int | string"u8, "~string"u8, "string"u8),
        new("~int | string"u8, "~string | int"u8, "int | string"u8),
        new("~int | string | ∅"u8, "~string | int"u8, "int | string"u8),
        new("~int | myInt | ∅"u8, "~string | int"u8, "int"u8),
        new("~int | string | 𝓤"u8, "~string | int"u8, "int | ~string"u8),
        new("~int | string | myInt"u8, "~string | int"u8, "int | string"u8)
    }.slice()) {
        var xl = maketl(test.xl);
        var yl = maketl(test.yl);
        @string got = xl.intersect(yl).String();
        if (got != test.want) {
            Ꮡt.Errorf("(%v).intersect(%v) = %v; want %v"u8, test.xl, test.yl, got, test.want);
        }
    }
}

internal partial struct TestTermlistEqual_type /*dyn*/ {
    internal @string xl, yl;
    internal bool want;
}

public static void TestTermlistEqual(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistEqual_type[]{
        new("∅"u8, "∅"u8, true),
        new("∅"u8, "𝓤"u8, false),
        new("𝓤"u8, "𝓤"u8, true),
        new("𝓤 | int"u8, "𝓤"u8, true),
        new("𝓤 | int"u8, "string | 𝓤"u8, true),
        new("𝓤 | myInt"u8, "string | 𝓤"u8, true),
        new("int | ~string"u8, "string | int"u8, false),
        new("~int | string"u8, "string | myInt"u8, false),
        new("int | ~string | ∅"u8, "string | int | ~string"u8, true)
    }.slice()) {
        var xl = maketl(test.xl);
        var yl = maketl(test.yl);
        var got = xl.equal(yl);
        if (got != test.want) {
            Ꮡt.Errorf("(%v).equal(%v) = %v; want %v"u8, test.xl, test.yl, got, test.want);
        }
    }
}

internal partial struct TestTermlistIncludes_type /*dyn*/ {
    internal @string xl, typ;
    internal bool want;
}

public static void TestTermlistIncludes(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistIncludes_type[]{
        new("∅"u8, "int"u8, false),
        new("𝓤"u8, "int"u8, true),
        new("~int"u8, "int"u8, true),
        new("int"u8, "string"u8, false),
        new("~int"u8, "string"u8, false),
        new("~int"u8, "myInt"u8, true),
        new("int | string"u8, "string"u8, true),
        new("~int | string"u8, "int"u8, true),
        new("~int | string"u8, "myInt"u8, true),
        new("~int | myInt | ∅"u8, "myInt"u8, true),
        new("myInt | ∅ | 𝓤"u8, "int"u8, true)
    }.slice()) {
        var xl = maketl(test.xl);
        var yl = testTerm(test.typ).Value.typ;
        var got = xl.includes(yl);
        if (got != test.want) {
            Ꮡt.Errorf("(%v).includes(%v) = %v; want %v"u8, test.xl, yl, got, test.want);
        }
    }
}

internal partial struct TestTermlistSupersetOf_type /*dyn*/ {
    internal @string xl, typ;
    internal bool want;
}

public static void TestTermlistSupersetOf(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistSupersetOf_type[]{
        new("∅"u8, "∅"u8, true),
        new("∅"u8, "𝓤"u8, false),
        new("∅"u8, "int"u8, false),
        new("𝓤"u8, "∅"u8, true),
        new("𝓤"u8, "𝓤"u8, true),
        new("𝓤"u8, "int"u8, true),
        new("𝓤"u8, "~int"u8, true),
        new("𝓤"u8, "myInt"u8, true),
        new("~int"u8, "int"u8, true),
        new("~int"u8, "~int"u8, true),
        new("~int"u8, "myInt"u8, true),
        new("int"u8, "~int"u8, false),
        new("myInt"u8, "~int"u8, false),
        new("int"u8, "string"u8, false),
        new("~int"u8, "string"u8, false),
        new("int | string"u8, "string"u8, true),
        new("int | string"u8, "~string"u8, false),
        new("~int | string"u8, "int"u8, true),
        new("~int | string"u8, "myInt"u8, true),
        new("~int | string | ∅"u8, "string"u8, true),
        new("~string | ∅ | 𝓤"u8, "myInt"u8, true)
    }.slice()) {
        var xl = maketl(test.xl);
        var y = testTerm(test.typ);
        var got = xl.supersetOf(y);
        if (got != test.want) {
            Ꮡt.Errorf("(%v).supersetOf(%v) = %v; want %v"u8, test.xl, y.OrTypedNil(), got, test.want);
        }
    }
}

internal partial struct TestTermlistSubsetOf_type /*dyn*/ {
    internal @string xl, yl;
    internal bool want;
}

public static void TestTermlistSubsetOf(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in new TestTermlistSubsetOf_type[]{
        new("∅"u8, "∅"u8, true),
        new("∅"u8, "𝓤"u8, true),
        new("𝓤"u8, "∅"u8, false),
        new("𝓤"u8, "𝓤"u8, true),
        new("int"u8, "int | string"u8, true),
        new("~int"u8, "int | string"u8, false),
        new("~int"u8, "myInt | string"u8, false),
        new("myInt"u8, "~int | string"u8, true),
        new("~int"u8, "string | string | int | ~int"u8, true),
        new("myInt"u8, "string | string | ~int"u8, true),
        new("int | string"u8, "string"u8, false),
        new("int | string"u8, "string | int"u8, true),
        new("int | ~string"u8, "string | int"u8, false),
        new("myInt | ~string"u8, "string | int | 𝓤"u8, true),
        new("int | ~string"u8, "string | int | ∅ | string"u8, false),
        new("int | myInt"u8, "string | ~int | ∅ | string"u8, true)
    }.slice()) {
        var xl = maketl(test.xl);
        var yl = maketl(test.yl);
        var got = xl.subsetOf(yl);
        if (got != test.want) {
            Ꮡt.Errorf("(%v).subsetOf(%v) = %v; want %v"u8, test.xl, test.yl, got, test.want);
        }
    }
}

} // end types_internal_test_package
