// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/typestring.go
// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// This file implements printing of types.
namespace go.go;

using bytes = bytes_package;
using fmt = fmt_package;
using slices = slices_package;
using strconv = strconv_package;
using strings = strings_package;
using utf8 = global::go.unicode.utf8_package;
using global::go.unicode;
using token = global::go.go.token_package;

partial class types_package {

// type Qualifier is a methodless func type — rendered inline as its base delegate

// RelativeTo returns a [Qualifier] that fully qualifies members of
// all packages other than pkg.
public static Func<ж<Package>, @string> RelativeTo(ж<Package> Ꮡpkg) {
    if (Ꮡpkg == nil) {
        return default!;
    }
    return (ж<Package> other) => {
        if (Ꮡpkg == other) {
            return ""u8; // same package; unqualified
        }
        return other.Path();
    };
}

// TypeString returns the string representation of typ.
// The [Qualifier] controls the printing of
// package-level objects, and may be nil.
public static @string TypeString(ΔType typ, Func<ж<Package>, @string> qf) {
    ref var buf = ref heap(new bytes.Buffer(), out var Ꮡbuf);
    WriteType(Ꮡbuf, typ, qf);
    return Ꮡbuf.String();
}

// WriteType writes the string representation of typ to buf.
// The [Qualifier] controls the printing of
// package-level objects, and may be nil.
public static void WriteType(ж<bytes.Buffer> Ꮡbuf, ΔType typ, Func<ж<Package>, @string> qf) {
    newTypeWriter(Ꮡbuf, qf).typ(typ);
}

// WriteSignature writes the representation of the signature sig to buf,
// without a leading "func" keyword. The [Qualifier] controls the printing
// of package-level objects, and may be nil.
public static void WriteSignature(ж<bytes.Buffer> Ꮡbuf, ж<ΔSignature> Ꮡsig, Func<ж<Package>, @string> qf) {
    newTypeWriter(Ꮡbuf, qf).signature(Ꮡsig);
}

[GoType] partial struct typeWriter {
    internal ж<bytes.Buffer> buf;
    internal map<ΔType, bool> seen;
    internal Func<ж<Package>, @string> qf;
    internal ж<Context> ctxt;    // if non-nil, we are type hashing
    internal ж<TypeParamList> tparams; // local type parameters
    internal bool paramNames;           // if set, write function parameter names, otherwise, write types only
    internal bool tpSubscripts;           // if set, write type parameter indices as subscripts
    internal bool pkgInfo;           // package-annotate first unexported-type field to avoid confusing type description
}

internal static ж<typeWriter> newTypeWriter(ж<bytes.Buffer> Ꮡbuf, Func<ж<Package>, @string> qf) {
    return Ꮡ(new typeWriter(Ꮡbuf, new map<ΔType, bool>(), qf, nil, nil, true, false, false));
}

internal static ж<typeWriter> newTypeHasher(ж<bytes.Buffer> Ꮡbuf, ж<Context> Ꮡctxt) {
    assert(Ꮡctxt != nil);
    return Ꮡ(new typeWriter(Ꮡbuf, new map<ΔType, bool>(), default!, Ꮡctxt, nil, false, false, false));
}

[GoRecv] internal static void @byte(this ref typeWriter w, byte b) {
    if (w.ctxt != nil) {
        if (b == (rune)' ') {
            b = (rune)'#';
        }
        w.buf.WriteByte(b);
        return;
    }
    w.buf.WriteByte(b);
    if (b == (rune)',' || b == (rune)';') {
        w.buf.WriteByte((rune)' ');
    }
}

[GoRecv] internal static void @string(this ref typeWriter w, @string s) {
    w.buf.WriteString(s);
}

[GoRecv] internal static void error(this ref typeWriter w, @string msg) {
    if (w.ctxt != nil) {
        throw panic(msg);
    }
    w.buf.WriteString("<"u8 + msg + ">"u8);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string packageˢ = " /* package "u8;
internal static readonly @string emptyUnionˢ = "empty union"u8;
internal static readonly @string anyˢ = "any"u8;
internal static readonly @string interfaceComparableˢ = "interface{comparable}"u8;
internal static readonly @string implicitˢ = "/* implicit */ "u8;
internal static readonly @string unknownChannelDirectionˢ = "unknown channel direction"u8;
internal static readonly @string unnamedTypeParameterˢ = "unnamed type parameter"u8;
internal static readonly @string typeParameterˢ2 = "/* type parameter */"u8;

internal static void typ(this ж<typeWriter> Ꮡw, ΔType typ) {
    GoFrame ᒐ = default;
    try {
        ref var w = ref Ꮡw.DerefOrNull();

        if (w.seen[typ]) {
            w.error("cycle to "u8 + goTypeName(typ));
            return;
        }
        w.seen[typ] = true;
        defer((ᴛ1, ᴛ2) => delete(ᴛ1, ᴛ2), Ꮡw.Value.seen, typ, ref ᒐ);
        switch (typ.type()) {
        case null: {
            w.error(nilˢ2);
            break;
        }
        case ж<Basic> t: {
            if (isExported((~t).name)) {
                // exported basic types go into package unsafe
                // (currently this is just unsafe.Pointer)
                {
                    var (obj, _) = (~Unsafe).scope.Lookup((~t).name)._<ж<TypeName>>(ᐧ); if (obj != nil) {
                        w.typeName(obj);
                        break;
                    }
                }
            }
            w.@string((~t).name);
            break;
        }
        case ж<Array> t: {
            w.@byte((rune)'[');
            w.@string(strconv.FormatInt((~t).len, 10));
            w.@byte((rune)']');
            Ꮡw.typ((~t).elem);
            break;
        }
        case ж<Slice> t: {
            w.@string("[]"u8);
            Ꮡw.typ((~t).elem);
            break;
        }
        case ж<Struct> t: {
            w.@string(structˢ);
            foreach (var (i, f) in (~t).fields) {
                if (i > 0) {
                    w.@byte((rune)';');
                }
                // If disambiguating one struct for another, look for the first unexported field.
                // Do this first in case of nested structs; tag the first-outermost field.
                var pkgAnnotate = false;
                if (w.qf == default! && w.pkgInfo && !isExported((~f).name)) {
                    // note for embedded types, type name is field name, and "string" etc are lower case hence unexported.
                    pkgAnnotate = true;
                    w.pkgInfo = false; // only tag once
                }
                // This doesn't do the right thing for embedded type
                // aliases where we should print the alias name, not
                // the aliased type (see go.dev/issue/44410).
                if (!(~f).embedded) {
                    w.@string((~f).name);
                    w.@byte((rune)' ');
                }
                Ꮡw.typ((~f).typ);
                if (pkgAnnotate) {
                    w.@string(packageˢ);
                    w.@string((~f).pkg.Path());
                    w.@string(" */ "u8);
                }
                {
                    @string tag = t.Tag(i); if (tag != ""u8) {
                        w.@byte((rune)' ');
                        // TODO(gri) If tag contains blanks, replacing them with '#'
                        //           in Context.TypeHash may produce another tag
                        //           accidentally.
                        w.@string(strconv.Quote(tag));
                    }
                }
            }
            w.@byte((rune)'}');
            break;
        }
        case ж<Pointer> t: {
            w.@byte((rune)'*');
            Ꮡw.typ((~t).@base);
            break;
        }
        case ж<Tuple> t: {
            Ꮡw.tuple(t, false);
            break;
        }
        case ж<ΔSignature> t: {
            w.@string(funcˢ);
            Ꮡw.signature(t);
            break;
        }
        case ж<Union> t: {
            if (t.Len() == 0) {
                // Unions only appear as (syntactic) embedded elements
                // in interfaces and syntactically cannot be empty.
                w.error(emptyUnionˢ);
                break;
            }
            foreach (var (i, tΔ1) in (~t).terms) {
                if (i > 0) {
                    w.@string(termSep);
                }
                if ((~tΔ1).tilde) {
                    w.@byte((rune)'~');
                }
                Ꮡw.typ((~tΔ1).typ);
            }
            break;
        }
        case ж<Interface> t: {
            if (w.ctxt == nil) {
                if (AreEqual(t, universeAnyAlias.of(TypeName.Ꮡobject).Type().Underlying())) {
                    // When not hashing, we can try to improve type strings by writing "any"
                    // for a type that is pointer-identical to universeAny.
                    // TODO(rfindley): this logic should not be necessary with
                    // gotypesalias=1. Remove once that is always the case.
                    w.@string(anyˢ);
                    break;
                }
                if (AreEqual(t, (~asNamed(universeComparable.Type())).underlying)) {
                    w.@string(interfaceComparableˢ);
                    break;
                }
            }
            if ((~t).@implicit) {
                if (len((~t).methods) == 0 && len((~t).embeddeds) == 1) {
                    Ꮡw.typ((~t).embeddeds[0]);
                    break;
                }
                // Something's wrong with the implicit interface.
                // Print it as such and continue.
                w.@string(implicitˢ);
            }
            w.@string(interfaceˢ);
            var first = true;
            if (w.ctxt != nil){
                Ꮡw.typeSet(t.typeSet());
            } else {
                foreach (var (_, m) in (~t).methods) {
                    if (!first) {
                        w.@byte((rune)';');
                    }
                    first = false;
                    w.@string((~m).name);
                    Ꮡw.signature((~m).typ._<ж<ΔSignature>>());
                }
                foreach (var (_, typΔ1) in (~t).embeddeds) {
                    if (!first) {
                        w.@byte((rune)';');
                    }
                    first = false;
                    Ꮡw.typ(typΔ1);
                }
            }
            w.@byte((rune)'}');
            break;
        }
        case ж<Map> t: {
            w.@string(mapˢ);
            Ꮡw.typ((~t).key);
            w.@byte((rune)']');
            Ꮡw.typ((~t).elem);
            break;
        }
        case ж<Chan> t: {
            @string s = default!;
            bool parens = default!;
            var exprᴛ1 = (~t).dir;
            if (exprᴛ1 == SendRecv) {
                s = chanˢ3;
                {
                    var (c, _) = (~t).elem._<ж<Chan>>(ᐧ); if (c != nil && (~c).dir == RecvOnly) {
                        // chan (<-chan T) requires parentheses
                        parens = true;
                    }
                }
            }
            else if (exprᴛ1 == SendOnly) {
                s = chanˢ;
            }
            else if (exprᴛ1 == RecvOnly) {
                s = chanˢ2;
            }
            else { /* default: */
                w.error(unknownChannelDirectionˢ);
            }

            w.@string(s);
            if (parens) {
                w.@byte((rune)'(');
            }
            Ꮡw.typ((~t).elem);
            if (parens) {
                w.@byte((rune)')');
            }
            break;
        }
        case ж<Named> t: {
            if (w.ctxt != nil) {
                // If hashing, write a unique prefix for t to represent its identity, since
                // named type identity is pointer identity.
                w.@string(strconv.Itoa(w.ctxt.getID(new NamedжΔType(t))));
            }
            w.typeName((~t).obj); // when hashing written for readability of the hash only
            if ((~t).inst != nil){
                // instantiated type
                Ꮡw.typeList((~(~t).inst).targs.list());
            } else 
            if (w.ctxt == nil && t.TypeParams().Len() != 0) {
                // For type hashing, don't need to format the TypeParams
                // parameterized type
                Ꮡw.tParamList(t.TypeParams().list());
            }
            break;
        }
        case ж<TypeParam> t: {
            if ((~t).obj == nil) {
                w.error(unnamedTypeParameterˢ);
                break;
            }
            {
                nint i = slices.Index(w.tparams.list(), t); if (i >= 0){
                    // The names of type parameters that are declared by the type being
                    // hashed are not part of the type identity. Replace them with a
                    // placeholder indicating their index.
                    w.@string(fmt.Sprintf("$%d"u8, i));
                } else {
                    w.@string((~(~t).obj).name);
                    if (w.tpSubscripts || w.ctxt != nil) {
                        w.@string(subscript((~t).id));
                    }
                    // If the type parameter name is the same as a predeclared object
                    // (say int), point out where it is declared to avoid confusing
                    // error messages. This doesn't need to be super-elegant; we just
                    // need a clear indication that this is not a predeclared name.
                    if (w.ctxt == nil && Universe.Lookup((~(~t).obj).name) != default!) {
                        if (isTypes2){
                            w.@string(fmt.Sprintf(" /* with %s declared at %v */"u8, (~(~t).obj).name, (~t).obj.of(TypeName.Ꮡobject).Pos()));
                        } else {
                            // Can't print position information because
                            // we don't have a token.FileSet accessible.
                            w.@string(typeParameterˢ2);
                        }
                    }
                }
            }
            break;
        }
        case ж<Alias> t: {
            w.typeName((~t).obj);
            {
                var list = (~t).targs.list(); if (len(list) != 0){
                    // instantiated type
                    Ꮡw.typeList(list);
                } else 
                if (w.ctxt == nil && t.TypeParams().Len() != 0) {
                    // For type hashing, don't need to format the TypeParams
                    // parameterized type
                    Ꮡw.tParamList(t.TypeParams().list());
                }
            }
            if (w.ctxt != nil) {
                // TODO(gri) do we need to print the alias type name, too?
                Ꮡw.typ(Unalias((~(~t).obj).typ));
            }
            break;
        }
        default: {
            var t = typ;
            w.@string(t.String());
            break;
        }}
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
}

// For externally defined implementations of Type.
// Note: In this case cycles won't be caught.

// typeSet writes a canonical hash for an interface type set.
internal static void typeSet(this ж<typeWriter> Ꮡw, ж<_TypeSet> Ꮡs) {
    ref var w = ref Ꮡw.DerefOrNull();
    ref var s = ref Ꮡs.DerefOrNull();

    assert(w.ctxt != nil);
    var first = true;
    foreach (var (_, m) in s.methods) {
        if (!first) {
            w.@byte((rune)';');
        }
        first = false;
        w.@string((~m).name);
        Ꮡw.signature((~m).typ._<ж<ΔSignature>>());
    }
    switch (ᐧ) {
    case {} when s.terms.isAll(): {
        break;
    }
    case {} when s.terms.isEmpty(): {
        w.@string(s.terms.String());
        break;
    }
    default: {
// nothing to do
        slice<@string> termHashes = default!;
        foreach (var (_, Δterm) in s.terms) {
            // terms are not canonically sorted, so we sort their hashes instead.
            ref var buf = ref heap(new bytes.Buffer(), out var Ꮡbuf);
            if ((~Δterm).tilde) {
                buf.WriteByte((rune)'~');
            }
            newTypeHasher(Ꮡbuf, w.ctxt).typ((~Δterm).typ);
            termHashes = append(termHashes, Ꮡbuf.String());
        }
        slices.Sort<slice<@string>, @string>(termHashes);
        if (!first) {
            w.@byte((rune)';');
        }
        w.@string(strings.Join(termHashes, "|"u8));
        break;
    }}

}

internal static void typeList(this ж<typeWriter> Ꮡw, slice<ΔType> list) {
    ref var w = ref Ꮡw.DerefOrNull();

    w.@byte((rune)'[');
    foreach (var (i, typ) in list) {
        if (i > 0) {
            w.@byte((rune)',');
        }
        Ꮡw.typ(typ);
    }
    w.@byte((rune)']');
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string nilTypeParameterˢ = "nil type parameter"u8;

internal static void tParamList(this ж<typeWriter> Ꮡw, slice<ж<TypeParam>> list) {
    ref var w = ref Ꮡw.DerefOrNull();

    w.@byte((rune)'[');
    ΔType prev = default!;
    foreach (var (i, tpar) in list) {
        // Determine the type parameter and its constraint.
        // list is expected to hold type parameter names,
        // but don't crash if that's not the case.
        if (tpar == nil) {
            w.error(nilTypeParameterˢ);
            continue;
        }
        if (i > 0) {
            if (!AreEqual((~tpar).bound, prev)) {
                // bound changed - write previous one before advancing
                w.@byte((rune)' ');
                Ꮡw.typ(prev);
            }
            w.@byte((rune)',');
        }
        prev = tpar.Value.bound;
        Ꮡw.typ(new TypeParamжΔType(tpar));
    }
    if (prev != default!) {
        w.@byte((rune)' ');
        Ꮡw.typ(prev);
    }
    w.@byte((rune)']');
}

[GoRecv] internal static void typeName(this ref typeWriter w, ж<TypeName> Ꮡobj) {
    ref var obj = ref Ꮡobj.DerefOrNull();

    w.@string(packagePrefix(obj.pkg, w.qf));
    w.@string(obj.name);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string expectedStringTypeˢ = "expected string type"u8;

internal static void tuple(this ж<typeWriter> Ꮡw, ж<Tuple> Ꮡtup, bool variadic) {
    ref var w = ref Ꮡw.DerefOrNull();
    ref var tup = ref Ꮡtup.DerefOrNull();

    w.@byte((rune)'(');
    if (Ꮡtup != nil) {
        foreach (var (i, v) in tup.vars) {
            if (i > 0) {
                w.@byte((rune)',');
            }
            // parameter names are ignored for type identity and thus type hashes
            if (w.ctxt == nil && (~v).name != ""u8 && w.paramNames) {
                w.@string((~v).name);
                w.@byte((rune)' ');
            }
            var typ = v.Value.typ;
            if (variadic && i == len(tup.vars) - 1) {
                {
                    var (s, ok) = typ._<ж<Slice>>(ᐧ); if (ok){
                        w.@string("..."u8);
                        typ = s.Value.elem;
                    } else {
                        // special case:
                        // append(s, "foo"...) leads to signature func([]byte, string...)
                        {
                            var (t, _) = under(typ)._<ж<Basic>>(ᐧ); if (t == nil || (~t).kind != ΔString) {
                                w.error(expectedStringTypeˢ);
                                continue;
                            }
                        }
                        Ꮡw.typ(typ);
                        w.@string("..."u8);
                        continue;
                    }
                }
            }
            Ꮡw.typ(typ);
        }
    }
    w.@byte((rune)')');
}

internal static void signature(this ж<typeWriter> Ꮡw, ж<ΔSignature> Ꮡsig) {
    GoFrame ᒐ = default;
    try {
        ref var w = ref Ꮡw.DerefOrNull();
        ref var sig = ref Ꮡsig.DerefOrNull();

        if (sig.TypeParams().Len() != 0) {
            if (w.ctxt != nil) {
                assert(w.tparams == nil);
                w.tparams = sig.TypeParams();
                defer(() => {
                    Ꮡw.Value.tparams = default!;
                }, ref ᒐ);
            }
            Ꮡw.tParamList(sig.TypeParams().list());
        }
        Ꮡw.tuple(sig.@params, sig.variadic);
        nint n = sig.results.Len();
        if (n == 0) {
            // no result
            return;
        }
        w.@byte((rune)' ');
        if (n == 1 && (w.ctxt != nil || (~(~sig.results).vars[0]).name == ""u8)) {
            // single unnamed result (if type hashing, name must be ignored)
            Ꮡw.typ((~(~sig.results).vars[0]).typ);
            return;
        }
        // multiple or named result(s)
        Ꮡw.tuple(sig.results, false);
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
}

// subscript returns the decimal (utf8) representation of x using subscript digits.
internal static @string subscript(uint64 x) {
    const nint w = /* len("₀") */ 3; // all digits 0...9 have the same utf8 width
    array<byte> buf = new(96); /* 32 * w */
    nint i = len(buf);
    while (ᐧ) {
        i -= w;
        utf8.EncodeRune(buf.slice(i), (rune)'₀' + (rune)(x % 10)); // '₀' == U+2080
        x /= 10;
        if (x == 0) {
            break;
        }
    }
    return ((@string)(buf.slice(i)));
}

} // end types_package
