// Code generated by mklockrank.go; DO NOT EDIT.
namespace go;

partial class runtime_package {

partial struct lockRank /*num:nint*/;

// Constants representing the ranks of all non-leaf runtime locks, in rank order.
// Locks with lower rank must be taken before locks with higher rank,
// in addition to satisfying the partial order in lockPartialOrder.
// A few ranks allow self-cycles, which are specified in lockPartialOrder.
internal static lockRank lockRankUnknown => /* iota */ 0;

internal static lockRank lockRankSysmon => 1;

internal static lockRank lockRankScavenge => 2;

internal static lockRank lockRankForcegc => 3;

internal static lockRank lockRankDefer => 4;

internal static lockRank lockRankSweepWaiters => 5;

internal static lockRank lockRankAssistQueue => 6;

internal static lockRank lockRankStrongFromWeakQueue => 7;

internal static lockRank lockRankSweep => 8;

internal static lockRank lockRankTestR => 9;

internal static lockRank lockRankTestW => 10;

internal static lockRank lockRankTimerSend => 11;

internal static lockRank lockRankAllocmW => 12;

internal static lockRank lockRankExecW => 13;

internal static lockRank lockRankCpuprof => 14;

internal static lockRank lockRankPollCache => 15;

internal static lockRank lockRankPollDesc => 16;

internal static lockRank lockRankWakeableSleep => 17;

internal static lockRank lockRankHchan => 18;

internal static lockRank lockRankAllocmR => 19;

internal static lockRank lockRankExecR => 20;

internal static lockRank lockRankSched => 21;

internal static lockRank lockRankAllg => 22;

internal static lockRank lockRankAllp => 23;

internal static lockRank lockRankNotifyList => 24;

internal static lockRank lockRankSudog => 25;

internal static lockRank lockRankTimers => 26;

internal static lockRank lockRankTimer => 27;

internal static lockRank lockRankNetpollInit => 28;

internal static lockRank lockRankRoot => 29;

internal static lockRank lockRankItab => 30;

internal static lockRank lockRankReflectOffs => 31;

internal static lockRank lockRankSynctest => 32;

internal static lockRank lockRankUserArenaState => 33;

internal static lockRank lockRankTraceBuf => 34;

internal static lockRank lockRankTraceStrings => 35;

internal static lockRank lockRankFin => 36;

internal static lockRank lockRankSpanSetSpine => 37;

internal static lockRank lockRankMspanSpecial => 38;

internal static lockRank lockRankTraceTypeTab => 39;

internal static lockRank lockRankGcBitsArenas => 40;

internal static lockRank lockRankProfInsert => 41;

internal static lockRank lockRankProfBlock => 42;

internal static lockRank lockRankProfMemActive => 43;

internal static lockRank lockRankProfMemFuture => 44;

internal static lockRank lockRankGscan => 45;

internal static lockRank lockRankStackpool => 46;

internal static lockRank lockRankStackLarge => 47;

internal static lockRank lockRankHchanLeaf => 48;

internal static lockRank lockRankWbufSpans => 49;

internal static lockRank lockRankMheap => 50;

internal static lockRank lockRankMheapSpecial => 51;

internal static lockRank lockRankGlobalAlloc => 52;

internal static lockRank lockRankTrace => 53;

internal static lockRank lockRankTraceStackTab => 54;

internal static lockRank lockRankPanic => 55;

internal static lockRank lockRankDeadlock => 56;

internal static lockRank lockRankRaceFini => 57;

internal static lockRank lockRankAllocmRInternal => 58;

internal static lockRank lockRankExecRInternal => 59;

internal static lockRank lockRankTestRInternal => 60;

// lockRankLeafRank is the rank of lock that does not have a declared rank,
// and hence is a leaf lock.
internal static lockRank lockRankLeafRank => 1000;

// lockNames gives the names associated with each of the above ranks.
internal static slice<@string> lockNames = new golib.SparseArray<@string>{
    [(int)lockRankSysmon] = "sysmon"u8,
    [(int)lockRankScavenge] = "scavenge"u8,
    [(int)lockRankForcegc] = "forcegc"u8,
    [(int)lockRankDefer] = "defer"u8,
    [(int)lockRankSweepWaiters] = "sweepWaiters"u8,
    [(int)lockRankAssistQueue] = "assistQueue"u8,
    [(int)lockRankStrongFromWeakQueue] = "strongFromWeakQueue"u8,
    [(int)lockRankSweep] = "sweep"u8,
    [(int)lockRankTestR] = "testR"u8,
    [(int)lockRankTestW] = "testW"u8,
    [(int)lockRankTimerSend] = "timerSend"u8,
    [(int)lockRankAllocmW] = "allocmW"u8,
    [(int)lockRankExecW] = "execW"u8,
    [(int)lockRankCpuprof] = "cpuprof"u8,
    [(int)lockRankPollCache] = "pollCache"u8,
    [(int)lockRankPollDesc] = "pollDesc"u8,
    [(int)lockRankWakeableSleep] = "wakeableSleep"u8,
    [(int)lockRankHchan] = "hchan"u8,
    [(int)lockRankAllocmR] = "allocmR"u8,
    [(int)lockRankExecR] = "execR"u8,
    [(int)lockRankSched] = "sched"u8,
    [(int)lockRankAllg] = "allg"u8,
    [(int)lockRankAllp] = "allp"u8,
    [(int)lockRankNotifyList] = "notifyList"u8,
    [(int)lockRankSudog] = "sudog"u8,
    [(int)lockRankTimers] = "timers"u8,
    [(int)lockRankTimer] = "timer"u8,
    [(int)lockRankNetpollInit] = "netpollInit"u8,
    [(int)lockRankRoot] = "root"u8,
    [(int)lockRankItab] = "itab"u8,
    [(int)lockRankReflectOffs] = "reflectOffs"u8,
    [(int)lockRankSynctest] = "synctest"u8,
    [(int)lockRankUserArenaState] = "userArenaState"u8,
    [(int)lockRankTraceBuf] = "traceBuf"u8,
    [(int)lockRankTraceStrings] = "traceStrings"u8,
    [(int)lockRankFin] = "fin"u8,
    [(int)lockRankSpanSetSpine] = "spanSetSpine"u8,
    [(int)lockRankMspanSpecial] = "mspanSpecial"u8,
    [(int)lockRankTraceTypeTab] = "traceTypeTab"u8,
    [(int)lockRankGcBitsArenas] = "gcBitsArenas"u8,
    [(int)lockRankProfInsert] = "profInsert"u8,
    [(int)lockRankProfBlock] = "profBlock"u8,
    [(int)lockRankProfMemActive] = "profMemActive"u8,
    [(int)lockRankProfMemFuture] = "profMemFuture"u8,
    [(int)lockRankGscan] = "gscan"u8,
    [(int)lockRankStackpool] = "stackpool"u8,
    [(int)lockRankStackLarge] = "stackLarge"u8,
    [(int)lockRankHchanLeaf] = "hchanLeaf"u8,
    [(int)lockRankWbufSpans] = "wbufSpans"u8,
    [(int)lockRankMheap] = "mheap"u8,
    [(int)lockRankMheapSpecial] = "mheapSpecial"u8,
    [(int)lockRankGlobalAlloc] = "globalAlloc"u8,
    [(int)lockRankTrace] = "trace"u8,
    [(int)lockRankTraceStackTab] = "traceStackTab"u8,
    [(int)lockRankPanic] = "panic"u8,
    [(int)lockRankDeadlock] = "deadlock"u8,
    [(int)lockRankRaceFini] = "raceFini"u8,
    [(int)lockRankAllocmRInternal] = "allocmRInternal"u8,
    [(int)lockRankExecRInternal] = "execRInternal"u8,
    [(int)lockRankTestRInternal] = "testRInternal"u8
}.slice();

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string unknownˢ = "UNKNOWN"u8;
internal static readonly @string leafˢ = "LEAF"u8;
internal static readonly @string badRankˢ = "BAD RANK"u8;

internal static @string String(this lockRank rank) {
    if (rank == 0) {
        return unknownˢ;
    }
    if (rank == lockRankLeafRank) {
        return leafˢ;
    }
    if (rank < 0 || (nint)rank >= len(lockNames)) {
        return badRankˢ;
    }
    return lockNames[rank];
}

// lockPartialOrder is the transitive closure of the lock rank graph.
// An entry for rank X lists all of the ranks that can already be held
// when rank X is acquired.
//
// Lock ranks that allow self-cycles list themselves.
internal static slice<slice<lockRank>> lockPartialOrder = new golib.SparseArray<slice<lockRank>>{
    [(int)lockRankSysmon] = new lockRank[]{}.slice(),
    [(int)lockRankScavenge] = new lockRank[]{lockRankSysmon}.slice(),
    [(int)lockRankForcegc] = new lockRank[]{lockRankSysmon}.slice(),
    [(int)lockRankDefer] = new lockRank[]{}.slice(),
    [(int)lockRankSweepWaiters] = new lockRank[]{}.slice(),
    [(int)lockRankAssistQueue] = new lockRank[]{}.slice(),
    [(int)lockRankStrongFromWeakQueue] = new lockRank[]{}.slice(),
    [(int)lockRankSweep] = new lockRank[]{}.slice(),
    [(int)lockRankTestR] = new lockRank[]{}.slice(),
    [(int)lockRankTestW] = new lockRank[]{}.slice(),
    [(int)lockRankTimerSend] = new lockRank[]{}.slice(),
    [(int)lockRankAllocmW] = new lockRank[]{}.slice(),
    [(int)lockRankExecW] = new lockRank[]{}.slice(),
    [(int)lockRankCpuprof] = new lockRank[]{}.slice(),
    [(int)lockRankPollCache] = new lockRank[]{}.slice(),
    [(int)lockRankPollDesc] = new lockRank[]{}.slice(),
    [(int)lockRankWakeableSleep] = new lockRank[]{}.slice(),
    [(int)lockRankHchan] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankWakeableSleep, lockRankHchan}.slice(),
    [(int)lockRankAllocmR] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan}.slice(),
    [(int)lockRankExecR] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan}.slice(),
    [(int)lockRankSched] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR}.slice(),
    [(int)lockRankAllg] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched}.slice(),
    [(int)lockRankAllp] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched}.slice(),
    [(int)lockRankNotifyList] = new lockRank[]{}.slice(),
    [(int)lockRankSudog] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankWakeableSleep, lockRankHchan, lockRankNotifyList}.slice(),
    [(int)lockRankTimers] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankTimers}.slice(),
    [(int)lockRankTimer] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankTimers}.slice(),
    [(int)lockRankNetpollInit] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankTimers, lockRankTimer}.slice(),
    [(int)lockRankRoot] = new lockRank[]{}.slice(),
    [(int)lockRankItab] = new lockRank[]{}.slice(),
    [(int)lockRankReflectOffs] = new lockRank[]{lockRankItab}.slice(),
    [(int)lockRankSynctest] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankRoot, lockRankItab, lockRankReflectOffs}.slice(),
    [(int)lockRankUserArenaState] = new lockRank[]{}.slice(),
    [(int)lockRankTraceBuf] = new lockRank[]{lockRankSysmon, lockRankScavenge}.slice(),
    [(int)lockRankTraceStrings] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankTraceBuf}.slice(),
    [(int)lockRankFin] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankSpanSetSpine] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankMspanSpecial] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankTraceTypeTab] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankGcBitsArenas] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankMspanSpecial}.slice(),
    [(int)lockRankProfInsert] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankProfBlock] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankProfMemActive] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings}.slice(),
    [(int)lockRankProfMemFuture] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankItab, lockRankReflectOffs, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankProfMemActive}.slice(),
    [(int)lockRankGscan] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture}.slice(),
    [(int)lockRankStackpool] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan}.slice(),
    [(int)lockRankStackLarge] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan}.slice(),
    [(int)lockRankHchanLeaf] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankHchanLeaf}.slice(),
    [(int)lockRankWbufSpans] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan}.slice(),
    [(int)lockRankMheap] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankStackpool, lockRankStackLarge, lockRankWbufSpans}.slice(),
    [(int)lockRankMheapSpecial] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankStackpool, lockRankStackLarge, lockRankWbufSpans, lockRankMheap}.slice(),
    [(int)lockRankGlobalAlloc] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankStackpool, lockRankStackLarge, lockRankWbufSpans, lockRankMheap, lockRankMheapSpecial}.slice(),
    [(int)lockRankTrace] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankStackpool, lockRankStackLarge, lockRankWbufSpans, lockRankMheap}.slice(),
    [(int)lockRankTraceStackTab] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankDefer, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollCache, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR, lockRankExecR, lockRankSched, lockRankAllg, lockRankAllp, lockRankNotifyList, lockRankSudog, lockRankTimers, lockRankTimer, lockRankNetpollInit, lockRankRoot, lockRankItab, lockRankReflectOffs, lockRankSynctest, lockRankUserArenaState, lockRankTraceBuf, lockRankTraceStrings, lockRankFin, lockRankSpanSetSpine, lockRankMspanSpecial, lockRankGcBitsArenas, lockRankProfInsert, lockRankProfBlock, lockRankProfMemActive, lockRankProfMemFuture, lockRankGscan, lockRankStackpool, lockRankStackLarge, lockRankWbufSpans, lockRankMheap, lockRankTrace}.slice(),
    [(int)lockRankPanic] = new lockRank[]{}.slice(),
    [(int)lockRankDeadlock] = new lockRank[]{lockRankPanic, lockRankDeadlock}.slice(),
    [(int)lockRankRaceFini] = new lockRank[]{lockRankPanic}.slice(),
    [(int)lockRankAllocmRInternal] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankAllocmW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankAllocmR}.slice(),
    [(int)lockRankExecRInternal] = new lockRank[]{lockRankSysmon, lockRankScavenge, lockRankForcegc, lockRankSweepWaiters, lockRankAssistQueue, lockRankStrongFromWeakQueue, lockRankSweep, lockRankTestR, lockRankTimerSend, lockRankExecW, lockRankCpuprof, lockRankPollDesc, lockRankWakeableSleep, lockRankHchan, lockRankExecR}.slice(),
    [(int)lockRankTestRInternal] = new lockRank[]{lockRankTestR, lockRankTestW}.slice()
}.slice();

} // end runtime_package
