// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Serving of pprof-like profiles.
namespace go.@internal.trace;

using bufio = bufio_package;
using fmt = fmt_package;
using profile = go.@internal.profile_package;
using trace = go.@internal.trace_package;
using http = net.http_package;
using os = os_package;
using exec = go.os.exec_package;
using filepath = path.filepath_package;
using runtime = runtime_package;
using time = time_package;
using fs = go.io.fs_package;
using go.@internal;
using go.os;
using io = io_package;
using net;
using path;
using ꓸꓸꓸany = Span<any>;

partial class traceviewer_package {

// type ProfileFunc is a methodless func type — rendered inline as its base delegate

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
private static readonly @string rawˢ = "raw"u8;
private static readonly @string contentTypeˢ = "Content-Type"u8;
private static readonly @string applicationOctetStreamˢ = "application/octet-stream"u8;
private static readonly @string textPlainCharsetUtf8ˢ = "text/plain; charset=utf-8"u8;
private static readonly @string xGoPprofˢ = "X-Go-Pprof"u8;
private static readonly @string blockˢ = "block"u8;
private static readonly @string toolˢ = "tool"u8;
private static readonly @string pprofˢ = "pprof"u8;
private static readonly @string svgˢ = "-svg"u8;
private static readonly @string outputˢ = "-output"u8;
private static readonly @string imageSvgXmlˢ = "image/svg+xml"u8;

// SVGProfileHandlerFunc serves pprof-like profile generated by prof as svg.
public static http.HandlerFunc SVGProfileHandlerFunc(Func<ж<http.Request>, (slice<ProfileRecord>, error)> f) {
    return (http.ResponseWriter w, ж<http.Request> r) => {
        GoFrame ᒐ = default;
        try {
            if (r.FormValue(rawˢ) != ""u8) {
                w.Header().Set(contentTypeˢ, applicationOctetStreamˢ);
                void failf(@string s, params ꓸꓸꓸany argsʗp) {
                    var args = argsʗp.sslice();
                    w.Header().Set(contentTypeˢ, textPlainCharsetUtf8ˢ);
                    w.Header().Set(xGoPprofˢ, "1"u8);
                    http.Error(w, fmt.Sprintf(s, args.ꓸꓸꓸ), http.StatusInternalServerError);
                }
                var (recordsΔ1, errΔ1) = f(r);
                if (errΔ1 != default!) {
                    failf("failed to get records: %v"u8, errΔ1);
                    return;
                }
                {
                    var errΔ2 = BuildProfile(recordsΔ1).Write(new http_ResponseWriterᴠWriter(w)); if (errΔ2 != default!) {
                        failf("failed to write profile: %v"u8, errΔ2);
                        return;
                    }
                }
                return;
            }
            var (blockf, err) = os.CreateTemp(""u8, blockˢ);
            if (err != default!) {
                http.Error(w, fmt.Sprintf("failed to create temp file: %v"u8, err), http.StatusInternalServerError);
                return;
            }
            var blockfʗ1 = blockf;
            defer(() => {
                blockfʗ1.Close();
                os.Remove(blockfʗ1.Name());
            }, ref ᒐ);
            (var records, err) = f(r);
            if (err != default!) {
                http.Error(w, fmt.Sprintf("failed to generate profile: %v"u8, err), http.StatusInternalServerError);
            }
            var blockb = bufio.NewWriter(new os.FileжWriter(blockf));
            {
                var errΔ1 = BuildProfile(records).Write(new bufio_WriterжWriter(blockb)); if (errΔ1 != default!) {
                    http.Error(w, fmt.Sprintf("failed to write profile: %v"u8, errΔ1), http.StatusInternalServerError);
                    return;
                }
            }
            {
                var errΔ2 = blockb.Flush(); if (errΔ2 != default!) {
                    http.Error(w, fmt.Sprintf("failed to flush temp file: %v"u8, errΔ2), http.StatusInternalServerError);
                    return;
                }
            }
            {
                var errΔ3 = blockf.Close(); if (errΔ3 != default!) {
                    http.Error(w, fmt.Sprintf("failed to close temp file: %v"u8, errΔ3), http.StatusInternalServerError);
                    return;
                }
            }
            @string svgFilename = blockf.Name() + ".svg"u8;
            {
                var (output, errΔ4) = exec.Command(goCmd(), toolˢ, pprofˢ, svgˢ, outputˢ, svgFilename, blockf.Name()).CombinedOutput(); if (errΔ4 != default!) {
                    http.Error(w, fmt.Sprintf("failed to execute go tool pprof: %v\n%s"u8, errΔ4, output), http.StatusInternalServerError);
                    return;
                }
            }
            defer(os.Remove, svgFilename, ref ᒐ);
            w.Header().Set(contentTypeˢ, imageSvgXmlˢ);
            http.ServeFile(w, r, svgFilename);
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
    };
}

partial struct ProfileRecord {
    public slice<ж<trace.Frame>> Stack;
    public uint64 Count;
    public time.Duration Time;
}

public static ж<profile.Profile> BuildProfile(slice<ProfileRecord> prof) {
    var p = Ꮡ(new profile.Profile(
        PeriodType: Ꮡ(new profile.ValueType(Type: "trace"u8, Unit: "count"u8)),
        Period: 1,
        SampleType: new ж<profile.ValueType>[]{
            Ꮡ(new profile.ValueType(Type: "contentions"u8, Unit: "count"u8)),
            Ꮡ(new profile.ValueType(Type: "delay"u8, Unit: "nanoseconds"u8))
        }.slice()
    ));
    var locs = new map<uint64, ж<profile.Location>>();
    var funcs = new map<@string, ж<profile.Function>>();
    foreach (var (_, rec) in prof) {
        slice<ж<profile.Location>> sloc = default!;
        foreach (var (_, frame) in rec.Stack) {
            var loc = locs[(~frame).PC];
            if (loc == nil) {
                var fn = funcs[(~frame).File + (~frame).Fn];
                if (fn == nil) {
                    fn = Ꮡ(new profile.Function(
                        ID: (uint64)(len((~p).Function) + 1),
                        Name: (~frame).Fn,
                        SystemName: (~frame).Fn,
                        Filename: (~frame).File
                    ));
                    p.Value.Function = append((~p).Function, fn);
                    funcs[(~frame).File + (~frame).Fn] = fn;
                }
                loc = Ꮡ(new profile.Location(
                    ID: (uint64)(len((~p).Location) + 1),
                    Address: (~frame).PC,
                    Line: new profile.Line[]{
                        new(
                            Function: fn,
                            ΔLine: (int64)(~frame).Line
                        )
                    }.slice()
                ));
                p.Value.Location = append((~p).Location, loc);
                locs[(~frame).PC] = loc;
            }
            sloc = append(sloc, loc);
        }
        p.Value.Sample = append((~p).Sample, Ꮡ(new profile.Sample(
            Value: new int64[]{(int64)rec.Count, (int64)rec.Time}.slice(),
            Location: sloc
        )));
    }
    return p;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
private static readonly @string exeˢ = ".exe"u8;
private static readonly @string binˢ = "bin"u8;

internal static @string goCmd() {
    @string exeSuffix = default!;
    if (runtime.GOOS == "windows"u8) {
        exeSuffix = exeˢ;
    }
    @string path = filepath.Join(runtime.GOROOT(), binˢ, "go" + exeSuffix);
    {
        var (_, err) = os.Stat(path); if (err == default!) {
            return path;
        }
    }
    return "go"u8;
}

} // end traceviewer_package
