import io, re, subprocess
# Rewrites the COORD section's "STATE AT THIS REVISION" block in RESUME-SESSIONS.md (hnd worktree) from the
# current position.  BRANCH pins are read from origin by ls-remote at write time (never typed).  LF only.
RS = "C:/go2cs-tmp-coord/hnd/docs/phase4/RESUME-SESSIONS.md"
G = "C:/Projects/go2cs"
def tip(ref):
    out = subprocess.run(["git", "-C", G, "ls-remote", "origin", "refs/heads/" + ref], capture_output=True).stdout.decode().strip()
    return out[:40] if out else "NOT-AT-ORIGIN"
t = io.open(RS, encoding="utf-8").read()
assert "\r" not in t
a = t.index("STATE AT THIS REVISION")
b = t.index("FIRST ACTION: re-arm the Monitor")
refs = {
    "hnd": tip("claude/coord-handover"), "mbx": tip("claude/mailbox"), "ver": tip("claude/version-go1.24.13"),
    "c1rel": tip("claude/c1-h5-relocation"), "c2h5c": tip("claude/c2-h5c-slnx-orphan"), "skel": tip("claude/laneR-docs-h6-skeleton"),
    "rb": tip("claude/coord-runbook-h5-tags"), "c1g1": tip("claude/c1-handown-address-guard"), "c1g2": tip("claude/c1-train49-guards"),
}
block = """STATE AT THIS REVISION (2026-09-13 21:45, weekly usage 94 percent -- SAVE-STATE MODE):
  BRANCH: claude/coord-handover %(hnd)s yes landed -- the handover log (block 10 + this file; block 11 = this refresh)
  BRANCH: claude/mailbox %(mbx)s yes transport -- rotated 2026-09-13 02:36
  BRANCH: claude/version-go1.24.13 %(ver)s yes cut -- the H5 branch: checkpoint 1 (dc78fb0df8: seeded reconvert at go1.24.13 + H5c; the C1-1/C1-2 appliers) then C1's relocation (c8d50e014f moves/deletes/two registry keys; a4ece44fff namespace/class lines). NOT the H5 gate.
  BRANCH: claude/c1-h5-relocation %(c1rel)s yes accepted -- the relocation source ref (landed on the version branch by fast-forward)
  BRANCH: claude/c2-h5c-slnx-orphan %(c2h5c)s yes announced -- H5c: slnx guard + ORPHANED class + relocate REFUSED + report-only items; C2 is cutting the SELECTION fix on top (derive deselected from the emission; explanation gate = selection at both GOROOTs under the converter's printed tag set); i7 parse gate on every push
  BRANCH: claude/laneR-docs-h6-skeleton %(skel)s yes accepted -- the H6 audit skeleton at 145 rows == the version-branch census (R's record, G's amendments); lands on the VERSION BRANCH; train-48 seat 4 stays SHA-pinned at d18059950
  BRANCH: claude/coord-runbook-h5-tags %(rb)s yes announced -- runbook H5 in-stage amendment (one tag resolution; selection-based DELETE-DESELECTED gate; carry the regenerated stdlib slnx; go2cs.slnx follows moved packages); lands on master with the H5 gate docs commit
  BRANCH: claude/c1-handown-address-guard %(c1g1)s yes accepted -- train 49 row (converter-guard)
  BRANCH: claude/c1-train49-guards %(c1g2)s yes accepted -- train 49 rows (ValueClone vacuity; go2cs.slnx path guard)
  master tip: 271300cea0 (docs) over 1885bce69 (doctrine d) over 31fe4925d (TRAIN 47 LANDED 17:26). Train 48 assembles on 271300cea0.
  THE LADDER: H5 in its next-wall loop on the version branch. Step 2 read (i9 7ae5355bb): the corpus solution LOADS (the
    stdlib slnx is REGENERATED by the reconvert; the step-5 wall was the regenerated file not carried), runtime 0 errors,
    8 errors in two packages (sync: hand-owns vs the 1.24 shape; weak: Pointer<T> visibility + Strong->Value), unique unbuilt;
    H5c had DELETED five live purego files (its own tag resolution; C2 5c47976ea located it) -> i9 RESTORES them from the
    preserved staging root, runs H5c on C2's fixed tip (DELETE-DESELECTED must read 0), appliers, builds, then CHECKPOINT 2
    (+ src/go2cs.slnx following moved packages) announce-then-push; C1 cuts ONE commit on it (weak: public + Strong->Value;
    sync re-derives against the 1.24.13 auto + the pinned Go read from the golang/go tag; the xor_generic relocation to
    crypto/internal/fips140/subtle); i9 rebuilds the corpus solution -> THE H5 GATE READING. Then H6 (G fills the 145-row
    audit from the PAIR: half A = i9's preserved three staging roots, half B + the -tests pair cut by G on G-LAPTOP from the
    byte-identical binary e0b2a4c109053c6b (tree ddf7cb17c8, go1.24.13, -trimpath -buildvcs=false, hash equal on 3 boxes);
    a side is a file the converter WROTE in that half (per-target run-window mtime); moved-package rows take the old-path
    emission; ARRIVED rows have no outgoing side; half A moves to G-LAPTOP by share + sha256 manifest).
  TRAIN 48 (template .claude/coord-scripts/train48/, i7-LOCAL -- see the OWNER HAND above): 18 rows pinned at origin
    (table in coord-train48-assemble.sh; 217 derive ops in t48-derive.py; NOTES sections 17-23), rows 9/15 BOARD conflicts
    PRE-RESOLVED by union slots (coord-train48-resolutions/), 18 seat-content arms (green at the union, red at the base),
    online self-check 0 FAIL, dry-read 0 FAIL, rehearsal replay 18 clean. RUN 1 stopped at the A-assertions (0 arms -- the
    fill point, now filled). RUN 2 launched 21:18 in worktree C:/go2cs-tmp-coord/t48-asm (detached at 271300cea0) from
    coord-train48-assemble-run2.sh (md5 2ff36bc5e938) via launch-run2.sh; record coord-train48-assemble-run2.stdout with the
    wrapper line `assembly exit=N`. On green: land-anchor census -> land (signed) -> read back -> prune seats -> resume refresh.
    IF THE i7 IS LOST: the template is re-derivable ONLY from the local files -- the derive inputs are train47/ (also local);
    the seat table, the allowed= rulings, the stack (13 on 11), the SHA-mode row 4 and the 18 arms are described in the
    handover blocks 9-11 and the mailbox (817f98813, 46198c1b9 s4, 80c948a7f); re-cutting from those is a day's work.
  TRAIN 49 board: C1 address guard + two guards (above), G's H6 gate c9c1b5f73 + liveness 44857cdf8, C2 sizing 43e0dff04,
    trampoline map 4bc0c35b0, the array-length converter seat (unclaimed), the vocabulary gap (a .claude-shaped class).
  OWNER HANDS OPEN: the coordinator instruments push decision (username paths + the scrub literal; this file's OWNER HAND
    above); cloud allowlist for the dotnet builds host AND go.dev/dl (C1/C2 hold neither pinned Go SDK); R-LAPTOP
    src/lane-r-packrace.ps1; the thermal-sentence host; delete claude/awesome-franklin-ba9agv; remote branch deletions
    blocked at coordinator tooling; a fleet share for off-box copies of the pair roots.

"""
for k, v in refs.items():
    block = block.replace("%(" + k + ")s", v)
t = t[:a] + block + t[b:]
assert "\r" not in t
io.open(RS, "w", encoding="utf-8", newline="\n").write(t)
print("COORD state block rewritten; pins:", {k: v[:9] for k, v in refs.items()})
