// Code generated by generate1024.go. DO NOT EDIT.
namespace go.crypto.@internal.fips140;

using bytes = bytes_package;
using fips140 = go.crypto.@internal.fips140_package;
using drbg = go.crypto.@internal.fips140.drbg_package;
using sha3 = go.crypto.@internal.fips140.sha3_package;
using subtle = go.crypto.@internal.fips140.subtle_package;
using errors = errors_package;
using go.crypto.@internal;
using go.crypto.@internal.fips140;

partial class mlkem_package {

// A DecapsulationKey1024 is the secret key used to decapsulate a shared key from a
// ciphertext. It includes various precomputed values.
[GoType] partial struct DecapsulationKey1024 {
    internal array<byte> d = new(32); // decapsulation key seed
    internal array<byte> z = new(32); // implicit rejection sampling seed
    internal array<byte> ρ = new(32); // sampleNTT seed for A, stored for the encapsulation key
    internal array<byte> h = new(32); // H(ek), stored for ML-KEM.Decaps_internal
    internal partial ref encryptionKey1024 encryptionKey1024 { get; }
    internal partial ref decryptionKey1024 decryptionKey1024 { get; }
}

// Bytes returns the decapsulation key as a 64-byte seed in the "d || z" form.
//
// The decapsulation key must be kept secret.
[GoRecv] public static slice<byte> Bytes(this ref DecapsulationKey1024 dk) {
    array<byte> b = new(64); /* SeedSize */
    copy(b[..], dk.d[..]);
    copy(b[32..], dk.z[..]);
    return b[..];
}

// TestingOnlyExpandedBytes1024 returns the decapsulation key as a byte slice
// using the full expanded NIST encoding.
//
// This should only be used for ACVP testing. For all other purposes prefer
// the Bytes method that returns the (much smaller) seed.
public static slice<byte> TestingOnlyExpandedBytes1024(ж<DecapsulationKey1024> Ꮡdk) {
    ref var dk = ref Ꮡdk.DerefOrNull();

    var b = new slice<byte>(0, decapsulationKeySize1024);
    // ByteEncode₁₂(s)
    foreach (var (i, _) in dk.s) {
        b = polyByteEncode(b, dk.s[i]);
    }
    // ByteEncode₁₂(t) || ρ
    foreach (var (i, _) in dk.t) {
        b = polyByteEncode(b, dk.t[i]);
    }
    b = appendꓸꓸꓸ(b, dk.ρ[..]);
    // H(ek) || z
    b = appendꓸꓸꓸ(b, dk.h[..]);
    b = appendꓸꓸꓸ(b, dk.z[..]);
    return b;
}

// EncapsulationKey returns the public encapsulation key necessary to produce
// ciphertexts.
[GoRecv] public static ж<EncapsulationKey1024> EncapsulationKey(this ref DecapsulationKey1024 dk) {
    return Ꮡ(new EncapsulationKey1024(
        ρ: dk.ρ.Clone(),
        h: dk.h.Clone(),
        encryptionKey1024: dk.encryptionKey1024.ΔClone()
    ));
}

// An EncapsulationKey1024 is the public key used to produce ciphertexts to be
// decapsulated by the corresponding [DecapsulationKey1024].
[GoType] partial struct EncapsulationKey1024 {
    internal array<byte> ρ = new(32); // sampleNTT seed for A
    internal array<byte> h = new(32); // H(ek)
    internal partial ref encryptionKey1024 encryptionKey1024 { get; }
}

// Bytes returns the encapsulation key as a byte slice.
[GoRecv] public static slice<byte> Bytes(this ref EncapsulationKey1024 ek) {
    // The actual logic is in a separate function to outline this allocation.
    var b = new slice<byte>(0, EncapsulationKeySize1024);
    return ek.bytes(b);
}

[GoRecv] internal static slice<byte> bytes(this ref EncapsulationKey1024 ek, slice<byte> b) {
    foreach (var (i, _) in ek.t) {
        b = polyByteEncode(b, ek.t[i]);
    }
    b = appendꓸꓸꓸ(b, ek.ρ[..]);
    return b;
}

// encryptionKey1024 is the parsed and expanded form of a PKE encryption key.
[GoType] partial struct encryptionKey1024 {
    internal array<nttElement> t = new(k1024);     // ByteDecode₁₂(ek[:384k])
    internal array<nttElement> a = new(k1024 * k1024); // A[i*k+j] = sampleNTT(ρ, j, i)
}

// decryptionKey1024 is the parsed and expanded form of a PKE decryption key.
[GoType] partial struct decryptionKey1024 {
    internal array<nttElement> s = new(k1024); // ByteDecode₁₂(dk[:decryptionKey1024Size])
}

// GenerateKey1024 generates a new decapsulation key, drawing random bytes from
// a DRBG. The decapsulation key must be kept secret.
public static (ж<DecapsulationKey1024>, error) GenerateKey1024() {
    // The actual logic is in a separate function to outline this allocation.
    var dk = Ꮡ(new DecapsulationKey1024(nil));
    return generateKey1024(dk);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlKemPctˢ = "ML-KEM PCT"u8;

internal static (ж<DecapsulationKey1024>, error) generateKey1024(ж<DecapsulationKey1024> Ꮡdk) {
    ref var d = ref heap(new array<byte>(32), out var Ꮡd);
    drbg.Read(d[..]);
    ref var z = ref heap(new array<byte>(32), out var Ꮡz);
    drbg.Read(z[..]);
    kemKeyGen1024(Ꮡdk, Ꮡd, ref z);
    fips140.PCT(mlKemPctˢ, () => kemPCT1024(Ꮡdk));
    fips140.RecordApproved();
    return (Ꮡdk, default!);
}

// GenerateKeyInternal1024 is a derandomized version of GenerateKey1024,
// exclusively for use in tests.
public static ж<DecapsulationKey1024> GenerateKeyInternal1024([GoArrayDims(32)] ж<array<byte>> Ꮡd, [GoArrayDims(32)] ж<array<byte>> Ꮡz) {
    var dk = Ꮡ(new DecapsulationKey1024(nil));
    kemKeyGen1024(dk, Ꮡd, ref (Ꮡz).DerefOrNull());
    return dk;
}

// NewDecapsulationKey1024 parses a decapsulation key from a 64-byte
// seed in the "d || z" form. The seed must be uniformly random.
public static (ж<DecapsulationKey1024>, error) NewDecapsulationKey1024(slice<byte> seed) {
    // The actual logic is in a separate function to outline this allocation.
    var dk = Ꮡ(new DecapsulationKey1024(nil));
    return newKeyFromSeed1024(dk, seed);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlkemInvalidSeedLengthˢ = "mlkem: invalid seed length"u8;

internal static (ж<DecapsulationKey1024>, error) newKeyFromSeed1024(ж<DecapsulationKey1024> Ꮡdk, slice<byte> seed) {
    if (len(seed) != SeedSize) {
        return (default!, errors.New(mlkemInvalidSeedLengthˢ));
    }
    var d = Ꮡ(array<byte>.Alias(seed[..32], 32));
    var z = Ꮡ(array<byte>.Alias(seed[32..], 32));
    kemKeyGen1024(Ꮡdk, d, ref (z).DerefOrNull());
    fips140.RecordApproved();
    return (Ꮡdk, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlkemInvalidNistˢ = "mlkem: invalid NIST decapsulation key length"u8;
internal static readonly @string mlkemInvalidSecretKeyˢ = "mlkem: invalid secret key encoding"u8;
internal static readonly @string mlkemInconsistentHEkInˢ = "mlkem: inconsistent H(ek) in encoded bytes"u8;

// TestingOnlyNewDecapsulationKey1024 parses a decapsulation key from its expanded NIST format.
//
// Bytes() must not be called on the returned key, as it will not produce the
// original seed.
//
// This function should only be used for ACVP testing. Prefer NewDecapsulationKey1024 for all
// other purposes.
public static (ж<DecapsulationKey1024>, error) TestingOnlyNewDecapsulationKey1024(slice<byte> b) {
    if (len(b) != decapsulationKeySize1024) {
        return (default!, errors.New(mlkemInvalidNistˢ));
    }
    var dk = Ꮡ(new DecapsulationKey1024(nil));
    foreach (var (i, _) in (~dk).s) {
        error errΔ1 = default!;
        (dk.Value.s[i], errΔ1) = polyByteDecode<nttElement>(b[..(int)(encodingSize12)]);
        if (errΔ1 != default!) {
            return (default!, errors.New(mlkemInvalidSecretKeyˢ));
        }
        b = b[(int)(encodingSize12)..];
    }
    var (ek, err) = NewEncapsulationKey1024(b[..(int)(EncapsulationKeySize1024)]);
    if (err != default!) {
        return (default!, err);
    }
    dk.Value.ρ = ek.Value.ρ.Clone();
    dk.Value.h = ek.Value.h.Clone();
    dk.Value.encryptionKey1024 = ek.Value.encryptionKey1024.ΔClone();
    b = b[(int)(EncapsulationKeySize1024)..];
    if (!bytes_package.Equal((~dk).h[..], b[..32])) {
        return (default!, errors.New(mlkemInconsistentHEkInˢ));
    }
    b = b[32..];
    copy((~dk).z[..], b);
    // Generate a random d value for use in Bytes(). This is a safety mechanism
    // that avoids returning a broken key vs a random key if this function is
    // called in contravention of the TestingOnlyNewDecapsulationKey1024 function
    // comment advising against it.
    drbg.Read((~dk).d[..]);
    return (dk, default!);
}

// kemKeyGen1024 generates a decapsulation key.
//
// It implements ML-KEM.KeyGen_internal according to FIPS 203, Algorithm 16, and
// K-PKE.KeyGen according to FIPS 203, Algorithm 13. The two are merged to save
// copies and allocations.
internal static void kemKeyGen1024(ж<DecapsulationKey1024> Ꮡdk, [GoArrayDims(32)] ж<array<byte>> Ꮡd, ref array<byte> z) {
    ref var dk = ref Ꮡdk.DerefOrNull();
    ref var d = ref Ꮡd.DerefOrNull();

    dk.d = d.Clone();
    dk.z = z.Clone();
    var g = sha3.New512();
    g.Write(d[..]);
    g.Write(new byte[]{k1024}.slice()); // Module dimension as a domain separator.
    var G = g.Sum(new slice<byte>(0, 64));
    var (ρ, σ) = (G[..32], G[32..]);
    dk.ρ = new array<byte>(ρ, 32);
    var A = Ꮡdk.of(DecapsulationKey1024.Ꮡa);
    for (var i = (byte)0; i < k1024; i++) {
        for (var j = (byte)0; j < k1024; j++) {
            A.Value[(byte)(i * (byte)k1024 + j)] = sampleNTT(ρ, j, i);
        }
    }
    byte N = default!;
    var s = Ꮡdk.of(DecapsulationKey1024.Ꮡs);
    foreach (var (i, _) in s.Value) {
        s.Value[i] = ntt(samplePolyCBD(σ, N));
        N++;
    }
    var e = GoReflect.WithElemDims(new slice<nttElement>(k1024), 256);
    foreach (var (i, _) in e) {
        e[i] = ntt(samplePolyCBD(σ, N));
        N++;
    }
    var t = Ꮡdk.of(DecapsulationKey1024.Ꮡt);
    foreach (var (i, _) in t.Value) {
        // t = A ◦ s + e
        t.Value[i] = e[i].Clone();
        foreach (var (j, _) in s.Value) {
            t.Value[i] = polyAdd<nttElement>(t.Value[i], nttMul(A.Value[i * (nint)k1024 + j], s.Value[j]));
        }
    }
    var H = sha3.New256();
    var ek = dk.EncapsulationKey().Bytes();
    H.Write(ek);
    H.Sum(dk.h[..0]);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlkemPctFailedˢ = "mlkem: PCT failed"u8;

// kemPCT1024 performs a Pairwise Consistency Test per FIPS 140-3 IG 10.3.A
// Additional Comment 1: "For key pairs generated for use with approved KEMs in
// FIPS 203, the PCT shall consist of applying the encapsulation key ek to
// encapsulate a shared secret K leading to ciphertext c, and then applying
// decapsulation key dk to retrieve the same shared secret K. The PCT passes if
// the two shared secret K values are equal. The PCT shall be performed either
// when keys are generated/imported, prior to the first exportation, or prior to
// the first operational use (if not exported before the first use)."
internal static error kemPCT1024(ж<DecapsulationKey1024> Ꮡdk) {
    ref var dk = ref Ꮡdk.DerefOrNull();

    var ek = dk.EncapsulationKey();
    var (K, c) = ek.Encapsulate();
    var (K1, err) = Ꮡdk.Decapsulate(c);
    if (err != default!) {
        return err;
    }
    if (subtle.ConstantTimeCompare(K, K1) != 1) {
        return errors.New(mlkemPctFailedˢ);
    }
    return default!;
}

// Encapsulate generates a shared key and an associated ciphertext from an
// encapsulation key, drawing random bytes from a DRBG.
//
// The shared key must be kept secret.
public static (slice<byte> sharedKey, slice<byte> ciphertext) Encapsulate(this ж<EncapsulationKey1024> Ꮡek) {
    // The actual logic is in a separate function to outline this allocation.
    ref var cc = ref heap(new array<byte>(1568), out var Ꮡcc);
    return Ꮡek.encapsulate(Ꮡcc);
}

internal static (slice<byte> sharedKey, slice<byte> ciphertext) encapsulate(this ж<EncapsulationKey1024> Ꮡek, [GoArrayDims(1568)] ж<array<byte>> Ꮡcc) {
    ref var m = ref heap(new array<byte>(32), out var Ꮡm);
    drbg.Read(m[..]);
    // Note that the modulus check (step 2 of the encapsulation key check from
    // FIPS 203, Section 7.2) is performed by polyByteDecode in parseEK1024.
    fips140.RecordApproved();
    return kemEncaps1024(Ꮡcc, ref (Ꮡek).DerefOrNull(), Ꮡm);
}

// EncapsulateInternal is a derandomized version of Encapsulate, exclusively for
// use in tests.
public static (slice<byte> sharedKey, slice<byte> ciphertext) EncapsulateInternal(this ж<EncapsulationKey1024> Ꮡek, [GoArrayDims(32)] ж<array<byte>> Ꮡm) {
    var cc = Ꮡ(new byte[]{}.array(1568));
    return kemEncaps1024(cc, ref (Ꮡek).DerefOrNull(), Ꮡm);
}

// kemEncaps1024 generates a shared key and an associated ciphertext.
//
// It implements ML-KEM.Encaps_internal according to FIPS 203, Algorithm 17.
internal static (slice<byte> K, slice<byte> c) kemEncaps1024([GoArrayDims(1568)] ж<array<byte>> Ꮡcc, ref EncapsulationKey1024 ek, [GoArrayDims(32)] ж<array<byte>> Ꮡm) {
    slice<byte> K = default!;
    slice<byte> c = default!;

    ref var m = ref Ꮡm.DerefOrNull();
    var g = sha3.New512();
    g.Write(m[..]);
    g.Write(ek.h[..]);
    var G = g.Sum(default!);
    K = G[..(int)(SharedKeySize)];
    var r = G[(int)(SharedKeySize)..];
    c = pkeEncrypt1024(Ꮡcc, ref nonnil(ref ek).encryptionKey1024, Ꮡm, r);
    return (K, c);
}

// NewEncapsulationKey1024 parses an encapsulation key from its encoded form.
// If the encapsulation key is not valid, NewEncapsulationKey1024 returns an error.
public static (ж<EncapsulationKey1024>, error) NewEncapsulationKey1024(slice<byte> encapsulationKey) {
    // The actual logic is in a separate function to outline this allocation.
    var ek = Ꮡ(new EncapsulationKey1024(nil));
    return parseEK1024(ek, encapsulationKey);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlkemInvalidˢ = "mlkem: invalid encapsulation key length"u8;

// parseEK1024 parses an encryption key from its encoded form.
//
// It implements the initial stages of K-PKE.Encrypt according to FIPS 203,
// Algorithm 14.
internal static (ж<EncapsulationKey1024>, error) parseEK1024(ж<EncapsulationKey1024> Ꮡek, slice<byte> ekPKE) {
    ref var ek = ref Ꮡek.DerefOrNull();

    if (len(ekPKE) != EncapsulationKeySize1024) {
        return (default!, errors.New(mlkemInvalidˢ));
    }
    var h = sha3.New256();
    h.Write(ekPKE);
    h.Sum(ek.h[..0]);
    foreach (var (i, _) in ek.t) {
        error err = default!;
        (ek.t[i], err) = polyByteDecode<nttElement>(ekPKE[..(int)(encodingSize12)]);
        if (err != default!) {
            return (default!, err);
        }
        ekPKE = ekPKE[(int)(encodingSize12)..];
    }
    copy(ek.ρ[..], ekPKE);
    for (var i = (byte)0; i < k1024; i++) {
        for (var j = (byte)0; j < k1024; j++) {
            ek.a[(byte)(i * (byte)k1024 + j)] = sampleNTT(ek.ρ[..], j, i);
        }
    }
    return (Ꮡek, default!);
}

// pkeEncrypt1024 encrypt a plaintext message.
//
// It implements K-PKE.Encrypt according to FIPS 203, Algorithm 14, although the
// computation of t and AT is done in parseEK1024.
internal static slice<byte> pkeEncrypt1024([GoArrayDims(1568)] ж<array<byte>> Ꮡcc, ref encryptionKey1024 ex, [GoArrayDims(32)] ж<array<byte>> Ꮡm, slice<byte> rnd) {
    ref var cc = ref Ꮡcc.DerefOrNull();

    byte N = default!;
    var (r, e1) = (GoReflect.WithElemDims(new slice<nttElement>(k1024), 256), GoReflect.WithElemDims(new slice<ringElement>(k1024), 256));
    foreach (var (i, _) in r) {
        r[i] = ntt(samplePolyCBD(rnd, N));
        N++;
    }
    foreach (var (i, _) in e1) {
        e1[i] = samplePolyCBD(rnd, N);
        N++;
    }
    var e2 = samplePolyCBD(rnd, N);
    var u = GoReflect.WithElemDims(new slice<ringElement>(k1024), 256); // NTT⁻¹(AT ◦ r) + e1
    foreach (var (i, _) in u) {
        u[i] = e1[i].Clone();
        foreach (var (j, _) in r) {
            // Note that i and j are inverted, as we need the transposed of A.
            u[i] = polyAdd<ringElement>(u[i], inverseNTT(nttMul(ex.a[j * (nint)k1024 + i], r[j])));
        }
    }
    var μ = ringDecodeAndDecompress1(ref (Ꮡm).DerefOrNull());
    nttElement vNTT = default!;                  // t⊺ ◦ r
    foreach (var (i, _) in ex.t) {
        vNTT = polyAdd(vNTT, nttMul(ex.t[i], r[i]));
    }
    var v = polyAdd(polyAdd(inverseNTT(vNTT), e2), μ);
    var c = cc[..0];
    foreach (var (_, vᴛ1) in u) {
        var f = vᴛ1.Clone();

        c = ringCompressAndEncode11(c, f);
    }
    c = ringCompressAndEncode5(c, v);
    return c;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string mlkemInvalidCiphertextˢ = "mlkem: invalid ciphertext length"u8;

// Decapsulate generates a shared key from a ciphertext and a decapsulation key.
// If the ciphertext is not valid, Decapsulate returns an error.
//
// The shared key must be kept secret.
public static (slice<byte> sharedKey, error err) Decapsulate(this ж<DecapsulationKey1024> Ꮡdk, slice<byte> ciphertext) {
    if (len(ciphertext) != CiphertextSize1024) {
        return (default!, errors.New(mlkemInvalidCiphertextˢ));
    }
    var c = Ꮡ(array<byte>.Alias(ciphertext, 1568));
    // Note that the hash check (step 3 of the decapsulation input check from
    // FIPS 203, Section 7.3) is foregone as a DecapsulationKey is always
    // validly generated by ML-KEM.KeyGen_internal.
    return (kemDecaps1024(ref (Ꮡdk).DerefOrNull(), c), default!);
}

// kemDecaps1024 produces a shared key from a ciphertext.
//
// It implements ML-KEM.Decaps_internal according to FIPS 203, Algorithm 18.
internal static slice<byte> /*K*/ kemDecaps1024(ref DecapsulationKey1024 dk, [GoArrayDims(1568)] ж<array<byte>> Ꮡc) {
    ref var c = ref Ꮡc.DerefOrNull();

    fips140.RecordApproved();
    var m = pkeDecrypt1024(ref nonnil(ref dk).decryptionKey1024, Ꮡc);
    var g = sha3.New512();
    g.Write(m[..]);
    g.Write(dk.h[..]);
    var G = g.Sum(new slice<byte>(0, 64));
    var (Kprime, r) = (G[..(int)(SharedKeySize)], G[(int)(SharedKeySize)..]);
    var J = sha3.NewShake256();
    J.Write(dk.z[..]);
    J.Write(c[..]);
    var Kout = new slice<byte>(SharedKeySize);
    J.Read(Kout);
    ref var cc = ref heap(new array<byte>(1568), out var Ꮡcc);
    var c1 = pkeEncrypt1024(Ꮡcc, ref nonnil(ref dk).encryptionKey1024, Ꮡ(array<byte>.Alias(m, 32)), r);
    subtle.ConstantTimeCopy(subtle.ConstantTimeCompare(c[..], c1), Kout, Kprime);
    return Kout;
}

// pkeDecrypt1024 decrypts a ciphertext.
//
// It implements K-PKE.Decrypt according to FIPS 203, Algorithm 15,
// although s is retained from kemKeyGen1024.
internal static slice<byte> pkeDecrypt1024(ref decryptionKey1024 dx, [GoArrayDims(1568)] ж<array<byte>> Ꮡc) {
    ref var c = ref Ꮡc.DerefOrNull();

    var u = GoReflect.WithElemDims(new slice<ringElement>(k1024), 256);
    foreach (var (i, _) in u) {
        var bΔ1 = Ꮡ(array<byte>.Alias(c.slice((nint)encodingSize11 * i, (nint)encodingSize11 * (i + 1)), 352));
        u[i] = ringDecodeAndDecompress11(bΔ1);
    }
    var b = Ꮡ(array<byte>.Alias(c[(int)(encodingSize11 * k1024)..], 160));
    var v = ringDecodeAndDecompress5(b);
    nttElement mask = default!;                  // s⊺ ◦ NTT(u)
    foreach (var (i, _) in dx.s) {
        mask = polyAdd(mask, nttMul(dx.s[i], ntt(u[i])));
    }
    var w = polySub(v, inverseNTT(mask));
    return ringCompressAndEncode1(default!, w);
}

} // end mlkem_package
