# tK-countassert.py -- TRAIN K fixup helper: the silent-duplication / silent-subtraction asserts on files every seat
# merged CLEANLY (merge-hazards: a clean merge is exactly when duplication hides). READ-ONLY: git objects only.
#
#   python tK-countassert.py regs  <repo> <base> <head>   # PRERES-K1 (go2cs-src.projitems) + PRERES-K3 (go2cs.slnx and
#                                                         # the 4 BehavioralTests *Tests.cs registration files)
#   python tK-countassert.py nuget <repo> <base> <head>   # PRERES-K2 (src/push-nuget.ps1: both seats' lines present)
#
# THE PREDICTION is taken from the assembled union's own history, not from the merged file: walk the FIRST-PARENT
# chain base..head; every commit on it is a seat merge M with parents (U, seat). A seat's OWN change to a file is the
# sum of the per-commit diffs of the NON-MERGE commits in U..seat (each against its one parent) -- exactly the commits
# the seat brings that the union did not already hold. That is independent of any merge-base pick: `git diff
# merge-base(U, seat) seat` is NOT, because a criss-cross has more than one best base and plain merge-base picks one
# arbitrarily (at c2-gen-guard's merge 0aef70f524, `merge-base --all` returns f819887fa3 AND 272afeef93; from the
# latter the seat reads +7/+8/+21x4 on these files -- TRAIN J's own inserts -- from the former projitems +1, which is
# right only because S1 touches none of them). A MERGE commit inside U..seat (c2-gen-guard stacking S1; r-hop-
# population-gen's S4 landing merge) contributes nothing of its own only if it is clean on the file, so its combined
# diff (`diff-tree --cc`) for the file must be EMPTY; an evil merge on a counted file is unmodeled and fails.
# Keep-every-side then predicts: lines(head) = lines(base) + sum(added - deleted), and the same for the registration
# keys. A SECOND derivation, made by hand at authoring time (each seat's diff from merge-base(seat, f819887fa3),
# 2026-09-30 -- for c2-gen-guard that base is f819887fa3, whose diff also carries S1's delta, harmless here because S1
# touches none of these files), is carried as AUTHORED below and must agree; a disagreement aborts.
# Exit: 0 pass, 3 fail.
import re, subprocess, sys
from collections import Counter

BT = "src/tests/Behavioral/BehavioralTests/"
# file -> (registration-key regex, AUTHORED (lines, keys) at base f819887fa3, AUTHORED (lines, keys) at the union)
REGS = {
    "src/go2cs/go2cs-src.projitems": (r'Include="([^"]+)"', (407, 393), (414, 400)),   # 7 seats x 1 (PRERES-K1/K7)
    "src/go2cs.slnx": (r'<Project Path="([^"]+)"', (1058, 863), (1064, 869)),            # 6 seats x 1 (PRERES-K3)
    BT + "CompileTests.cs": (r'public void (Check\w+)\(\)', (2232, 733), (2250, 739)),     # 6 seats x 3 lines
    BT + "OutputComparisonTests.cs": (r'public void (Check\w+)\(\)', (2230, 705), (2248, 711)),
    BT + "TargetComparisonTests.cs": (r'public void (Check\w+)\(\)', (2282, 733), (2300, 739)),
    BT + "TranspileTests.cs": (r'public void (Check\w+)\(\)', (2228, 733), (2246, 739)),
}
NUGET = "src/push-nuget.ps1"
NUGET_AUTHORED = (1927, 1965)  # r-hop-population-gen +4/-2, i9-j0-uuid-rehearsal +38/-2
# Distinctive tokens, derived from each seat's own diff (a1f133c3a9..seat), with the count each must have in the union.
NUGET_TOKENS = {
    "r-hop-population-gen 5b011e7cbf": [
        ('$populationPath = Join-Path $repoRoot "docs\\phase4\\data\\population-go$preflightGoPin.txt"', 1),
        ('hopA-inputs\\recon-lists\\population-go$preflightGoPin.txt', 0),       # the old read is GONE
        ("generated by src\\go2cs\\internal\\genpopulation", 1),
    ],
    "i9-j0-uuid-rehearsal 86508936a3": [
        (".PARAMETER VersionSuffix", 1),
        ("[string]$VersionSuffix", 1),                                               # the param block's new last entry
        ("-VersionSuffix is a local-rehearsal pack and is refused with -Push, -BumpBuild and -VerifyOnly", 1),
        ("$packVersion = if ($VersionSuffix)", 1),
        ('$packVersionArgs = @(if ($VersionSuffix) { "-p:PackageVersion=$packVersion" })', 1),
        ("--no-build --nologo -v m @packVersionArgs", 1),                           # the pack line carries it
        ("--no-build --nologo -v m\n", 0),                                           # ... and no un-suffixed twin survives
    ],
}


def git(repo, *a):
    r = subprocess.run(["git", "-C", repo] + list(a), capture_output=True)
    if r.returncode != 0:
        raise SystemExit(f"git {' '.join(a)} failed: {r.stderr.decode('utf-8', 'replace').strip()}")
    return r.stdout.decode("utf-8", "surrogateescape")


def blob(repo, rev, path):
    r = subprocess.run(["git", "-C", repo, "show", f"{rev}:{path}"], capture_output=True)
    return r.stdout.decode("utf-8", "surrogateescape").replace("\r\n", "\n") if r.returncode == 0 else ""


def chain(repo, base, head):
    """The seat merges on the first-parent chain, oldest first: (merge, U, seat, [(commit, [parents])] of U..seat)."""
    out = []
    for line in git(repo, "rev-list", "--first-parent", "--reverse", "--parents", f"{base}..{head}").split("\n"):
        parts = line.split()
        if not parts:
            continue
        if len(parts) != 3:
            raise SystemExit(f"first-parent commit {parts[0][:10]} is not a two-parent seat merge ({len(parts) - 1} parents)")
        m, u, s = parts
        own = [(x[0], x[1:]) for x in (ln.split() for ln in git(repo, "rev-list", "--reverse", "--parents", f"{u}..{s}").split("\n")) if x]
        if not own:
            raise SystemExit(f"seat merge {m[:10]}: {u[:10]}..{s[:10]} is empty (the seat was already in the union)")
        out.append((m, u, s, own))
    return out


def seat_delta(repo, s, own, path, rxc=None, lines=False):
    """The seat's OWN change to path: (added, deleted, key delta, Counter of line deltas) summed over its non-merge
    commits; None when none of them touches path. A merge in U..seat must be clean on path (empty --cc)."""
    a = d = kd = 0
    ld, hit = Counter(), False
    for c, ps in own:
        if len(ps) != 1:
            cc = git(repo, "diff-tree", "--cc", "--no-commit-id", "-r", c, "--", path).strip()
            if cc:
                raise SystemExit(f"seat {s[:10]}: merge {c[:10]} changes {path} beyond its parents (an evil merge); "
                                 f"the per-commit sum cannot model it -- subtract it by hand")
            continue
        ns = git(repo, "diff-tree", "--no-commit-id", "--numstat", "-r", c, "--", path).strip()
        if not ns:
            continue
        f = ns.split("\t")
        if f[0] == "-":
            raise SystemExit(f"seat {s[:10]}: commit {c[:10]} reads {path} as binary")
        hit = True
        a, d = a + int(f[0]), d + int(f[1])
        if rxc is not None or lines:
            now, was = blob(repo, c, path), blob(repo, ps[0], path)
            if rxc is not None:
                kd += len(rxc.findall(now)) - len(rxc.findall(was))
            if lines:
                ld.update(Counter(now.split("\n")))
                ld.subtract(Counter(was.split("\n")))
    return (a, d, kd, ld) if hit else None


def nlines(t):
    return t.count("\n")


def regs(repo, base, head):
    ch = chain(repo, base, head)
    bad = []
    print(f"REGS chain: {len(ch)} seat merges on the first-parent chain {base[:10]}..{head[:10]}")
    for path, (rx, auth_base, auth_union) in REGS.items():
        rxc = re.compile(rx)
        b = blob(repo, base, path)
        lines, keys = nlines(b), len(rxc.findall(b))
        touched = []
        for m, u, s, own in ch:
            sd = seat_delta(repo, s, own, path, rxc=rxc)
            if sd is None:
                continue
            a, d, kd, _ = sd
            lines += a - d
            keys += kd
            touched.append(f"{s[:10]}(+{a}/-{d},keys{kd:+d})")
        h = blob(repo, head, path)
        got_lines, got_keys = nlines(h), len(rxc.findall(h))
        dups = sorted(k for k, n in Counter(rxc.findall(h)).items() if n > 1)
        ok = (got_lines, got_keys) == (lines, keys) == auth_union and (nlines(b), len(rxc.findall(b))) == auth_base and not dups
        print(f"  {'OK  ' if ok else 'FAIL'} {path}: base {nlines(b)}/{len(rxc.findall(b))} + {len(touched)} seat(s) "
              f"-> predicted {lines}/{keys}, authored {auth_union[0]}/{auth_union[1]}, union {got_lines}/{got_keys} "
              f"(lines/keys), duplicate keys {len(dups)}")
        print(f"       seats: {' '.join(touched) if touched else '(none)'}")
        for k in dups[:10]:
            print(f"       DUPLICATE KEY: {k}")
        if not ok:
            bad.append(path)
    print("REGS PASS" if not bad else f"REGS FAIL: {len(bad)} file(s): {' '.join(bad)}")
    return 0 if not bad else 3


def nuget(repo, base, head):
    ch = chain(repo, base, head)
    b, h = blob(repo, base, NUGET), blob(repo, head, NUGET)
    bad = []
    # (1) the line count, predicted from the chain exactly as regs() does
    lines, touched, expect = nlines(b), [], Counter()
    for m, u, s, own in ch:
        sd = seat_delta(repo, s, own, NUGET, lines=True)
        if sd is None:
            continue
        a, d, _, ld = sd
        lines += a - d
        touched.append(f"{s[:10]}(+{a}/-{d})")
        # (2) every non-blank line the seat's own commits changed must occur in the union exactly as often as base +
        # every seat's own delta of that line predicts (catches a lost hunk AND a doubled one)
        for ln, dl in ld.items():
            if ln.strip() and dl:
                expect[ln] += dl
    hc, bc = Counter(h.split("\n")), Counter(b.split("\n"))
    wrong = [ln for ln, dlt in expect.items() if hc[ln] != bc[ln] + dlt]
    print(f"NUGET seats touching {NUGET}: {' '.join(touched) if touched else '(none)'}")
    print(f"  lines: base {nlines(b)} predicted {lines} authored {NUGET_AUTHORED[1]} union {nlines(h)}")
    if not (nlines(h) == lines == NUGET_AUTHORED[1] and nlines(b) == NUGET_AUTHORED[0]):
        bad.append("line count")
    print(f"  changed-line multiset: {len(expect)} distinct lines checked, {len(wrong)} off")
    for ln in wrong[:15]:
        print(f"    OFF: union has {hc[ln]}, predicted {bc[ln] + expect[ln]}: {ln.strip()[:140]}")
    if wrong:
        bad.append("changed-line multiset")
    # (3) the named tokens, per seat
    for seat, toks in NUGET_TOKENS.items():
        for tok, want in toks:
            n = h.count(tok)
            print(f"  {'OK  ' if n == want else 'FAIL'} [{seat}] x{n} (want {want}): {tok.strip()[:110]}")
            if n != want:
                bad.append(f"token {tok.strip()[:40]}")
    # (4) the param block reads VerifyOnly then VersionSuffix, closed once
    pb = re.search(r"\nparam\(\n(.*?)\n\)\n", h, re.S)
    tail = [x.strip() for x in pb.group(1).split("\n")][-2:] if pb else []
    okpb = tail == ["[switch]$VerifyOnly,", "[string]$VersionSuffix"]
    print(f"  {'OK  ' if okpb else 'FAIL'} param block tail: {tail}")
    if not okpb:
        bad.append("param block")
    print("NUGET PASS" if not bad else f"NUGET FAIL: {'; '.join(bad)}")
    return 0 if not bad else 3


if __name__ == "__main__":
    mode, repo, base, head = sys.argv[1:5]
    base = git(repo, "rev-parse", f"{base}^{{commit}}").strip()
    head = git(repo, "rev-parse", f"{head}^{{commit}}").strip()
    sys.exit(regs(repo, base, head) if mode == "regs" else nuget(repo, base, head) if mode == "nuget" else 2)
