// Code generated by go2cs. DO NOT EDIT.
// Package-level variable initialization ordered to match Go's dependency order
// (types.Info.InitOrder), where C#'s static field initializer order (undefined
// across partial class files) would differ. Each initᴛ method lives beside its
// variable's declaration; C# runs every static field initializer before this
// constructor body, so all non-relocated dependencies are already initialized.
namespace go.runtime;

partial class pprof_package {
    static pprof_package() {
        initᴛgoroutineProfile();
        initᴛthreadcreateProfile();
        initᴛheapProfile();
        initᴛallocsProfile();
        initᴛblockProfile();
        initᴛmutexProfile();
        initᴛᴛtests();
    }

    // -tests hook: implemented by the internal test variant's relocated-initializer
    // file when its _test.go files need init-order relocation into this same class;
    // erased entirely (declaration and call) when unimplemented — the production
    // compile set excludes the *_test.cs implementation.
    static partial void initᴛᴛtests();
} // end pprof_package
