// RuntimeErrorPanic.cs - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// Use of this source code is governed by an MIT-style license
// that can be found in the LICENSE file.

using System;
using System.Diagnostics.CodeAnalysis;

namespace go.golib;

/// <summary>
/// Represents common runtime error messages thrown in Go environment.
/// </summary>
public static class RuntimeErrorPanic
{
    private const string RuntimeErrorMessage = "runtime error: ";

    private const string NilPointerDereferenceMessage = $"{RuntimeErrorMessage}invalid memory address or nil pointer dereference";
    /// <summary>
    /// A converter-emitted method-expression wrapper's OWN nil-receiver fault (an interface method
    /// expression `I.M(nil)`, or a promoted `(*Outer).M(nil)`): Go's wrapper faults there, and Go keeps
    /// the wrapper frame because its callee is sigpanic. Marked RaisedByWrapper for runtime's splice.
    /// </summary>
    public static PanicException WrapperNilReceiver()
    {
        return new PanicException(NilPointerDereferenceMessage) { FaultKind = PanicFaultKind.Memory, RaisedByWrapper = true };
    }

    /// <summary>
    /// Go's panicwrap: a value method called through a nil *T by the autogenerated `(*T).M` wrapper,
    /// with Go's message ("value method pkg.T.M called using nil *T pointer").
    /// </summary>
    public static PanicException Panicwrap(string message)
    {
        return new PanicException((@string)message) { FaultKind = PanicFaultKind.Panicwrap, RaisedByWrapper = true };
    }

    public static PanicException NilPointerDereference()
    {
        // A fault: Go reaches gopanic through sigpanic and panicmem (runtime's captureCallers splices both).
        return new PanicException(NilPointerDereferenceMessage) { FaultKind = PanicFaultKind.Memory };
    }

    private const string TokenArithmeticMessage =
        $"{RuntimeErrorMessage}unsafe pointer arithmetic on a managed pointer with no address "
        + "(a Go-layout byte offset into CLR-laid-out storage cannot be honoured)";
    /// <summary>
    /// The REFUSAL: a number derived by arithmetic from a pointer that has no machine address.
    /// </summary>
    /// <remarks>
    /// Refusing BY NAME, catchably, is the whole point. The alternative is not "it works" — it is a
    /// native box over a number that is not an address, and the first write through it takes the
    /// process down uncatchably, so a package reports nothing instead of reporting a failure.
    /// This says what happened, at the point it happened, and lets recover() see it.
    ///
    /// The underlying model question — a Go-layout offset landing on a managed reference slot in a
    /// CLR-auto-laid-out struct — is NOT answered here and is not meant to be: it stays open, and
    /// this makes it loud instead of fatal.
    /// </remarks>
    public static PanicException UnsafePointerArithmeticWithoutAddress()
    {
        return new PanicException(TokenArithmeticMessage);
    }

    private const string OrderTokenDereferenceMessage =
        $"{RuntimeErrorMessage}dereference of a managed pointer with no address "
        + "(*{0} over 0x{1} — the order token of a reference-bearing pointee at offset 0, Q44 §10.3 "
        + "arm 2a; a Go-layout byte offset into CLR-laid-out storage cannot be honoured)";
    /// <summary>
    /// The REFUSAL, arm 2a: a dereference of a native box whose address is a live box's ORDER
    /// TOKEN — a number no memory answers to.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The SIBLING of <see cref="UnsafePointerArithmeticWithoutAddress"/>, one arm over, and it
    /// exists because that one cannot fire here BY CONSTRUCTION: <c>IsTokenArithmetic</c> requires
    /// the number to differ from its allocation base, and at OFFSET 0 the number IS the base. So a
    /// reference-bearing pointee reinterpreted at offset 0 — Go's
    /// <c>*(*V)(unsafe.Add(unsafe.Pointer(&amp;in), 0))</c>, which reflect's own <c>setField</c>
    /// helper performs — reached a native box over a number that is not an address, and the write
    /// through it took the process down.
    /// </para>
    /// <para>
    /// ⚠ AT THE DEREFERENCE AND NOT AT THE CONVERSION, which is measured rather than preferred:
    /// refusing the conversion took SEVEN GolibTests red against an empty base, because the native
    /// box over a token is a deliberate carrier whose address IS the token (the full reading is at
    /// <c>ж.NativeBox.cs</c>'s <c>OrderTokenRefusal</c>). The failure MODE is the entire point,
    /// exactly as for the arithmetic twin: the write was an UNCATCHABLE AccessViolation, so a
    /// package reported nothing at all rather than reporting a failure — measured at reflect's
    /// TestIsZero, which ended the host after 195 tests had started. A caught panic the harness can
    /// attribute leaves the model question open and loud instead of fatal.
    /// </para>
    /// </remarks>
    public static PanicException UnsafePointerOrderTokenDereferenced(Type pointee, nuint token)
    {
        return new PanicException(string.Format(OrderTokenDereferenceMessage, pointee.Name, token.ToString("x")));
    }

    private const string NativeArrayViewMessage =
        $"{RuntimeErrorMessage}cannot view native memory as {{0}}: the address has no managed element "
        + "storage behind it, and a Go array is a window on a real managed array "
        + "(see docs/phase4/DESIGN-native-array-view.md)";
    /// <summary>
    /// The SAFETY FLOOR: a genuinely-native address converted to a pointer whose pointee is an
    /// <c>array&lt;E&gt;</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>array&lt;E&gt;</c> is a MANAGED struct whose first field is an <c>E[]</c> reference, and a
    /// native box materializes its value out of the pointed-at bytes — so the composition
    /// REINTERPRETS whatever lives at that address AS A MANAGED REFERENCE and dereferences it.
    /// Measured: zeroed memory reads a length of 0, a silent wrong answer; memory filled with 0xAB
    /// reads a length of -1414812757, the data bytes themselves, returned instead of faulting by
    /// luck. Refusing BY NAME converts a type-safety hole into a diagnostic that names its own
    /// cause, at the cost of turning latent-SILENT into latent-LOUD.
    /// </para>
    /// <para>
    /// It is reached only when the address carries NO provenance record — a pinned-managed address
    /// resolves to its box and never arrives here, which is what keeps Go-legal reinterprets over
    /// pinned storage working. The message names the shape rather than the site because the site is
    /// a conversion the reader has to find in the emitted C#; the design document is where the fork
    /// and its remedy are written down.
    /// </para>
    /// </remarks>
    public static PanicException NativeArrayViewWithoutElementStorage(Type arrayType)
    {
        Type[] arguments = arrayType.IsGenericType ? arrayType.GetGenericArguments() : [];
        string shape = arguments.Length == 1 ? $"array<{arguments[0].Name}>" : arrayType.Name;

        return new PanicException(string.Format(NativeArrayViewMessage, shape));
    }

    private const string IndexOutOfRangeMessage = $"{RuntimeErrorMessage}index out of range [{{0}}] with length {{1}}";

    // Go's boundsNegErrorFmt for boundsIndex: a NEGATIVE signed index prints without the length.
    private const string IndexNegativeMessage = $"{RuntimeErrorMessage}index out of range [{{0}}]";

    // runtime's boundsErrorCode for `s[x], 0 <= x < len(s) failed` (runtime/error.go: boundsIndex).
    private const byte BoundsIndex = 0;

    /// <summary>
    /// Go's panic for a SIGNED index out of range: <c>runtime.boundsError{x: index, signed: true,
    /// y: length, code: boundsIndex}</c>, which goPanicIndex raises and which satisfies
    /// <c>runtime.Error</c>.
    /// </summary>
    /// <remarks>
    /// The value comes from <see cref="BoundsErrorValue"/>, so its <c>Error()</c> is Go's own
    /// formatting: <c>index out of range [2] with length 2</c>, and for a NEGATIVE index
    /// <c>index out of range [-1]</c> with no length. Unregistered, the fallback string carries the
    /// same text; see <see cref="BoundsErrorValue"/> for that bound.
    /// </remarks>
    public static PanicException IndexOutOfRange(int64 index, int64 length)
    {
        RuntimePanicCheck.Check("index out of range");
        return new PanicException(BoundsErrorValue?.Invoke(index, length, true, BoundsIndex) ??
                                  string.Format(index < 0 ? IndexNegativeMessage : IndexOutOfRangeMessage, index, length));
    }

    /// <summary>
    /// Go's panic for an UNSIGNED index out of range: <c>runtime.boundsError{x: index, signed: false,
    /// y: length, code: boundsIndex}</c>, goPanicIndexU's value. An unsigned index is never negative,
    /// so the text always carries the length: <c>index out of range [18446744073709551615] with
    /// length 2</c>, where a signed reading of the same bits would print <c>[-1]</c>.
    /// </summary>
    public static PanicException IndexOutOfRange(uint64 index, int64 length)
    {
        RuntimePanicCheck.Check("index out of range");
        return new PanicException(BoundsErrorValue?.Invoke(unchecked((int64)index), length, false, BoundsIndex) ??
                                  string.Format(IndexOutOfRangeMessage, index, length));
    }

    /// <summary>
    /// Supplies the Go runtime's <c>runtime.boundsError</c> for (x, y, signed, code), the value Go's
    /// goPanicIndex family panics with.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Registered by the runtime package (its <c>panicvalues_impl.cs</c> bridge) for the same reason as
    /// <see cref="IntegerDivideByZeroValue"/>: golib sits UNDER <c>runtime</c> and cannot name the type.
    /// runtime's TestRuntimePanicWithRuntimeError asserts <c>recover().(runtime.Error)</c> on
    /// <c>s[2]</c>.
    /// </para>
    /// <para>
    /// THE DESIGN LIMIT, shared by every hook here (this one, <see cref="PlainErrorValue"/> and
    /// <see cref="IntegerDivideByZeroValue"/>): a hook is registered by runtime's module initializer,
    /// so a program whose import closure never reaches runtime has nothing registered, and these
    /// panics recover as a STRING rather than a value satisfying <c>runtime.Error</c>. The TEXT is
    /// Go's either way; only the type differs. Measured (COORD review, 2026-09-28): a program with no
    /// imports has no runtime.dll in its output and recovers strings, while one importing
    /// <c>errors</c> matches Go exactly, because every package's import hooks force its imports'
    /// initializers and errors reaches runtime through internal/reflectlite (so do strings, io,
    /// strconv, sort, fmt, os and sync). Only closures made entirely of leaf packages (math,
    /// math/bits, unicode, unicode/utf8, cmp, unsafe) stay unregistered.
    /// </para>
    /// </remarks>
    public static Func<long, long, bool, byte, object>? BoundsErrorValue { get; set; }

    /// <summary>
    /// Supplies the Go runtime's <c>runtime.plainError</c> for a message: the value Go panics with
    /// for a nil-map write, a close of a closed or nil channel, a send on a closed channel and
    /// makechan's size check.
    /// </summary>
    /// <remarks>
    /// Registered by the runtime package, as <see cref="BoundsErrorValue"/> is. A plainError prints
    /// as its bare text (no <c>runtime error: </c> prefix, exactly as Go prints it), so the panic TEXT
    /// is what these sites raised before; only the recovered value's TYPE changes, from a string to
    /// one satisfying <c>runtime.Error</c>. Unregistered, the plain message stands.
    /// </remarks>
    public static Func<string, object>? PlainErrorValue { get; set; }

    /// <summary>
    /// A Go runtime panic whose value is <c>runtime.plainError(message)</c>.
    /// </summary>
    public static PanicException PlainError(string message)
    {
        return new PanicException(PlainErrorValue?.Invoke(message) ?? message);
    }

    private const string MakeChanSizeOutOfRangeMessage = "makechan: size out of range";

    /// <summary>
    /// Go's panic for <c>make(chan T, n)</c> with a size Go rejects (runtime/chan.go's makechan): a
    /// negative <c>n</c>, or one whose buffer (<c>elem.Size_ * n</c>) overflows or exceeds
    /// <c>maxAlloc - hchanSize</c>. The CLR raised an ArgumentOutOfRangeException or an
    /// OverflowException there, and recover() sees neither.
    /// </summary>
    public static PanicException MakeChanSizeOutOfRange()
    {
        return PlainError(MakeChanSizeOutOfRangeMessage);
    }

    /// <summary>
    /// A NAMED platform bound, not a Go panic: <c>make(chan T, n)</c> with a size Go ACCEPTS but a
    /// managed ring buffer cannot hold (more than <see cref="Array.MaxLength"/> elements; for a
    /// zero-size element Go has no memory bound at all). Recoverable and named, never an escaping
    /// OverflowException.
    /// </summary>
    public static PanicException MakeChanSizeBeyondManagedBuffer(nint size)
    {
        return new PanicException($"makechan: size {size} exceeds the {Array.MaxLength}-element buffer a managed channel can hold (Go accepts it for this element type; a platform bound of go2cs)");
    }

    private const string SliceBoundsOutOfRangeMessage = $"{RuntimeErrorMessage}slice bounds out of range ";
    public static PanicException SliceBoundsOutOfRange(int64 low, int64 high, int64 max, int64 capacity)
    {
        RuntimePanicCheck.Check("slice bounds out of range");
        // Mirrors the Go runtime's message shapes for a slice expression s[low:high:max]
        string bounds;

        if (max > capacity)
            bounds = $"[::{max}] with capacity {capacity}";
        else if (high > max)
            bounds = max == capacity ? $"[:{high}] with capacity {capacity}" : $"[:{high}:{max}]";
        else if (low < 0)
            bounds = $"[{low}:]";
        else
            bounds = $"[{low}:{high}]";

        return new PanicException(SliceBoundsOutOfRangeMessage + bounds);
    }

    /// <summary>
    /// Go's panic for a STRING slice expression <c>s[low:high]</c> out of range, in the Go runtime's
    /// string shapes: <c>[:5] with length 3</c> when high passes the length, <c>[4:3]</c> when low
    /// passes high. A string has a length, not a capacity, which is the only difference from
    /// <see cref="SliceBoundsOutOfRange"/>.
    /// </summary>
    public static PanicException StringSliceBoundsOutOfRange(int64 low, int64 high, int64 length)
    {
        RuntimePanicCheck.Check("slice bounds out of range");
        string bounds = high > length ? $"[:{high}] with length {length}" : low < 0 ? $"[{low}:]" : $"[{low}:{high}]";
        return new PanicException(SliceBoundsOutOfRangeMessage + bounds);
    }

    private const string ArrayConversionLengthMessage = $"{RuntimeErrorMessage}cannot convert slice with length {{0}} to array or pointer to array with length {{1}}";

    /// <summary>
    /// Go's panic for a <c>[N]T(s)</c> / <c>(*[N]T)(s)</c> conversion whose source slice is shorter
    /// than <c>N</c> — the message the runtime itself prints, raised as a recoverable panic.
    /// </summary>
    public static PanicException ArrayConversionLength(int64 sourceLength, int64 length)
    {
        RuntimePanicCheck.Check("slice length too short to convert to array or pointer to array");
        return new PanicException(string.Format(ArrayConversionLengthMessage, sourceLength, length));
    }

    private const string IntegerDivideByZeroMessage = $"{RuntimeErrorMessage}integer divide by zero";

    /// <summary>
    /// Supplies the Go runtime's OWN divide-by-zero panic value (<c>runtime.divideError</c>, whose
    /// dynamic type is the unexported <c>runtime.errorString</c>).
    /// </summary>
    /// <remarks>
    /// Go's compiler lowers an integer division to a zero check plus <c>runtime.panicdivide()</c>, so
    /// <c>recover()</c> yields a value satisfying <c>runtime.Error</c> — math/bits' TestDiv32PanicZero
    /// asserts exactly that (<c>err.(runtime.Error)</c>) on the panic raised by the IMPLICIT hardware
    /// division in <c>Div32</c>, unlike Div/Div64 which panic explicitly. golib sits UNDER the converted
    /// <c>runtime</c> package and so cannot name that value; the runtime package registers it here
    /// (see its <c>panicvalues_impl.cs</c> bridge), leaving this layer dependency-free. When nothing has
    /// registered — a converted program that never links <c>runtime</c> — the panic falls back to the
    /// plain message below, which still reads and prints identically and only loses the type assertion.
    /// </remarks>
    public static Func<object>? IntegerDivideByZeroValue { get; set; }

    /// <summary>
    /// A panic Go raises from a RUNTIME frame, reproduced by hand-owned C# (unsafe.Slice's length checks,
    /// runtime's hash refusals; reflect's nil-map write and nil-channel close raise Go's plainError through PlainError, which is equally unspliced). The value is converted exactly
    /// as <see cref="builtin.panic"/> converts it, but the panic keeps the default fault kind
    /// (<see cref="PanicFaultKind.Unmodelled"/>), so runtime.Callers does not splice it as Go source.
    /// </summary>
    public static PanicException RuntimeRaised(object? state)
    {
        return new PanicException(state is string s ? (@string)s : state);
    }

    public static PanicException IntegerDivideByZero()
    {
        // Go reaches gopanic through panicdivide, the compiler's zero check (runtime's captureCallers splices it).
        return new PanicException(IntegerDivideByZeroValue?.Invoke() ?? IntegerDivideByZeroMessage) { FaultKind = PanicFaultKind.Divide };
    }

    private const string NegativeShiftAmountMessage = $"{RuntimeErrorMessage}negative shift amount";

    /// <summary>
    /// The <c>runtime.shiftError</c> value (<c>runtime.Error</c>), as the converted runtime registers
    /// it; see <see cref="IntegerDivideByZeroValue"/>, which this mirrors.
    /// </summary>
    public static Func<object>? ShiftErrorValue { get; set; }

    /// <summary>
    /// Go's panic for a shift whose signed count is negative at run time (runtime.panicshift), raised by
    /// golib's signed-count <c>GoShift</c> overloads.
    /// </summary>
    public static PanicException NegativeShiftAmount()
    {
        RuntimePanicCheck.Check("negative shift amount");
        return new PanicException(ShiftErrorValue?.Invoke() ?? NegativeShiftAmountMessage);
    }

    private const string ComparingUncomparableTypeMessage = $"{RuntimeErrorMessage}comparing uncomparable type {{0}}";

    /// <summary>
    /// Go's panic for <c>==</c> between two interface values whose shared dynamic type has no equal
    /// algorithm — a slice, map or func, or a struct/array that transitively contains one.
    /// </summary>
    /// <param name="goTypeName">Dynamic type, spelled as Go spells it (<c>map[string]int</c>, <c>[1][]int</c>, <c>main.withSlice</c>).</param>
    /// <remarks>
    /// Recoverable, like every other runtime error minted here: Go raises this from
    /// <c>runtime.panicunsafe</c>-family code with a <c>runtime.Error</c> value, so a
    /// <c>defer func(){ recover() }()</c> observes it and prints the message verbatim. Measured
    /// against go1.23.12 for each shape the caller gates (see <c>builtin.AreEqual</c>).
    /// </remarks>
    public static PanicException ComparingUncomparableType(string goTypeName)
    {
        return new PanicException(string.Format(ComparingUncomparableTypeMessage, goTypeName));
    }

    private const string MakeSliceLenOutOfRangeMessage = $"{RuntimeErrorMessage}makeslice: len out of range";
    public static PanicException MakeSliceLenOutOfRange()
    {
        return new PanicException(MakeSliceLenOutOfRangeMessage);
    }

    private const string RangeFunctionContinuedMessage = $"{RuntimeErrorMessage}range function continued iteration after function for loop body returned false";

    /// <summary>
    /// Go's panic for a range-over-func sequence that calls <c>yield</c> again after the loop body
    /// answered false (runtime/panic.go's <c>rangeDoneError</c>).
    /// </summary>
    public static PanicException RangeFunctionContinued()
    {
        return new PanicException(RangeFunctionContinuedMessage);
    }

    private const string MakeSliceCapOutOfRangeMessage = $"{RuntimeErrorMessage}makeslice: cap out of range";
    public static PanicException MakeSliceCapOutOfRange()
    {
        return new PanicException(MakeSliceCapOutOfRangeMessage);
    }

    /// <summary>
    /// Converts a .NET exception that corresponds to a Go runtime panic into a <see cref="PanicException"/>,
    /// so it can be recovered with <c>recover()</c> and reported like a Go panic. Returns <c>false</c>
    /// (leaving the exception to propagate unchanged) for exceptions that are not Go runtime panics.
    /// </summary>
    /// <param name="ex">Exception to inspect.</param>
    /// <param name="panic">Resulting panic when the exception maps to a Go runtime panic.</param>
    /// <returns><c>true</c> if <paramref name="ex"/> is (or maps to) a Go panic; otherwise <c>false</c>.</returns>
    /// <remarks>
    /// This is the ONE place a .NET exception becomes a Go panic, so it is also where the panic's
    /// origin is snapshotted (<see cref="PanicException.PanicTrace"/>) — a mapped runtime error is
    /// synthesized HERE and was never thrown at the fault site, so only <paramref name="ex"/> carries
    /// those frames, and once this returns they are the caller's last chance to be recorded. Doing it
    /// at the adoption point rather than in each adopter is what lets a panic that passes through NO
    /// <c>GoFunc</c> at all — a function that never defers, so nothing wraps it — still report where
    /// it faulted. The snapshot is once-only, so a panic re-adopted by each enclosing frame keeps the
    /// innermost (deepest) origin, and nothing is computed on a non-panicking path.
    /// </remarks>
    public static bool TryAsPanic(Exception ex, [NotNullWhen(true)] out PanicException? panic)
    {
        switch (ex)
        {
            case PanicException panicException:
                panic = panicException;
                panic.CaptureThrowSite(ex);
                return true;
            case DivideByZeroException:
                // Go: integer division or modulo by zero panics with a runtime error. .NET raises
                // DivideByZeroException for the same operation; map it so recover() behaves like Go.
                panic = IntegerDivideByZero();
                panic.CaptureThrowSite(ex);
                return true;
            case NullReferenceException:
                // Go: dereferencing a nil pointer panics with "runtime error: invalid memory address
                // or nil pointer dereference" — a RECOVERABLE panic that real Go code relies on
                // (sync's TestNilPool calls Get/Put on a nil *Pool and requires recover() to catch
                // it). The converted equivalent — reading `Ꮡp.Value` through a nil ж<T>, or any nil
                // reference deref in emitted code — raises NullReferenceException, which recover()
                // could not see, so the panic escaped as an unrecoverable infrastructure error.
                // Mapping it here gives recover() Go's behavior and prints Go's message verbatim.
                panic = NilPointerDereference();
                panic.CaptureThrowSite(ex);
                return true;
            default:
                panic = null;
                return false;
        }
    }
}
