// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.debug;

using static go.debug.dwarf_package;
using io = io_package;
using strings = strings_package;
using testing = testing_package;
using dwarf = go.debug.dwarf_package;
using go.debug;
using static go.debug.dwarf_internal_test_package;

partial class dwarf_test_package {

internal static ж<dwarf.LineFile> file1C = Ꮡ(new LineFile(Name: "/home/austin/go.dev/src/debug/dwarf/testdata/line1.c"u8));
internal static ж<dwarf.LineFile> file1H = Ꮡ(new LineFile(Name: "/home/austin/go.dev/src/debug/dwarf/testdata/line1.h"u8));
internal static ж<dwarf.LineFile> file2C = Ꮡ(new LineFile(Name: "/home/austin/go.dev/src/debug/dwarf/testdata/line2.c"u8));

public static void TestLineELFGCC(ж<testing.T> Ꮡt) {
    // Generated by:
    //   # gcc --version | head -n1
    //   gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
    //   # gcc -g -o line-gcc.elf line*.c
    // Line table based on readelf --debug-dump=rawline,decodedline
    var want = new dwarf.LineEntry[]{
        new(Address: 0x40059d, File: file1H, Line: 2, IsStmt: true),
        new(Address: 0x4005a5, File: file1H, Line: 2, IsStmt: true),
        new(Address: 0x4005b4, File: file1H, Line: 5, IsStmt: true),
        new(Address: 0x4005bd, File: file1H, Line: 6, IsStmt: true, Discriminator: 2),
        new(Address: 0x4005c7, File: file1H, Line: 5, IsStmt: true, Discriminator: 2),
        new(Address: 0x4005cb, File: file1H, Line: 5, IsStmt: false, Discriminator: 1),
        new(Address: 0x4005d1, File: file1H, Line: 7, IsStmt: true),
        new(Address: 0x4005e7, File: file1C, Line: 6, IsStmt: true),
        new(Address: 0x4005eb, File: file1C, Line: 7, IsStmt: true),
        new(Address: 0x4005f5, File: file1C, Line: 8, IsStmt: true),
        new(Address: 0x4005ff, File: file1C, Line: 9, IsStmt: true),
        new(Address: 0x400601, EndSequence: true),
        new(Address: 0x400601, File: file2C, Line: 4, IsStmt: true),
        new(Address: 0x400605, File: file2C, Line: 5, IsStmt: true),
        new(Address: 0x40060f, File: file2C, Line: 6, IsStmt: true),
        new(Address: 0x400611, EndSequence: true)
    }.slice();
    var files = new slice<ж<dwarf.LineFile>>[]{new ж<dwarf.LineFile>[]{default!, file1H, file1C}.slice(), new ж<dwarf.LineFile>[]{default!, file2C}.slice()}.slice();
    testLineTable(Ꮡt, want, files, elfData(Ꮡt, testdataLineGccElfˢ));
}

public static void TestLineELFGCCZstd(ж<testing.T> Ꮡt) {
    // Generated by:
    //   # gcc --version | head -n1
    //   gcc (Debian 12.2.0-10) 12.2.0
    //   # gcc -g -no-pie -Wl,--compress-debug-sections=zstd line*.c
    var zfile1H = Ꮡ(new LineFile(Name: "/home/iant/go/src/debug/dwarf/testdata/line1.h"u8));
    var zfile1C = Ꮡ(new LineFile(Name: "/home/iant/go/src/debug/dwarf/testdata/line1.c"u8));
    var zfile2C = Ꮡ(new LineFile(Name: "/home/iant/go/src/debug/dwarf/testdata/line2.c"u8));
    // Line table based on readelf --debug-dump=rawline,decodedline
    var want = new dwarf.LineEntry[]{
        new(Address: 0x401126, File: zfile1H, Line: 2, Column: 1, IsStmt: true),
        new(Address: 0x40112a, File: zfile1H, Line: 5, Column: 8, IsStmt: true),
        new(Address: 0x401131, File: zfile1H, Line: 5, Column: 2, IsStmt: true),
        new(Address: 0x401133, File: zfile1H, Line: 6, Column: 10, IsStmt: true, Discriminator: 3),
        new(Address: 0x40113d, File: zfile1H, Line: 5, Column: 22, IsStmt: true, Discriminator: 3),
        new(Address: 0x401141, File: zfile1H, Line: 5, Column: 15, IsStmt: true, Discriminator: 1),
        new(Address: 0x401147, File: zfile1H, Line: 7, Column: 1, IsStmt: true),
        new(Address: 0x40114b, File: zfile1C, Line: 6, Column: 1, IsStmt: true),
        new(Address: 0x40114f, File: zfile1C, Line: 7, Column: 2, IsStmt: true),
        new(Address: 0x401159, File: zfile1C, Line: 8, Column: 2, IsStmt: true),
        new(Address: 0x401168, File: zfile1C, Line: 9, Column: 1, IsStmt: true),
        new(Address: 0x40116a, EndSequence: true),
        new(Address: 0x40116a, File: zfile2C, Line: 4, Column: 1, IsStmt: true),
        new(Address: 0x40116e, File: zfile2C, Line: 5, Column: 2, IsStmt: true),
        new(Address: 0x40117d, File: zfile2C, Line: 6, Column: 1, IsStmt: true),
        new(Address: 0x401180, EndSequence: true)
    }.slice();
    var files = new slice<ж<dwarf.LineFile>>[]{
        new ж<dwarf.LineFile>[]{zfile1C, zfile1H, zfile1C}.slice(),
        new ж<dwarf.LineFile>[]{zfile2C, zfile2C}.slice()
    }.slice();
    testLineTable(Ꮡt, want, files, elfData(Ꮡt, testdataLineGccZstdElfˢ));
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string homeAustinGoDevˢ = "/home/austin/go.dev/"u8;
internal static readonly @string cWorkdirGoˢ = "C:\\workdir\\go\\"u8;
internal static readonly @string testdataLineGccWinBinˢ = "testdata/line-gcc-win.bin"u8;

public static void TestLineGCCWindows(ж<testing.T> Ꮡt) {
    // Generated by:
    //   > gcc --version
    //   gcc (tdm64-1) 4.9.2
    //   > gcc -g -o line-gcc-win.bin line1.c C:\workdir\go\src\debug\dwarf\testdata\line2.c
    ж<dwarf.LineFile> toWindows(ж<dwarf.LineFile> lf) {
        ref var lf2 = ref heap<dwarf.LineFile>(out var Ꮡlf2);
        lf2 = lf.Value;
        lf2.Name = strings.Replace(lf2.Name, homeAustinGoDevˢ, cWorkdirGoˢ, -1);
        lf2.Name = strings.Replace(lf2.Name, "/"u8, "\\"u8, -1);
        return Ꮡlf2;
    }
    var file1CΔ1 = toWindows(dwarf_test_package.file1C);
    var file1HΔ1 = toWindows(dwarf_test_package.file1H);
    var file2CΔ1 = toWindows(dwarf_test_package.file2C);
    // Line table based on objdump --dwarf=rawline,decodedline
    var want = new dwarf.LineEntry[]{
        new(Address: 0x401530, File: file1HΔ1, Line: 2, IsStmt: true),
        new(Address: 0x401538, File: file1HΔ1, Line: 5, IsStmt: true),
        new(Address: 0x401541, File: file1HΔ1, Line: 6, IsStmt: true, Discriminator: 3),
        new(Address: 0x40154b, File: file1HΔ1, Line: 5, IsStmt: true, Discriminator: 3),
        new(Address: 0x40154f, File: file1HΔ1, Line: 5, IsStmt: false, Discriminator: 1),
        new(Address: 0x401555, File: file1HΔ1, Line: 7, IsStmt: true),
        new(Address: 0x40155b, File: file1CΔ1, Line: 6, IsStmt: true),
        new(Address: 0x401563, File: file1CΔ1, Line: 6, IsStmt: true),
        new(Address: 0x401568, File: file1CΔ1, Line: 7, IsStmt: true),
        new(Address: 0x40156d, File: file1CΔ1, Line: 8, IsStmt: true),
        new(Address: 0x401572, File: file1CΔ1, Line: 9, IsStmt: true),
        new(Address: 0x401578, EndSequence: true),
        new(Address: 0x401580, File: file2CΔ1, Line: 4, IsStmt: true),
        new(Address: 0x401588, File: file2CΔ1, Line: 5, IsStmt: true),
        new(Address: 0x401595, File: file2CΔ1, Line: 6, IsStmt: true),
        new(Address: 0x40159b, EndSequence: true)
    }.slice();
    var files = new slice<ж<dwarf.LineFile>>[]{new ж<dwarf.LineFile>[]{default!, file1HΔ1, file1CΔ1}.slice(), new ж<dwarf.LineFile>[]{default!, file2CΔ1}.slice()}.slice();
    testLineTable(Ꮡt, want, files, peData(Ꮡt, testdataLineGccWinBinˢ));
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string testdataLineClangElfˢ = "testdata/line-clang.elf"u8;

public static void TestLineELFClang(ж<testing.T> Ꮡt) {
    // Generated by:
    //   # clang --version | head -n1
    //   Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
    //   # clang -g -o line-clang.elf line*.
    var want = new dwarf.LineEntry[]{
        new(Address: 0x400530, File: file1C, Line: 6, IsStmt: true),
        new(Address: 0x400534, File: file1C, Line: 7, IsStmt: true, PrologueEnd: true),
        new(Address: 0x400539, File: file1C, Line: 8, IsStmt: true),
        new(Address: 0x400545, File: file1C, Line: 9, IsStmt: true),
        new(Address: 0x400550, File: file1H, Line: 2, IsStmt: true),
        new(Address: 0x400554, File: file1H, Line: 5, IsStmt: true, PrologueEnd: true),
        new(Address: 0x400568, File: file1H, Line: 6, IsStmt: true),
        new(Address: 0x400571, File: file1H, Line: 5, IsStmt: true),
        new(Address: 0x400581, File: file1H, Line: 7, IsStmt: true),
        new(Address: 0x400583, EndSequence: true),
        new(Address: 0x400590, File: file2C, Line: 4, IsStmt: true),
        new(Address: 0x4005a0, File: file2C, Line: 5, IsStmt: true, PrologueEnd: true),
        new(Address: 0x4005a7, File: file2C, Line: 6, IsStmt: true),
        new(Address: 0x4005b0, EndSequence: true)
    }.slice();
    var files = new slice<ж<dwarf.LineFile>>[]{new ж<dwarf.LineFile>[]{default!, file1C, file1H}.slice(), new ж<dwarf.LineFile>[]{default!, file2C}.slice()}.slice();
    testLineTable(Ꮡt, want, files, elfData(Ꮡt, testdataLineClangElfˢ));
}

public static void TestLineRnglists(ж<testing.T> Ꮡt) {
    // Test a newer file, generated by clang.
    var @file = Ꮡ(new LineFile(Name: "/usr/local/google/home/iant/foo.c"u8));
    var want = new dwarf.LineEntry[]{
        new(Address: 0x401020, File: @file, Line: 12, IsStmt: true),
        new(Address: 0x401020, File: @file, Line: 13, Column: 12, IsStmt: true, PrologueEnd: true),
        new(Address: 0x401022, File: @file, Line: 13, Column: 7),
        new(Address: 0x401024, File: @file, Line: 17, Column: 1, IsStmt: true),
        new(Address: 0x401027, File: @file, Line: 16, Column: 10, IsStmt: true),
        new(Address: 0x40102c, EndSequence: true),
        new(Address: 0x401000, File: @file, Line: 2, IsStmt: true),
        new(Address: 0x401000, File: @file, Line: 6, Column: 17, IsStmt: true, PrologueEnd: true),
        new(Address: 0x401002, File: @file, Line: 6, Column: 3),
        new(Address: 0x401019, File: @file, Line: 9, Column: 3, IsStmt: true),
        new(Address: 0x40101a, File: @file, Line: 0, Column: 3),
        new(Address: 0x40101c, File: @file, Line: 9, Column: 3),
        new(Address: 0x40101d, EndSequence: true)
    }.slice();
    var files = new slice<ж<dwarf.LineFile>>[]{new ж<dwarf.LineFile>[]{@file}.slice()}.slice();
    testLineTable(Ꮡt, want, files, elfData(Ꮡt, testdataRnglistxElfˢ));
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly object dReaderNextˢ = (@string)"d.Reader().Next:"u8;
internal static readonly object dLineReaderˢ = (@string)"d.LineReader:"u8;
internal static readonly object lrNextˢ = (@string)"lr.Next:"u8;
internal static readonly object lrNextAfterResetFailedˢ = (@string)"lr.Next after Reset failed:"u8;
internal static readonly object lrNextAfterResetReturnedˢ = (@string)"lr.Next after Reset returned"u8;
internal static readonly object insteadOfˢ = (@string)"instead of"u8;
internal static readonly object expectedIoEofAfterSeekToˢ = (@string)"expected io.EOF after seek to end, got"u8;
internal static readonly object lrNextAfterSeekToˢ = (@string)"lr.Next after seek to"u8;
internal static readonly object failedˢ = (@string)"failed:"u8;
internal static readonly object returnedˢ = (@string)"returned"u8;

public static void TestLineSeek(ж<testing.T> Ꮡt) {
    var d = elfData(Ꮡt, testdataLineGccElfˢ);
    // Get the line table for the first CU.
    var (cu, err) = d.Reader().Next();
    if (err != default!) {
        Ꮡt.Fatal(dReaderNextˢ, err);
    }
    (var lr, err) = d.LineReader(cu);
    if (err != default!) {
        Ꮡt.Fatal(dLineReaderˢ, err);
    }
    // Read entries forward.
    ref var line = ref heap(new dwarf.LineEntry(), out var Ꮡline);
    slice<dwarf.LineReaderPos> posTable = default!;
    slice<dwarf.LineEntry> table = default!;
    while (ᐧ) {
        posTable = append(posTable, lr.Tell());
        var errΔ1 = lr.Next(Ꮡline);
        if (errΔ1 != default!) {
            if (AreEqual(errΔ1, io.EOF)) {
                break;
            }
            Ꮡt.Fatal(lrNextˢ, errΔ1);
        }
        table = append(table, line);
    }
    // Test that Reset returns to the first line.
    lr.Reset();
    {
        var errΔ2 = lr.Next(Ꮡline); if (errΔ2 != default!){
            Ꮡt.Fatal(lrNextAfterResetFailedˢ, errΔ2);
        } else 
        if (line != table[0]) {
            Ꮡt.Fatal(lrNextAfterResetReturnedˢ, line, insteadOfˢ, table[0]);
        }
    }
    // Check that entries match when seeking backward.
    for (nint i = len(posTable) - 1; i >= 0; i--) {
        lr.Seek(posTable[i]);
        var errΔ3 = lr.Next(Ꮡline);
        if (i == len(posTable) - 1){
            if (!AreEqual(errΔ3, io.EOF)) {
                Ꮡt.Fatal(expectedIoEofAfterSeekToˢ, errΔ3);
            }
        } else 
        if (errΔ3 != default!){
            Ꮡt.Fatal(lrNextAfterSeekToˢ, posTable[i], failedˢ, errΔ3);
        } else 
        if (line != table[i]) {
            Ꮡt.Fatal(lrNextAfterSeekToˢ, posTable[i], returnedˢ, line, insteadOfˢ, table[i]);
        }
    }
    // Check that seeking to a PC returns the right line.
    {
        var errΔ4 = lr.SeekPC(table[0].Address - 1, Ꮡline); if (!AreEqual(errΔ4, ErrUnknownPC)) {
            Ꮡt.Fatalf("lr.SeekPC to %#x returned %v instead of ErrUnknownPC"u8, table[0].Address - 1, errΔ4);
        }
    }
    foreach (var (i, testLine) in table) {
        if (testLine.EndSequence) {
            {
                var errΔ5 = lr.SeekPC(testLine.Address, Ꮡline); if (!AreEqual(errΔ5, ErrUnknownPC)) {
                    Ꮡt.Fatalf("lr.SeekPC to %#x returned %v instead of ErrUnknownPC"u8, testLine.Address, errΔ5);
                }
            }
            continue;
        }
        var nextPC = table[i + 1].Address;
        for (var pc = testLine.Address; pc < nextPC; pc++) {
            {
                var errΔ6 = lr.SeekPC(pc, Ꮡline); if (errΔ6 != default!){
                    Ꮡt.Fatalf("lr.SeekPC to %#x failed: %v"u8, pc, errΔ6);
                } else 
                if (line != testLine) {
                    Ꮡt.Fatalf("lr.SeekPC to %#x returned %v instead of %v"u8, pc, line, testLine);
                }
            }
        }
    }
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly object drNextˢ = (@string)"dr.Next:"u8;
internal static readonly @string cCrossdevˢ = "C:/crossdev/"u8;
internal static readonly object fileTablesDoNotMatchGotˢ = (@string)"File tables do not match. Got:"u8;
internal static readonly object wantˢ = (@string)"Want:"u8;
internal static readonly object lineTablesDoNotMatchGotˢ = (@string)"Line tables do not match. Got:"u8;

internal static void testLineTable(ж<testing.T> Ꮡt, slice<dwarf.LineEntry> want, slice<slice<ж<dwarf.LineFile>>> files, ж<dwarf.Data> Ꮡd) {
    ref var t = ref Ꮡt.DerefOrNull();
    ref var d = ref Ꮡd.DerefOrNull();

    // Get line table from d.
    slice<dwarf.LineEntry> got = default!;
    var dr = Ꮡd.Reader();
    while (ᐧ) {
        var (ent, err) = dr.Next();
        if (err != default!){
            Ꮡt.Fatal(drNextˢ, err);
        } else 
        if (ent == nil) {
            break;
        }
        if ((~ent).Tag != TagCompileUnit) {
            dr.SkipChildren();
            continue;
        }
        // Ignore system compilation units (this happens in
        // the Windows binary). We'll still decode the line
        // table, but won't check it.
        @string name = ent.Val(AttrName)._<@string>();
        var ignore = strings.HasPrefix(name, cCrossdevˢ) || strings.HasPrefix(name, "../../"u8);
        // Decode CU's line table.
        (var lr, err) = Ꮡd.LineReader(ent);
        if (err != default!){
            Ꮡt.Fatal(dLineReaderˢ, err);
        } else 
        if (lr == nil) {
            continue;
        }
        while (ᐧ) {
            ref var line = ref heap(new dwarf.LineEntry(), out var Ꮡline);
            var errΔ1 = lr.Next(Ꮡline);
            if (errΔ1 != default!) {
                if (AreEqual(errΔ1, io.EOF)) {
                    break;
                }
                Ꮡt.Fatal(lrNextˢ, errΔ1);
            }
            // Ignore sources from the Windows build environment.
            if (ignore) {
                continue;
            }
            got = append(got, line);
        }
        // Check file table.
        if (!ignore) {
            if (!compareFiles(files[0], lr.Files())) {
                Ꮡt.Log(fileTablesDoNotMatchGotˢ);
                dumpFiles(Ꮡt, lr.Files());
                Ꮡt.Log(wantˢ);
                dumpFiles(Ꮡt, files[0]);
                Ꮡt.Fail();
            }
            files = files[1..];
        }
    }
    // Compare line tables.
    if (!compareLines(Ꮡt, got, want)) {
        Ꮡt.Log(lineTablesDoNotMatchGotˢ);
        dumpLines(Ꮡt, got);
        Ꮡt.Log(wantˢ);
        dumpLines(Ꮡt, want);
        Ꮡt.FailNow();
    }
}

internal static bool compareFiles(slice<ж<dwarf.LineFile>> a, slice<ж<dwarf.LineFile>> b) {
    if (len(a) != len(b)) {
        return false;
    }
    foreach (var (i, _) in a) {
        if (a[i] == nil && b[i] == nil) {
            continue;
        }
        if (a[i] != nil && b[i] != nil && (~a[i]).Name == (~b[i]).Name) {
            continue;
        }
        return false;
    }
    return true;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string nilˢ = "<nil>"u8;

internal static void dumpFiles(ж<testing.T> Ꮡt, slice<ж<dwarf.LineFile>> files) {
    foreach (var (i, f) in files) {
        @string name = nilˢ;
        if (f != nil) {
            name = f.Value.Name;
        }
        Ꮡt.Logf("  %d %s"u8, i, name);
    }
}

internal static bool compareLines(ж<testing.T> Ꮡt, slice<dwarf.LineEntry> a, slice<dwarf.LineEntry> b) {
    Ꮡt.Helper();
    if (len(a) != len(b)) {
        Ꮡt.Errorf("len(a) == %d, len(b) == %d"u8, len(a), len(b));
        return false;
    }
    foreach (var (i, _) in a) {
        var (al, bl) = (a[i], b[i]);
        // If both are EndSequence, then the only other valid
        // field is Address. Otherwise, test equality of all
        // fields.
        if (al.EndSequence && bl.EndSequence && al.Address == bl.Address) {
            continue;
        }
        if ((~al.File).Name != (~bl.File).Name) {
            Ꮡt.Errorf("%d: name %v != name %v"u8, i, (~al.File).Name, (~bl.File).Name);
            return false;
        }
        al.File = default!;
        bl.File = default!;
        if (al != bl) {
            Ꮡt.Errorf("%d: %#v != %#v"u8, i, al, bl);
            return false;
        }
    }
    return true;
}

internal static void dumpLines(ж<testing.T> Ꮡt, slice<dwarf.LineEntry> lines) {
    foreach (var (_, l) in lines) {
        Ꮡt.Logf("  %+v File:%+v"u8, l, l.File.OrTypedNil());
    }
}

partial struct joinTest {
    internal @string dirname, filename;
    internal @string path;
}

// Note: the Go compiler currently emits DWARF line table paths
// with '/' instead of '\' (see issues #19784, #36495). These
// tests are to cover cases that might come up for Windows Go
// binaries.
// The following are "best effort". We shouldn't see relative
// base directories in DWARF, but these test that pathJoin
// doesn't fail miserably if it sees one.
internal static slice<joinTest> joinTests = new joinTest[]{
    new("a"u8, "b"u8, "a/b"u8),
    new("a"u8, ""u8, "a"u8),
    new(""u8, "b"u8, "b"u8),
    new("/a"u8, "b"u8, "/a/b"u8),
    new("/a/"u8, "b"u8, "/a/b"u8),
    new(@"C:\Windows\"u8, @"System32"u8, @"C:\Windows\System32"u8),
    new(@"C:\Windows\"u8, @""u8, @"C:\Windows\"u8),
    new(@"C:\"u8, @"Windows"u8, @"C:\Windows"u8),
    new(@"C:\Windows\"u8, @"C:System32"u8, @"C:\Windows\System32"u8),
    new(@"C:\Windows"u8, @"a/b"u8, @"C:\Windows\a/b"u8),
    new(@"\\host\share\"u8, @"foo"u8, @"\\host\share\foo"u8),
    new(@"\\host\share\"u8, @"foo\bar"u8, @"\\host\share\foo\bar"u8),
    new(@"//host/share/"u8, @"foo/bar"u8, @"//host/share/foo/bar"u8),
    new(@"c:/workdir/go/src/x"u8, @"y.go"u8, @"c:/workdir/go/src/x/y.go"u8),
    new(@"d:/some/thing/"u8, @"b.go"u8, @"d:/some/thing/b.go"u8),
    new(@"e:\blah\"u8, @"foo.c"u8, @"e:\blah\foo.c"u8),
    new(@"C:"u8, @"a"u8, @"C:a"u8),
    new(@"C:"u8, @"a\b"u8, @"C:a\b"u8),
    new(@"C:."u8, @"a"u8, @"C:.\a"u8),
    new(@"C:a"u8, @"b"u8, @"C:a\b"u8)
}.slice();

public static void TestPathJoin(ж<testing.T> Ꮡt) {
    foreach (var (_, test) in joinTests) {
        @string got = dwarf_internal_test_package.PathJoin(test.dirname, test.filename);
        if (test.path != got) {
            Ꮡt.Errorf("pathJoin(%q, %q) = %q, want %q"u8, test.dirname, test.filename, got, test.path);
        }
    }
}

public static void TestPathLineReaderMalformed(ж<testing.T> Ꮡt) {
    // This test case drawn from issue #52354. What's happening
    // here is that the stmtList attribute in the compilation
    // unit is malformed (negative).
    slice<byte> aranges = default!;
    slice<byte> frame = default!;
    slice<byte> pubnames = default!;
    slice<byte> ranges = default!;
    slice<byte> str = default!;
    var abbrev = new byte[]{0x10, 0x20, 0x20, 0x20, 0x21, 0x20, 0x10, 0x21, 0x61,
        0x0, 0x0, 0xff, 0x20, 0xff, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
        0x20, 0x20, 0x20, 0x20, 0x20, 0x20}.slice();
    var info = new byte[]{0x0, 0x0, 0x0, 0x9, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0,
        0x20, 0x10, 0x10}.slice();
    var line = new byte[]{0x20}.slice();
    var (Data0, err) = New(abbrev, aranges, frame, info, line, pubnames, ranges, str);
    if (err != default!) {
        Ꮡt.Fatalf("error unexpected: %v"u8, err);
    }
    var Reader0 = Data0.Reader();
    (var Entry0, err) = Reader0.Next();
    if (err != default!) {
        Ꮡt.Fatalf("error unexpected: %v"u8, err);
    }
    (var LineReader0, err) = Data0.LineReader(Entry0);
    if (err == default!) {
        Ꮡt.Fatalf("expected error"u8);
    }
    if (LineReader0 != nil) {
        Ꮡt.Fatalf("expected nil line reader"u8);
    }
}

} // end dwarf_test_package
