// MethodValueFmRecord pins runtime.FuncForPC(...).Name() for a VALUE-receiver method value: Go runs
// every method value of T.M through one autogenerated `-fm` wrapper, `main.T.valueMethod-fm`, whether
// the receiver was bound through a value or through a pointer. The converter emits such a method value
// as a lambda over a COPY of the receiver (Go copies it when the method value is evaluated), so the
// function the converted program can name is that lambda -- which reads as the enclosing function's
// literal (`main.main.func1`) unless the conversion records it. MethodValueFuncNames pins every other
// method-value and method-expression shape.
//
// A LITERAL whose whole body calls the same method is a different Go function (`main.main.funcN`), so
// one is kept beside the method values as the control the record must not capture.
package main

import (
	"fmt"
	"reflect"
	"runtime"
)

type T struct{ n int }

func (t T) valueMethod() int { return t.n }

func nameOf(fn any) string {
	f := runtime.FuncForPC(reflect.ValueOf(fn).Pointer())
	if f == nil {
		return "<nil Func>"
	}
	if name := f.Name(); name != "" {
		return name
	}
	return "<empty name>"
}

func main() {
	t := T{n: 1}
	p := &t

	fmt.Println("method value, value receiver:        ", nameOf(t.valueMethod))
	fmt.Println("method value, via pointer, value rcv:", nameOf(p.valueMethod))

	literal := func() int { return t.valueMethod() }
	fmt.Println("literal calling the same method:     ", nameOf(literal))

	// The copy is taken when the method value is evaluated: a later write to t is not seen.
	bound := t.valueMethod
	t.n = 2
	fmt.Println("bound receiver is a copy:            ", bound())

	// Go HIDES the -fm wrapper from runtime.Callers: a walk from inside the method reaches call, then
	// main, with no wrapper frame between (measured on go1.24.13, with and without -gcflags=-l).
	call(t.walk)
}

// walk prints the frames above it, up to main.
//
//go:noinline
func (t T) walk() int {
	pc := make([]uintptr, 8)
	frames := runtime.CallersFrames(pc[:runtime.Callers(1, pc)])
	for {
		f, more := frames.Next()
		fmt.Println("frame:                               ", f.Function)
		if !more || f.Function == "main.main" {
			return t.n
		}
	}
}

//go:noinline
func call(f func() int) int { return f() }
