// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go;

using bufio = bufio_package;
using bzip2 = compress.bzip2_package;
using fmt = fmt_package;
using testenv = @internal.testenv_package;
using Δio = io_package;
using Δos = os_package;
using filepath = path.filepath_package;
using syntax = regexp.syntax_package;
using slices = slices_package;
using strconv = strconv_package;
using strings = strings_package;
using testing = testing_package;
using utf8 = go.unicode.utf8_package;
using @internal;
using compress;
using go.unicode;
using path;
using regexp;
using static go.regexp_package;

partial class regexp_internal_test_package {

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string testdataRe2SearchTxtˢ = "testdata/re2-search.txt"u8;

// TestRE2 tests this package's regexp API against test cases
// considered during RE2's exhaustive tests, which run all possible
// regexps over a given set of atoms and operators, up to a given
// complexity, over all possible strings over a given alphabet,
// up to a given size. Rather than try to link with RE2, we read a
// log file containing the test cases and the expected matches.
// The log file, re2-exhaustive.txt, is generated by running 'make log'
// in the open source RE2 distribution https://github.com/google/re2/.
//
// The test file format is a sequence of stanzas like:
//
//	strings
//	"abc"
//	"123x"
//	regexps
//	"[a-z]+"
//	0-3;0-3
//	-;-
//	"([0-9])([0-9])([0-9])"
//	-;-
//	-;0-3 0-1 1-2 2-3
//
// The stanza begins by defining a set of strings, quoted
// using Go double-quote syntax, one per line. Then the
// regexps section gives a sequence of regexps to run on
// the strings. In the block that follows a regexp, each line
// gives the semicolon-separated match results of running
// the regexp on the corresponding string.
// Each match result is either a single -, meaning no match, or a
// space-separated sequence of pairs giving the match and
// submatch indices. An unmatched subexpression formats
// its pair as a single - (not illustrated above).  For now
// each regexp run produces two match results, one for a
// “full match” that restricts the regexp to matching the entire
// string or nothing, and one for a “partial match” that gives
// the leftmost first match found in the string.
//
// Lines beginning with # are comments. Lines beginning with
// a capital letter are test names printed during RE2's test suite
// and are echoed into t but otherwise ignored.
//
// At time of writing, re2-exhaustive.txt is 59 MB but compresses to 385 kB,
// so we store re2-exhaustive.txt.bz2 in the repository and decompress it on the fly.
public static void TestRE2Search(ж<testing.T> Ꮡt) {
    testRE2(Ꮡt, testdataRe2SearchTxtˢ);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string bz2ˢ = ".bz2"u8;

internal static void testRE2(ж<testing.T> Ꮡt, @string @file) {
    GoFrame ᒐ = default;
    try {
        ref var t = ref Ꮡt.DerefOrNull();

        var (f, err) = Δos.Open(@file);
        if (err != default!) {
            Ꮡt.Fatal(err);
        }
        var fʗ1 = f;
        defer(() => fʗ1.Close(), ref ᒐ);
        Δio.Reader txt = default!;
        if (strings.HasSuffix(@file, bz2ˢ)){
            var z = bzip2.NewReader(new regexp_test_package.os_FileжReader(f));
            txt = z;
            @file = @file.slice(0, len(@file) - len(".bz2")); // for error messages
        } else {
            txt = new regexp_test_package.os_FileжReader(f);
        }
        nint lineno = 0;
        var scanner = bufio.NewScanner(txt);
        slice<@string> str = default!;
        slice<@string> input = default!;
        bool inStrings = default!;
        ж<global::go.regexp_package.Regexp> re = default!;
        ж<global::go.regexp_package.Regexp> refull = default!;
        nint nfail = default!;
        nint ncase = default!;
        for (nint linenoΔ1 = 1; scanner.Scan(); linenoΔ1++) {
            @string line = scanner.Text();
            switch (ᐧ) {
            case {} when line == ""u8: {
                Ꮡt.Fatalf("%s:%d: unexpected blank line"u8, @file, linenoΔ1);
                break;
            }
            case {} when line[0] is (rune)'#': {
                continue;
                break;
            }
            case {} when (rune)'A' <= line[0] && line[0] <= (rune)'Z': {
                Ꮡt.Logf("%s\n"u8, // Test name.
 line);
                continue;
                break;
            }
            case {} when line == "strings"u8: {
                str = str[..0];
                inStrings = true;
                break;
            }
            case {} when line == "regexps"u8: {
                inStrings = false;
                break;
            }
            case {} when line[0] is (rune)'"': {
                var (q, errΔ2) = strconv.Unquote(line);
                if (errΔ2 != default!) {
                    // Fatal because we'll get out of sync.
                    Ꮡt.Fatalf("%s:%d: unquote %s: %v"u8, @file, linenoΔ1, line, errΔ2);
                }
                if (inStrings) {
                    str = append(str, q);
                    continue;
                }
                if (len(input) != 0) {
                    // Is a regexp.
                    Ꮡt.Fatalf("%s:%d: out of sync: have %d strings left before %#q"u8, @file, linenoΔ1, len(input), q);
                }
                (re, errΔ2) = tryCompile(q);
                if (errΔ2 != default!) {
                    if (errΔ2.Error() == "error parsing regexp: invalid escape sequence: `\\C`"u8) {
                        // We don't and likely never will support \C; keep going.
                        continue;
                    }
                    Ꮡt.Errorf("%s:%d: compile %#q: %v"u8, @file, linenoΔ1, q, errΔ2);
                    {
                        nfail++; if (nfail >= 100) {
                            Ꮡt.Fatalf("stopping after %d errors"u8, nfail);
                        }
                    }
                    continue;
                }
                @string full = @"\A(?:"u8 + q + @")\z"u8;
                (refull, errΔ2) = tryCompile(full);
                if (errΔ2 != default!) {
                    // Fatal because q worked, so this should always work.
                    Ꮡt.Fatalf("%s:%d: compile full %#q: %v"u8, @file, linenoΔ1, full, errΔ2);
                }
                input = str;
                break;
            }
            case {} when line[0] == (rune)'-' || (rune)'0' <= line[0] && line[0] <= (rune)'9': {
                ncase++;
                if (re == nil) {
                    // A sequence of match results.
                    // Failed to compile: skip results.
                    continue;
                }
                if (len(input) == 0) {
                    Ꮡt.Fatalf("%s:%d: out of sync: no input remaining"u8, @file, linenoΔ1);
                }
                @string text = default!;
                (text, input) = (input[0], input[1..]);
                if (!isSingleBytes(text) && strings.Contains(re.String(), @"\B"u8)) {
                    // RE2's \B considers every byte position,
                    // so it sees 'not word boundary' in the
                    // middle of UTF-8 sequences. This package
                    // only considers the positions between runes,
                    // so it disagrees. Skip those cases.
                    continue;
                }
                var res = strings.Split(line, ";"u8);
                if (len(res) != len(run)) {
                    Ꮡt.Fatalf("%s:%d: have %d test results, want %d"u8, @file, linenoΔ1, len(res), len(run));
                }
                foreach (var (i, _) in res) {
                    var (have, suffix) = run[i](re, refull, text);
                    var want = parseResult(Ꮡt, @file, linenoΔ1, res[i]);
                    if (!slices.Equal<slice<nint>, nint>(have, want)) {
                        Ꮡt.Errorf("%s:%d: %#q%s.FindSubmatchIndex(%#q) = %v, want %v"u8, @file, linenoΔ1, re.OrTypedNil(), suffix, text, have, want);
                        {
                            nfail++; if (nfail >= 100) {
                                Ꮡt.Fatalf("stopping after %d errors"u8, nfail);
                            }
                        }
                        continue;
                    }
                    (var b, suffix) = Δmatch[i](re, refull, text);
                    if (b != (want != default!)) {
                        Ꮡt.Errorf("%s:%d: %#q%s.MatchString(%#q) = %v, want %v"u8, @file, linenoΔ1, re.OrTypedNil(), suffix, text, b, !b);
                        {
                            nfail++; if (nfail >= 100) {
                                Ꮡt.Fatalf("stopping after %d errors"u8, nfail);
                            }
                        }
                        continue;
                    }
                }
                break;
            }
            default: {
                Ꮡt.Fatalf("%s:%d: out of sync: %s\n"u8, @file, linenoΔ1, line);
                break;
            }}

        }
        {
            var errΔ3 = scanner.Err(); if (errΔ3 != default!) {
                Ꮡt.Fatalf("%s:%d: %v"u8, @file, lineno, errΔ3);
            }
        }
        if (len(input) != 0) {
            Ꮡt.Fatalf("%s:%d: out of sync: have %d strings left at EOF"u8, @file, lineno, len(input));
        }
        Ꮡt.Logf("%d cases tested"u8, ncase);
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
}

internal static slice<Func<ж<global::go.regexp_package.Regexp>, ж<global::go.regexp_package.Regexp>, @string, (slice<nint>, @string)>> run;
internal static void initᴛrun() { run = new Func<ж<global::go.regexp_package.Regexp>, ж<global::go.regexp_package.Regexp>, @string, (slice<nint>, @string)>[]{
    runFull,
    runPartial,
    runFullLongest,
    runPartialLongest
}.slice(); }

internal static (slice<nint>, @string) runFull(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var refull = ref Ꮡrefull.DerefOrNull();

    refull.longest = false;
    return (Ꮡrefull.FindStringSubmatchIndex(text), "[full]");
}

internal static (slice<nint>, @string) runPartial(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var re = ref Ꮡre.DerefOrNull();

    re.longest = false;
    return (Ꮡre.FindStringSubmatchIndex(text), "");
}

internal static (slice<nint>, @string) runFullLongest(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var refull = ref Ꮡrefull.DerefOrNull();

    refull.longest = true;
    return (Ꮡrefull.FindStringSubmatchIndex(text), "[full,longest]");
}

internal static (slice<nint>, @string) runPartialLongest(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var re = ref Ꮡre.DerefOrNull();

    re.longest = true;
    return (Ꮡre.FindStringSubmatchIndex(text), "[longest]");
}

internal static slice<Func<ж<global::go.regexp_package.Regexp>, ж<global::go.regexp_package.Regexp>, @string, (bool, @string)>> Δmatch;
internal static void initᴛΔmatch() { Δmatch = new Func<ж<global::go.regexp_package.Regexp>, ж<global::go.regexp_package.Regexp>, @string, (bool, @string)>[]{
    matchFull,
    matchPartial,
    matchFullLongest,
    matchPartialLongest
}.slice(); }

internal static (bool, @string) matchFull(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var refull = ref Ꮡrefull.DerefOrNull();

    refull.longest = false;
    return (Ꮡrefull.MatchString(text), "[full]");
}

internal static (bool, @string) matchPartial(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var re = ref Ꮡre.DerefOrNull();

    re.longest = false;
    return (Ꮡre.MatchString(text), "");
}

internal static (bool, @string) matchFullLongest(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var refull = ref Ꮡrefull.DerefOrNull();

    refull.longest = true;
    return (Ꮡrefull.MatchString(text), "[full,longest]");
}

internal static (bool, @string) matchPartialLongest(ж<global::go.regexp_package.Regexp> Ꮡre, ж<global::go.regexp_package.Regexp> Ꮡrefull, @string text) {
    ref var re = ref Ꮡre.DerefOrNull();

    re.longest = true;
    return (Ꮡre.MatchString(text), "[longest]");
}

internal static bool isSingleBytes(@string s) {
    foreach (var (_, c) in s) {
        if (c >= utf8.RuneSelf) {
            return false;
        }
    }
    return true;
}

internal static (ж<global::go.regexp_package.Regexp> re, error err) tryCompile(@string s) {
    ж<global::go.regexp_package.Regexp> re = default!;
    error err = default!;
    GoFrame ᒐ = default;
    try {
        // Protect against panic during Compile.
        defer(() => {
            {
                var r = recover(); if (r != default!) {
                    err = fmt.Errorf("panic: %v"u8, r);
                }
            }
        }, ref ᒐ);
        (re, err) = Compile(s);
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
    return (re, err);
}

internal static slice<nint> parseResult(ж<testing.T> Ꮡt, @string @file, nint lineno, @string res) {
    // A single - indicates no match.
    if (res == "-"u8) {
        return default!;
    }
    // Otherwise, a space-separated list of pairs.
    nint n = 1;
    for (nint j = 0; j < len(res); j++) {
        if (res[j] == (rune)' ') {
            n++;
        }
    }
    var @out = new slice<nint>(2 * n);
    nint i = 0;
    n = 0;
    for (nint j = 0; j <= len(res); j++) {
        if (j == len(res) || res[j] == (rune)' ') {
            // Process a single pair.  - means no submatch.
            @string pair = res.slice(i, j);
            if (pair == "-"u8){
                @out[n] = -1;
                @out[n + 1] = -1;
            } else {
                var (loStr, hiStr, _) = strings.Cut(pair, "-"u8);
                var (lo, err1) = strconv.Atoi(loStr);
                var (hi, err2) = strconv.Atoi(hiStr);
                if (err1 != default! || err2 != default! || lo > hi) {
                    Ꮡt.Fatalf("%s:%d: invalid pair %s"u8, @file, lineno, pair);
                }
                @out[n] = lo;
                @out[n + 1] = hi;
            }
            n += 2;
            i = j + 1;
        }
    }
    return @out;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string testdataDatˢ = "testdata/*.dat"u8;

// TestFowler runs this package's regexp API against the
// POSIX regular expression tests collected by Glenn Fowler
// at http://www2.research.att.com/~astopen/testregex/testregex.html.
public static void TestFowler(ж<testing.T> Ꮡt) {
    var (files, err) = filepath.Glob(testdataDatˢ);
    if (err != default!) {
        Ꮡt.Fatal(err);
    }
    foreach (var (_, @file) in files) {
        Ꮡt.Log(@file);
        testFowler(Ꮡt, @file);
    }
}

internal static ж<global::go.regexp_package.Regexp> notab;
internal static void initᴛnotab() { notab = MustCompilePOSIX(@"[^\t]+"u8); }

internal static void testFowler(ж<testing.T> Ꮡt, @string @file) {
    GoFrame ᒐ = default;
    try {
        ref var t = ref Ꮡt.DerefOrNull();

        var (f, err) = Δos.Open(@file);
        if (err != default!) {
            Ꮡt.Error(err);
            return;
        }
        var fʗ1 = f;
        defer(() => fʗ1.Close(), ref ᒐ);
        var b = bufio.NewReader(new regexp_test_package.os_FileжReader(f));
        nint lineno = 0;
        @string lastRegexp = ""u8;
Reading:
        while (ᐧ) {
            lineno++;
            var (line, errΔ1) = b.ReadString((rune)'\n');
            if (errΔ1 != default!) {
                if (!AreEqual(errΔ1, Δio.EOF)) {
                    Ꮡt.Errorf("%s:%d: %v"u8, @file, lineno, errΔ1);
                }
                goto break_Reading;
            }
            // http://www2.research.att.com/~astopen/man/man1/testregex.html
            //
            // INPUT FORMAT
            //   Input lines may be blank, a comment beginning with #, or a test
            //   specification. A specification is five fields separated by one
            //   or more tabs. NULL denotes the empty string and NIL denotes the
            //   0 pointer.
            if (line[0] == (rune)'#' || line[0] == (rune)'\n') {
                goto continue_Reading;
            }
            line = line.slice(0, len(line) - 1);
            var field = notab.FindAllString(line, -1);
            foreach (var (i, fΔ1) in field) {
                if (fΔ1 == "NULL"u8) {
                    field[i] = ""u8;
                }
                if (fΔ1 == "NIL"u8) {
                    Ꮡt.Logf("%s:%d: skip: %s"u8, @file, lineno, line);
                    goto continue_Reading;
                }
            }
            if (len(field) == 0) {
                goto continue_Reading;
            }
            //   Field 1: the regex(3) flags to apply, one character per REG_feature
            //   flag. The test is skipped if REG_feature is not supported by the
            //   implementation. If the first character is not [BEASKLP] then the
            //   specification is a global control line. One or more of [BEASKLP] may be
            //   specified; the test will be repeated for each mode.
            //
            //     B 	basic			BRE	(grep, ed, sed)
            //     E 	REG_EXTENDED		ERE	(egrep)
            //     A	REG_AUGMENTED		ARE	(egrep with negation)
            //     S	REG_SHELL		SRE	(sh glob)
            //     K	REG_SHELL|REG_AUGMENTED	KRE	(ksh glob)
            //     L	REG_LITERAL		LRE	(fgrep)
            //
            //     a	REG_LEFT|REG_RIGHT	implicit ^...$
            //     b	REG_NOTBOL		lhs does not match ^
            //     c	REG_COMMENT		ignore space and #...\n
            //     d	REG_SHELL_DOT		explicit leading . match
            //     e	REG_NOTEOL		rhs does not match $
            //     f	REG_MULTIPLE		multiple \n separated patterns
            //     g	FNM_LEADING_DIR		testfnmatch only -- match until /
            //     h	REG_MULTIREF		multiple digit backref
            //     i	REG_ICASE		ignore case
            //     j	REG_SPAN		. matches \n
            //     k	REG_ESCAPE		\ to escape [...] delimiter
            //     l	REG_LEFT		implicit ^...
            //     m	REG_MINIMAL		minimal match
            //     n	REG_NEWLINE		explicit \n match
            //     o	REG_ENCLOSED		(|&) magic inside [@|&](...)
            //     p	REG_SHELL_PATH		explicit / match
            //     q	REG_DELIMITED		delimited pattern
            //     r	REG_RIGHT		implicit ...$
            //     s	REG_SHELL_ESCAPED	\ not special
            //     t	REG_MUSTDELIM		all delimiters must be specified
            //     u	standard unspecified behavior -- errors not counted
            //     v	REG_CLASS_ESCAPE	\ special inside [...]
            //     w	REG_NOSUB		no subexpression match array
            //     x	REG_LENIENT		let some errors slide
            //     y	REG_LEFT		regexec() implicit ^...
            //     z	REG_NULL		NULL subexpressions ok
            //     $	                        expand C \c escapes in fields 2 and 3
            //     /	                        field 2 is a regsubcomp() expression
            //     =	                        field 3 is a regdecomp() expression
            //
            //   Field 1 control lines:
            //
            //     C		set LC_COLLATE and LC_CTYPE to locale in field 2
            //
            //     ?test ...	output field 5 if passed and != EXPECTED, silent otherwise
            //     &test ...	output field 5 if current and previous passed
            //     |test ...	output field 5 if current passed and previous failed
            //     ; ...	output field 2 if previous failed
            //     {test ...	skip if failed until }
            //     }		end of skip
            //
            //     : comment		comment copied as output NOTE
            //     :comment:test	:comment: ignored
            //     N[OTE] comment	comment copied as output NOTE
            //     T[EST] comment	comment
            //
            //     number		use number for nmatch (20 by default)
            @string flag = field[0];
            switch (flag[0]) {
            case (rune)'?' or (rune)'&' or (rune)'|' or (rune)';' or (rune)'{' or (rune)'}': {
                flag = flag[1..];
                if (flag == ""u8) {
                    // Ignore all the control operators.
                    // Just run everything.
                    goto continue_Reading;
                }
                break;
            }
            case (rune)':': {
                bool okΔ2 = default!;
                {
                    (_, flag, okΔ2) = strings.Cut(flag[1..], ":"u8); if (!okΔ2) {
                        Ꮡt.Logf("skip: %s"u8, line);
                        goto continue_Reading;
                    }
                }
                break;
            }
            case (rune)'C' or (rune)'N' or (rune)'T' or (rune)'0' or (rune)'1' or (rune)'2' or (rune)'3' or (rune)'4' or (rune)'5' or (rune)'6' or (rune)'7' or (rune)'8' or (rune)'9': {
                Ꮡt.Logf("skip: %s"u8, line);
                goto continue_Reading;
                break;
            }}

            // Can check field count now that we've handled the myriad comment formats.
            if (len(field) < 4) {
                Ꮡt.Errorf("%s:%d: too few fields: %s"u8, @file, lineno, line);
                goto continue_Reading;
            }
            // Expand C escapes (a.k.a. Go escapes).
            if (strings.Contains(flag, "$"u8)) {
                @string fΔ2 = @"""" + field[1] + @"""";
                {
                    (field[1], errΔ1) = strconv.Unquote(fΔ2); if (errΔ1 != default!) {
                        Ꮡt.Errorf("%s:%d: cannot unquote %s"u8, @file, lineno, fΔ2);
                    }
                }
                fΔ2 = @"""" + field[2] + @"""";
                {
                    (field[2], errΔ1) = strconv.Unquote(fΔ2); if (errΔ1 != default!) {
                        Ꮡt.Errorf("%s:%d: cannot unquote %s"u8, @file, lineno, fΔ2);
                    }
                }
            }
            //   Field 2: the regular expression pattern; SAME uses the pattern from
            //     the previous specification.
            //
            if (field[1] == "SAME") {
                field[1] = lastRegexp;
            }
            lastRegexp = field[1];
            //   Field 3: the string to match.
            @string text = field[2];
            //   Field 4: the test outcome...
            var (ok, shouldCompile, shouldMatch, pos) = parseFowlerResult(field[3]);
            if (!ok) {
                Ꮡt.Errorf("%s:%d: cannot parse result %#q"u8, @file, lineno, field[3]);
                goto continue_Reading;
            }
            //   Field 5: optional comment appended to the report.
Testing:
            foreach (var (_, c) in flag) {
                // Run test once for each specified capital letter mode that we support.
                @string pattern = field[1];
                var syn = (syntax.Flags)(syntax.POSIX | syntax.ClassNL);
                switch (c) {
                default: {
                    goto continue_Testing;
                    break;
                }
                case (rune)'E': {
                    break;
                }
                case (rune)'L': {
                    pattern = QuoteMeta(pattern);
                    break;
                }}

                // extended regexp (what we support)
                // literal
                foreach (var (_, cΔ1) in flag) {
                    switch (cΔ1) {
                    case (rune)'i': {
                        syn |= (syntax.Flags)(syntax.FoldCase);
                        break;
                    }}

                }
                var (re, errΔ2) = compile(pattern, syn, true);
                if (errΔ2 != default!) {
                    if (shouldCompile) {
                        Ꮡt.Errorf("%s:%d: %#q did not compile"u8, @file, lineno, pattern);
                    }
                    goto continue_Testing;
                }
                if (!shouldCompile) {
                    Ꮡt.Errorf("%s:%d: %#q should not compile"u8, @file, lineno, pattern);
                    goto continue_Testing;
                }
                var Δmatch = re.MatchString(text);
                if (Δmatch != shouldMatch) {
                    Ꮡt.Errorf("%s:%d: %#q.Match(%#q) = %v, want %v"u8, @file, lineno, pattern, text, Δmatch, shouldMatch);
                    goto continue_Testing;
                }
                var have = re.FindStringSubmatchIndex(text);
                if ((len(have) > 0) != Δmatch) {
                    Ꮡt.Errorf("%s:%d: %#q.Match(%#q) = %v, but %#q.FindSubmatchIndex(%#q) = %v"u8, @file, lineno, pattern, text, Δmatch, pattern, text, have);
                    goto continue_Testing;
                }
                if (len(have) > len(pos)) {
                    have = have.slice(0, len(pos));
                }
                if (!slices.Equal<slice<nint>, nint>(have, pos)) {
                    Ꮡt.Errorf("%s:%d: %#q.FindSubmatchIndex(%#q) = %v, want %v"u8, @file, lineno, pattern, text, have, pos);
                }
continue_Testing:;
            }
break_Testing:;
continue_Reading:;
        }
break_Reading:;
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
}

internal static (bool ok, bool compiled, bool matched, slice<nint> pos) parseFowlerResult(@string s) {
    bool ok = default!;
    bool compiled = default!;
    bool matched = default!;
    slice<nint> pos = default!;

    //   Field 4: the test outcome. This is either one of the posix error
    //     codes (with REG_ omitted) or the match array, a list of (m,n)
    //     entries with m and n being first and last+1 positions in the
    //     field 3 string, or NULL if REG_NOSUB is in effect and success
    //     is expected. BADPAT is acceptable in place of any regcomp(3)
    //     error code. The match[] array is initialized to (-2,-2) before
    //     each test. All array elements from 0 to nmatch-1 must be specified
    //     in the outcome. Unspecified endpoints (offset -1) are denoted by ?.
    //     Unset endpoints (offset -2) are denoted by X. {x}(o:n) denotes a
    //     matched (?{...}) expression, where x is the text enclosed by {...},
    //     o is the expression ordinal counting from 1, and n is the length of
    //     the unmatched portion of the subject string. If x starts with a
    //     number then that is the return value of re_execf(), otherwise 0 is
    //     returned.
    switch (ᐧ) {
    case {} when s == ""u8: {
        ok = true;
        compiled = true;
        matched = true;
        return (ok, compiled, matched, pos);
    }
    case {} when s == "NOMATCH"u8: {
        ok = true;
        compiled = true;
        matched = false;
        return (ok, compiled, matched, pos);
    }
    case {} when (rune)'A' <= s[0] && s[0] <= (rune)'Z': {
        ok = true;
        compiled = false;
        return (ok, compiled, matched, pos);
    }}

    // Match with no position information.
    // Match failure.
    // All the other error codes are compile errors.
    compiled = true;
    slice<nint> x = default!;
    while (s != ""u8) {
        byte end = (rune)')';
        if (len(x) % 2 == 0) {
            if (s[0] != (rune)'(') {
                ok = false;
                return (ok, compiled, matched, pos);
            }
            s = s[1..];
            end = (rune)',';
        }
        nint i = 0;
        while (i < len(s) && s[i] != end) {
            i++;
        }
        if (i == 0 || i == len(s)) {
            ok = false;
            return (ok, compiled, matched, pos);
        }
        nint v = -1;
        error err = default!;
        if (s.slice(0, i) != "?") {
            (v, err) = strconv.Atoi(s.slice(0, i));
            if (err != default!) {
                ok = false;
                return (ok, compiled, matched, pos);
            }
        }
        x = append(x, v);
        s = s.slice(i + 1);
    }
    if (len(x) % 2 != 0) {
        ok = false;
        return (ok, compiled, matched, pos);
    }
    ok = true;
    matched = true;
    pos = x;
    return (ok, compiled, matched, pos);
}

internal static slice<byte> text;

internal static slice<byte> makeText(nint n) {
    if (len(text) >= n) {
        return text.slice(0, n);
    }
    text = new slice<byte>(n);
    var x = ~(uint32)0;
    foreach (var (i, _) in text) {
        x += x;
        x ^= (uint32)(1);
        if ((int32)x < 0) {
            x ^= (uint32)(0x88888eefU);
        }
        if (x % 31 == 0){
            text[i] = (rune)'\n';
        } else {
            text[i] = (byte)(x % (0x7E + 1 - 0x20) + 0x20);
        }
    }
    return text;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string raceˢ = "-race"u8;
internal static readonly object matchˢ = (@string)"match!"u8;

public static void BenchmarkMatch(ж<testing.B> Ꮡb) {
    var isRaceBuilder = strings.HasSuffix(testenv.Builder(), raceˢ);
    foreach (var (_, data) in benchData) {
        var r = MustCompile(data.re);
        foreach (var (_, vᴛ1) in benchSizes) {
            ref var size = ref heap(new benchSizesᴛ1(), out var Ꮡsize);
            size = vᴛ1;

            if ((isRaceBuilder || testing.Short()) && size.n > (1 << (int)(10))) {
                continue;
            }
            var t = makeText(size.n);
            var rʗ1 = r;
            var sizeʗ1 = size;
            var tʗ1 = t;
            Ꮡb.Run(data.name + "/"u8 + size.name, (ж<testing.B> bΔ1) => {
                bΔ1.SetBytes((int64)sizeʗ1.n);
                for (nint i = 0; i < (~bΔ1).N; i++) {
                    if (rʗ1.Match(tʗ1)) {
                        bΔ1.Fatal(matchˢ);
                    }
                }
            });
        }
    }
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string sAZˢ = @"(?s)\A.*\z"u8;
internal static readonly object notMatchˢ = (@string)"not match!"u8;

public static void BenchmarkMatch_onepass_regex(ж<testing.B> Ꮡb) {
    var isRaceBuilder = strings.HasSuffix(testenv.Builder(), raceˢ);
    var r = MustCompile(sAZˢ);
    if ((~r).onepass == nil) {
        Ꮡb.Fatalf("want onepass regex, but %q is not onepass"u8, r.OrTypedNil());
    }
    foreach (var (_, vᴛ1) in benchSizes) {
        ref var size = ref heap(new benchSizesᴛ1(), out var Ꮡsize);
        size = vᴛ1;

        if ((isRaceBuilder || testing.Short()) && size.n > (1 << (int)(10))) {
            continue;
        }
        var t = makeText(size.n);
        var rʗ1 = r;
        var sizeʗ1 = size;
        var tʗ1 = t;
        Ꮡb.Run(size.name, (ж<testing.B> bΔ1) => {
            bΔ1.SetBytes((int64)sizeʗ1.n);
            bΔ1.ReportAllocs();
            for (nint i = 0; i < (~bΔ1).N; i++) {
                if (!rʗ1.Match(tʗ1)) {
                    bΔ1.Fatal(notMatchˢ);
                }
            }
        });
    }
}

internal static slice<compileBenchDataᴛ1> benchData = new compileBenchDataᴛ1[]{
    new("Easy0"u8, "ABCDEFGHIJKLMNOPQRSTUVWXYZ$"u8),
    new("Easy0i"u8, "(?i)ABCDEFGHIJklmnopqrstuvwxyz$"u8),
    new("Easy1"u8, "A[AB]B[BC]C[CD]D[DE]E[EF]F[FG]G[GH]H[HI]I[IJ]J$"u8),
    new("Medium"u8, "[XYZ]ABCDEFGHIJKLMNOPQRSTUVWXYZ$"u8),
    new("Hard"u8, "[ -~]*ABCDEFGHIJKLMNOPQRSTUVWXYZ$"u8),
    new("Hard1"u8, "ABCD|CDEF|EFGH|GHIJ|IJKL|KLMN|MNOP|OPQR|QRST|STUV|UVWX|WXYZ"u8)
}.slice();


[GoType("dyn")] partial struct benchSizesᴛ1 {
    internal @string name;
    internal nint n;
}
internal static slice<benchSizesᴛ1> benchSizes = new benchSizesᴛ1[]{
    new("16"u8, 16),
    new("32"u8, 32),
    new("1K"u8, (1 << (int)(10))),
    new("32K"u8, (32 << (int)(10))),
    new("1M"u8, (1 << (int)(20))),
    new("32M"u8, (32 << (int)(20)))
}.slice();

public static void TestLongest(ж<testing.T> Ꮡt) {
    var (re, err) = Compile(@"a(|b)"u8);
    if (err != default!) {
        Ꮡt.Fatal(err);
    }
    {
        @string g = re.FindString("ab"u8);
        @string w = "a"u8; if (g != w) {
            Ꮡt.Errorf("first match was %q, want %q"u8, g, w);
        }
    }
    re.Longest();
    {
        @string g = re.FindString("ab"u8);
        @string w = "ab"u8; if (g != w) {
            Ꮡt.Errorf("longest match was %q, want %q"u8, g, w);
        }
    }
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string oneTwoThreeFourFiveSixˢ = @"(one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|twentyone|twentytwo|twentythree|twentyfour|twentyfive|twentysix|twentyseven|twentyeight|twentynine|thirty|thirtyone|thirtytwo|thirtythree|thirtyfour|thirtyfive|thirtysix|thirtyseven|thirtyeight|thirtynine|forty|fortyone|fortytwo|fortythree|fortyfour|fortyfive|fortysix|fortyseven|fortyeight|fortynine|fifty|fiftyone|fiftytwo|fiftythree|fiftyfour|fiftyfive|fiftysix|fiftyseven|fiftyeight|fiftynine|sixty|sixtyone|sixtytwo|sixtythree|sixtyfour|sixtyfive|sixtysix|sixtyseven|sixtyeight|sixtynine|seventy|seventyone|seventytwo|seventythree|seventyfour|seventyfive|seventysix|seventyseven|seventyeight|seventynine|eighty|eightyone|eightytwo|eightythree|eightyfour|eightyfive|eightysix|eightyseven|eightyeight|eightynine|ninety|ninetyone|ninetytwo|ninetythree|ninetyfour|ninetyfive|ninetysix|ninetyseven|ninetyeight|ninetynine|onehundred)"u8;
internal static readonly @string twoˢ = "two"u8;
internal static readonly @string xxxˢ = "xxx"u8;

// TestProgramTooLongForBacktrack tests that a regex which is too long
// for the backtracker still executes properly.
public static void TestProgramTooLongForBacktrack(ж<testing.T> Ꮡt) {
    var longRegex = MustCompile(oneTwoThreeFourFiveSixˢ);
    if (!longRegex.MatchString(twoˢ)) {
        Ꮡt.Errorf("longRegex.MatchString(\"two\") was false, want true"u8);
    }
    if (longRegex.MatchString(xxxˢ)) {
        Ꮡt.Errorf("longRegex.MatchString(\"xxx\") was true, want false"u8);
    }
}

} // end regexp_internal_test_package
