// sourcemeta_test.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package sourcemeta

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

const fixtureInfo = `// <auto-generated/>
// <ExportedTypeAliases>
[assembly: GoTypeAlias("ΔUUID", "UUID")]
// </ExportedTypeAliases>
[assembly: GoImplement<UUID, go.fmt_package.Stringer>]
[assembly: GoSourcePositionMaps("not metadata")]
`

// writeFixture builds a -recurse output root's src/ tree: the module root package (flat package_info.cs),
// a sub-package whose metadata varies by GOOS (no flat copy; windows + linux flavors), and a Go main that a
// pack excludes.
func writeFixture(t *testing.T) string {
	t.Helper()
	src := t.TempDir()

	write := func(rel, body string) {
		t.Helper()
		full := filepath.Join(src, filepath.FromSlash(rel))

		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("example.com/mod/package_info.cs", fixtureInfo)
	write("example.com/mod/example.com.mod.csproj", "<Project />")
	write("example.com/mod/sub/example.com.mod.sub.csproj", "<Project />")
	write("example.com/mod/sub/windows/package_info.cs", "[assembly: GoImplement<W, go.io_package.Reader>]\n")
	write("example.com/mod/sub/linux/package_info.cs", "[assembly: GoImplement<L, go.io_package.Reader>]\n")
	write("example.com/mod/cmd/tool/package_info.cs", "[assembly: GoImplement<T, go.io_package.Reader>]\n")
	write("example.com/mod/cmd/tool/tool.csproj", "<Project />")

	return src
}

var fixturePackages = []Package{
	{ImportPath: "example.com/mod", Assembly: "example.com.mod"},
	{ImportPath: "example.com/mod/sub", Assembly: "example.com.mod.sub"},
}

func fixtureDescription(t *testing.T) Description {
	t.Helper()
	sections, err := Collect(writeFixture(t), fixturePackages)

	if err != nil {
		t.Fatal(err)
	}

	return Description{
		Module:        "example.com/mod",
		ModuleVersion: "v1.6.0",
		Go2csRelease:  "1.24.13.3",
		Requires:      []Require{{Module: "example.com/dep", Version: "v0.2.0", NuGetID: "nugetgo.example.com.dep"}},
		Packages:      fixturePackages,
		Sections:      sections,
	}
}

func TestCollectKeepsThePackedPackagesAndTheirFlavors(t *testing.T) {
	sections, err := Collect(writeFixture(t), fixturePackages)

	if err != nil {
		t.Fatal(err)
	}

	want := map[string][]string{
		"example.com.mod": {
			"// <ExportedTypeAliases>",
			`[assembly: GoTypeAlias("ΔUUID", "UUID")]`,
			"// </ExportedTypeAliases>",
			"[assembly: GoImplement<UUID, go.fmt_package.Stringer>]",
		},
		"example.com.mod.sub":       {"[assembly: GoImplement<W, go.io_package.Reader>]"},
		"example.com.mod.sub@linux": {"[assembly: GoImplement<L, go.io_package.Reader>]"},
	}

	if !reflect.DeepEqual(sections, want) {
		t.Errorf("sections = %#v\nwant %#v", sections, want)
	}
}

func TestCollectRefusesAPackageWithoutPackageInfo(t *testing.T) {
	_, err := Collect(writeFixture(t), append(fixturePackages, Package{ImportPath: "example.com/mod/missing", Assembly: "example.com.mod.missing"}))

	if err == nil || !strings.Contains(err.Error(), "example.com/mod/missing") {
		t.Errorf("a packed package with no package_info.cs was accepted (err %v)", err)
	}
}

func TestGenerateWritesTheV1Layout(t *testing.T) {
	data, err := Generate(fixtureDescription(t))

	if err != nil {
		t.Fatal(err)
	}

	text := string(data)

	if !strings.HasPrefix(text, Magic+"\n") {
		t.Errorf("the file does not open with %q:\n%s", Magic, text)
	}

	for _, want := range []string{
		"\nmodule example.com/mod\n",
		"\nmodule-version v1.6.0\n",
		"\ngo2cs-release 1.24.13.3\n",
		"\nrequire example.com/dep v0.2.0 nugetgo.example.com.dep\n",
		"\npackage example.com/mod example.com.mod\n",
		"\npackage example.com/mod/sub example.com.mod.sub\n",
		"\n##example.com.mod\n// <ExportedTypeAliases>\n",
		"\n##example.com.mod.sub@linux\n[assembly: GoImplement<L, go.io_package.Reader>]\n",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("the file lacks %q:\n%s", want, text)
		}
	}

	if strings.Contains(text, "\r") || strings.HasPrefix(text, "\uFEFF") || strings.Contains(text, "GoSourcePositionMaps") {
		t.Errorf("the file carries a CR, a BOM or a non-metadata line:\n%s", text)
	}

	again, _ := Generate(fixtureDescription(t))

	if string(again) != text {
		t.Errorf("Generate is not deterministic")
	}
}

func TestParseReadsBackWhatGenerateWrote(t *testing.T) {
	d := fixtureDescription(t)
	data, err := Generate(d)

	if err != nil {
		t.Fatal(err)
	}

	parsed, err := Parse(data)

	if err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(parsed, d) {
		t.Errorf("round trip changed the description:\n got %#v\nwant %#v", parsed, d)
	}
}

func TestParseAcceptsCommentsAndBlankLines(t *testing.T) {
	body := Magic + "\n# a comment\n\nmodule example.com/mod\nmodule-version v1.0.0\ngo2cs-release 1.24.13.3\n" +
		"package example.com/mod example.com.mod\n\n##example.com.mod\n# comment inside\n[assembly: GoImplement<A, B>]\n"

	d, err := Parse([]byte(body))

	if err != nil {
		t.Fatal(err)
	}

	if !reflect.DeepEqual(d.Sections["example.com.mod"], []string{"[assembly: GoImplement<A, B>]"}) {
		t.Errorf("section = %q", d.Sections["example.com.mod"])
	}
}

// A malformed self-description makes the consumer fall back to local conversion (COORD ruling 2026-10-02),
// and the warning must say WHAT is malformed -- so every refusal names its line and its fault.
func TestParseNamesWhatIsMalformed(t *testing.T) {
	head := Magic + "\nmodule example.com/mod\nmodule-version v1.0.0\ngo2cs-release 1.24.13.3\npackage example.com/mod example.com.mod\n"
	section := "##example.com.mod\n[assembly: GoImplement<A, B>]\n"

	cases := []struct {
		name string
		body string
		want string
	}{
		{"no magic", strings.TrimPrefix(head, Magic+"\n") + section, "line 1"},
		{"a later schema", strings.Replace(head, " v1", " v2", 1) + section, "v2"},
		{"a byte-order mark", "\xEF\xBB\xBF" + head + section, "byte-order mark"},
		{"a carriage return", strings.Replace(head, "module example.com/mod\n", "module example.com/mod\r\n", 1) + section, "carriage return"},
		{"a second module line", head + "module example.com/other\n" + section, "a second module"},
		{"an unknown key", head + "colour blue\n" + section, "unknown"},
		{"a short require", head + "require example.com/dep v1.0.0\n" + section, "require"},
		{"an invalid require id", head + "require example.com/dep v1.0.0 bad id!\n" + section, "require"},
		{"a go.-prefixed require id", head + "require example.com/dep v1.0.0 go.example.com.dep\n" + section, `uses the "go." prefix`},
		// A malformed go. ID is refused for its malformation alone: the prefix rule runs after the validity check.
		{"a malformed go.-prefixed require id", head + "require example.com/dep v1.0.0 go..dep\n" + section, "the registry's rule"},
		{"no go2cs-release", strings.Replace(head, "go2cs-release 1.24.13.3\n", "", 1) + section, "go2cs-release"},
		{"an invalid module-version", strings.Replace(head, "v1.0.0", "1.0.0", 1) + section, "module-version"},
		{"a package without a section", head + "package example.com/mod/sub example.com.mod.sub\n" + section, "example.com.mod.sub"},
		{"a section for no listed package", head + section + "##example.com.mod.other\n[assembly: GoImplement<A, B>]\n", "example.com.mod.other"},
		{"a package outside the module", head + "package example.com/elsewhere example.com.elsewhere\n" + section + "##example.com.elsewhere\n", "outside"},
		{"a record before any section", head + "[assembly: GoImplement<A, B>]\n" + section, "line 6"},
	}

	for _, c := range cases {
		_, err := Parse([]byte(c.body))

		if err == nil {
			t.Errorf("%s: accepted", c.name)
			continue
		}

		if !strings.Contains(err.Error(), c.want) {
			t.Errorf("%s: the refusal does not name %q: %v", c.name, c.want, err)
		}

		if c.name == "a malformed go.-prefixed require id" && strings.Contains(err.Error(), `uses the "go." prefix`) {
			t.Errorf("%s: a malformed ID must yield ONE nuget-id problem, its malformation: %v", c.name, err)
		}
	}
}

// Generate refuses what Parse would refuse, so a pack can never produce a file its consumer rejects.
func TestGenerateRefusesWhatParseWouldRefuse(t *testing.T) {
	mutate := []struct {
		name   string
		change func(*Description)
		want   string
	}{
		{"invalid module path", func(d *Description) { d.Module = "Example.com/mod" }, "module"},
		{"module-version without its v", func(d *Description) { d.ModuleVersion = "1.6.0" }, "module-version"},
		{"empty go2cs-release", func(d *Description) { d.Go2csRelease = "" }, "go2cs-release"},
		{"no package", func(d *Description) { d.Packages = nil }, "package"},
		{"duplicate package", func(d *Description) { d.Packages = append(d.Packages, d.Packages[0]) }, "example.com/mod"},
		{"invalid require id", func(d *Description) { d.Requires[0].NuGetID = "a..b" }, "nuget-id"},
		{"go.-prefixed require id", func(d *Description) { d.Requires[0].NuGetID = "GO.Example.Dep" }, `uses the "go." prefix`},
		{"missing section", func(d *Description) { delete(d.Sections, "example.com.mod") }, "example.com.mod"},
	}

	for _, m := range mutate {
		d := fixtureDescription(t)
		m.change(&d)

		if _, err := Generate(d); err == nil || !strings.Contains(err.Error(), m.want) {
			t.Errorf("%s: Generate did not refuse naming %q (err %v)", m.name, m.want, err)
		}
	}
}

// CheckModuleNuGetID refuses the standard library's "go." prefix in any letter case and nothing else (owner ruling,
// 2026-10-02): the registry's lint and every go2cs reader of a module's NuGet ID apply this one rule.
func TestCheckModuleNuGetIDRefusesOnlyTheGoPrefix(t *testing.T) {
	for _, id := range []string{"go.github.com.google.uuid", "GO.github.com.google.uuid", "Go.Uuid", "go.x"} {
		err := CheckModuleNuGetID(id)

		if err == nil {
			t.Errorf("%q: accepted", id)
			continue
		}

		want := `nuget-id "` + id + `" uses the "go." prefix, which is the converted Go standard library; the ID of a converted module starts with "nugetgo."`

		if err.Error() != want {
			t.Errorf("%q: the refusal reads %q, want %q", id, err.Error(), want)
		}
	}

	for _, id := range []string{"nugetgo.github.com.google.uuid", "golang.x", "gopher.x", "go-x.y", "gox", "go", "Acme.Go.x", "Example.HashSet"} {
		if err := CheckModuleNuGetID(id); err != nil {
			t.Errorf("%q: refused: %v", id, err)
		}
	}
}
