// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by generate.go. DO NOT EDIT.
global using p521UntypedFieldElement = go.array<ulong>;

namespace go.crypto.@internal.fips140.nistec;

using subtle = go.crypto.@internal.fips140.subtle_package;
using errors = errors_package;
using go.crypto.@internal.fips140;

partial class fiat_package {

// P521Element is an integer modulo 2^521 - 1.
//
// The zero value is a valid zero element.
partial struct P521Element {
    // Values are represented internally always in the Montgomery domain, and
    // converted in Bytes and SetBytes.
    internal p521MontgomeryDomainFieldElement x;
}

internal static UntypedInt p521ElementLen => 66;

// One sets e = 1, and returns e.
public static ж<P521Element> One(this ж<P521Element> Ꮡe) {
    ref var e = ref Ꮡe.DerefOrNull();

    p521SetOne(ref nonnil(ref e).x);
    return Ꮡe;
}

// Equal returns 1 if e == t, and zero otherwise.
public static nint Equal(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt) {
    var eBytes = Ꮡe.Bytes();
    var tBytes = Ꮡt.Bytes();
    return subtle.ConstantTimeCompare(eBytes, tBytes);
}

// IsZero returns 1 if e == 0, and zero otherwise.
public static nint IsZero(this ж<P521Element> Ꮡe) {
    var zero = new slice<byte>(p521ElementLen);
    var eBytes = Ꮡe.Bytes();
    return subtle.ConstantTimeCompare(eBytes, zero);
}

// Set sets e = t, and returns e.
public static ж<P521Element> Set(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var t = ref Ꮡt.DerefOrNull();

    e.x = t.x.Clone();
    return Ꮡe;
}

// Bytes returns the 66-byte big-endian encoding of e.
public static slice<byte> Bytes(this ж<P521Element> Ꮡe) {
    // This function is outlined to make the allocations inline in the caller
    // rather than happen on the heap.
    ref var @out = ref heap(new array<byte>(66), out var Ꮡout);
    return Ꮡe.bytes(Ꮡout);
}

internal static slice<byte> bytes(this ж<P521Element> Ꮡe, /*[66]*/ ж<array<byte>> Ꮡout) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var @out = ref Ꮡout.DerefOrNull();

    p521NonMontgomeryDomainFieldElement tmp = default!;
    p521FromMontgomery(ref tmp, ref nonnil(ref e).x);
    var ᴛ1 = tmp.Value;
    p521ToBytes(ref (Ꮡout).DerefOrNull(), ref ᴛ1);
    p521InvertEndianness(@out[..]);
    return @out[..];
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
private static readonly @string invalidP521Elementˢ = "invalid P521Element encoding"u8;

// SetBytes sets e = v, where v is a big-endian 66-byte encoding, and returns e.
// If v is not 66 bytes or it encodes a value higher than 2^521 - 1,
// SetBytes returns nil and an error, and e is unchanged.
public static (ж<P521Element>, error) SetBytes(this ж<P521Element> Ꮡe, slice<byte> v) {
    ref var e = ref Ꮡe.DerefOrNull();

    if (len(v) != p521ElementLen) {
        return (default!, errors.New(invalidP521Elementˢ));
    }
    // Check for non-canonical encodings (p + k, 2p + k, etc.) by comparing to
    // the encoding of -1 mod p, so p - 1, the highest canonical encoding.
    slice<byte> minusOneEncoding = @new<P521Element>().Sub(
        @new<P521Element>(), @new<P521Element>().One()).Bytes();
    foreach (var (i, _) in v) {
        if (v[i] < minusOneEncoding[i]) {
            break;
        }
        if (v[i] > minusOneEncoding[i]) {
            return (default!, errors.New(invalidP521Elementˢ));
        }
    }
    ref var @in = ref heap(new array<byte>(66), out var Ꮡin);
    copy(@in[..], v);
    p521InvertEndianness(@in[..]);
    p521NonMontgomeryDomainFieldElement tmp = default!;
    var ᴛ2 = tmp.Value;
    p521FromBytes(ref ᴛ2, ref @in);
    p521ToMontgomery(ref nonnil(ref e).x, ref tmp);
    return (Ꮡe, default!);
}

// Add sets e = t1 + t2, and returns e.
public static ж<P521Element> Add(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt1, ж<P521Element> Ꮡt2) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var t1 = ref Ꮡt1.DerefOrNull();
    ref var t2 = ref Ꮡt2.DerefOrNull();

    p521Add(ref nonnil(ref e).x, ref nonnil(ref t1).x, ref nonnil(ref t2).x);
    return Ꮡe;
}

// Sub sets e = t1 - t2, and returns e.
public static ж<P521Element> Sub(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt1, ж<P521Element> Ꮡt2) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var t1 = ref Ꮡt1.DerefOrNull();
    ref var t2 = ref Ꮡt2.DerefOrNull();

    p521Sub(ref nonnil(ref e).x, ref nonnil(ref t1).x, ref nonnil(ref t2).x);
    return Ꮡe;
}

// Mul sets e = t1 * t2, and returns e.
public static ж<P521Element> Mul(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt1, ж<P521Element> Ꮡt2) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var t1 = ref Ꮡt1.DerefOrNull();
    ref var t2 = ref Ꮡt2.DerefOrNull();

    p521Mul(ref nonnil(ref e).x, ref nonnil(ref t1).x, ref nonnil(ref t2).x);
    return Ꮡe;
}

// Square sets e = t * t, and returns e.
public static ж<P521Element> Square(this ж<P521Element> Ꮡe, ж<P521Element> Ꮡt) {
    ref var e = ref Ꮡe.DerefOrNull();
    ref var t = ref Ꮡt.DerefOrNull();

    p521Square(ref nonnil(ref e).x, ref nonnil(ref t).x);
    return Ꮡe;
}

// Select sets v to a if cond == 1, and to b if cond == 0.
public static ж<P521Element> Select(this ж<P521Element> Ꮡv, ж<P521Element> Ꮡa, ж<P521Element> Ꮡb, nint cond) {
    ref var v = ref Ꮡv.DerefOrNull();
    ref var a = ref Ꮡa.DerefOrNull();
    ref var b = ref Ꮡb.DerefOrNull();

    var ᴛ3 = nonnil(ref v).x.Value;

    var ᴛ4 = nonnil(ref b).x.Value;

    var ᴛ5 = nonnil(ref a).x.Value;
    p521Selectznz(ref ᴛ3, ((p521Uint1)(uint64)cond),
        ref ᴛ4, ref ᴛ5);
    return Ꮡv;
}

internal static void p521InvertEndianness(slice<byte> v) {
    for (nint i = 0; i < len(v) / 2; i++) {
        (v[i], v[len(v) - 1 - i]) = (v[len(v) - 1 - i], v[i]);
    }
}

} // end fiat_package
