// Code generated by 'go generate'; DO NOT EDIT.
namespace go.@internal.syscall;

using sysdll = go.@internal.syscall.windows.sysdll_package;
using syscall = syscall_package;
using @unsafe = unsafe_package;
using go.@internal.syscall.windows;

partial class windows_package {

// Go runs an imported package's `init` before this package's own; .NET would never load
// an assembly nothing has touched yet, so that initialization is forced here.
[GoInit] internal static void initᴛᴛimportꓸinternalꓸsyscallꓸwindowsꓸsysdll() {
    builtin.initPackage(typeof(go.@internal.syscall.windows.sysdll_package));
}

internal static @unsafe.Pointer _ᴛ1ʗ;

// Do the interface allocations only once for common
// Errno values.
internal static UntypedInt errnoERROR_IO_PENDING => 997;

internal static error errERROR_IO_PENDING = ((syscall.Errno)errnoERROR_IO_PENDING);
internal static error errERROR_EINVAL = ((syscall.Errno)syscall.EINVAL);

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
internal static error errnoErr(syscall.Errno e) {
    var exprᴛ1 = e;
    if (exprᴛ1 == (syscall.Errno)(0)) {
        return errERROR_EINVAL;
    }
    if (exprᴛ1 == errnoERROR_IO_PENDING) {
        return errERROR_IO_PENDING;
    }

    // TODO: add more here, after collecting data on the common
    // error values see on Windows. (perhaps when running
    // all.bat?)
    return e;
}

internal static ж<syscall.LazyDLL> modadvapi32 = syscall.NewLazyDLL(sysdll.Add("advapi32.dll"u8));
internal static ж<syscall.LazyDLL> modbcryptprimitives = syscall.NewLazyDLL(sysdll.Add("bcryptprimitives.dll"u8));
internal static ж<syscall.LazyDLL> modiphlpapi = syscall.NewLazyDLL(sysdll.Add("iphlpapi.dll"u8));
internal static ж<syscall.LazyDLL> modkernel32 = syscall.NewLazyDLL(sysdll.Add("kernel32.dll"u8));
internal static ж<syscall.LazyDLL> modnetapi32 = syscall.NewLazyDLL(sysdll.Add("netapi32.dll"u8));
internal static ж<syscall.LazyDLL> modntdll = syscall.NewLazyDLL(sysdll.Add("ntdll.dll"u8));
internal static ж<syscall.LazyDLL> modpsapi = syscall.NewLazyDLL(sysdll.Add("psapi.dll"u8));
internal static ж<syscall.LazyDLL> moduserenv = syscall.NewLazyDLL(sysdll.Add("userenv.dll"u8));
internal static ж<syscall.LazyDLL> modws2_32 = syscall.NewLazyDLL(sysdll.Add("ws2_32.dll"u8));
internal static ж<syscall.LazyProc> procAdjustTokenPrivileges = modadvapi32.NewProc("AdjustTokenPrivileges"u8);
internal static ж<syscall.LazyProc> procDuplicateTokenEx = modadvapi32.NewProc("DuplicateTokenEx"u8);
internal static ж<syscall.LazyProc> procImpersonateSelf = modadvapi32.NewProc("ImpersonateSelf"u8);
internal static ж<syscall.LazyProc> procLookupPrivilegeValueW = modadvapi32.NewProc("LookupPrivilegeValueW"u8);
internal static ж<syscall.LazyProc> procOpenSCManagerW = modadvapi32.NewProc("OpenSCManagerW"u8);
internal static ж<syscall.LazyProc> procOpenServiceW = modadvapi32.NewProc("OpenServiceW"u8);
internal static ж<syscall.LazyProc> procOpenThreadToken = modadvapi32.NewProc("OpenThreadToken"u8);
internal static ж<syscall.LazyProc> procQueryServiceStatus = modadvapi32.NewProc("QueryServiceStatus"u8);
internal static ж<syscall.LazyProc> procRevertToSelf = modadvapi32.NewProc("RevertToSelf"u8);
internal static ж<syscall.LazyProc> procSetTokenInformation = modadvapi32.NewProc("SetTokenInformation"u8);
internal static ж<syscall.LazyProc> procProcessPrng = modbcryptprimitives.NewProc("ProcessPrng"u8);
internal static ж<syscall.LazyProc> procGetAdaptersAddresses = modiphlpapi.NewProc("GetAdaptersAddresses"u8);
internal static ж<syscall.LazyProc> procCreateEventW = modkernel32.NewProc("CreateEventW"u8);
internal static ж<syscall.LazyProc> procGetACP = modkernel32.NewProc("GetACP"u8);
internal static ж<syscall.LazyProc> procGetComputerNameExW = modkernel32.NewProc("GetComputerNameExW"u8);
internal static ж<syscall.LazyProc> procGetConsoleCP = modkernel32.NewProc("GetConsoleCP"u8);
internal static ж<syscall.LazyProc> procGetCurrentThread = modkernel32.NewProc("GetCurrentThread"u8);
internal static ж<syscall.LazyProc> procGetFileInformationByHandleEx = modkernel32.NewProc("GetFileInformationByHandleEx"u8);
internal static ж<syscall.LazyProc> procGetFinalPathNameByHandleW = modkernel32.NewProc("GetFinalPathNameByHandleW"u8);
internal static ж<syscall.LazyProc> procGetModuleFileNameW = modkernel32.NewProc("GetModuleFileNameW"u8);
internal static ж<syscall.LazyProc> procGetTempPath2W = modkernel32.NewProc("GetTempPath2W"u8);
internal static ж<syscall.LazyProc> procGetVolumeInformationByHandleW = modkernel32.NewProc("GetVolumeInformationByHandleW"u8);
internal static ж<syscall.LazyProc> procGetVolumeNameForVolumeMountPointW = modkernel32.NewProc("GetVolumeNameForVolumeMountPointW"u8);
internal static ж<syscall.LazyProc> procLockFileEx = modkernel32.NewProc("LockFileEx"u8);
internal static ж<syscall.LazyProc> procModule32FirstW = modkernel32.NewProc("Module32FirstW"u8);
internal static ж<syscall.LazyProc> procModule32NextW = modkernel32.NewProc("Module32NextW"u8);
internal static ж<syscall.LazyProc> procMoveFileExW = modkernel32.NewProc("MoveFileExW"u8);
internal static ж<syscall.LazyProc> procMultiByteToWideChar = modkernel32.NewProc("MultiByteToWideChar"u8);
internal static ж<syscall.LazyProc> procRtlLookupFunctionEntry = modkernel32.NewProc("RtlLookupFunctionEntry"u8);
internal static ж<syscall.LazyProc> procRtlVirtualUnwind = modkernel32.NewProc("RtlVirtualUnwind"u8);
internal static ж<syscall.LazyProc> procSetFileInformationByHandle = modkernel32.NewProc("SetFileInformationByHandle"u8);
internal static ж<syscall.LazyProc> procUnlockFileEx = modkernel32.NewProc("UnlockFileEx"u8);
internal static ж<syscall.LazyProc> procVirtualQuery = modkernel32.NewProc("VirtualQuery"u8);
internal static ж<syscall.LazyProc> procNetShareAdd = modnetapi32.NewProc("NetShareAdd"u8);
internal static ж<syscall.LazyProc> procNetShareDel = modnetapi32.NewProc("NetShareDel"u8);
internal static ж<syscall.LazyProc> procNetUserGetLocalGroups = modnetapi32.NewProc("NetUserGetLocalGroups"u8);
internal static ж<syscall.LazyProc> procRtlGetVersion = modntdll.NewProc("RtlGetVersion"u8);
internal static ж<syscall.LazyProc> procGetProcessMemoryInfo = modpsapi.NewProc("GetProcessMemoryInfo"u8);
internal static ж<syscall.LazyProc> procCreateEnvironmentBlock = moduserenv.NewProc("CreateEnvironmentBlock"u8);
internal static ж<syscall.LazyProc> procDestroyEnvironmentBlock = moduserenv.NewProc("DestroyEnvironmentBlock"u8);
internal static ж<syscall.LazyProc> procGetProfilesDirectoryW = moduserenv.NewProc("GetProfilesDirectoryW"u8);
internal static ж<syscall.LazyProc> procWSAGetOverlappedResult = modws2_32.NewProc("WSAGetOverlappedResult"u8);
internal static ж<syscall.LazyProc> procWSASocketW = modws2_32.NewProc("WSASocketW"u8);

// go2cs generated this placeholder — func adjustTokenPrivileges is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

public static error /*err*/ DuplicateTokenEx(syscall.Token hExistingToken, uint32 dwDesiredAccess, ж<syscall.SecurityAttributes> ᏑlpTokenAttributes, uint32 impersonationLevel, TokenType tokenType, ж<syscall.Token> ᏑphNewToken) {
    error err = default!;

    var ᴋ0 = ᏑlpTokenAttributes;
    var ᴋ1 = ᏑphNewToken;
        var (r1, _, e1) = syscall.Syscall6(procDuplicateTokenEx.Addr(), 6, (uintptr)hExistingToken, (uintptr)dwDesiredAccess, (uintptr)ᴋ0, (uintptr)impersonationLevel, (uintptr)(uint32)tokenType, (uintptr)ᴋ1);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ ImpersonateSelf(uint32 impersonationlevel) {
    error err = default!;

    var (r1, _, e1) = syscall.Syscall(procImpersonateSelf.Addr(), 1, (uintptr)impersonationlevel, 0, 0);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ LookupPrivilegeValue(ж<uint16> Ꮡsystemname, ж<uint16> Ꮡname, ж<LUID> Ꮡluid) {
    error err = default!;

    var ᴋ2 = Ꮡsystemname;
    var ᴋ3 = Ꮡname;
    var ᴋ4 = Ꮡluid;
        var (r1, _, e1) = syscall.Syscall(procLookupPrivilegeValueW.Addr(), 3, (uintptr)ᴋ2, (uintptr)ᴋ3, (uintptr)ᴋ4);
    System.GC.KeepAlive(ᴋ2);
    System.GC.KeepAlive(ᴋ3);
    System.GC.KeepAlive(ᴋ4);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static (syscallꓸHandle handle, error err) OpenSCManager(ж<uint16> ᏑmachineName, ж<uint16> ᏑdatabaseName, uint32 access) {
    syscallꓸHandle handle = default!;
    error err = default!;

    var ᴋ5 = ᏑmachineName;
    var ᴋ6 = ᏑdatabaseName;
        var (r0, _, e1) = syscall.Syscall(procOpenSCManagerW.Addr(), 3, (uintptr)ᴋ5, (uintptr)ᴋ6, (uintptr)access);
    System.GC.KeepAlive(ᴋ5);
    System.GC.KeepAlive(ᴋ6);
    handle = ((syscallꓸHandle)r0);
    if (handle == 0) {
        err = errnoErr(e1);
    }
    return (handle, err);
}

public static (syscallꓸHandle handle, error err) OpenService(syscallꓸHandle mgr, ж<uint16> ᏑserviceName, uint32 access) {
    syscallꓸHandle handle = default!;
    error err = default!;

    var ᴋ7 = ᏑserviceName;
        var (r0, _, e1) = syscall.Syscall(procOpenServiceW.Addr(), 3, (uintptr)mgr, (uintptr)ᴋ7, (uintptr)access);
    System.GC.KeepAlive(ᴋ7);
    handle = ((syscallꓸHandle)r0);
    if (handle == 0) {
        err = errnoErr(e1);
    }
    return (handle, err);
}

public static error /*err*/ OpenThreadToken(syscallꓸHandle h, uint32 access, bool openasself, ж<syscall.Token> Ꮡtoken) {
    error err = default!;

    uint32 _p0 = default!;
    if (openasself) {
        _p0 = 1;
    }
    var ᴋ8 = Ꮡtoken;
        var (r1, _, e1) = syscall.Syscall6(procOpenThreadToken.Addr(), 4, (uintptr)h, (uintptr)access, (uintptr)_p0, (uintptr)ᴋ8, 0, 0);
    System.GC.KeepAlive(ᴋ8);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ QueryServiceStatus(syscallꓸHandle hService, ж<SERVICE_STATUS> ᏑlpServiceStatus) {
    error err = default!;

    var ᴋ9 = ᏑlpServiceStatus;
        var (r1, _, e1) = syscall.Syscall(procQueryServiceStatus.Addr(), 2, (uintptr)hService, (uintptr)ᴋ9, 0);
    System.GC.KeepAlive(ᴋ9);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ RevertToSelf() {
    error err = default!;

    var (r1, _, e1) = syscall.Syscall(procRevertToSelf.Addr(), 0, 0, 0, 0);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ SetTokenInformation(syscall.Token tokenHandle, uint32 tokenInformationClass, uintptr tokenInformation, uint32 tokenInformationLength) {
    error err = default!;

    var (r1, _, e1) = syscall.Syscall6(procSetTokenInformation.Addr(), 4, (uintptr)tokenHandle, (uintptr)tokenInformationClass, (uintptr)tokenInformation, (uintptr)tokenInformationLength, 0, 0);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ ProcessPrng(slice<byte> buf) {
    error err = default!;

    ж<byte> _p0 = default!;
    if (len(buf) > 0) {
        _p0 = Ꮡ(buf, 0);
    }
    var ᴋ10 = _p0;
        var (r1, _, e1) = syscall.Syscall(procProcessPrng.Addr(), 2, (uintptr)ᴋ10, (uintptr)len(buf), 0);
    System.GC.KeepAlive(ᴋ10);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*errcode*/ GetAdaptersAddresses(uint32 family, uint32 flags, uintptr reserved, ж<IpAdapterAddresses> ᏑadapterAddresses, ж<uint32> ᏑsizePointer) {
    error errcode = default!;

    var ᴋ11 = ᏑadapterAddresses;
    var ᴋ12 = ᏑsizePointer;
        var (r0, _, _) = syscall.Syscall6(procGetAdaptersAddresses.Addr(), 5, (uintptr)family, (uintptr)flags, (uintptr)reserved, (uintptr)ᴋ11, (uintptr)ᴋ12, 0);
    System.GC.KeepAlive(ᴋ11);
    System.GC.KeepAlive(ᴋ12);
    if (r0 != 0) {
        errcode = ((syscall.Errno)r0);
    }
    return errcode;
}

public static (syscallꓸHandle handle, error err) CreateEvent(ж<SecurityAttributes> ᏑeventAttrs, uint32 manualReset, uint32 initialState, ж<uint16> Ꮡname) {
    syscallꓸHandle handle = default!;
    error err = default!;

    var ᴋ13 = ᏑeventAttrs;
    var ᴋ14 = Ꮡname;
        var (r0, _, e1) = syscall.Syscall6(procCreateEventW.Addr(), 4, (uintptr)ᴋ13, (uintptr)manualReset, (uintptr)initialState, (uintptr)ᴋ14, 0, 0);
    System.GC.KeepAlive(ᴋ13);
    System.GC.KeepAlive(ᴋ14);
    handle = ((syscallꓸHandle)r0);
    if (handle == 0) {
        err = errnoErr(e1);
    }
    return (handle, err);
}

public static uint32 /*acp*/ GetACP() {
    uint32 acp = default!;

    var (r0, _, _) = syscall.Syscall(procGetACP.Addr(), 0, 0, 0, 0);
    acp = (uint32)r0;
    return acp;
}

public static error /*err*/ GetComputerNameEx(uint32 nameformat, ж<uint16> Ꮡbuf, ж<uint32> Ꮡn) {
    error err = default!;

    var ᴋ15 = Ꮡbuf;
    var ᴋ16 = Ꮡn;
        var (r1, _, e1) = syscall.Syscall(procGetComputerNameExW.Addr(), 3, (uintptr)nameformat, (uintptr)ᴋ15, (uintptr)ᴋ16);
    System.GC.KeepAlive(ᴋ15);
    System.GC.KeepAlive(ᴋ16);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static uint32 /*ccp*/ GetConsoleCP() {
    uint32 ccp = default!;

    var (r0, _, _) = syscall.Syscall(procGetConsoleCP.Addr(), 0, 0, 0, 0);
    ccp = (uint32)r0;
    return ccp;
}

public static (syscallꓸHandle pseudoHandle, error err) GetCurrentThread() {
    syscallꓸHandle pseudoHandle = default!;
    error err = default!;

    var (r0, _, e1) = syscall.Syscall(procGetCurrentThread.Addr(), 0, 0, 0, 0);
    pseudoHandle = ((syscallꓸHandle)r0);
    if (pseudoHandle == 0) {
        err = errnoErr(e1);
    }
    return (pseudoHandle, err);
}

public static error /*err*/ GetFileInformationByHandleEx(syscallꓸHandle handle, uint32 @class, ж<byte> Ꮡinfo, uint32 bufsize) {
    error err = default!;

    var ᴋ17 = Ꮡinfo;
        var (r1, _, e1) = syscall.Syscall6(procGetFileInformationByHandleEx.Addr(), 4, (uintptr)handle, (uintptr)@class, (uintptr)ᴋ17, (uintptr)bufsize, 0, 0);
    System.GC.KeepAlive(ᴋ17);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static (uint32 n, error err) GetFinalPathNameByHandle(syscallꓸHandle @file, ж<uint16> ᏑfilePath, uint32 filePathSize, uint32 flags) {
    uint32 n = default!;
    error err = default!;

    var ᴋ18 = ᏑfilePath;
        var (r0, _, e1) = syscall.Syscall6(procGetFinalPathNameByHandleW.Addr(), 4, (uintptr)@file, (uintptr)ᴋ18, (uintptr)filePathSize, (uintptr)flags, 0, 0);
    System.GC.KeepAlive(ᴋ18);
    n = (uint32)r0;
    if (n == 0) {
        err = errnoErr(e1);
    }
    return (n, err);
}

public static (uint32 n, error err) GetModuleFileName(syscallꓸHandle module, ж<uint16> Ꮡfn, uint32 len) {
    uint32 n = default!;
    error err = default!;

    var ᴋ19 = Ꮡfn;
        var (r0, _, e1) = syscall.Syscall(procGetModuleFileNameW.Addr(), 3, (uintptr)module, (uintptr)ᴋ19, (uintptr)len);
    System.GC.KeepAlive(ᴋ19);
    n = (uint32)r0;
    if (n == 0) {
        err = errnoErr(e1);
    }
    return (n, err);
}

public static (uint32 n, error err) GetTempPath2(uint32 buflen, ж<uint16> Ꮡbuf) {
    uint32 n = default!;
    error err = default!;

    var ᴋ20 = Ꮡbuf;
        var (r0, _, e1) = syscall.Syscall(procGetTempPath2W.Addr(), 2, (uintptr)buflen, (uintptr)ᴋ20, 0);
    System.GC.KeepAlive(ᴋ20);
    n = (uint32)r0;
    if (n == 0) {
        err = errnoErr(e1);
    }
    return (n, err);
}

public static error /*err*/ GetVolumeInformationByHandle(syscallꓸHandle @file, ж<uint16> ᏑvolumeNameBuffer, uint32 volumeNameSize, ж<uint32> ᏑvolumeNameSerialNumber, ж<uint32> ᏑmaximumComponentLength, ж<uint32> ᏑfileSystemFlags, ж<uint16> ᏑfileSystemNameBuffer, uint32 fileSystemNameSize) {
    error err = default!;

    var ᴋ21 = ᏑvolumeNameBuffer;
    var ᴋ22 = ᏑvolumeNameSerialNumber;
    var ᴋ23 = ᏑmaximumComponentLength;
    var ᴋ24 = ᏑfileSystemFlags;
    var ᴋ25 = ᏑfileSystemNameBuffer;
        var (r1, _, e1) = syscall.Syscall9(procGetVolumeInformationByHandleW.Addr(), 8, (uintptr)@file, (uintptr)ᴋ21, (uintptr)volumeNameSize, (uintptr)ᴋ22, (uintptr)ᴋ23, (uintptr)ᴋ24, (uintptr)ᴋ25, (uintptr)fileSystemNameSize, 0);
    System.GC.KeepAlive(ᴋ21);
    System.GC.KeepAlive(ᴋ22);
    System.GC.KeepAlive(ᴋ23);
    System.GC.KeepAlive(ᴋ24);
    System.GC.KeepAlive(ᴋ25);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ GetVolumeNameForVolumeMountPoint(ж<uint16> ᏑvolumeMountPoint, ж<uint16> ᏑvolumeName, uint32 bufferlength) {
    error err = default!;

    var ᴋ26 = ᏑvolumeMountPoint;
    var ᴋ27 = ᏑvolumeName;
        var (r1, _, e1) = syscall.Syscall(procGetVolumeNameForVolumeMountPointW.Addr(), 3, (uintptr)ᴋ26, (uintptr)ᴋ27, (uintptr)bufferlength);
    System.GC.KeepAlive(ᴋ26);
    System.GC.KeepAlive(ᴋ27);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ LockFileEx(syscallꓸHandle @file, uint32 flags, uint32 reserved, uint32 bytesLow, uint32 bytesHigh, ж<syscall.Overlapped> Ꮡoverlapped) {
    error err = default!;

    var ᴋ28 = Ꮡoverlapped;
        var (r1, _, e1) = syscall.Syscall6(procLockFileEx.Addr(), 6, (uintptr)@file, (uintptr)flags, (uintptr)reserved, (uintptr)bytesLow, (uintptr)bytesHigh, (uintptr)ᴋ28);
    System.GC.KeepAlive(ᴋ28);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

// go2cs generated this placeholder — func Module32First is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

// go2cs generated this placeholder — func Module32Next is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

public static error /*err*/ MoveFileEx(ж<uint16> Ꮡfrom, ж<uint16> Ꮡto, uint32 flags) {
    error err = default!;

    var ᴋ29 = Ꮡfrom;
    var ᴋ30 = Ꮡto;
        var (r1, _, e1) = syscall.Syscall(procMoveFileExW.Addr(), 3, (uintptr)ᴋ29, (uintptr)ᴋ30, (uintptr)flags);
    System.GC.KeepAlive(ᴋ29);
    System.GC.KeepAlive(ᴋ30);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static (int32 nwrite, error err) MultiByteToWideChar(uint32 codePage, uint32 dwFlags, ж<byte> Ꮡstr, int32 nstr, ж<uint16> Ꮡwchar, int32 nwchar) {
    int32 nwrite = default!;
    error err = default!;

    var ᴋ31 = Ꮡstr;
    var ᴋ32 = Ꮡwchar;
        var (r0, _, e1) = syscall.Syscall6(procMultiByteToWideChar.Addr(), 6, (uintptr)codePage, (uintptr)dwFlags, (uintptr)ᴋ31, (uintptr)nstr, (uintptr)ᴋ32, (uintptr)nwchar);
    System.GC.KeepAlive(ᴋ31);
    System.GC.KeepAlive(ᴋ32);
    nwrite = (int32)r0;
    if (nwrite == 0) {
        err = errnoErr(e1);
    }
    return (nwrite, err);
}

public static uintptr /*ret*/ RtlLookupFunctionEntry(uintptr pc, ж<uintptr> ᏑbaseAddress, ж<byte> Ꮡtable) {
    uintptr ret = default!;

    var ᴋ33 = ᏑbaseAddress;
    var ᴋ34 = Ꮡtable;
        var (r0, _, _) = syscall.Syscall(procRtlLookupFunctionEntry.Addr(), 3, (uintptr)pc, (uintptr)ᴋ33, (uintptr)ᴋ34);
    System.GC.KeepAlive(ᴋ33);
    System.GC.KeepAlive(ᴋ34);
    ret = (uintptr)r0;
    return ret;
}

public static uintptr /*ret*/ RtlVirtualUnwind(uint32 handlerType, uintptr baseAddress, uintptr pc, uintptr entry, uintptr ctxt, ж<uintptr> Ꮡdata, ж<uintptr> Ꮡframe, ж<byte> Ꮡctxptrs) {
    uintptr ret = default!;

    var ᴋ35 = Ꮡdata;
    var ᴋ36 = Ꮡframe;
    var ᴋ37 = Ꮡctxptrs;
        var (r0, _, _) = syscall.Syscall9(procRtlVirtualUnwind.Addr(), 8, (uintptr)handlerType, (uintptr)baseAddress, (uintptr)pc, (uintptr)entry, (uintptr)ctxt, (uintptr)ᴋ35, (uintptr)ᴋ36, (uintptr)ᴋ37, 0);
    System.GC.KeepAlive(ᴋ35);
    System.GC.KeepAlive(ᴋ36);
    System.GC.KeepAlive(ᴋ37);
    ret = (uintptr)r0;
    return ret;
}

public static error /*err*/ SetFileInformationByHandle(syscallꓸHandle handle, uint32 fileInformationClass, @unsafe.Pointer buf, uint32 bufsize) {
    error err = default!;

    var (r1, _, e1) = syscall.Syscall6(procSetFileInformationByHandle.Addr(), 4, (uintptr)handle, (uintptr)fileInformationClass, (uintptr)buf, (uintptr)bufsize, 0, 0);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ UnlockFileEx(syscallꓸHandle @file, uint32 reserved, uint32 bytesLow, uint32 bytesHigh, ж<syscall.Overlapped> Ꮡoverlapped) {
    error err = default!;

    var ᴋ38 = Ꮡoverlapped;
        var (r1, _, e1) = syscall.Syscall6(procUnlockFileEx.Addr(), 5, (uintptr)@file, (uintptr)reserved, (uintptr)bytesLow, (uintptr)bytesHigh, (uintptr)ᴋ38, 0);
    System.GC.KeepAlive(ᴋ38);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ VirtualQuery(uintptr address, ж<MemoryBasicInformation> Ꮡbuffer, uintptr length) {
    error err = default!;

    var ᴋ39 = Ꮡbuffer;
        var (r1, _, e1) = syscall.Syscall(procVirtualQuery.Addr(), 3, (uintptr)address, (uintptr)ᴋ39, (uintptr)length);
    System.GC.KeepAlive(ᴋ39);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

// go2cs generated this placeholder — func NetShareAdd is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

public static error /*neterr*/ NetShareDel(ж<uint16> ᏑserverName, ж<uint16> ᏑnetName, uint32 reserved) {
    error neterr = default!;

    var ᴋ40 = ᏑserverName;
    var ᴋ41 = ᏑnetName;
        var (r0, _, _) = syscall.Syscall(procNetShareDel.Addr(), 3, (uintptr)ᴋ40, (uintptr)ᴋ41, (uintptr)reserved);
    System.GC.KeepAlive(ᴋ40);
    System.GC.KeepAlive(ᴋ41);
    if (r0 != 0) {
        neterr = ((syscall.Errno)r0);
    }
    return neterr;
}

// go2cs generated this placeholder — func NetUserGetLocalGroups is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

// go2cs generated this placeholder — func rtlGetVersion is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

public static error /*err*/ GetProcessMemoryInfo(syscallꓸHandle handle, ж<PROCESS_MEMORY_COUNTERS> ᏑmemCounters, uint32 cb) {
    error err = default!;

    var ᴋ48 = ᏑmemCounters;
        var (r1, _, e1) = syscall.Syscall(procGetProcessMemoryInfo.Addr(), 3, (uintptr)handle, (uintptr)ᴋ48, (uintptr)cb);
    System.GC.KeepAlive(ᴋ48);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ CreateEnvironmentBlock(ж<ж<uint16>> Ꮡblock, syscall.Token token, bool inheritExisting) {
    error err = default!;

    uint32 _p0 = default!;
    if (inheritExisting) {
        _p0 = 1;
    }
    var ᴋ49 = Ꮡblock;
        var (r1, _, e1) = syscall.Syscall(procCreateEnvironmentBlock.Addr(), 3, (uintptr)ᴋ49, (uintptr)token, (uintptr)_p0);
    System.GC.KeepAlive(ᴋ49);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ DestroyEnvironmentBlock(ж<uint16> Ꮡblock) {
    error err = default!;

    var ᴋ50 = Ꮡblock;
        var (r1, _, e1) = syscall.Syscall(procDestroyEnvironmentBlock.Addr(), 1, (uintptr)ᴋ50, 0, 0);
    System.GC.KeepAlive(ᴋ50);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

public static error /*err*/ GetProfilesDirectory(ж<uint16> Ꮡdir, ж<uint32> ᏑdirLen) {
    error err = default!;

    var ᴋ51 = Ꮡdir;
    var ᴋ52 = ᏑdirLen;
        var (r1, _, e1) = syscall.Syscall(procGetProfilesDirectoryW.Addr(), 2, (uintptr)ᴋ51, (uintptr)ᴋ52, 0);
    System.GC.KeepAlive(ᴋ51);
    System.GC.KeepAlive(ᴋ52);
    if (r1 == 0) {
        err = errnoErr(e1);
    }
    return err;
}

// go2cs generated this placeholder — func WSAGetOverlappedResult is hand-converted with managed semantics in the package's *_impl.cs ([module: GoManualConversion])

public static (syscallꓸHandle handle, error err) WSASocket(int32 af, int32 typ, int32 protocol, ж<syscall.WSAProtocolInfo> Ꮡprotinfo, uint32 group, uint32 flags) {
    syscallꓸHandle handle = default!;
    error err = default!;

    var ᴋ53 = Ꮡprotinfo;
        var (r0, _, e1) = syscall.Syscall6(procWSASocketW.Addr(), 6, (uintptr)af, (uintptr)typ, (uintptr)protocol, (uintptr)ᴋ53, (uintptr)group, (uintptr)flags);
    System.GC.KeepAlive(ᴋ53);
    handle = ((syscallꓸHandle)r0);
    if (handle == syscall.InvalidHandle) {
        err = errnoErr(e1);
    }
    return (handle, err);
}

} // end windows_package
