// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.compress;

using bytes = bytes_package;
using io = io_package;
using testing = testing_package;
using static go.compress.zlib_package;

partial class zlib_internal_test_package {

internal partial struct zlibTest {
    internal @string desc;
    internal @string raw;
    internal slice<byte> compressed;
    internal slice<byte> dict;
    internal error err;
}

// Compare-to-golden test data was generated by the ZLIB example program at
// https://www.zlib.net/zpipe.c
internal static slice<zlibTest> zlibTests;
internal static void initᴛzlibTests() { zlibTests = new zlibTest[]{
    new(
        "truncated empty"u8,
        ""u8,
        new byte[]{}.slice(),
        default!,
        io.ErrUnexpectedEOF
    ),
    new(
        "truncated dict"u8,
        ""u8,
        new byte[]{0x78, 0xbb}.slice(),
        new byte[]{0x00}.slice(),
        io.ErrUnexpectedEOF
    ),
    new(
        "truncated checksum"u8,
        ""u8,
        new byte[]{0x78, 0xbb, 0x00, 0x01, 0x00, 0x01, 0xca, 0x48,
            0xcd, 0xc9, 0xc9, 0xd7, 0x51, 0x28, 0xcf, 0x2f,
            0xca, 0x49, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff
        }.slice(),
        new byte[]{0x00}.slice(),
        io.ErrUnexpectedEOF
    ),
    new(
        "empty"u8,
        ""u8,
        new byte[]{0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01}.slice(),
        default!,
        default!
    ),
    new(
        "goodbye"u8,
        "goodbye, world"u8,
        new byte[]{
            0x78, 0x9c, 0x4b, 0xcf, 0xcf, 0x4f, 0x49, 0xaa,
            0x4c, 0xd5, 0x51, 0x28, 0xcf, 0x2f, 0xca, 0x49,
            0x01, 0x00, 0x28, 0xa5, 0x05, 0x5e
        }.slice(),
        default!,
        default!
    ),
    new(
        "bad header (CINFO)"u8,
        ""u8,
        new byte[]{0x88, 0x98, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01}.slice(),
        default!,
        ErrHeader
    ),
    new(
        "bad header (FCHECK)"u8,
        ""u8,
        new byte[]{0x78, 0x9f, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01}.slice(),
        default!,
        ErrHeader
    ),
    new(
        "bad checksum"u8,
        ""u8,
        new byte[]{0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0xff}.slice(),
        default!,
        ErrChecksum
    ),
    new(
        "not enough data"u8,
        ""u8,
        new byte[]{0x78, 0x9c, 0x03, 0x00, 0x00, 0x00}.slice(),
        default!,
        io.ErrUnexpectedEOF
    ),
    new(
        "excess data is silently ignored"u8,
        ""u8,
        new byte[]{
            0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01,
            0x78, 0x9c, 0xff
        }.slice(),
        default!,
        default!
    ),
    new(
        "dictionary"u8,
        "Hello, World!\n"u8,
        new byte[]{
            0x78, 0xbb, 0x1c, 0x32, 0x04, 0x27, 0xf3, 0x00,
            0xb1, 0x75, 0x20, 0x1c, 0x45, 0x2e, 0x00, 0x24,
            0x12, 0x04, 0x74
        }.slice(),
        new byte[]{
            0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x0a
        }.slice(),
        default!
    ),
    new(
        "wrong dictionary"u8,
        ""u8,
        new byte[]{
            0x78, 0xbb, 0x1c, 0x32, 0x04, 0x27, 0xf3, 0x00,
            0xb1, 0x75, 0x20, 0x1c, 0x45, 0x2e, 0x00, 0x24,
            0x12, 0x04, 0x74
        }.slice(),
        new byte[]{
            0x48, 0x65, 0x6c, 0x6c
        }.slice(),
        ErrDictionary
    ),
    new(
        "truncated zlib stream amid raw-block"u8,
        "hello"u8,
        new byte[]{
            0x78, 0x9c, 0x00, 0x0c, 0x00, 0xf3, 0xff, 0x68, 0x65, 0x6c, 0x6c, 0x6f
        }.slice(),
        default!,
        io.ErrUnexpectedEOF
    ),
    new(
        "truncated zlib stream amid fixed-block"u8,
        "He"u8,
        new byte[]{
            0x78, 0x9c, 0xf2, 0x48, 0xcd
        }.slice(),
        default!,
        io.ErrUnexpectedEOF
    )
}.slice(); }

public static void TestDecompressor(ж<testing.T> Ꮡt) {
    GoFrame ᒐ = default;
    try {
        var b = @new<bytes.Buffer>();
        foreach (var (_, tt) in zlibTests) {
            var @in = bytes.NewReader(tt.compressed);
            var (zr, err) = NewReaderDict(new zlib_test_package.bytes_ReaderжReader(@in), tt.dict);
            if (err != default!) {
                if (!AreEqual(err, tt.err)) {
                    Ꮡt.Errorf("%s: NewReader: %s"u8, tt.desc, err);
                }
                continue;
            }
            var zrʗ1 = zr;
            defer(() => zrʗ1.Close(), ref ᒐ);
            // Read and verify correctness of data.
            b.Reset();
            (var n, err) = io.Copy(new zlib_test_package.bytes_BufferжWriter(b), zr);
            if (err != default!) {
                if (!AreEqual(err, tt.err)) {
                    Ꮡt.Errorf("%s: io.Copy: %v want %v"u8, tt.desc, err, tt.err);
                }
                continue;
            }
            @string s = b.String();
            if (s != tt.raw) {
                Ꮡt.Errorf("%s: got %d-byte %q want %d-byte %q"u8, tt.desc, n, s, len(tt.raw), tt.raw);
            }
            // Check for sticky errors.
            {
                var (nΔ1, errΔ1) = zr.Read(new byte[]{0}.slice()); if (nΔ1 != 0 || !AreEqual(errΔ1, io.EOF)) {
                    Ꮡt.Errorf("%s: Read() = (%d, %v), want (0, io.EOF)"u8, tt.desc, nΔ1, errΔ1);
                }
            }
            {
                var errΔ2 = zr.Close(); if (errΔ2 != default!) {
                    Ꮡt.Errorf("%s: Close() = %v, want nil"u8, tt.desc, errΔ2);
                }
            }
        }
    }
    catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
    finally { ᒐ.Run(); }
}

} // end zlib_internal_test_package
