// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/synctest", new string[]
        {
            "synctest.go",
            "synctest_test.go",
        });
        registry.Add("TestChannelFromOutsideBubble", synctest_test_package.TestChannelFromOutsideBubble, "synctest_test.go", 183);
        registry.Add("TestCond", synctest_test_package.TestCond, "synctest_test.go", 290);
        registry.Add("TestDeadlockChild", synctest_test_package.TestDeadlockChild, "synctest_test.go", 281);
        registry.Add("TestDeadlockRoot", synctest_test_package.TestDeadlockRoot, "synctest_test.go", 274);
        registry.Add("TestGoroutineWait", synctest_test_package.TestGoroutineWait, "synctest_test.go", 51);
        registry.Add("TestIteratorPull", synctest_test_package.TestIteratorPull, "synctest_test.go", 369);
        registry.Add("TestIteratorPush", synctest_test_package.TestIteratorPush, "synctest_test.go", 340);
        registry.Add("TestMallocs", synctest_test_package.TestMallocs, "synctest_test.go", 83);
        registry.Add("TestNow", synctest_test_package.TestNow, "synctest_test.go", 19);
        registry.Add("TestReflectFuncOf", synctest_test_package.TestReflectFuncOf, "synctest_test.go", 398);
        registry.Add("TestRunEmpty", synctest_test_package.TestRunEmpty, "synctest_test.go", 40);
        registry.Add("TestSimpleWait", synctest_test_package.TestSimpleWait, "synctest_test.go", 45);
        registry.Add("TestTimeAfter", synctest_test_package.TestTimeAfter, "synctest_test.go", 154);
        registry.Add("TestTimerFromInsideBubble", synctest_test_package.TestTimerFromInsideBubble, "synctest_test.go", 233);
        registry.Add("TestTimerFromOutsideBubble", synctest_test_package.TestTimerFromOutsideBubble, "synctest_test.go", 173);
        registry.Add("TestTimerReadAfterDeadline", synctest_test_package.TestTimerReadAfterDeadline, "synctest_test.go", 119);
        registry.Add("TestTimerReadBeforeDeadline", synctest_test_package.TestTimerReadBeforeDeadline, "synctest_test.go", 108);
        registry.Add("TestTimerReset", synctest_test_package.TestTimerReset, "synctest_test.go", 132);
        registry.Add("TestWait", synctest_test_package.TestWait, "synctest_test.go", 60);
        registry.Add("TestWaitGroup", synctest_test_package.TestWaitGroup, "synctest_test.go", 419);
        return TestHost.Run(registry, args);
    }
}
