<#
.SYNOPSIS
    The module license file a nugetgo package packs (docs/PLAN-nugetgo.md B6): the upstream file, verbatim, under
    its own name. Nothing is ever inferred from its contents.

.DESCRIPTION
    The accepted names, and their order of preference, are the converter's own: moduleLicenseNames in
    src/go2cs/licensing.go, which a -recurse conversion uses to copy a dependency module's license. This module
    keeps a copy because PowerShell cannot read the Go list; Test-NugetgoIdentity.ps1 pins the two against each
    other, so the copy cannot drift.
#>
#Requires -Version 5.1

$script:NugetgoLicenseNames = @(
    'LICENSE', 'LICENSE.md', 'LICENSE.txt',
    'LICENCE', 'LICENCE.md', 'LICENCE.txt',
    'COPYING', 'COPYING.md', 'COPYING.txt'
)

function Get-NugetgoLicenseNames { $script:NugetgoLicenseNames }

# Returns @{ Name; Path; Reason }: the module root's license file in preference order, matched case-insensitively and
# spelled as the directory spells it (Name and Path set, Reason $null), or Name/Path $null with a Reason naming the
# directory and the names looked for.
function Find-NugetgoModuleLicense {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$ModuleDir)

    if (-not (Test-Path -LiteralPath $ModuleDir -PathType Container)) {
        return [pscustomobject]@{ Name = $null; Path = $null; Reason = "no module directory at $ModuleDir" }
    }

    $files = @(Get-ChildItem -LiteralPath $ModuleDir -File)

    foreach ($want in $script:NugetgoLicenseNames) {
        foreach ($file in $files) {
            if ([string]::Equals($file.Name, $want, [StringComparison]::OrdinalIgnoreCase)) {
                return [pscustomobject]@{ Name = $file.Name; Path = $file.FullName; Reason = $null }
            }
        }
    }

    [pscustomobject]@{ Name = $null; Path = $null; Reason = "no license file in $ModuleDir (looked for $($script:NugetgoLicenseNames -join ', '))" }
}

# The upstream license file's Copyright lines, trimmed, in file order: the lines the nupkg's Copyright field carries
# (B6) and that head each packed assembly's copyright attribute. A line counts only when it STARTS with "Copyright"
# (case-sensitive), so a license's "copyright notice, this list of conditions" clause is not one.
function Get-NugetgoCopyrightLines {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$LicenseFile)

    @(Get-Content -LiteralPath $LicenseFile | Where-Object { $_ -cmatch '^\s*Copyright\b' } | ForEach-Object { $_.Trim() })
}

# The last line of every packed third-party assembly's copyright: the go2cs-written scaffolding the conversion adds.
$script:NugetgoScaffoldingCopyright = 'go2cs scaffolding: Copyright (c) 2018-2026 The go2cs Authors'
$script:Go2csHolder = 'The go2cs Authors'

# Returns @{ Copyright; Skip; Reason }: the copyright attribute a packed library assembly carries (owner ruling
# 2026-10-04: the UPSTREAM holder) -- the upstream Copyright line(s), then the go2cs scaffolding line, joined by "; ".
# Skip is set when every upstream line already names The go2cs Authors (hashset): the csproj template's own value
# names that holder, so the assembly keeps it. A license file with no Copyright line is refused (Copyright $null,
# Skip $false, Reason set).
function Get-NugetgoAssemblyCopyright {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$LicenseFile)

    $lines = @(Get-NugetgoCopyrightLines -LicenseFile $LicenseFile)
    if ($lines.Count -eq 0) {
        return [pscustomobject]@{ Copyright = $null; Skip = $false; Reason = "the upstream license file carries no Copyright line: $LicenseFile" }
    }
    if (@($lines | Where-Object { -not $_.Contains($script:Go2csHolder) }).Count -eq 0) {
        return [pscustomobject]@{ Copyright = $null; Skip = $true; Reason = "every upstream Copyright line names $($script:Go2csHolder), whom the csproj template's own value already names" }
    }
    [pscustomobject]@{ Copyright = (@($lines) + $script:NugetgoScaffoldingCopyright) -join '; '; Skip = $false; Reason = $null }
}

# A value as an MSBuild property literal inside XML: MSBuild's special characters as %XX (so a ';' is never a list
# separator and a '$' or '@' never an expansion), then XML-escaped.
function ConvertTo-NugetgoMSBuildLiteral([string]$Value) {
    $msbuild = [regex]::Replace($Value, '[%$@'';?*]', { param($m) '%{0:X2}' -f [int][char]$m.Value })
    [System.Security.SecurityElement]::Escape($msbuild)
}

# The marker that identifies a Directory.Build.targets this pack wrote, so a later pack refreshes its own file and
# never overwrites a foreign one.
$script:NugetgoTargetsMarker = '<!-- Generated by nugetgo-pack.ps1. -->'
function Get-NugetgoTargetsMarker { $script:NugetgoTargetsMarker }

# The Directory.Build.targets that sits in the converted module's own directory (<root>/src/<module path>/) and makes
# its packed library assemblies carry the upstream holder. It lives in the converted tree, so the conversion
# repository pushed from that tree rebuilds the same attribute. MSBuild imports only the NEAREST
# Directory.Build.targets, so this one imports the output root's (go2cs -recurse writes it) before its own properties.
function New-NugetgoAssemblyMetadataTargets {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ModulePath,
        [Parameter(Mandatory)][string]$Copyright,
        [Parameter(Mandatory)][string]$Company,
        [Parameter(Mandatory)][string]$Authors
    )

    @(
        '<Project>',
        '',
        "  $script:NugetgoTargetsMarker",
        '',
        "  <!-- The packed library assemblies of $ModulePath name their UPSTREAM copyright holder: the upstream license",
        '       file''s Copyright line(s), then the go2cs scaffolding line. This file is imported after each project body,',
        '       so it overrides the csproj template''s values; a Go main package and a converted test project are not',
        '       packed and keep the template''s. MSBuild imports only the nearest Directory.Build.targets, so the output',
        '       root''s (written by go2cs -recurse) is imported first. -->',
        '  <PropertyGroup>',
        '    <NugetgoParentBuildTargets>$([MSBuild]::GetPathOfFileAbove(''Directory.Build.targets'', ''$(MSBuildThisFileDirectory)../''))</NugetgoParentBuildTargets>',
        '  </PropertyGroup>',
        '  <Import Project="$(NugetgoParentBuildTargets)" Condition="''$(NugetgoParentBuildTargets)'' != ''''" />',
        '',
        "  <PropertyGroup Condition=`"'`$(OutputType)' == 'Library' and !`$(MSBuildProjectName.EndsWith('.tests'))`">",
        "    <Copyright>$(ConvertTo-NugetgoMSBuildLiteral $Copyright)</Copyright>",
        "    <Company>$(ConvertTo-NugetgoMSBuildLiteral $Company)</Company>",
        "    <Authors>$(ConvertTo-NugetgoMSBuildLiteral $Authors)</Authors>",
        '  </PropertyGroup>',
        '',
        '</Project>',
        ''
    ) -join "`r`n"
}

Export-ModuleMember -Function Get-NugetgoLicenseNames, Find-NugetgoModuleLicense, Get-NugetgoCopyrightLines, Get-NugetgoAssemblyCopyright,
    ConvertTo-NugetgoMSBuildLiteral, Get-NugetgoTargetsMarker, New-NugetgoAssemblyMetadataTargets
