// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package time provides functionality for measuring and displaying time.
//
// The calendrical calculations always assume a Gregorian calendar, with
// no leap seconds.
//
// # Monotonic Clocks
//
// Operating systems provide both a “wall clock,” which is subject to
// changes for clock synchronization, and a “monotonic clock,” which is
// not. The general rule is that the wall clock is for telling time and
// the monotonic clock is for measuring time. Rather than split the API,
// in this package the Time returned by [time.Now] contains both a wall
// clock reading and a monotonic clock reading; later time-telling
// operations use the wall clock reading, but later time-measuring
// operations, specifically comparisons and subtractions, use the
// monotonic clock reading.
//
// For example, this code always computes a positive elapsed time of
// approximately 20 milliseconds, even if the wall clock is changed during
// the operation being timed:
//
//	start := time.Now()
//	... operation that takes 20 milliseconds ...
//	t := time.Now()
//	elapsed := t.Sub(start)
//
// Other idioms, such as [time.Since](start), [time.Until](deadline), and
// time.Now().Before(deadline), are similarly robust against wall clock
// resets.
//
// The rest of this section gives the precise details of how operations
// use monotonic clocks, but understanding those details is not required
// to use this package.
//
// The Time returned by time.Now contains a monotonic clock reading.
// If Time t has a monotonic clock reading, t.Add adds the same duration to
// both the wall clock and monotonic clock readings to compute the result.
// Because t.AddDate(y, m, d), t.Round(d), and t.Truncate(d) are wall time
// computations, they always strip any monotonic clock reading from their results.
// Because t.In, t.Local, and t.UTC are used for their effect on the interpretation
// of the wall time, they also strip any monotonic clock reading from their results.
// The canonical way to strip a monotonic clock reading is to use t = t.Round(0).
//
// If Times t and u both contain monotonic clock readings, the operations
// t.After(u), t.Before(u), t.Equal(u), t.Compare(u), and t.Sub(u) are carried out
// using the monotonic clock readings alone, ignoring the wall clock
// readings. If either t or u contains no monotonic clock reading, these
// operations fall back to using the wall clock readings.
//
// On some systems the monotonic clock will stop if the computer goes to sleep.
// On such a system, t.Sub(u) may not accurately reflect the actual
// time that passed between t and u. The same applies to other functions and
// methods that subtract times, such as [Since], [Until], [Time.Before], [Time.After],
// [Time.Add], [Time.Equal] and [Time.Compare]. In some cases, you may need to strip
// the monotonic clock to get accurate results.
//
// Because the monotonic clock reading has no meaning outside
// the current process, the serialized forms generated by t.GobEncode,
// t.MarshalBinary, t.MarshalJSON, and t.MarshalText omit the monotonic
// clock reading, and t.Format provides no format for it. Similarly, the
// constructors [time.Date], [time.Parse], [time.ParseInLocation], and [time.Unix],
// as well as the unmarshalers t.GobDecode, t.UnmarshalBinary.
// t.UnmarshalJSON, and t.UnmarshalText always create times with
// no monotonic clock reading.
//
// The monotonic clock reading exists only in [Time] values. It is not
// a part of [Duration] values or the Unix times returned by t.Unix and
// friends.
//
// Note that the Go == operator compares not just the time instant but
// also the [Location] and the monotonic clock reading. See the
// documentation for the Time type for a discussion of equality
// testing for Time values.
//
// For debugging, the result of t.String does include the monotonic
// clock reading if present. If t != u because of different monotonic clock readings,
// that difference will be visible when printing t.String() and u.String().
//
// # Timer Resolution
//
// [Timer] resolution varies depending on the Go runtime, the operating system
// and the underlying hardware.
// On Unix, the resolution is ~1ms.
// On Windows version 1803 and newer, the resolution is ~0.5ms.
// On older Windows versions, the default resolution is ~16ms, but
// a higher resolution may be requested using [golang.org/x/sys/windows.TimeBeginPeriod].
namespace go;

using errors = errors_package;
using bits = math.bits_package;
// blank import: unsafe_package (side effects only; no using emitted — a `using _` alias hijacks C# discards) // for go:linkname
using math;

partial class time_package {

// A Time represents an instant in time with nanosecond precision.
//
// Programs using times should typically store and pass them as values,
// not pointers. That is, time variables and struct fields should be of
// type [time.Time], not *time.Time.
//
// A Time value can be used by multiple goroutines simultaneously except
// that the methods [Time.GobDecode], [Time.UnmarshalBinary], [Time.UnmarshalJSON] and
// [Time.UnmarshalText] are not concurrency-safe.
//
// Time instants can be compared using the [Time.Before], [Time.After], and [Time.Equal] methods.
// The [Time.Sub] method subtracts two instants, producing a [Duration].
// The [Time.Add] method adds a Time and a Duration, producing a Time.
//
// The zero value of type Time is January 1, year 1, 00:00:00.000000000 UTC.
// As this time is unlikely to come up in practice, the [Time.IsZero] method gives
// a simple way of detecting a time that has not been initialized explicitly.
//
// Each time has an associated [Location]. The methods [Time.Local], [Time.UTC], and Time.In return a
// Time with a specific Location. Changing the Location of a Time value with
// these methods does not change the actual instant it represents, only the time
// zone in which to interpret it.
//
// Representations of a Time value saved by the [Time.GobEncode], [Time.MarshalBinary], [Time.AppendBinary],
// [Time.MarshalJSON], [Time.MarshalText] and [Time.AppendText] methods store the [Time.Location]'s offset,
// but not the location name. They therefore lose information about Daylight Saving Time.
//
// In addition to the required “wall clock” reading, a Time may contain an optional
// reading of the current process's monotonic clock, to provide additional precision
// for comparison or subtraction.
// See the “Monotonic Clocks” section in the package documentation for details.
//
// Note that the Go == operator compares not just the time instant but also the
// Location and the monotonic clock reading. Therefore, Time values should not
// be used as map or database keys without first guaranteeing that the
// identical Location has been set for all values, which can be achieved
// through use of the UTC or Local method, and that the monotonic clock reading
// has been stripped by setting t = t.Round(0). In general, prefer t.Equal(u)
// to t == u, since t.Equal uses the most accurate comparison available and
// correctly handles the case when only one of its arguments has a monotonic
// clock reading.
[GoType] partial struct Time {
    // wall and ext encode the wall time seconds, wall time nanoseconds,
    // and optional monotonic clock reading in nanoseconds.
    //
    // From high to low bit position, wall encodes a 1-bit flag (hasMonotonic),
    // a 33-bit seconds field, and a 30-bit wall time nanoseconds field.
    // The nanoseconds field is in the range [0, 999999999].
    // If the hasMonotonic bit is 0, then the 33-bit field must be zero
    // and the full signed 64-bit wall seconds since Jan 1 year 1 is stored in ext.
    // If the hasMonotonic bit is 1, then the 33-bit field holds a 33-bit
    // unsigned wall seconds since Jan 1 year 1885, and ext holds a
    // signed 64-bit monotonic clock reading, nanoseconds since process start.
    internal uint64 wall;
    internal int64 ext;
    // loc specifies the Location that should be used to
    // determine the minute, hour, month, day, and year
    // that correspond to this Time.
    // The nil location means UTC.
    // All UTC times are represented with loc==nil, never loc==&utcLoc.
    internal ж<ΔLocation> loc;
}

internal static UntypedInt hasMonotonic => /* 1 << 63 */ 9223372036854775808;
internal const int64 maxWall = /* wallToInternal + (1<<33 - 1) */ 68043243391; // year 2157
internal const int64 minWall = /* wallToInternal */ 59453308800;        // year 1885
internal static UntypedInt nsecMask => /* 1<<30 - 1 */ 1073741823;
internal static UntypedInt nsecShift => 30;

// These helpers for manipulating the wall and monotonic clock readings
// take pointer receivers, even when they don't modify the time,
// to make them cheaper to call.

// nsec returns the time's nanoseconds.
[GoRecv] internal static int32 nsec(this ref Time t) {
    return (int32)((uint64)(t.wall & (uint64)nsecMask));
}

// sec returns the time's seconds since Jan 1 year 1.
[GoRecv] internal static int64 sec(this ref Time t) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        return wallToInternal + (int64)(((t.wall << (int)(1)) >> (int)((nsecShift + 1))));
    }
    return t.ext;
}

// unixSec returns the time's seconds since Jan 1 1970 (Unix time).
[GoRecv] internal static int64 unixSec(this ref Time t) {
    return t.sec() + internalToUnix;
}

// addSec adds d seconds to the time.
[GoRecv] internal static void addSec(this ref Time t, int64 d) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        var sec = (int64)(((t.wall << (int)(1)) >> (int)((nsecShift + 1))));
        var dsec = sec + d;
        if (0 <= dsec && dsec <= 8589934591L) {
            t.wall = (uint64)((uint64)((uint64)(t.wall & (uint64)nsecMask) | ((uint64)dsec << (int)(nsecShift))) | (uint64)hasMonotonic);
            return;
        }
        // Wall second now out of range for packed field.
        // Move to ext.
        t.stripMono();
    }
    // Check if the sum of t.ext and d overflows and handle it properly.
    var sum = t.ext + d;
    if ((sum > t.ext) == (d > 0)){
        t.ext = sum;
    } else 
    if (d > 0){
        t.ext = 9223372036854775807L;
    } else {
        t.ext = -(9223372036854775807L);
    }
}

// setLoc sets the location associated with the time.
[GoRecv] internal static void setLoc(this ref Time t, ж<ΔLocation> Ꮡloc) {
    ref var loc = ref Ꮡloc.DerefOrNull();

    if (Ꮡloc == ᏑutcLoc) {
        Ꮡloc = default!; loc = ref Ꮡloc.DerefOrNull();
    }
    t.stripMono();
    t.loc = Ꮡloc;
}

// stripMono strips the monotonic clock reading in t.
[GoRecv] internal static void stripMono(this ref Time t) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        t.ext = t.sec();
        t.wall &= (uint64)(nsecMask);
    }
}

// setMono sets the monotonic clock reading in t.
// If t cannot hold a monotonic clock reading,
// because its wall time is too large,
// setMono is a no-op.
[GoRecv] internal static void setMono(this ref Time t, int64 m) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) == 0) {
        var sec = t.ext;
        if (sec < minWall || maxWall < sec) {
            return;
        }
        t.wall |= (uint64)((uint64)((uint64)hasMonotonic | ((uint64)(sec - minWall) << (int)(nsecShift))));
    }
    t.ext = m;
}

// mono returns t's monotonic clock reading.
// It returns 0 for a missing reading.
// This function is used only for testing,
// so it's OK that technically 0 is a valid
// monotonic clock reading as well.
[GoRecv] internal static int64 mono(this ref Time t) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) == 0) {
        return 0;
    }
    return t.ext;
}

// IsZero reports whether t represents the zero time instant,
// January 1, year 1, 00:00:00 UTC.
public static bool IsZero(this Time t) {
    return t.sec() == 0 && t.nsec() == 0;
}

// After reports whether the time instant t is after u.
public static bool After(this Time t, Time u) {
    if ((uint64)((uint64)(t.wall & u.wall) & (uint64)hasMonotonic) != 0) {
        return t.ext > u.ext;
    }
    var ts = t.sec();
    var us = u.sec();
    return ts > us || ts == us && t.nsec() > u.nsec();
}

// Before reports whether the time instant t is before u.
public static bool Before(this Time t, Time u) {
    if ((uint64)((uint64)(t.wall & u.wall) & (uint64)hasMonotonic) != 0) {
        return t.ext < u.ext;
    }
    var ts = t.sec();
    var us = u.sec();
    return ts < us || ts == us && t.nsec() < u.nsec();
}

// Compare compares the time instant t with u. If t is before u, it returns -1;
// if t is after u, it returns +1; if they're the same, it returns 0.
public static nint Compare(this Time t, Time u) {
    int64 tc = default!;
    int64 uc = default!;
    if ((uint64)((uint64)(t.wall & u.wall) & (uint64)hasMonotonic) != 0){
        (tc, uc) = (t.ext, u.ext);
    } else {
        (tc, uc) = (t.sec(), u.sec());
        if (tc == uc) {
            (tc, uc) = ((int64)t.nsec(), (int64)u.nsec());
        }
    }
    switch (ᐧ) {
    case {} when tc < uc: {
        return -1;
    }
    case {} when tc > uc: {
        return +1;
    }}

    return 0;
}

// Equal reports whether t and u represent the same time instant.
// Two times can be equal even if they are in different locations.
// For example, 6:00 +0200 and 4:00 UTC are Equal.
// See the documentation on the Time type for the pitfalls of using == with
// Time values; most code should use Equal instead.
public static bool Equal(this Time t, Time u) {
    if ((uint64)((uint64)(t.wall & u.wall) & (uint64)hasMonotonic) != 0) {
        return t.ext == u.ext;
    }
    return t.sec() == u.sec() && t.nsec() == u.nsec();
}

[GoType("num:nint")] partial struct ΔMonth;

public static ΔMonth January => /* 1 + iota */ 1;
public static ΔMonth February => 2;
public static ΔMonth March => 3;
public static ΔMonth April => 4;
public static ΔMonth May => 5;
public static ΔMonth June => 6;
public static ΔMonth July => 7;
public static ΔMonth August => 8;
public static ΔMonth September => 9;
public static ΔMonth October => 10;
public static ΔMonth November => 11;
public static ΔMonth December => 12;

// String returns the English name of the month ("January", "February", ...).
public static @string String(this ΔMonth m) {
    if (January <= m && m <= December) {
        return longMonthNames[m - 1];
    }
    var buf = new slice<byte>(20);
    nint n = fmtInt(buf, (uint64)(nint)m);
    return "%!Month("u8 + ((sstring)(buf[(int)(n)..])) + ")"u8;
}

[GoType("num:nint")] partial struct ΔWeekday;

public static ΔWeekday Sunday => /* iota */ 0;
public static ΔWeekday Monday => 1;
public static ΔWeekday Tuesday => 2;
public static ΔWeekday Wednesday => 3;
public static ΔWeekday Thursday => 4;
public static ΔWeekday Friday => 5;
public static ΔWeekday Saturday => 6;

// String returns the English name of the day ("Sunday", "Monday", ...).
public static @string String(this ΔWeekday d) {
    if (Sunday <= d && d <= Saturday) {
        return longDayNames[d];
    }
    var buf = new slice<byte>(20);
    nint n = fmtInt(buf, (uint64)(nint)d);
    return "%!Weekday("u8 + ((sstring)(buf[(int)(n)..])) + ")"u8;
}

// Computations on Times
//
// The zero value for a Time is defined to be
//	January 1, year 1, 00:00:00.000000000 UTC
// which (1) looks like a zero, or as close as you can get in a date
// (1-1-1 00:00:00 UTC), (2) is unlikely enough to arise in practice to
// be a suitable "not set" sentinel, unlike Jan 1 1970, and (3) has a
// non-negative year even in time zones west of UTC, unlike 1-1-0
// 00:00:00 UTC, which would be 12-31-(-1) 19:00:00 in New York.
//
// The zero Time value does not force a specific epoch for the time
// representation. For example, to use the Unix epoch internally, we
// could define that to distinguish a zero value from Jan 1 1970, that
// time would be represented by sec=-1, nsec=1e9. However, it does
// suggest a representation, namely using 1-1-1 00:00:00 UTC as the
// epoch, and that's what we do.
//
// The Add and Sub computations are oblivious to the choice of epoch.
//
// The presentation computations - year, month, minute, and so on - all
// rely heavily on division and modulus by positive constants. For
// calendrical calculations we want these divisions to round down, even
// for negative values, so that the remainder is always positive, but
// Go's division (like most hardware division instructions) rounds to
// zero. We can still do those computations and then adjust the result
// for a negative numerator, but it's annoying to write the adjustment
// over and over. Instead, we can change to a different epoch so long
// ago that all the times we care about will be positive, and then round
// to zero and round down coincide. These presentation routines already
// have to add the zone offset, so adding the translation to the
// alternate epoch is cheap. For example, having a non-negative time t
// means that we can write
//
//	sec = t % 60
//
// instead of
//
//	sec = t % 60
//	if sec < 0 {
//		sec += 60
//	}
//
// everywhere.
//
// The calendar runs on an exact 400 year cycle: a 400-year calendar
// printed for 1970-2369 will apply as well to 2370-2769. Even the days
// of the week match up. It simplifies date computations to choose the
// cycle boundaries so that the exceptional years are always delayed as
// long as possible: March 1, year 0 is such a day:
// the first leap day (Feb 29) is four years minus one day away,
// the first multiple-of-4 year without a Feb 29 is 100 years minus one day away,
// and the first multiple-of-100 year with a Feb 29 is 400 years minus one day away.
// March 1 year Y for any Y = 0 mod 400 is also such a day.
//
// Finally, it's convenient if the delta between the Unix epoch and
// long-ago epoch is representable by an int64 constant.
//
// These three considerations—choose an epoch as early as possible, that
// starts on March 1 of a year equal to 0 mod 400, and that is no more than
// 2⁶³ seconds earlier than 1970—bring us to the year -292277022400.
// We refer to this moment as the absolute zero instant, and to times
// measured as a uint64 seconds since this year as absolute times.
//
// Times measured as an int64 seconds since the year 1—the representation
// used for Time's sec field—are called internal times.
//
// Times measured as an int64 seconds since the year 1970 are called Unix
// times.
//
// It is tempting to just use the year 1 as the absolute epoch, defining
// that the routines are only valid for years >= 1. However, the
// routines would then be invalid when displaying the epoch in time zones
// west of UTC, since it is year 0. It doesn't seem tenable to say that
// printing the zero time correctly isn't supported in half the time
// zones. By comparison, it's reasonable to mishandle some times in
// the year -292277022400.
//
// All this is opaque to clients of the API and can be changed if a
// better implementation presents itself.
//
// The date calculations are implemented using the following clever math from
// Cassio Neri and Lorenz Schneider, “Euclidean affine functions and their
// application to calendar algorithms,” SP&E 2023. https://doi.org/10.1002/spe.3172
//
// Define a “calendrical division” (f, f°, f*) to be a triple of functions converting
// one time unit into a whole number of larger units and the remainder and back.
// For example, in a calendar with no leap years, (d/365, d%365, y*365) is the
// calendrical division for days into years:
//
//	(f)  year := days/365
//	(f°) yday := days%365
//	(f*) days := year*365 (+ yday)
//
// Note that f* is usually the “easy” function to write: it's the
// calendrical multiplication that inverts the more complex division.
//
// Neri and Schneider prove that when f* takes the form
//
//	f*(n) = (a n + b) / c
//
// using integer division rounding down with a ≥ c > 0,
// which they call a Euclidean affine function or EAF, then:
//
//	f(n) = (c n + c - b - 1) / a
//	f°(n) = (c n + c - b - 1) % a / c
//
// This gives a fairly direct calculation for any calendrical division for which
// we can write the calendrical multiplication in EAF form.
// Because the epoch has been shifted to March 1, all the calendrical
// multiplications turn out to be possible to write in EAF form.
// When a date is broken into [century, cyear, amonth, mday],
// with century, cyear, and mday 0-based,
// and amonth 3-based (March = 3, ..., January = 13, February = 14),
// the calendrical multiplications written in EAF form are:
//
//	yday = (153 (amonth-3) + 2) / 5 = (153 amonth - 457) / 5
//	cday = 365 cyear + cyear/4 = 1461 cyear / 4
//	centurydays = 36524 century + century/4 = 146097 century / 4
//	days = centurydays + cday + yday + mday.
//
// We can only handle one periodic cycle per equation, so the year
// calculation must be split into [century, cyear], handling both the
// 100-year cycle and the 400-year cycle.
//
// The yday calculation is not obvious but derives from the fact
// that the March through January calendar repeats the 5-month
// 153-day cycle 31, 30, 31, 30, 31 (we don't care about February
// because yday only ever count the days _before_ February 1,
// since February is the last month).
//
// Using the rule for deriving f and f° from f*, these multiplications
// convert to these divisions:
//
//	century := (4 days + 3) / 146097
//	cdays := (4 days + 3) % 146097 / 4
//	cyear := (4 cdays + 3) / 1461
//	ayday := (4 cdays + 3) % 1461 / 4
//	amonth := (5 ayday + 461) / 153
//	mday := (5 ayday + 461) % 153 / 5
//
// The a in ayday and amonth stands for absolute (March 1-based)
// to distinguish from the standard yday (January 1-based).
//
// After computing these, we can translate from the March 1 calendar
// to the standard January 1 calendar with branch-free math assuming a
// branch-free conversion from bool to int 0 or 1, denoted int(b) here:
//
//	isJanFeb := int(yday >= marchThruDecember)
//	month := amonth - isJanFeb*12
//	year := century*100 + cyear + isJanFeb
//	isLeap := int(cyear%4 == 0) & (int(cyear != 0) | int(century%4 == 0))
//	day := 1 + mday
//	yday := 1 + ayday + 31 + 28 + isLeap&^isJanFeb - 365*isJanFeb
//
// isLeap is the standard leap-year rule, but the split year form
// makes the divisions all reduce to binary masking.
// Note that day and yday are 1-based, in contrast to mday and ayday.

// To keep the various units separate, we define integer types
// for each. These are never stored in interfaces nor allocated,
// so their type information does not appear in Go binaries.
internal static UntypedInt secondsPerMinute => 60;

internal static UntypedInt secondsPerHour => /* 60 * secondsPerMinute */ 3600;

internal static UntypedInt secondsPerDay => /* 24 * secondsPerHour */ 86400;

internal static UntypedInt secondsPerWeek => /* 7 * secondsPerDay */ 604800;

internal static UntypedInt daysPer400Years => /* 365*400 + 97 */ 146097;

internal static UntypedInt marchThruDecember => /* 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31 + 30 + 31 */ 306;

internal static UntypedInt absoluteYears => 292277022400;

internal static UntypedInt internalYear => 1;

internal const int64 absoluteToInternal = /* -(absoluteYears*365.2425 + marchThruDecember) * secondsPerDay */ -9223371966606163200;

internal const int64 internalToAbsolute = /* -absoluteToInternal */ 9223371966606163200;

internal const int64 unixToInternal = /* (1969*365 + 1969/4 - 1969/100 + 1969/400) * secondsPerDay */ 62135596800;

internal const int64 internalToUnix = /* -unixToInternal */ -62135596800;

internal const int64 absoluteToUnix = /* absoluteToInternal + internalToUnix */ -9223372028741760000;

internal const int64 unixToAbsolute = /* unixToInternal + internalToAbsolute */ 9223372028741760000;

internal const int64 wallToInternal = /* (1884*365 + 1884/4 - 1884/100 + 1884/400) * secondsPerDay */ 59453308800;

[GoType("num:uint64")] partial struct absSeconds;

[GoType("num:uint64")] partial struct absDays;

[GoType("num:uint64")] partial struct absCentury;

[GoType("num:nint")] partial struct absCyear;

[GoType("num:nint")] partial struct absYday;

[GoType("num:nint")] partial struct absMonth;

[GoType("num:nint")] partial struct absLeap;

[GoType("num:nint")] partial struct absJanFeb;

// dateToAbsDays takes a standard year/month/day and returns the
// number of days from the absolute epoch to that day.
// The days argument can be out of range and in particular can be negative.
internal static absDays dateToAbsDays(int64 year, ΔMonth month, nint day) {
    // See “Computations on Times” comment above.
    var amonth = (uint32)(nint)month;
    var janFeb = (uint32)0;
    if (amonth < 3) {
        janFeb = 1;
    }
    amonth += 12 * janFeb;
    var y = (uint64)year - (uint64)janFeb + (uint64)absoluteYears;
    // For amonth is in the range [3,14], we want:
    //
    //	ayday := (153*amonth - 457) / 5
    //
    // (See the “Computations on Times” comment above
    // as well as Neri and Schneider, section 7.)
    //
    // That is equivalent to:
    //
    //	ayday := (979*amonth - 2919) >> 5
    //
    // and the latter form uses a couple fewer instructions,
    // so use it, saving a few cycles.
    // See Neri and Schneider, section 8.3
    // for more about this optimization.
    //
    // (Note that there is no saved division, because the compiler
    // implements / 5 without division in all cases.)
    var ayday = ((979 * amonth - 2919) >> (int)(5));
    var century = y / 100;
    var cyear = (uint32)(y % 100);
    var cday = 1461 * cyear / 4;
    var centurydays = 146097 * century / 4;
    return ((absDays)(centurydays + (uint64)((int64)(cday + ayday) + (int64)day - 1)));
}

// days converts absolute seconds to absolute days.
internal static absDays days(this absSeconds abs) {
    return ((absDays)(uint64)(abs / (uint64)secondsPerDay));
}

// split splits days into century, cyear, ayday.
internal static (absCentury century, absCyear cyear, absYday ayday) split(this absDays days) {
    absCentury century = default!;
    absCyear cyear = default!;
    absYday ayday = default!;

    // See “Computations on Times” comment above.
    var d = 4 * (uint64)days + 3;
    century = ((absCentury)(d / 146097));
    // This should be
    //	cday := uint32(d % 146097) / 4
    //	cd := 4*cday + 3
    // which is to say
    //	cday := uint32(d % 146097) >> 2
    //	cd := cday<<2 + 3
    // but of course (x>>2<<2)+3 == x|3,
    // so do that instead.
    var cd = (uint32)((uint32)(d % 146097) | 3);
    // For cdays in the range [0,146097] (100 years), we want:
    //
    //	cyear := (4 cdays + 3) / 1461
    //	yday := (4 cdays + 3) % 1461 / 4
    //
    // (See the “Computations on Times” comment above
    // as well as Neri and Schneider, section 7.)
    //
    // That is equivalent to:
    //
    //	cyear := (2939745 cdays) >> 32
    //	yday := (2939745 cdays) & 0xFFFFFFFF / 2939745 / 4
    //
    // so do that instead, saving a few cycles.
    // See Neri and Schneider, section 8.3
    // for more about this optimization.
    var (hi, lo) = bits.Mul32(2939745, (uint32)cd);
    cyear = ((absCyear)(nint)hi);
    ayday = ((absYday)(nint)(lo / 2939745 / 4));
    return (century, cyear, ayday);
}

// split splits ayday into absolute month and standard (1-based) day-in-month.
internal static (absMonth m, nint mday) split(this absYday ayday) {
    // See “Computations on Times” comment above.
    //
    // For yday in the range [0,366],
    //
    //	amonth := (5 yday + 461) / 153
    //	mday := (5 yday + 461) % 153 / 5
    //
    // is equivalent to:
    //
    //	amonth = (2141 yday + 197913) >> 16
    //	mday = (2141 yday + 197913) & 0xFFFF / 2141
    //
    // so do that instead, saving a few cycles.
    // See Neri and Schneider, section 8.3.
    var d = 2141 * (uint32)(nint)ayday + 197913;
    return (((absMonth)(nint)((d >> (int)(16)))), 1 + (nint)(((uint32)(d & 0xFFFF)) / 2141));
}

// janFeb returns 1 if the March 1-based ayday is in January or February, 0 otherwise.
internal static absJanFeb janFeb(this absYday ayday) {
    // See “Computations on Times” comment above.
    absJanFeb jf = ((absJanFeb)0);
    if (ayday >= marchThruDecember) {
        jf = 1;
    }
    return jf;
}

// month returns the standard Month for (m, janFeb)
internal static ΔMonth month(this absMonth m, absJanFeb janFeb) {
    // See “Computations on Times” comment above.
    return ((ΔMonth)(nint)m) - ((ΔMonth)(nint)janFeb) * 12;
}

// leap returns 1 if (century, cyear) is a leap year, 0 otherwise.
internal static absLeap leap(this absCentury century, absCyear cyear) {
    // See “Computations on Times” comment above.
    nint y4ok = 0;
    if (cyear % 4 == 0) {
        y4ok = 1;
    }
    nint y100ok = 0;
    if (cyear != 0) {
        y100ok = 1;
    }
    nint y400ok = 0;
    if (century % 4 == 0) {
        y400ok = 1;
    }
    return ((absLeap)((nint)(y4ok & ((nint)(y100ok | y400ok)))));
}

// year returns the standard year for (century, cyear, janFeb).
internal static nint year(this absCentury century, absCyear cyear, absJanFeb janFeb) {
    // See “Computations on Times” comment above.
    return (nint)((uint64)century * 100 - (uint64)absoluteYears) + (nint)cyear + (nint)janFeb;
}

// yday returns the standard 1-based yday for (ayday, janFeb, leap).
internal static nint yday(this absYday ayday, absJanFeb janFeb, absLeap leap) {
    // See “Computations on Times” comment above.
    return (nint)ayday + (1 + 31 + 28) + (nint)((nint)leap & ~(nint)janFeb) - 365 * (nint)janFeb;
}

// date converts days into standard year, month, day.
internal static (nint year, ΔMonth month, nint day) date(this absDays days) {
    nint year = default!;
    ΔMonth month = default!;
    nint day = default!;

    var (century, cyear, ayday) = days.split();
    (var amonth, day) = ayday.split();
    absJanFeb janFeb = ayday.janFeb();
    year = century.year(cyear, janFeb);
    month = amonth.month(janFeb);
    return (year, month, day);
}

// yearYday converts days into the standard year and 1-based yday.
internal static (nint year, nint yday) yearYday(this absDays days) {
    nint year = default!;
    nint yday = default!;

    var (century, cyear, ayday) = days.split();
    absJanFeb janFeb = ayday.janFeb();
    year = century.year(cyear, janFeb);
    yday = ayday.yday(janFeb, century.leap(cyear));
    return (year, yday);
}

// absSec returns the time t as an absolute seconds, adjusted by the zone offset.
// It is called when computing a presentation property like Month or Hour.
// We'd rather call it abs, but there are linknames to abs that make that problematic.
// See timeAbs below.
internal static absSeconds absSec(this Time t) {
    var l = t.loc;
    // Avoid function calls when possible.
    if (l == nil || l == ᏑlocalLoc) {
        l = l.get();
    }
    var sec = t.unixSec();
    if (l != ᏑutcLoc) {
        if ((~l).cacheZone != nil && (~l).cacheStart <= sec && sec < (~l).cacheEnd){
            sec += (int64)(~(~l).cacheZone).offset;
        } else {
            var (_, offset, _, _, _) = l.lookup(sec);
            sec += (int64)offset;
        }
    }
    return ((absSeconds)(uint64)(sec + (9223372028741760000L)));
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string utcˢ = "UTC"u8;

// locabs is a combination of the Zone and abs methods,
// extracting both return values from a single zone lookup.
internal static (@string name, nint offset, absSeconds abs) locabs(this Time t) {
    @string name = default!;
    nint offset = default!;
    absSeconds abs = default!;

    var l = t.loc;
    if (l == nil || l == ᏑlocalLoc) {
        l = l.get();
    }
    // Avoid function call if we hit the local time cache.
    var sec = t.unixSec();
    if (l != ᏑutcLoc){
        if ((~l).cacheZone != nil && (~l).cacheStart <= sec && sec < (~l).cacheEnd){
            name = l.Value.cacheZone.Value.name;
            offset = l.Value.cacheZone.Value.offset;
        } else {
            (name, offset, _, _, _) = l.lookup(sec);
        }
        sec += (int64)offset;
    } else {
        name = utcˢ;
    }
    abs = ((absSeconds)(uint64)(sec + (9223372028741760000L)));
    return (name, offset, abs);
}

// Date returns the year, month, and day in which t occurs.
public static (nint year, ΔMonth month, nint day) Date(this Time t) {
    return t.absSec().days().date();
}

// Year returns the year in which t occurs.
public static nint Year(this Time t) {
    var (century, cyear, ayday) = t.absSec().days().split();
    absJanFeb janFeb = ayday.janFeb();
    return century.year(cyear, janFeb);
}

// Month returns the month of the year specified by t.
public static ΔMonth Month(this Time t) {
    var (_, _, ayday) = t.absSec().days().split();
    var (amonth, _) = ayday.split();
    return amonth.month(ayday.janFeb());
}

// Day returns the day of the month specified by t.
public static nint Day(this Time t) {
    var (_, _, ayday) = t.absSec().days().split();
    var (_, day) = ayday.split();
    return day;
}

// Weekday returns the day of the week specified by t.
public static ΔWeekday Weekday(this Time t) {
    return t.absSec().days().weekday();
}

// weekday returns the day of the week specified by days.
internal static ΔWeekday weekday(this absDays days) {
    // March 1 of the absolute year, like March 1 of 2000, was a Wednesday.
    return ((ΔWeekday)(nint)(((uint64)days + (uint64)(nint)Wednesday) % 7));
}

// ISOWeek returns the ISO 8601 year and week number in which t occurs.
// Week ranges from 1 to 53. Jan 01 to Jan 03 of year n might belong to
// week 52 or 53 of year n-1, and Dec 29 to Dec 31 might belong to week 1
// of year n+1.
public static (nint year, nint week) ISOWeek(this Time t) {
    nint year = default!;

    // According to the rule that the first calendar week of a calendar year is
    // the week including the first Thursday of that year, and that the last one is
    // the week immediately preceding the first calendar week of the next calendar year.
    // See https://www.iso.org/obp/ui#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.1.23 for details.
    // weeks start with Monday
    // Monday Tuesday Wednesday Thursday Friday Saturday Sunday
    // 1      2       3         4        5      6        7
    // +3     +2      +1        0        -1     -2       -3
    // the offset to Thursday
    var days = t.absSec().days();
    var thu = days + ((absDays)(uint64)((nint)(Thursday - ((days - 1).weekday() + 1))));
    (year, var yday) = thu.yearYday();
    return (year, (yday - 1) / 7 + 1);
}

// Clock returns the hour, minute, and second within the day specified by t.
public static (nint hour, nint min, nint sec) Clock(this Time t) {
    return t.absSec().clock();
}

// clock returns the hour, minute, and second within the day specified by abs.
internal static (nint hour, nint min, nint sec) clock(this absSeconds abs) {
    nint hour = default!;
    nint min = default!;
    nint sec = default!;

    sec = (nint)(uint64)(abs % (uint64)secondsPerDay);
    hour = sec / (nint)secondsPerHour;
    sec -= hour * (nint)secondsPerHour;
    min = sec / (nint)secondsPerMinute;
    sec -= min * (nint)secondsPerMinute;
    return (hour, min, sec);
}

// Hour returns the hour within the day specified by t, in the range [0, 23].
public static nint Hour(this Time t) {
    return (nint)(uint64)(t.absSec() % (uint64)secondsPerDay) / (nint)secondsPerHour;
}

// Minute returns the minute offset within the hour specified by t, in the range [0, 59].
public static nint Minute(this Time t) {
    return (nint)(uint64)(t.absSec() % (uint64)secondsPerHour) / (nint)secondsPerMinute;
}

// Second returns the second offset within the minute specified by t, in the range [0, 59].
public static nint Second(this Time t) {
    return (nint)(uint64)(t.absSec() % (uint64)secondsPerMinute);
}

// Nanosecond returns the nanosecond offset within the second specified by t,
// in the range [0, 999999999].
public static nint Nanosecond(this Time t) {
    return (nint)t.nsec();
}

// YearDay returns the day of the year specified by t, in the range [1,365] for non-leap years,
// and [1,366] in leap years.
public static nint YearDay(this Time t) {
    var (_, yday) = t.absSec().days().yearYday();
    return yday;
}

[GoType("num:int64")] partial struct Duration;

internal static Duration minDuration => /* -1 << 63 */ -9223372036854775808;
internal static Duration maxDuration => /* 1<<63 - 1 */ 9223372036854775807;

// Common durations. There is no definition for units of Day or larger
// to avoid confusion across daylight savings time zone transitions.
//
// To count the number of units in a [Duration], divide:
//
//	second := time.Second
//	fmt.Print(int64(second/time.Millisecond)) // prints 1000
//
// To convert an integer number of units to a Duration, multiply:
//
//	seconds := 10
//	fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
public static Duration ΔNanosecond => 1;

public static Duration Microsecond => /* 1000 * Nanosecond */ 1000;

public static Duration Millisecond => /* 1000 * Microsecond */ 1000000;

public static Duration ΔSecond => /* 1000 * Millisecond */ 1000000000;

public static Duration ΔMinute => /* 60 * Second */ 60000000000;

public static Duration ΔHour => /* 60 * Minute */ 3600000000000;

// String returns a string representing the duration in the form "72h3m0.5s".
// Leading zero units are omitted. As a special case, durations less than one
// second format use a smaller unit (milli-, micro-, or nanoseconds) to ensure
// that the leading digit is non-zero. The zero duration formats as 0s.
public static @string String(this Duration d) {
    // This is inlinable to take advantage of "function outlining".
    // Thus, the caller can decide whether a string must be heap allocated.
    ref var arr = ref heap(new array<byte>(32), out var Ꮡarr);
    nint n = d.format(Ꮡarr);
    return ((@string)(arr[(int)(n)..]));
}

// format formats the representation of d into the end of buf and
// returns the offset of the first character.
internal static nint format(this Duration d, [GoArrayDims(32)] ж<array<byte>> Ꮡbuf) {
    ref var buf = ref Ꮡbuf.DerefOrNull();

    // Largest time is 2540400h10m10.000000000s
    nint w = 32;
    var u = (uint64)(int64)d;
    var neg = d < 0;
    if (neg) {
        u = ((uint64)0 - u);
    }
    if (u < (uint64)(int64)ΔSecond){
        // Special case: if duration is smaller than a second,
        // use smaller units, like 1.2ms
        nint prec = default!;
        w--;
        buf[w] = (rune)'s';
        w--;
        switch (ᐧ) {
        case {} when u is 0: {
            buf[w] = (rune)'0';
            return w;
        }
        case {} when u < (uint64)(int64)Microsecond: {
            prec = 0;
            buf[w] = (rune)'n';
            break;
        }
        case {} when u < (uint64)(int64)Millisecond: {
            prec = 3;
            w--; // Need room for two bytes.
            copy(buf[(int)(w)..], // print nanoseconds
 // print microseconds
 // U+00B5 'µ' micro sign == 0xC2 0xB5
 "µ"u8);
            break;
        }
        default: {
            prec = 6;
            buf[w] = (rune)'m';
            break;
        }}

        // print milliseconds
        (w, u) = fmtFrac(buf[..(int)(w)], u, prec);
        w = fmtInt(buf[..(int)(w)], u);
    } else {
        w--;
        buf[w] = (rune)'s';
        (w, u) = fmtFrac(buf[..(int)(w)], u, 9);
        // u is now integer seconds
        w = fmtInt(buf[..(int)(w)], u % 60);
        u /= 60;
        // u is now integer minutes
        if (u > 0) {
            w--;
            buf[w] = (rune)'m';
            w = fmtInt(buf[..(int)(w)], u % 60);
            u /= 60;
            // u is now integer hours
            // Stop at hours because days can be different lengths.
            if (u > 0) {
                w--;
                buf[w] = (rune)'h';
                w = fmtInt(buf[..(int)(w)], u);
            }
        }
    }
    if (neg) {
        w--;
        buf[w] = (rune)'-';
    }
    return w;
}

// fmtFrac formats the fraction of v/10**prec (e.g., ".12345") into the
// tail of buf, omitting trailing zeros. It omits the decimal
// point too when the fraction is 0. It returns the index where the
// output bytes begin and the value v/10**prec.
internal static (nint nw, uint64 nv) fmtFrac(slice<byte> buf, uint64 v, nint prec) {
    // Omit trailing zeros up to and including decimal point.
    nint w = len(buf);
    var print = false;
    for (nint i = 0; i < prec; i++) {
        var digit = v % 10;
        print = print || digit != 0;
        if (print) {
            w--;
            buf[w] = (byte)((byte)digit + (rune)'0');
        }
        v /= 10;
    }
    if (print) {
        w--;
        buf[w] = (rune)'.';
    }
    return (w, v);
}

// fmtInt formats v into the tail of buf.
// It returns the index where the output begins.
internal static nint fmtInt(slice<byte> buf, uint64 v) {
    nint w = len(buf);
    if (v == 0){
        w--;
        buf[w] = (rune)'0';
    } else {
        while (v > 0) {
            w--;
            buf[w] = (byte)((byte)(v % 10) + (rune)'0');
            v /= 10;
        }
    }
    return w;
}

// Nanoseconds returns the duration as an integer nanosecond count.
public static int64 Nanoseconds(this Duration d) {
    return (int64)d;
}

// Microseconds returns the duration as an integer microsecond count.
public static int64 Microseconds(this Duration d) {
    return (int64)d / 1000;
}

// Milliseconds returns the duration as an integer millisecond count.
public static int64 Milliseconds(this Duration d) {
    return (int64)d / 1000000;
}

// These methods return float64 because the dominant
// use case is for printing a floating point number like 1.5s, and
// a truncation to integer would make them not useful in those cases.
// Splitting the integer and fraction ourselves guarantees that
// converting the returned float64 to an integer rounds the same
// way that a pure integer conversion would have, even in cases
// where, say, float64(d.Nanoseconds())/1e9 would have rounded
// differently.

// Seconds returns the duration as a floating point number of seconds.
public static float64 Seconds(this Duration d) {
    var sec = d / ΔSecond;
    var nsec = d % ΔSecond;
    return (float64)(int64)sec + (float64)(int64)nsec / 1e9D;
}

// Minutes returns the duration as a floating point number of minutes.
public static float64 Minutes(this Duration d) {
    var min = d / ΔMinute;
    var nsec = d % ΔMinute;
    return (float64)(int64)min + (float64)(int64)nsec / (60D * 1e9D);
}

// Hours returns the duration as a floating point number of hours.
public static float64 Hours(this Duration d) {
    var hour = d / ΔHour;
    var nsec = d % ΔHour;
    return (float64)(int64)hour + (float64)(int64)nsec / (60D * 60D * 1e9D);
}

// Truncate returns the result of rounding d toward zero to a multiple of m.
// If m <= 0, Truncate returns d unchanged.
public static Duration Truncate(this Duration d, Duration m) {
    if (m <= 0) {
        return d;
    }
    return d - d % m;
}

// lessThanHalf reports whether x+x < y but avoids overflow,
// assuming x and y are both positive (Duration is signed).
internal static bool lessThanHalf(Duration x, Duration y) {
    return (uint64)(int64)x + (uint64)(int64)x < (uint64)(int64)y;
}

// Round returns the result of rounding d to the nearest multiple of m.
// The rounding behavior for halfway values is to round away from zero.
// If the result exceeds the maximum (or minimum)
// value that can be stored in a [Duration],
// Round returns the maximum (or minimum) duration.
// If m <= 0, Round returns d unchanged.
public static Duration Round(this Duration d, Duration m) {
    if (m <= 0) {
        return d;
    }
    var r = d % m;
    if (d < 0) {
        r = -r;
        if (lessThanHalf(r, m)) {
            return d + r;
        }
        {
            var d1 = d - m + r; if (d1 < d) {
                return d1;
            }
        }
        return minDuration; // overflow
    }
    if (lessThanHalf(r, m)) {
        return d - r;
    }
    {
        var d1 = d + m - r; if (d1 > d) {
            return d1;
        }
    }
    return maxDuration; // overflow
}

// Abs returns the absolute value of d.
// As a special case, Duration([math.MinInt64]) is converted to Duration([math.MaxInt64]),
// reducing its magnitude by 1 nanosecond.
public static Duration Abs(this Duration d) {
    switch (ᐧ) {
    case {} when d >= 0: {
        return d;
    }
    case {} when d == minDuration: {
        return maxDuration;
    }
    default: {
        return -d;
    }}

}

// Add returns the time t+d.
public static Time Add(this Time t, Duration d) {
    var dsec = (int64)(d / 1000000000);
    var nsec = t.nsec() + (int32)(int64)(d % 1000000000);
    if (nsec >= 1000000000){
        dsec++;
        nsec -= 1000000000;
    } else 
    if (nsec < 0) {
        dsec--;
        nsec += 1000000000;
    }
    t.wall = (uint64)((uint64)(t.wall & ~(uint64)nsecMask) | (uint64)nsec); // update nsec
    t.addSec(dsec);
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        var te = t.ext + (int64)d;
        if (d < 0 && te > t.ext || d > 0 && te < t.ext){
            // Monotonic clock reading now out of range; degrade to wall-only.
            t.stripMono();
        } else {
            t.ext = te;
        }
    }
    return t;
}

// Sub returns the duration t-u. If the result exceeds the maximum (or minimum)
// value that can be stored in a [Duration], the maximum (or minimum) duration
// will be returned.
// To compute t-d for a duration d, use t.Add(-d).
public static Duration Sub(this Time t, Time u) {
    if ((uint64)((uint64)(t.wall & u.wall) & (uint64)hasMonotonic) != 0) {
        return subMono(t.ext, u.ext);
    }
    var d = ((Duration)(t.sec() - u.sec())) * ΔSecond + ((Duration)(int64)(t.nsec() - u.nsec()));
    // Check for overflow or underflow.
    switch (ᐧ) {
    case {} when u.Add(d).Equal(t): {
        return d; // d is correct
    }
    case {} when t.Before(u): {
        return minDuration; // t - u is negative out of range
    }
    default: {
        return maxDuration; // t - u is positive out of range
    }}

}

internal static Duration subMono(int64 t, int64 u) {
    var d = ((Duration)(t - u));
    if (d < 0 && t > u) {
        return maxDuration; // t - u is positive out of range
    }
    if (d > 0 && t < u) {
        return minDuration; // t - u is negative out of range
    }
    return d;
}

// Since returns the time elapsed since t.
// It is shorthand for time.Now().Sub(t).
public static Duration Since(Time t) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        // Common case optimization: if t has monotonic time, then Sub will use only it.
        return subMono(runtimeNano() - startNano, t.ext);
    }
    return Now().Sub(t);
}

// Until returns the duration until t.
// It is shorthand for t.Sub(time.Now()).
public static Duration Until(Time t) {
    if ((uint64)(t.wall & (uint64)hasMonotonic) != 0) {
        // Common case optimization: if t has monotonic time, then Sub will use only it.
        return subMono(t.ext, runtimeNano() - startNano);
    }
    return t.Sub(Now());
}

// AddDate returns the time corresponding to adding the
// given number of years, months, and days to t.
// For example, AddDate(-1, 2, 3) applied to January 1, 2011
// returns March 4, 2010.
//
// Note that dates are fundamentally coupled to timezones, and calendrical
// periods like days don't have fixed durations. AddDate uses the Location of
// the Time value to determine these durations. That means that the same
// AddDate arguments can produce a different shift in absolute time depending on
// the base Time value and its Location. For example, AddDate(0, 0, 1) applied
// to 12:00 on March 27 always returns 12:00 on March 28. At some locations and
// in some years this is a 24 hour shift. In others it's a 23 hour shift due to
// daylight savings time transitions.
//
// AddDate normalizes its result in the same way that Date does,
// so, for example, adding one month to October 31 yields
// December 1, the normalized form for November 31.
public static Time AddDate(this Time t, nint years, nint months, nint days) {
    var (year, month, day) = t.Date();
    var (hour, min, sec) = t.Clock();
    return Date(year + years, month + ((ΔMonth)months), day + days, hour, min, sec, (nint)t.nsec(), t.Location());
}

// daysBefore returns the number of days in a non-leap year before month m.
// daysBefore(December+1) returns 365.
internal static nint daysBefore(ΔMonth m) {
    nint adj = 0;
    if (m >= March) {
        adj = -2;
    }
    // With the -2 adjustment after February,
    // we need to compute the running sum of:
    //	0  31  30  31  30  31  30  31  31  30  31  30  31
    // which is:
    //	0  31  61  92 122 153 183 214 245 275 306 336 367
    // This is almost exactly 367/12×(m-1) except for the
    // occasonal off-by-one suggesting there may be an
    // integer approximation of the form (a×m + b)/c.
    // A brute force search over small a, b, c finds that
    // (214×m - 211) / 7 computes the function perfectly.
    return (214 * (nint)m - 211) / 7 + adj;
}

internal static nint daysIn(ΔMonth m, nint year) {
    if (m == February) {
        if (isLeap(year)) {
            return 29;
        }
        return 28;
    }
    // With the special case of February eliminated, the pattern is
    //	31 30 31 30 31 30 31 31 30 31 30 31
    // Adding m&1 produces the basic alternation;
    // adding (m>>3)&1 inverts the alternation starting in August.
    return 30 + (nint)((ΔMonth)((m + (m >> (int)(3))) & 1));
}

// Provided by package runtime.
//
// now returns the current real time, and is superseded by runtimeNow which returns
// the fake synctest clock when appropriate.
//
// now should be an internal detail,
// but widely used packages access it using linkname.
// Notable members of the hall of shame include:
//   - gitee.com/quant1x/gox
//   - github.com/phuslu/log
//   - github.com/sethvargo/go-limiter
//   - github.com/ulule/limiter/v3
//
// Do not remove or change the type signature.
// See go.dev/issue/67401.
internal static partial (int64 sec, int32 nsec, int64 mono) now();

// runtimeNow returns the current time.
// When called within a synctest.Run bubble, it returns the group's fake clock.
//
//go:linkname runtimeNow
internal static partial (int64 sec, int32 nsec, int64 mono) runtimeNow();

// runtimeNano returns the current value of the runtime clock in nanoseconds.
// When called within a synctest.Run bubble, it returns the group's fake clock.
//
//go:linkname runtimeNano
internal static partial int64 runtimeNano();

// Monotonic times are reported as offsets from startNano.
// We initialize startNano to runtimeNano() - 1 so that on systems where
// monotonic time resolution is fairly low (e.g. Windows 2008
// which appears to have a default resolution of 15ms),
// we avoid ever reporting a monotonic time of 0.
// (Callers may want to use 0 as "time not set".)
internal static int64 startNano = runtimeNano() - 1;

// x/tools uses a linkname of time.Now in its tests. No harm done.
//go:linkname Now

// Now returns the current local time.
public static Time Now() {
    var (sec, nsec, mono) = runtimeNow();
    if (mono == 0) {
        return new Time((uint64)nsec, sec + unixToInternal, ΔLocal);
    }
    mono -= startNano;
    sec += 2682288000L;
    if (((uint64)sec >> (int)(33)) != 0) {
        // Seconds field overflowed the 33 bits available when
        // storing a monotonic time. This will be true after
        // March 16, 2157.
        return new Time((uint64)nsec, sec + minWall, ΔLocal);
    }
    return new Time((uint64)((uint64)((uint64)hasMonotonic | ((uint64)sec << (int)(nsecShift))) | (uint64)nsec), mono, ΔLocal);
}

internal static Time unixTime(int64 sec, int32 nsec) {
    return new Time((uint64)nsec, sec + unixToInternal, ΔLocal);
}

// UTC returns t with the location set to UTC.
public static Time UTC(this Time t) {
    t.setLoc(ᏑutcLoc);
    return t;
}

// Local returns t with the location set to local time.
public static Time Local(this Time t) {
    t.setLoc(ΔLocal);
    return t;
}

// In returns a copy of t representing the same time instant, but
// with the copy's location information set to loc for display
// purposes.
//
// In panics if loc is nil.
public static Time In(this Time t, ж<ΔLocation> Ꮡloc) {
    if (Ꮡloc == nil) {
        throw panic("time: missing Location in call to Time.In");
    }
    t.setLoc(Ꮡloc);
    return t;
}

// Location returns the time zone information associated with t.
public static ж<ΔLocation> Location(this Time t) {
    var l = t.loc;
    if (l == nil) {
        l = ΔUTC;
    }
    return l;
}

// Zone computes the time zone in effect at time t, returning the abbreviated
// name of the zone (such as "CET") and its offset in seconds east of UTC.
public static (@string name, nint offset) Zone(this Time t) {
    @string name = default!;
    nint offset = default!;

    (name, offset, _, _, _) = t.loc.lookup(t.unixSec());
    return (name, offset);
}

// ZoneBounds returns the bounds of the time zone in effect at time t.
// The zone begins at start and the next zone begins at end.
// If the zone begins at the beginning of time, start will be returned as a zero Time.
// If the zone goes on forever, end will be returned as a zero Time.
// The Location of the returned times will be the same as t.
public static (Time start, Time end) ZoneBounds(this Time t) {
    Time start = default!;
    Time end = default!;

    var (_, _, startSec, endSec, _) = t.loc.lookup(t.unixSec());
    if (startSec != alpha) {
        start = unixTime(startSec, 0);
        start.setLoc(t.loc);
    }
    if (endSec != omega) {
        end = unixTime(endSec, 0);
        end.setLoc(t.loc);
    }
    return (start, end);
}

// Unix returns t as a Unix time, the number of seconds elapsed
// since January 1, 1970 UTC. The result does not depend on the
// location associated with t.
// Unix-like operating systems often record time as a 32-bit
// count of seconds, but since the method here returns a 64-bit
// value it is valid for billions of years into the past or future.
public static int64 Unix(this Time t) {
    return t.unixSec();
}

// UnixMilli returns t as a Unix time, the number of milliseconds elapsed since
// January 1, 1970 UTC. The result is undefined if the Unix time in
// milliseconds cannot be represented by an int64 (a date more than 292 million
// years before or after 1970). The result does not depend on the
// location associated with t.
public static int64 UnixMilli(this Time t) {
    return t.unixSec() * 1000 + (int64)t.nsec() / 1000000;
}

// UnixMicro returns t as a Unix time, the number of microseconds elapsed since
// January 1, 1970 UTC. The result is undefined if the Unix time in
// microseconds cannot be represented by an int64 (a date before year -290307 or
// after year 294246). The result does not depend on the location associated
// with t.
public static int64 UnixMicro(this Time t) {
    return t.unixSec() * 1000000 + (int64)t.nsec() / 1000;
}

// UnixNano returns t as a Unix time, the number of nanoseconds elapsed
// since January 1, 1970 UTC. The result is undefined if the Unix time
// in nanoseconds cannot be represented by an int64 (a date before the year
// 1678 or after 2262). Note that this means the result of calling UnixNano
// on the zero Time is undefined. The result does not depend on the
// location associated with t.
public static int64 UnixNano(this Time t) {
    return (t.unixSec()) * 1000000000 + (int64)t.nsec();
}

internal const byte timeBinaryVersionV1 = /* iota + 1 */ 1;    // For general situation
internal const byte timeBinaryVersionV2 = 2;    // For LMT only

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string timeMarshalBinaryˢ = "Time.MarshalBinary: unexpected zone offset"u8;

// AppendBinary implements the [encoding.BinaryAppender] interface.
public static (slice<byte>, error) AppendBinary(this Time t, slice<byte> b) {
    int16 offsetMin = default!;   // minutes east of UTC. -1 is UTC.
    int8 offsetSec = default!;
    var version = timeBinaryVersionV1;
    if (t.Location() == ΔUTC){
        offsetMin = (int16)(-1);
    } else {
        var (_, offset) = t.Zone();
        if (offset % 60 != 0) {
            version = timeBinaryVersionV2;
            offsetSec = (int8)(offset % 60);
        }
        offset /= 60;
        if (offset < -32768 || offset == -1 || offset > 32767) {
            return (b, errors.New(timeMarshalBinaryˢ));
        }
        offsetMin = (int16)offset;
    }
    var sec = t.sec();
    var nsec = t.nsec();
    b = append(b,
        version, // byte 0 : version

        (byte)((sec >> (int)(56))), // bytes 1-8: seconds

        (byte)((sec >> (int)(48))),
        (byte)((sec >> (int)(40))),
        (byte)((sec >> (int)(32))),
        (byte)((sec >> (int)(24))),
        (byte)((sec >> (int)(16))),
        (byte)((sec >> (int)(8))),
        (byte)sec,
        (byte)((nsec >> (int)(24))), // bytes 9-12: nanoseconds

        (byte)((nsec >> (int)(16))),
        (byte)((nsec >> (int)(8))),
        (byte)nsec,
        (byte)((offsetMin >> (int)(8))), // bytes 13-14: zone offset in minutes

        (byte)offsetMin);
    if (version == timeBinaryVersionV2) {
        b = append(b, (byte)offsetSec);
    }
    return (b, default!);
}

// MarshalBinary implements the [encoding.BinaryMarshaler] interface.
public static (slice<byte>, error) MarshalBinary(this Time t) {
    var (b, err) = t.AppendBinary(new slice<byte>(0, 16));
    if (err != default!) {
        return (default!, err);
    }
    return (b, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string timeUnmarshalBinaryNoˢ = "Time.UnmarshalBinary: no data"u8;
internal static readonly @string timeUnmarshalBinaryˢ = "Time.UnmarshalBinary: unsupported version"u8;
internal static readonly @string timeUnmarshalBinaryˢ2 = "Time.UnmarshalBinary: invalid length"u8;

// UnmarshalBinary implements the [encoding.BinaryUnmarshaler] interface.
[GoRecv] public static error UnmarshalBinary(this ref Time t, slice<byte> data) {
    var buf = data;
    if (len(buf) == 0) {
        return errors.New(timeUnmarshalBinaryNoˢ);
    }
    var version = buf[0];
    if (version != timeBinaryVersionV1 && version != timeBinaryVersionV2) {
        return errors.New(timeUnmarshalBinaryˢ);
    }
    nint wantLen = 1 + 8 + 4 + 2;
    /*version*/
    /*sec*/
    /*nsec*/
    /*zone offset*/
    if (version == timeBinaryVersionV2) {
        wantLen++;
    }
    if (len(buf) != wantLen) {
        return errors.New(timeUnmarshalBinaryˢ2);
    }
    buf = buf[1..];
    var sec = (int64)((int64)((int64)((int64)((int64)((int64)((int64)((int64)buf[7] | ((int64)buf[6] << (int)(8))) | ((int64)buf[5] << (int)(16))) | ((int64)buf[4] << (int)(24))) | ((int64)buf[3] << (int)(32))) | ((int64)buf[2] << (int)(40))) | ((int64)buf[1] << (int)(48))) | ((int64)buf[0] << (int)(56)));
    buf = buf[8..];
    var nsec = (int32)((int32)((int32)((int32)buf[3] | ((int32)buf[2] << (int)(8))) | ((int32)buf[1] << (int)(16))) | ((int32)buf[0] << (int)(24)));
    buf = buf[4..];
    nint offset = (nint)((int16)((int16)buf[1] | (int16)((int16)buf[0] << (int)(8)))) * 60;
    if (version == timeBinaryVersionV2) {
        offset += (nint)buf[2];
    }
    t = new Time(nil);
    t.wall = (uint64)nsec;
    t.ext = sec;
    if (offset == -1 * 60){
        t.setLoc(ᏑutcLoc);
    } else 
    {
        var (_, localoff, _, _, _) = ΔLocal.lookup(t.unixSec()); if (offset == localoff){
            t.setLoc(ΔLocal);
        } else {
            t.setLoc(FixedZone(""u8, offset));
        }
    }
    return default!;
}

// TODO(rsc): Remove GobEncoder, GobDecoder, MarshalJSON, UnmarshalJSON in Go 2.
// The same semantics will be provided by the generic MarshalBinary, MarshalText,
// UnmarshalBinary, UnmarshalText.

// GobEncode implements the gob.GobEncoder interface.
public static (slice<byte>, error) GobEncode(this Time t) {
    return t.MarshalBinary();
}

// GobDecode implements the gob.GobDecoder interface.
[GoRecv] public static error GobDecode(this ref Time t, slice<byte> data) {
    return t.UnmarshalBinary(data);
}

// MarshalJSON implements the [encoding/json.Marshaler] interface.
// The time is a quoted string in the RFC 3339 format with sub-second precision.
// If the timestamp cannot be represented as valid RFC 3339
// (e.g., the year is out of range), then an error is reported.
public static (slice<byte>, error) MarshalJSON(this Time t) {
    var b = new slice<byte>(0, len(RFC3339Nano) + len(@""""""));
    b = append(b, (byte)((rune)'"'));
    (b, var err) = t.appendStrictRFC3339(b);
    b = append(b, (byte)((rune)'"'));
    if (err != default!) {
        return (default!, errors.New("Time.MarshalJSON: "u8 + err.Error()));
    }
    return (b, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string timeUnmarshalJSONInputIsˢ = "Time.UnmarshalJSON: input is not a JSON string"u8;

// UnmarshalJSON implements the [encoding/json.Unmarshaler] interface.
// The time must be a quoted string in the RFC 3339 format.
[GoRecv] public static error UnmarshalJSON(this ref Time t, slice<byte> data) {
    if (((sstring)data) == "null"u8) {
        return default!;
    }
    // TODO(https://go.dev/issue/47353): Properly unescape a JSON string.
    if (len(data) < 2 || data[0] != (rune)'"' || data[len(data) - 1] != (rune)'"') {
        return errors.New(timeUnmarshalJSONInputIsˢ);
    }
    data = data[(int)(len(@""""))..(int)(len(data) - len(@""""))];
    error err = default!;
    (t, err) = parseStrictRFC3339(data);
    return err;
}

internal static (slice<byte>, error) appendTo(this Time t, slice<byte> b, @string errPrefix) {
    (b, var err) = t.appendStrictRFC3339(b);
    if (err != default!) {
        return (default!, errors.New(errPrefix + err.Error()));
    }
    return (b, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string timeAppendTextˢ = "Time.AppendText: "u8;

// AppendText implements the [encoding.TextAppender] interface.
// The time is formatted in RFC 3339 format with sub-second precision.
// If the timestamp cannot be represented as valid RFC 3339
// (e.g., the year is out of range), then an error is returned.
public static (slice<byte>, error) AppendText(this Time t, slice<byte> b) {
    return t.appendTo(b, timeAppendTextˢ);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string timeMarshalTextˢ = "Time.MarshalText: "u8;

// MarshalText implements the [encoding.TextMarshaler] interface. The output
// matches that of calling the [Time.AppendText] method.
//
// See [Time.AppendText] for more information.
public static (slice<byte>, error) MarshalText(this Time t) {
    return t.appendTo(new slice<byte>(0, len(RFC3339Nano)), timeMarshalTextˢ);
}

// UnmarshalText implements the [encoding.TextUnmarshaler] interface.
// The time must be in the RFC 3339 format.
[GoRecv] public static error UnmarshalText(this ref Time t, slice<byte> data) {
    error err = default!;
    (t, err) = parseStrictRFC3339(data);
    return err;
}

// Unix returns the local Time corresponding to the given Unix time,
// sec seconds and nsec nanoseconds since January 1, 1970 UTC.
// It is valid to pass nsec outside the range [0, 999999999].
// Not all sec values have a corresponding time value. One such
// value is 1<<63-1 (the largest int64 value).
public static Time Unix(int64 sec, int64 nsec) {
    if (nsec < 0 || nsec >= 1000000000) {
        var n = nsec / 1000000000;
        sec += n;
        nsec -= n * 1000000000;
        if (nsec < 0) {
            nsec += 1000000000;
            sec--;
        }
    }
    return unixTime(sec, (int32)nsec);
}

// UnixMilli returns the local Time corresponding to the given Unix time,
// msec milliseconds since January 1, 1970 UTC.
public static Time UnixMilli(int64 msec) {
    return Unix(msec / 1000, (msec % 1000) * 1000000);
}

// UnixMicro returns the local Time corresponding to the given Unix time,
// usec microseconds since January 1, 1970 UTC.
public static Time UnixMicro(int64 usec) {
    return Unix(usec / 1000000, (usec % 1000000) * 1000);
}

// IsDST reports whether the time in the configured location is in Daylight Savings Time.
public static bool IsDST(this Time t) {
    var (_, _, _, _, isDST) = t.loc.lookup(t.Unix());
    return isDST;
}

internal static bool isLeap(nint year) {
    // year%4 == 0 && (year%100 != 0 || year%400 == 0)
    // Bottom 2 bits must be clear.
    // For multiples of 25, bottom 4 bits must be clear.
    // Thanks to Cassio Neri for this trick.
    nint mask = 0xf;
    if (year % 25 != 0) {
        mask = 3;
    }
    return (nint)(year & mask) == 0;
}

// norm returns nhi, nlo such that
//
//	hi * base + lo == nhi * base + nlo
//	0 <= nlo < base
internal static (nint nhi, nint nlo) norm(nint hi, nint lo, nint @base) {
    if (lo < 0) {
        nint n = quo((-lo - 1), @base) + 1;
        hi -= n;
        lo += n * @base;
    }
    if (lo >= @base) {
        nint n = quo(lo, @base);
        hi += n;
        lo -= n * @base;
    }
    return (hi, lo);
}

// Date returns the Time corresponding to
//
//	yyyy-mm-dd hh:mm:ss + nsec nanoseconds
//
// in the appropriate zone for that time in the given location.
//
// The month, day, hour, min, sec, and nsec values may be outside
// their usual ranges and will be normalized during the conversion.
// For example, October 32 converts to November 1.
//
// A daylight savings time transition skips or repeats times.
// For example, in the United States, March 13, 2011 2:15am never occurred,
// while November 6, 2011 1:15am occurred twice. In such cases, the
// choice of time zone, and therefore the time, is not well-defined.
// Date returns a time that is correct in one of the two zones involved
// in the transition, but it does not guarantee which.
//
// Date panics if loc is nil.
public static Time Date(nint year, ΔMonth month, nint day, nint hour, nint min, nint sec, nint nsec, ж<ΔLocation> Ꮡloc) {
    if (Ꮡloc == nil) {
        throw panic("time: missing Location in call to Date");
    }
    // Normalize month, overflowing into year.
    nint m = (nint)month - 1;
    (year, m) = norm(year, m, 12);
    month = ((ΔMonth)m) + 1;
    // Normalize nsec, sec, min, hour, overflowing into day.
    (sec, nsec) = norm(sec, nsec, 1000000000);
    (min, sec) = norm(min, sec, 60);
    (hour, min) = norm(hour, min, 60);
    (day, hour) = norm(day, hour, 24);
    // Convert to absolute time and then Unix time.
    var unix = (int64)(uint64)dateToAbsDays((int64)year, month, day) * (int64)secondsPerDay + (int64)(hour * (nint)secondsPerHour + min * (nint)secondsPerMinute + sec) + absoluteToUnix;
    // Look for zone offset for expected time, so we can adjust to UTC.
    // The lookup function expects UTC, so first we pass unix in the
    // hope that it will not be too close to a zone transition,
    // and then adjust if it is.
    var (_, offset, start, end, _) = Ꮡloc.lookup(unix);
    if (offset != 0) {
        var utc = unix - (int64)offset;
        // If utc is valid for the time zone we found, then we have the right offset.
        // If not, we get the correct offset by looking up utc in the location.
        if (utc < start || utc >= end) {
            (_, offset, _, _, _) = Ꮡloc.lookup(utc);
        }
        unix -= (int64)offset;
    }
    var t = unixTime(unix, (int32)nsec);
    t.setLoc(Ꮡloc);
    return t;
}

// Truncate returns the result of rounding t down to a multiple of d (since the zero time).
// If d <= 0, Truncate returns t stripped of any monotonic clock reading but otherwise unchanged.
//
// Truncate operates on the time as an absolute duration since the
// zero time; it does not operate on the presentation form of the
// time. Thus, Truncate(Hour) may return a time with a non-zero
// minute, depending on the time's Location.
public static Time Truncate(this Time t, Duration d) {
    t.stripMono();
    if (d <= 0) {
        return t;
    }
    var (_, r) = div(t, d);
    return t.Add(-r);
}

// Round returns the result of rounding t to the nearest multiple of d (since the zero time).
// The rounding behavior for halfway values is to round up.
// If d <= 0, Round returns t stripped of any monotonic clock reading but otherwise unchanged.
//
// Round operates on the time as an absolute duration since the
// zero time; it does not operate on the presentation form of the
// time. Thus, Round(Hour) may return a time with a non-zero
// minute, depending on the time's Location.
public static Time Round(this Time t, Duration d) {
    t.stripMono();
    if (d <= 0) {
        return t;
    }
    var (_, r) = div(t, d);
    if (lessThanHalf(r, d)) {
        return t.Add(-r);
    }
    return t.Add(d - r);
}

// div divides t by d and returns the quotient parity and remainder.
// We don't use the quotient parity anymore (round half up instead of round to even)
// but it's still here in case we change our minds.
internal static (nint qmod2, Duration r) div(Time t, Duration d) {
    nint qmod2 = default!;
    Duration r = default!;

    var neg = false;
    var nsec = t.nsec();
    var sec = t.sec();
    if (sec < 0) {
        // Operate on absolute value.
        neg = true;
        sec = -sec;
        nsec = -nsec;
        if (nsec < 0) {
            nsec += 1000000000;
            sec--; // sec >= 1 before the -- so safe
        }
    }
    switch (ᐧ) {
    case {} when d < ΔSecond && ΔSecond % (d + d) == 0: {
        qmod2 = (nint)((nint)(quo(nsec, (int32)(int64)d)) & 1);
        r = ((Duration)(int64)(rem(nsec, (int32)(int64)d)));
        break;
    }
    case {} when d % ΔSecond == 0: {
        var d1 = (int64)(d / ΔSecond);
        qmod2 = (nint)((nint)(quo(sec, d1)) & 1);
        r = ((Duration)(rem(sec, d1))) * ΔSecond + ((Duration)(int64)nsec);
        break;
    }
    default: {
        var secΔ2 = (uint64)sec;
        var tmp = ((secΔ2 >> (int)(32))) * 1000000000;
        var u1 = (tmp >> (int)(32));
        var u0 = (tmp << (int)(32));
        tmp = ((uint64)(secΔ2 & 0xFFFFFFFFU)) * 1000000000;
        var u0x = u0;
        u0 = u0 + tmp;
        if (u0 < u0x) {
            // Special case: 2d divides 1 second.
            // Special case: d is a multiple of 1 second.
            // General case.
            // This could be faster if more cleverness were applied,
            // but it's really only here to avoid special case restrictions in the API.
            // No one will care about these cases.
            // Compute nanoseconds as 128-bit number.
            u1++;
        }
        (u0x, u0) = (u0, u0 + (uint64)nsec);
        if (u0 < u0x) {
            u1++;
        }
        var d1 = (uint64)(int64)d;
        while ((d1 >> (int)(63)) != 1) {
            // Compute remainder by subtracting r<<k for decreasing k.
            // Quotient parity is whether we subtract on last round.
            d1 <<= (int)(1);
        }
        var d0 = (uint64)0;
        while (ᐧ) {
            qmod2 = 0;
            if (u1 > d1 || u1 == d1 && u0 >= d0) {
                // subtract
                qmod2 = 1;
                (u0x, u0) = (u0, u0 - d0);
                if (u0 > u0x) {
                    u1--;
                }
                u1 -= d1;
            }
            if (d1 == 0 && d0 == (uint64)(int64)d) {
                break;
            }
            d0 >>= (int)(1);
            d0 |= (uint64)((((uint64)(d1 & 1)) << (int)(63)));
            d1 >>= (int)(1);
        }
        r = ((Duration)(int64)u0);
        break;
    }}

    if (neg && r != 0) {
        // If input was negative and not an exact multiple of d, we computed q, r such that
        //	q*d + r = -t
        // But the right answers are given by -(q-1), d-r:
        //	q*d + r = -t
        //	-q*d - r = t
        //	-(q-1)*d + (d - r) = t
        qmod2 ^= (nint)(1);
        r = d - r;
    }
    return (qmod2, r);
}

// Regrettable Linkname Compatibility
//
// timeAbs, absDate, and absClock mimic old internal details, no longer used.
// Widely used packages linknamed these to get “faster” time routines.
// Notable members of the hall of shame include:
//   - gitee.com/quant1x/gox
//   - github.com/phuslu/log
//
// phuslu hard-coded 'Unix time + 9223372028715321600' [sic]
// as the input to absDate and absClock, using the old Jan 1-based
// absolute times.
// quant1x linknamed the time.Time.abs method and passed the
// result of that method to absDate and absClock.
//
// Keeping both of these working forces us to provide these three
// routines here, operating on the old Jan 1-based epoch instead
// of the new March 1-based epoch. And the fact that time.Time.abs
// was linknamed means that we have to call the current abs method
// something different (time.Time.absSec, defined above) to make it
// possible to provide this simulation of the old routines here.
//
// None of this code is linked into the binary if not referenced by
// these linkname-happy packages. In particular, despite its name,
// time.Time.abs does not appear in the time.Time method table.
//
// Do not remove these routines or their linknames, or change the
// type signature or meaning of arguments.

//go:linkname legacyTimeTimeAbs time.Time.abs
public static uint64 legacyTimeTimeAbs(Time t) {
    return (uint64)(t.absSec() - (uint64)(marchThruDecember * secondsPerDay));
}

//go:linkname legacyAbsClock time.absClock
public static (nint hour, nint min, nint sec) legacyAbsClock(uint64 abs) {
    return ((absSeconds)(abs + (uint64)(marchThruDecember * secondsPerDay))).clock();
}

//go:linkname legacyAbsDate time.absDate
public static (nint year, ΔMonth month, nint day, nint yday) legacyAbsDate(uint64 abs, bool full) {
    nint year = default!;
    ΔMonth month = default!;
    nint day = default!;
    nint yday = default!;

    var d = ((absSeconds)(abs + (uint64)(marchThruDecember * secondsPerDay))).days();
    (year, month, day) = d.date();
    (_, yday) = d.yearYday();
    yday--; // yearYday is 1-based, old API was 0-based
    return (year, month, day, yday);
}

} // end time_package
