// corpusRelease_test.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

package repoguard

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go2cs/internal/releasestamp"
)

// src/go2cs/corpus-release.txt is the converter's own record of the go2cs corpus release it belongs to: the
// -recurse=nuget third-party gate maps a published conversion only when the package's self-description names
// that release (docs/PLAN-nugetgo.md 4.6, the strict default). It is generated by internal/gencorpusrelease
// from releasestamp.PublishedStamp -- the LAST PUBLISHED release by the tree's own write-once snapshots, never
// version.props's arithmetic, which names a release from the moment push-nuget bumps it (before anything is
// packed, let alone published) and, across a hop, for the whole window before the new base's first publish.
//
// So this guard is red exactly when the record moved and the file did not: a release recorded without
// regenerating it, or a hand edit. The release flow that regenerates it at the record (release-nuget.ps1
// Phase 4) is held for the owner's word (COORD, 2026-10-02); until it lands, this guard is what catches a
// record commit that forgot the file.
func TestCorpusReleaseMatchesThePublishedStamp(t *testing.T) {
	root := repoRootFromPackageDir(t)
	props, err := os.ReadFile(filepath.Join(root, "src", "version.props"))

	if err != nil {
		t.Fatal(err)
	}

	published := releasestamp.PublishedStamp(string(props), releasestamp.SnapshotsDir(root))

	// ANTI-VACUITY: this repository has published releases, so an empty answer is a broken reader, and two
	// empty strings would otherwise agree.
	if published == "" {
		t.Fatalf("VACUOUS: no published stamp resolves from %s and %s", filepath.Join(root, "src", "version.props"), releasestamp.SnapshotsDir(root))
	}

	recordPath := filepath.Join(root, "src", "go2cs", "corpus-release.txt")
	record, err := os.ReadFile(recordPath)

	if err != nil {
		t.Fatalf("%s is missing: %v", recordPath, err)
	}

	if got := strings.TrimSpace(string(record)); got != published {
		t.Fatalf("%s names %q, but the last published release is %q (releasestamp.PublishedStamp). Regenerate it "+
			"with `go generate .` in src/go2cs and commit it with the release record.", recordPath, got, published)
	}
}

// The guard's own comparison, on a fabricated tree, in the two directions that matter: a release RECORDED
// (its snapshot written) moves the published stamp, so a file left behind fails; a counter BUMPED but not yet
// recorded (push-nuget Phase 1, or a release that died before its record) does not move it.
func TestCorpusReleaseFollowsTheRecordNotTheBump(t *testing.T) {
	snapshots := t.TempDir()

	for _, stamp := range []string{"1.24.13.2", "1.24.13.3"} {
		if err := os.MkdirAll(filepath.Join(snapshots, stamp), 0o755); err != nil {
			t.Fatal(err)
		}
	}

	props := func(build string) string {
		return "<GoStdLibVersion>1.24.13</GoStdLibVersion>\n<GoBuildNumber>" + build + "</GoBuildNumber>\n"
	}

	if got := releasestamp.PublishedStamp(props("4"), snapshots); got != "1.24.13.3" {
		t.Errorf("a bumped but unrecorded counter moved the published stamp to %q; want 1.24.13.3", got)
	}

	if err := os.MkdirAll(filepath.Join(snapshots, "1.24.13.4"), 0o755); err != nil {
		t.Fatal(err)
	}

	if got := releasestamp.PublishedStamp(props("4"), snapshots); got != "1.24.13.4" {
		t.Errorf("a recorded release did not move the published stamp: %q; want 1.24.13.4", got)
	}
}
