// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal.fips140test;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/fips140test", new string[]
        {
            "acvp_test.go",
            "alias_test.go",
            "cast_test.go",
            "check_test.go",
            "cmac_test.go",
            "ctrdrbg_test.go",
            "edwards25519_test.go",
            "fips_test.go",
            "indicator_test.go",
            "nistec_ordinv_test.go",
            "nistec_test.go",
            "sshkdf_test.go",
            "xaes_test.go",
        });
        registry.Add("TestACVP", fipstest_internal_test_package.TestACVP, "acvp_test.go", 588);
        registry.Add("TestAliasing", fipstest_internal_test_package.TestAliasing, "alias_test.go", 44);
        registry.Add("TestAllCASTs", fipstest_internal_test_package.TestAllCASTs, "cast_test.go", 64);
        registry.Add("TestCASTFailures", fipstest_internal_test_package.TestCASTFailures, "cast_test.go", 160);
        registry.Add("TestCASTPasses", fipstest_internal_test_package.TestCASTPasses, "cast_test.go", 135);
        registry.Add("TestCMAC", fipstest_internal_test_package.TestCMAC, "cmac_test.go", 14);
        registry.Add("TestConditionals", fipstest_internal_test_package.TestConditionals, "cast_test.go", 106);
        registry.Add("TestCounterDRBG", fipstest_internal_test_package.TestCounterDRBG, "ctrdrbg_test.go", 14);
        registry.Add("TestEdwards25519Allocations", fipstest_internal_test_package.TestEdwards25519Allocations, "edwards25519_test.go", 15);
        registry.Add("TestEquivalents", fipstest_internal_test_package.TestEquivalents, "nistec_test.go", 108);
        registry.Add("TestFIPSCheckInfo", fipstest_internal_test_package.TestFIPSCheckInfo, "check_test.go", 50);
        registry.Add("TestFIPSCheckVerify", fipstest_internal_test_package.TestFIPSCheckVerify, "check_test.go", 23);
        registry.Add("TestGetConfig", fipstest_internal_test_package.TestGetConfig, "acvp_test.go", 704);
        registry.Add("TestIndicator", fipstest_internal_test_package.TestIndicator, "indicator_test.go", 12);
        registry.Add("TestNISTECAllocations", fipstest_internal_test_package.TestNISTECAllocations, "nistec_test.go", 18);
        registry.Add("TestSSHACVPVector", fipstest_internal_test_package.TestSSHACVPVector, "sshkdf_test.go", 15);
        registry.Add("TestScalarMult", fipstest_internal_test_package.TestScalarMult, "nistec_test.go", 160);
        registry.Add("TestSha2256", fipstest_internal_test_package.TestSha2256, "acvp_test.go", 721);
        registry.Add("TestTooFewArgs", fipstest_internal_test_package.TestTooFewArgs, "acvp_test.go", 659);
        registry.Add("TestTooManyArgs", fipstest_internal_test_package.TestTooManyArgs, "acvp_test.go", 681);
        registry.Add("TestXAES", fipstest_internal_test_package.TestXAES, "xaes_test.go", 39);
        registry.Add("TestXAESAccumulated", fipstest_internal_test_package.TestXAESAccumulated, "xaes_test.go", 117);
        registry.Add("TestXAESAllocations", fipstest_internal_test_package.TestXAESAllocations, "xaes_test.go", 19);
        registry.Add("TestXAESVectors", fipstest_internal_test_package.TestXAESVectors, "xaes_test.go", 88);
        registry.SetTestMain(fipstest_internal_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
