// generate.go - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: AGPL-3.0-only
// Use of this source code is governed by the GNU Affero General Public License
// version 3 only, which can be found in the LICENSE file.
// Additional permission for emitted output: see LICENSE-EXCEPTION (AGPL section 7).

// Package stdlibmeta builds the converter's embedded record of the exported cross-package
// metadata published by each converted standard-library package's package_info.cs.
//
// It is shared by the genstdlibmeta generator and by the converter's in-process sync test,
// so the committed asset can never drift from src/core without a test failure.
package stdlibmeta

import (
	"bufio"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// AssetFileName is the generated asset the converter embeds, relative to src/go2cs.
const AssetFileName = "stdlib-metadata.txt"

// PackageInfoFileName duplicates the converter's symbols.go constant of the same name. The
// converter is `package main`, so its constants are not importable from here; the value is
// fixed by the emitted file's name and is asserted against the converter's constant by
// TestStdLibMetadataAssetFileName.
const PackageInfoFileName = "package_info.cs"

// ReferenceGOOS is the platform flavor a package's UNQUALIFIED section describes.
//
// Layout L3 (docs/phase4/DESIGN-multiplatform-corpus.md §8) moves a package's platform-VARYING
// artifacts into per-GOOS subfolders, and `package_info.cs` is one of them. The record is taken from
// the flat copy where one exists (flat wins, exactly as the converter's platformPackageInfoPath reads
// it), and otherwise from this GOOS's copy into the unqualified `##<name>` section: the flavor shipped
// as the package's `lib/{tfm}` asset (design §9(a)) and the one `$(GoTargetOS)` defaults to.
//
// Every OTHER flavor of such a package is recorded too, as `##<name>@<goos>` (FlavorSeparator).
// Until 2026-09-24 it was dropped, on the premise that a -recurse=nuget consumer could only ever see
// the `lib/` compile surface; go.lib's RID-selected compile asset (buildTransitive/go.lib.targets)
// makes a Linux consumer compile against the linux flavor, and a Linux conversion that still read the
// windows record emitted `syscallꓸHandle = go.syscall_package.ΔHandle` (CS0426) and a Δ-renamed
// `Sockaddr` the linux flavor does not have (CS0305). The converter now reads the section of the GOOS
// it is converting for, and falls back to the unqualified one.
//
// It duplicates the converter's platformDefaultTargetOS for the same reason PackageInfoFileName
// duplicates its constant (this package cannot import `package main`), and is asserted against it by
// TestStdLibMetadataAssetFileName.
const ReferenceGOOS = "windows"

// FlavorSeparator joins a package's dotted name to the GOOS of a non-reference flavor in a section
// header (`##syscall@linux`). `@` cannot occur in a dotted package name.
const FlavorSeparator = "@"

// SectionPrefix introduces a package section; the remainder of the line is the package's
// dotted name (`math.rand.v2`), matching PackageInfo.PackageName and the `go.<name>` NuGet
// package id. A single '#' introduces a file-level comment line.
const SectionPrefix = "##"

const aliasSectionStart = "// <ExportedTypeAliases>"
const aliasSectionEnd = "// </ExportedTypeAliases>"
const implementPrefix = "[assembly: GoImplement<"

// refPrimaryPrefix is the cross-package lowering contract's record (refVerdictPublication.go in
// the converter, which keys its own reader on the same spelling): the third record family a
// consumer reads back from a dependency, carried here so a NuGet-referenced package publishes its
// `ref`-receiver primaries exactly as an on-disk package_info.cs does.
const refPrimaryPrefix = "[assembly: GoRefPrimary("

var header = []string{
	"# Code generated by genstdlibmeta from ../core/**/" + PackageInfoFileName + "; DO NOT EDIT.",
	"#",
	"# The converter normally learns a referenced package's exported type aliases and",
	"# interface-implementation records by reading that package's " + PackageInfoFileName + " out of",
	"# the converted-source tree on disk. Under -recurse=nuget there is no such tree -- the",
	"# standard library arrives as pre-compiled go.<pkg> NuGet packages -- so the same facts",
	"# are carried here instead, captured from src/core (the tree push-nuget.ps1",
	"# packs), which makes the embedded record and the published assemblies one commit's output.",
	"#",
	"# Format: '##<dotted package name>' opens a section; its lines are the matching",
	"# " + PackageInfoFileName + " lines verbatim, so the converter's existing parsers read them unchanged.",
	"# A package whose metadata varies by platform (no flat " + PackageInfoFileName + ") keeps its",
	"# " + ReferenceGOOS + " flavor in the unqualified section and every other flavor in its own",
	"# '##<dotted package name>" + FlavorSeparator + "<goos>' section; a conversion for <goos> reads that section and",
	"# falls back to the unqualified one. Counts are of SECTIONS, not packages.",
	"#",
	"# Regenerate with `go generate .` from src/go2cs; never hand-edit.",
}

// Generate walks convertedRoot for package_info.cs files and returns the asset content, the
// number of sections written (a package with per-GOOS flavors writes one per flavor), and any
// error. Output is deterministic: sections are sorted by name and each carries its matched lines
// verbatim in file order.
func Generate(convertedRoot string) ([]byte, int, error) {
	sections, err := Collect(convertedRoot)

	if err != nil {
		return nil, 0, err
	}

	if len(sections) == 0 {
		return nil, 0, fmt.Errorf("no %s files found under %q -- is the converted standard library present?", PackageInfoFileName, convertedRoot)
	}

	names := make([]string, 0, len(sections))

	for name := range sections {
		names = append(names, name)
	}

	sort.Strings(names)

	var builder strings.Builder

	for _, line := range header {
		builder.WriteString(line)
		builder.WriteString("\n")
	}

	for _, name := range names {
		builder.WriteString("\n")
		builder.WriteString(SectionPrefix)
		builder.WriteString(name)
		builder.WriteString("\n")

		for _, line := range sections[name] {
			builder.WriteString(line)
			builder.WriteString("\n")
		}
	}

	return []byte(builder.String()), len(names), nil
}

// Collect returns, per dotted package name, the package_info.cs lines that carry exported
// cross-package metadata: the <ExportedTypeAliases> section (markers included, so an empty
// section still parses as "no aliases" rather than "unknown") and every GoImplement record.
// Layout L3 (docs/phase4/DESIGN-multiplatform-corpus.md §8) can put a package's package_info.cs in a
// per-GOOS subfolder instead of flat, so the walk is TWO passes: pass one records where every
// package_info.cs and every .csproj live, pass two decides which copy each package is described by.
//
// The per-GOOS folder is told from a nested package by the project file — a converted package
// directory always holds one, a source folder never does. That is the converter's own discriminator
// (isPlatformSourceFolder), and it is what keeps `internal/syscall/windows`, a real package whose
// name IS a GOOS, from being folded into `internal/syscall`.
func Collect(convertedRoot string) (map[string][]string, error) {
	infoDirs := map[string]string{} // package-info dir (rel, forward slashes) -> absolute file path
	packageDirs := map[string]bool{}

	err := filepath.WalkDir(convertedRoot, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if entry.IsDir() {
			switch entry.Name() {
			case "bin", "obj", "Generated", ".vs", ".git":
				return fs.SkipDir
			}

			return nil
		}

		relDir, relErr := filepath.Rel(convertedRoot, filepath.Dir(filePath))

		if relErr != nil {
			return relErr
		}

		relDir = filepath.ToSlash(relDir)

		switch {
		case entry.Name() == PackageInfoFileName:
			infoDirs[relDir] = filePath
		case strings.EqualFold(filepath.Ext(entry.Name()), ".csproj"):
			packageDirs[relDir] = true
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	sections := map[string][]string{}

	// Packages whose record came from a FLAT copy. Sorted order visits `syscall` before
	// `syscall/linux`, so a flat copy is always seen before any per-GOOS one of the same package.
	flat := map[string]bool{}

	for _, relDir := range sortedKeys(infoDirs) {
		packageDir := relDir
		flavor := ""

		if !packageDirs[relDir] && packageDirs[path.Dir(relDir)] {
			// A per-GOOS copy: the reference flavor keys the unqualified section, every other
			// flavor its own `<name>@<goos>` section (see ReferenceGOOS).
			packageDir = path.Dir(relDir)

			if goos := path.Base(relDir); goos != ReferenceGOOS {
				flavor = goos
			}
		}

		name := strings.ReplaceAll(packageDir, "/", ".")

		// A flat copy is authoritative for every flavor; a per-GOOS one only describes a package
		// that has none, which is exactly when the converter reads the per-GOOS copy.
		if packageDir != relDir && flat[name] {
			continue
		}

		if packageDir == relDir {
			flat[name] = true
		}

		if flavor != "" {
			name += FlavorSeparator + flavor
		}

		lines, readErr := extract(infoDirs[relDir])

		if readErr != nil {
			return nil, readErr
		}

		sections[name] = lines
	}

	return sections, nil
}

// sortedKeys returns a map's keys in sorted order, so the two-pass collection above is
// order-independent regardless of the filesystem walk.
func sortedKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))

	for key := range values {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	return keys
}

// extract pulls the metadata-bearing lines out of one package_info.cs, preserving their
// original spelling so the converter's regex parsers can consume them unchanged.
func extract(packageInfoFile string) ([]string, error) {
	file, err := os.Open(packageInfoFile)

	if err != nil {
		return nil, err
	}

	defer file.Close()

	var lines []string
	inAliasSection := false

	scanner := bufio.NewScanner(file)

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case trimmed == aliasSectionStart:
			inAliasSection = true
			lines = append(lines, trimmed)
		case trimmed == aliasSectionEnd:
			inAliasSection = false
			lines = append(lines, trimmed)
		case inAliasSection && strings.HasPrefix(trimmed, "[assembly: GoTypeAlias("):
			lines = append(lines, trimmed)
		case strings.HasPrefix(trimmed, implementPrefix):
			lines = append(lines, trimmed)
		case strings.HasPrefix(trimmed, refPrimaryPrefix):
			lines = append(lines, trimmed)
		}
	}

	return lines, scanner.Err()
}

// ExtractForTest exposes extract to the converter's own test suite, which asserts that record
// families sharing package_info.cs with the two this generator reads (today: GoSourcePositionMaps)
// are not scooped into the metadata.
func ExtractForTest(packageInfoFile string) ([]string, error) {
	return extract(packageInfoFile)
}
