using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using go;
using static go.runtime_package;

namespace GolibTests;

/// <summary>
/// Guards the frames of a method-expression WRAPPER (runtime/managed_impl.cs). Go's
/// TestCallersFromWrapper reads <c>CallersFrames([]uintptr{reflect.ValueOf(I.M).Pointer()})</c> and wants
/// <c>runtime_test.I.M</c>: a reflect func token must resolve in Frames.Next exactly as it does in
/// FuncForPC, and the converter's lambda must answer the wrapper's Go name. A live walk elides the
/// wrapper, as Go's does when the wrapper called an ordinary function. Red while Frames.Next knows only
/// caller spans and synthetic PCs.
/// </summary>
[TestClass]
public class MethodWrapperFrameTests
{
    [TestMethod]
    public void AReflectFuncTokenResolvesInCallersFramesAsInFuncForPC()
    {
        uintptr pc = reflect_package.ValueOf((System.Action)wrapperprobe_package.plain).Pointer();

        var (frame, more) = CallersFrames(new uintptr[] { pc }.slice()).Next();

        Assert.AreEqual("wrapperprobe.plain", (string)FuncForPC(pc).Name(), "FuncForPC's answer, the control");
        Assert.AreEqual("wrapperprobe.plain", (string)frame.Function, "Frames.Next must resolve the same token");
        Assert.IsFalse(more);
    }

    [TestMethod]
    public void AWrapperTokenNamesTheMethodExpression()
    {
        uintptr pc = reflect_package.ValueOf(wrapperprobe_package.interfaceWrapper).Pointer();

        var (frame, more) = CallersFrames(new uintptr[] { pc }.slice()).Next();

        Assert.AreEqual("wrapperprobe.I.M", (string)frame.Function);
        Assert.AreEqual("<autogenerated>", (string)frame.File);
        Assert.AreEqual(1L, (long)frame.Line);
        Assert.IsFalse(more);
        Assert.AreEqual("wrapperprobe.I.M", (string)FuncForPC(pc).Name());
    }

    [TestMethod]
    public void ALiveWalkElidesTheWrapper()
    {
        slice<uintptr> pcs = wrapperprobe_package.interfaceWrapper(new wrapperprobe_package.impl());

        List<string> functions = [];
        var frames = CallersFrames(pcs);

        while (true)
        {
            var (frame, more) = frames.Next();
            functions.Add($"{(string)frame.Function} {(string)frame.File}");

            if (!more)
                break;
        }

        string all = string.Join(" | ", functions);

        // Callers, callersHere, impl's M, and nothing below: the wrapper lambda is elided, and the
        // test host's thread is no goroutine, so no root follows.
        Assert.AreEqual(3, functions.Count, all);
        Assert.IsTrue(functions[1].StartsWith("wrapperprobe.callersHere "), all);
        // The wrapper's callee is the next frame: impl's M, whatever the host names it.
        Assert.IsTrue(functions[2].StartsWith("wrapperprobe.") && functions[2].Contains("M "), all);
        Assert.IsFalse(all.Contains("I.M"), all);
        Assert.IsFalse(all.Contains("<autogenerated>"), all);
    }

    // runtime.Stack's text follows the same rule: a wrapper that called a Go function is elided, and
    // only a wrapper that is itself the first Go frame (it faulted) prints.
    [TestMethod]
    public void StackTextElidesAWrapperThatCalledGo()
    {
        string text = wrapperprobe_package.stackWrapper(new wrapperprobe_package.stackImpl());

        StringAssert.Contains(text, "wrapperprobe.");
        Assert.IsFalse(text.Contains("IStack.S"), text);
    }
}
