// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.runtime.@internal.wasitest;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("runtime/internal/wasitest", new string[]
        {
            "host_test.go",
            "nonblock_test.go",
            "tcpecho_test.go",
        }, new string[]
        {
            "testdata",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestTCPEcho", wasi_test_package.TestTCPEcho, "tcpecho_test.go", 18);
        return TestHost.Run(registry, args);
    }
}
