// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package rsa implements RSA encryption as specified in PKCS #1 and RFC 8017.
//
// RSA is a single, fundamental operation that is used in this package to
// implement either public-key encryption or public-key signatures.
//
// The original specification for encryption and signatures with RSA is PKCS #1
// and the terms "RSA encryption" and "RSA signatures" by default refer to
// PKCS #1 version 1.5. However, that specification has flaws and new designs
// should use version 2, usually called by just OAEP and PSS, where
// possible.
//
// Two sets of interfaces are included in this package. When a more abstract
// interface isn't necessary, there are functions for encrypting/decrypting
// with v1.5/OAEP and signing/verifying with v1.5/PSS. If one needs to abstract
// over the public key primitive, the PrivateKey type implements the
// Decrypter and Signer interfaces from the crypto package.
//
// Operations involving private keys are implemented using constant-time
// algorithms, except for [GenerateKey] and for some operations involving
// deprecated multi-prime keys.
//
// # Minimum key size
//
// [GenerateKey] returns an error if a key of less than 1024 bits is requested,
// and all Sign, Verify, Encrypt, and Decrypt methods return an error if used
// with a key smaller than 1024 bits. Such keys are insecure and should not be
// used.
//
// The `rsa1024min=0` GODEBUG setting suppresses this error, but we recommend
// doing so only in tests, if necessary. Tests can use [testing.T.Setenv] or
// include `//go:debug rsa1024min=0` in a `_test.go` source file to set it.
//
// Alternatively, see the [GenerateKey (TestKey)] example for a pregenerated
// test-only 2048-bit key.
//
// [GenerateKey (TestKey)]: #example-GenerateKey-TestKey
namespace go.crypto;

using crypto = crypto_package;
using boring = go.crypto.@internal.boring_package;
using bbig = go.crypto.@internal.boring.bbig_package;
using bigmod = go.crypto.@internal.fips140.bigmod_package;
using rsa = go.crypto.@internal.fips140.rsa_package;
using fips140only = go.crypto.@internal.fips140only_package;
using randutil = go.crypto.@internal.randutil_package;
using rand = go.crypto.rand_package;
using subtle = go.crypto.subtle_package;
using errors = errors_package;
using fmt = fmt_package;
using godebug = go.@internal.godebug_package;
using io = io_package;
using math = math_package;
using big = go.math.big_package;
using go.@internal;
using go.crypto;
using go.crypto.@internal;
using go.crypto.@internal.boring;
using go.crypto.@internal.fips140;
using go.math;
using hash = hash_package;

partial class rsa_package {

internal static ж<bigꓸInt> bigOne = big.NewInt(1);

// A PublicKey represents the public part of an RSA key.
//
// The value of the modulus N is considered secret by this library and protected
// from leaking through timing side-channels. However, neither the value of the
// exponent E nor the precise bit size of N are similarly protected.
[GoType] partial struct PublicKey {
    public ж<bigꓸInt> N; // modulus
    public nint E;     // public exponent
}

// Any methods implemented on PublicKey might need to also be implemented on
// PrivateKey, as the latter embeds the former and will expose its methods.

// Size returns the modulus size in bytes. Raw signatures and ciphertexts
// for or by this public key will have the same size.
[GoRecv] public static nint Size(this ref PublicKey pub) {
    return (pub.N.BitLen() + 7) / 8;
}

// Equal reports whether pub and x have the same value.
[GoRecv] public static bool Equal(this ref PublicKey pub, cryptoꓸPublicKey x) {
    var (xx, ok) = x._<ж<PublicKey>>(ᐧ);
    if (!ok) {
        return false;
    }
    return bigIntEqual(pub.N, (~xx).N) && pub.E == (~xx).E;
}

// OAEPOptions is an interface for passing options to OAEP decryption using the
// crypto.Decrypter interface.
[GoType] partial struct OAEPOptions {
    // Hash is the hash function that will be used when generating the mask.
    public crypto.Hash Hash;
    // MGFHash is the hash function used for MGF1.
    // If zero, Hash is used instead.
    public crypto.Hash MGFHash;
    // Label is an arbitrary byte string that must be equal to the value
    // used when encrypting.
    public slice<byte> Label;
}

// A PrivateKey represents an RSA key
[GoType] partial struct PrivateKey {
    public partial ref PublicKey PublicKey { get; }            // public part.
    public ж<bigꓸInt> D; // private exponent
    public slice<ж<bigꓸInt>> Primes; // prime factors of N, has >= 2 elements.
    // Precomputed contains precomputed values that speed up RSA operations,
    // if available. It must be generated by calling PrivateKey.Precompute and
    // must not be modified.
    public PrecomputedValues Precomputed;
}

// Public returns the public key corresponding to priv.
public static cryptoꓸPublicKey Public(this ж<PrivateKey> Ꮡpriv) {
    return Ꮡpriv.of(PrivateKey.ᏑPublicKey);
}

// Equal reports whether priv and x have equivalent values. It ignores
// Precomputed values.
[GoRecv] public static bool Equal(this ref PrivateKey priv, cryptoꓸPrivateKey x) {
    var (xx, ok) = x._<ж<PrivateKey>>(ᐧ);
    if (!ok) {
        return false;
    }
    if (!priv.PublicKey.Equal(xx.of(PrivateKey.ᏑPublicKey)) || !bigIntEqual(priv.D, (~xx).D)) {
        return false;
    }
    if (len(priv.Primes) != len((~xx).Primes)) {
        return false;
    }
    foreach (var (i, _) in priv.Primes) {
        if (!bigIntEqual(priv.Primes[i], (~xx).Primes[i])) {
            return false;
        }
    }
    return true;
}

// bigIntEqual reports whether a and b are equal leaking only their bit length
// through timing side-channels.
internal static bool bigIntEqual(ж<bigꓸInt> Ꮡa, ж<bigꓸInt> Ꮡb) {
    ref var a = ref Ꮡa.DerefOrNull();
    ref var b = ref Ꮡb.DerefOrNull();

    return subtle.ConstantTimeCompare(a.Bytes(), b.Bytes()) == 1;
}

// Sign signs digest with priv, reading randomness from rand. If opts is a
// *[PSSOptions] then the PSS algorithm will be used, otherwise PKCS #1 v1.5 will
// be used. digest must be the result of hashing the input message using
// opts.HashFunc().
//
// This method implements [crypto.Signer], which is an interface to support keys
// where the private part is kept in, for example, a hardware module. Common
// uses should use the Sign* functions in this package directly.
public static (slice<byte>, error) Sign(this ж<PrivateKey> Ꮡpriv, io.Reader rand, slice<byte> digest, crypto.SignerOpts opts) {
    {
        var (pssOpts, ok) = opts._<ж<PSSOptions>>(ᐧ); if (ok) {
            return SignPSS(rand, Ꮡpriv, (~pssOpts).Hash, digest, pssOpts);
        }
    }
    return SignPKCS1v15(rand, Ꮡpriv, opts.HashFunc(), digest);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaInvalidOptionsˢ = "crypto/rsa: invalid options for Decrypt"u8;

// Decrypt decrypts ciphertext with priv. If opts is nil or of type
// *[PKCS1v15DecryptOptions] then PKCS #1 v1.5 decryption is performed. Otherwise
// opts must have type *[OAEPOptions] and OAEP decryption is done.
public static (slice<byte> plaintext, error err) Decrypt(this ж<PrivateKey> Ꮡpriv, io.Reader rand, slice<byte> ciphertext, cryptoꓸDecrypterOpts opts) {
    slice<byte> plaintext = default!;

    if (opts == default!) {
        return DecryptPKCS1v15(rand, Ꮡpriv, ciphertext);
    }
    switch (opts.type()) {
    case ж<OAEPOptions> optsΔ1: {
        if ((~optsΔ1).MGFHash == 0){
            return decryptOAEP((~optsΔ1).Hash.New(), (~optsΔ1).Hash.New(), Ꮡpriv, ciphertext, (~optsΔ1).Label);
        } else {
            return decryptOAEP((~optsΔ1).Hash.New(), (~optsΔ1).MGFHash.New(), Ꮡpriv, ciphertext, (~optsΔ1).Label);
        }
        break;
    }
    case ж<PKCS1v15DecryptOptions> optsΔ1: {
        {
            nint l = optsΔ1.Value.SessionKeyLen; if (l > 0){
                plaintext = new slice<byte>(l);
                {
                    var (_, errΔ1) = io.ReadFull(rand, plaintext); if (errΔ1 != default!) {
                        return (default!, errΔ1);
                    }
                }
                {
                    var errΔ2 = DecryptPKCS1v15SessionKey(rand, Ꮡpriv, ciphertext, plaintext); if (errΔ2 != default!) {
                        return (default!, errΔ2);
                    }
                }
                return (plaintext, default!);
            } else {
                return DecryptPKCS1v15(rand, Ꮡpriv, ciphertext);
            }
        }
        break;
    }
    default: {
        var optsΔ1 = opts;
        return (default!, errors.New(cryptoRsaInvalidOptionsˢ));
    }}
}

[GoType] partial struct PrecomputedValues {
    public ж<bigꓸInt> Dp, Dq; // D mod (P-1) (or mod Q-1)
    public ж<bigꓸInt> Qinv; // Q^-1 mod P
    // CRTValues is used for the 3rd and subsequent primes. Due to a
    // historical accident, the CRT for the first two primes is handled
    // differently in PKCS #1 and interoperability is sufficiently
    // important that we mirror this.
    //
    // Deprecated: These values are still filled in by Precompute for
    // backwards compatibility but are not used. Multi-prime RSA is very rare,
    // and is implemented by this package without CRT optimizations to limit
    // complexity.
    public slice<CRTValue> CRTValues;
    internal ж<rsa.PrivateKey> fips;
}

// CRTValue contains the precomputed Chinese remainder theorem values.
[GoType] partial struct CRTValue {
    public ж<bigꓸInt> Exp; // D mod (prime-1).
    public ж<bigꓸInt> Coeff; // R·Coeff ≡ 1 mod Prime.
    public ж<bigꓸInt> R; // product of primes prior to this (inc p and q).
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaMissingPrimesˢ = "crypto/rsa: missing primes"u8;

// Validate performs basic sanity checks on the key.
// It returns nil if the key is valid, or else an error describing a problem.
//
// It runs faster on valid keys if run after [Precompute].
[GoRecv] public static error Validate(this ref PrivateKey priv) {
    // We can operate on keys based on d alone, but it isn't possible to encode
    // with [crypto/x509.MarshalPKCS1PrivateKey], which unfortunately doesn't
    // return an error.
    if (len(priv.Primes) < 2) {
        return errors.New(cryptoRsaMissingPrimesˢ);
    }
    // If Precomputed.fips is set, then the key has been validated by
    // [rsa.NewPrivateKey] or [rsa.NewPrivateKeyWithoutCRT].
    if (priv.Precomputed.fips != nil) {
        return default!;
    }
    var (_, err) = priv.precompute();
    return err;
}

// rsa1024min is a GODEBUG that re-enables weak RSA keys if set to "0".
// See https://go.dev/issue/68762.
internal static ж<godebug.Setting> rsa1024min = godebug.New("rsa1024min"u8);

internal static error checkKeySize(nint size) {
    if (size >= 1024) {
        return default!;
    }
    if (rsa1024min.Value() == "0"u8) {
        rsa1024min.IncNonDefault();
        return default!;
    }
    return fmt.Errorf("crypto/rsa: %d-bit keys are insecure (see https://go.dev/pkg/crypto/rsa#hdr-Minimum_key_size)"u8, size);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaMissingPublicˢ = "crypto/rsa: missing public modulus"u8;

internal static error checkPublicKeySize(ref PublicKey k) {
    if (k.N == nil) {
        return errors.New(cryptoRsaMissingPublicˢ);
    }
    return checkKeySize(k.N.BitLen());
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaGeneratedKeyˢ = "crypto/rsa: generated key exponent too large"u8;

// GenerateKey generates a random RSA private key of the given bit size.
//
// If bits is less than 1024, [GenerateKey] returns an error. See the "[Minimum
// key size]" section for further details.
//
// Most applications should use [crypto/rand.Reader] as rand. Note that the
// returned key does not depend deterministically on the bytes read from rand,
// and may change between calls and/or between versions.
//
// [Minimum key size]: #hdr-Minimum_key_size
public static (ж<PrivateKey>, error) GenerateKey(io.Reader random, nint bits) {
    {
        var errΔ1 = checkKeySize(bits); if (errΔ1 != default!) {
            return (default!, errΔ1);
        }
    }
    if (boring.Enabled && AreEqual(random, boring.RandReader) && (bits == 2048 || bits == 3072 || bits == 4096)) {
        var (bN, bE, bD, bP, bQ, bDp, bDq, bQinv, errΔ2) = boring.GenerateKeyRSA(bits);
        if (errΔ2 != default!) {
            return (default!, errΔ2);
        }
        var NΔ1 = bbig.Dec(bN);
        var E = bbig.Dec(bE);
        var D = bbig.Dec(bD);
        var P = bbig.Dec(bP);
        var Q = bbig.Dec(bQ);
        var Dp = bbig.Dec(bDp);
        var Dq = bbig.Dec(bDq);
        var Qinv = bbig.Dec(bQinv);
        var e64 = E.Int64();
        if (!E.IsInt64() || (int64)(nint)e64 != e64) {
            return (default!, errors.New(cryptoRsaGeneratedKeyˢ));
        }
        var keyΔ1 = Ꮡ(new PrivateKey(
            PublicKey: new PublicKey(
                N: NΔ1,
                E: (nint)e64
            ),
            D: D,
            Primes: new ж<bigꓸInt>[]{P, Q}.slice(),
            Precomputed: new PrecomputedValues(
                Dp: Dp,
                Dq: Dq,
                Qinv: Qinv,
                CRTValues: new slice<CRTValue>(0)
            )
        ));
        // non-nil, to match Precompute
        return (keyΔ1, default!);
    }
    if (fips140only.Enabled && bits < 2048) {
        return (default!, errors.New(cryptoRsaUseOfKeysˢ));
    }
    if (fips140only.Enabled && bits % 2 == 1) {
        return (default!, errors.New(cryptoRsaUseOfKeysWithˢ));
    }
    if (fips140only.Enabled && !fips140only.ApprovedRandomReader(random)) {
        return (default!, errors.New(cryptoRsaOnlyCryptoRandˢ));
    }
    var (k, err) = rsa.GenerateKey(random, bits);
    if (bits < 256 && err != default!) {
        // Toy-sized keys have a non-negligible chance of hitting two hard
        // failure cases: p == q and d <= 2^(nlen / 2).
        //
        // Since these are impossible to hit for real keys, we don't want to
        // make the production code path more complex and harder to think about
        // to handle them.
        //
        // Instead, just rerun the whole process a total of 8 times, which
        // brings the chance of failure for 32-bit keys down to the same as for
        // 256-bit keys.
        for (nint i = 1; i < 8 && err != default!; i++) {
            (k, err) = rsa.GenerateKey(random, bits);
        }
    }
    if (err != default!) {
        return (default!, err);
    }
    var (N, e, d, p, q, dP, dQ, qInv) = k.Export();
    var key = Ꮡ(new PrivateKey(
        PublicKey: new PublicKey(
            N: @new<bigꓸInt>().SetBytes(N),
            E: e
        ),
        D: @new<bigꓸInt>().SetBytes(d),
        Primes: new ж<bigꓸInt>[]{
            @new<bigꓸInt>().SetBytes(p),
            @new<bigꓸInt>().SetBytes(q)
        }.slice(),
        Precomputed: new PrecomputedValues(
            fips: k,
            Dp: @new<bigꓸInt>().SetBytes(dP),
            Dq: @new<bigꓸInt>().SetBytes(dQ),
            Qinv: @new<bigꓸInt>().SetBytes(qInv),
            CRTValues: new slice<CRTValue>(0)
        )
    ));
    // non-nil, to match Precompute
    return (key, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaMultiPrimeRsaIsˢ = "crypto/rsa: multi-prime RSA is not allowed in FIPS 140-only mode"u8;
internal static readonly @string cryptoRsaˢ = "crypto/rsa: GenerateMultiPrimeKey: nprimes must be >= 2"u8;
internal static readonly @string cryptoRsaTooFewPrimesOfˢ = "crypto/rsa: too few primes of given length to generate an RSA key"u8;

// GenerateMultiPrimeKey generates a multi-prime RSA keypair of the given bit
// size and the given random source.
//
// Table 1 in "[On the Security of Multi-prime RSA]" suggests maximum numbers of
// primes for a given bit size.
//
// Although the public keys are compatible (actually, indistinguishable) from
// the 2-prime case, the private keys are not. Thus it may not be possible to
// export multi-prime private keys in certain formats or to subsequently import
// them into other code.
//
// This package does not implement CRT optimizations for multi-prime RSA, so the
// keys with more than two primes will have worse performance.
//
// Deprecated: The use of this function with a number of primes different from
// two is not recommended for the above security, compatibility, and performance
// reasons. Use [GenerateKey] instead.
//
// [On the Security of Multi-prime RSA]: http://www.cacr.math.uwaterloo.ca/techreports/2006/cacr2006-16.pdf
public static (ж<PrivateKey>, error) GenerateMultiPrimeKey(io.Reader random, nint nprimes, nint bits) {
    if (nprimes == 2) {
        return GenerateKey(random, bits);
    }
    if (fips140only.Enabled) {
        return (default!, errors.New(cryptoRsaMultiPrimeRsaIsˢ));
    }
    randutil.MaybeReadByte(random);
    var priv = @new<PrivateKey>();
    priv.Value.E = 65537;
    if (nprimes < 2) {
        return (default!, errors.New(cryptoRsaˢ));
    }
    if (bits < 64) {
        var primeLimit = (float64)(((uint64)1).Lsh((nuint)(quo(bits, nprimes))));
        // pi approximates the number of primes less than primeLimit
        var pi = primeLimit / (math.Log(primeLimit) - 1D);
        // Generated primes start with 11 (in binary) so we can only
        // use a quarter of them.
        pi /= 4D;
        // Use a factor of two to ensure that key generation terminates
        // in a reasonable amount of time.
        pi /= 2D;
        if (pi <= (float64)nprimes) {
            return (default!, errors.New(cryptoRsaTooFewPrimesOfˢ));
        }
    }
    var primes = new slice<ж<bigꓸInt>>(nprimes);
NextSetOfPrimes:
    while (ᐧ) {
        nint todo = bits;
        // crypto/rand should set the top two bits in each prime.
        // Thus each prime has the form
        //   p_i = 2^bitlen(p_i) × 0.11... (in base 2).
        // And the product is:
        //   P = 2^todo × α
        // where α is the product of nprimes numbers of the form 0.11...
        //
        // If α < 1/2 (which can happen for nprimes > 2), we need to
        // shift todo to compensate for lost bits: the mean value of 0.11...
        // is 7/8, so todo + shift - nprimes * log2(7/8) ~= bits - 1/2
        // will give good results.
        if (nprimes >= 7) {
            todo += (nprimes - 2) / 5;
        }
        for (nint i = 0; i < nprimes; i++) {
            error err = default!;
            (primes[i], err) = rand.Prime(random, quo(todo, (nprimes - i)));
            if (err != default!) {
                return (default!, err);
            }
            todo -= primes[i].BitLen();
        }
        // Make sure that primes is pairwise unequal.
        foreach (var (i, prime) in primes) {
            for (nint j = 0; j < i; j++) {
                if (prime.Cmp(primes[j]) == 0) {
                    goto continue_NextSetOfPrimes;
                }
            }
        }
        var n = @new<bigꓸInt>().Set(bigOne);
        var totient = @new<bigꓸInt>().Set(bigOne);
        var pminus1 = @new<bigꓸInt>();
        foreach (var (_, prime) in primes) {
            n.Mul(n, prime);
            pminus1.Sub(prime, bigOne);
            totient.Mul(totient, pminus1);
        }
        if (n.BitLen() != bits) {
            // This should never happen for nprimes == 2 because
            // crypto/rand should set the top two bits in each prime.
            // For nprimes > 2 we hope it does not happen often.
            goto continue_NextSetOfPrimes;
        }
        priv.Value.D = @new<bigꓸInt>();
        var e = big.NewInt((int64)(~priv).E);
        var ok = (~priv).D.ModInverse(e, totient);
        if (ok != nil) {
            priv.Value.Primes = primes;
            priv.Value.N = n;
            break;
        }
continue_NextSetOfPrimes:;
    }
break_NextSetOfPrimes:;
    priv.Precompute();
    {
        var err = priv.Validate(); if (err != default!) {
            return (default!, err);
        }
    }
    return (priv, default!);
}

// ErrMessageTooLong is returned when attempting to encrypt or sign a message
// which is too large for the size of the key. When using [SignPSS], this can also
// be returned if the size of the salt is too large.
public static error ErrMessageTooLong = errors.New("crypto/rsa: message too long for RSA key size"u8);

// ErrDecryption represents a failure to decrypt a message.
// It is deliberately vague to avoid adaptive attacks.
public static error ErrDecryption = errors.New("crypto/rsa: decryption error"u8);

// ErrVerification represents a failure to verify a signature.
// It is deliberately vague to avoid adaptive attacks.
public static error ErrVerification = errors.New("crypto/rsa: verification error"u8);

// Precompute performs some calculations that speed up private key operations
// in the future. It is safe to run on non-validated private keys.
[GoRecv] public static void Precompute(this ref PrivateKey priv) {
    if (priv.Precomputed.fips != nil) {
        return;
    }
    var (precomputed, err) = priv.precompute();
    if (err != default!) {
        // We don't have a way to report errors, so just leave the key
        // unmodified. Validate will re-run precompute.
        return;
    }
    priv.Precomputed = precomputed;
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaMissingPrivateˢ = "crypto/rsa: missing private exponent"u8;
internal static readonly @string cryptoRsaPrimePIsNilˢ = "crypto/rsa: prime P is nil"u8;
internal static readonly @string cryptoRsaPrimeQIsNilˢ = "crypto/rsa: prime Q is nil"u8;

[GoRecv] internal static (PrecomputedValues, error) precompute(this ref PrivateKey priv) {
    PrecomputedValues precomputed = default!;
    if (priv.N == nil) {
        return (precomputed, errors.New(cryptoRsaMissingPublicˢ));
    }
    if (priv.D == nil) {
        return (precomputed, errors.New(cryptoRsaMissingPrivateˢ));
    }
    if (len(priv.Primes) != 2) {
        return priv.precomputeLegacy();
    }
    if (priv.Primes[0] == nil) {
        return (precomputed, errors.New(cryptoRsaPrimePIsNilˢ));
    }
    if (priv.Primes[1] == nil) {
        return (precomputed, errors.New(cryptoRsaPrimeQIsNilˢ));
    }
    // If the CRT values are already set, use them.
    if (priv.Precomputed.Dp != nil && priv.Precomputed.Dq != nil && priv.Precomputed.Qinv != nil) {
        var (kΔ1, errΔ1) = rsa.NewPrivateKeyWithPrecomputation(priv.N.Bytes(), priv.E, priv.D.Bytes(),
            priv.Primes[0].Bytes(), priv.Primes[1].Bytes(),
            priv.Precomputed.Dp.Bytes(), priv.Precomputed.Dq.Bytes(), priv.Precomputed.Qinv.Bytes());
        if (errΔ1 != default!) {
            return (precomputed, errΔ1);
        }
        precomputed = priv.Precomputed;
        precomputed.fips = kΔ1;
        precomputed.CRTValues = new slice<CRTValue>(0);
        return (precomputed, default!);
    }
    var (k, err) = rsa.NewPrivateKey(priv.N.Bytes(), priv.E, priv.D.Bytes(),
        priv.Primes[0].Bytes(), priv.Primes[1].Bytes());
    if (err != default!) {
        return (precomputed, err);
    }
    precomputed.fips = k;
    var (_, _, _, _, _, dP, dQ, qInv) = k.Export();
    precomputed.Dp = @new<bigꓸInt>().SetBytes(dP);
    precomputed.Dq = @new<bigꓸInt>().SetBytes(dQ);
    precomputed.Qinv = @new<bigꓸInt>().SetBytes(qInv);
    precomputed.CRTValues = new slice<CRTValue>(0);
    return (precomputed, default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoRsaPrimeFactorIsˢ = "crypto/rsa: prime factor is nil"u8;
internal static readonly @string cryptoRsaPrimeFactorIs1ˢ = "crypto/rsa: prime factor is <= 1"u8;
internal static readonly @string cryptoRsaPrimeFactorsAreˢ = "crypto/rsa: prime factors are not relatively prime"u8;

[GoRecv] internal static (PrecomputedValues, error) precomputeLegacy(this ref PrivateKey priv) {
    PrecomputedValues precomputed = default!;
    var (k, err) = rsa.NewPrivateKeyWithoutCRT(priv.N.Bytes(), priv.E, priv.D.Bytes());
    if (err != default!) {
        return (precomputed, err);
    }
    precomputed.fips = k;
    if (len(priv.Primes) < 2) {
        return (precomputed, default!);
    }
    // Ensure the Mod and ModInverse calls below don't panic.
    foreach (var (_, prime) in priv.Primes) {
        if (prime == nil) {
            return (precomputed, errors.New(cryptoRsaPrimeFactorIsˢ));
        }
        if (prime.Cmp(bigOne) <= 0) {
            return (precomputed, errors.New(cryptoRsaPrimeFactorIs1ˢ));
        }
    }
    precomputed.Dp = @new<bigꓸInt>().Sub(priv.Primes[0], bigOne);
    precomputed.Dp.Mod(priv.D, precomputed.Dp);
    precomputed.Dq = @new<bigꓸInt>().Sub(priv.Primes[1], bigOne);
    precomputed.Dq.Mod(priv.D, precomputed.Dq);
    precomputed.Qinv = @new<bigꓸInt>().ModInverse(priv.Primes[1], priv.Primes[0]);
    if (precomputed.Qinv == nil) {
        return (precomputed, errors.New(cryptoRsaPrimeFactorsAreˢ));
    }
    var r = @new<bigꓸInt>().Mul(priv.Primes[0], priv.Primes[1]);
    precomputed.CRTValues = new slice<CRTValue>(len(priv.Primes) - 2);
    for (nint i = 2; i < len(priv.Primes); i++) {
        var prime = priv.Primes[i];
        var values = Ꮡ(precomputed.CRTValues, i - 2);
        values.Value.Exp = @new<bigꓸInt>().Sub(prime, bigOne);
        (~values).Exp.Mod(priv.D, (~values).Exp);
        values.Value.R = @new<bigꓸInt>().Set(r);
        values.Value.Coeff = @new<bigꓸInt>().ModInverse(r, prime);
        if ((~values).Coeff == nil) {
            return (precomputed, errors.New(cryptoRsaPrimeFactorsAreˢ));
        }
        r.Mul(r, prime);
    }
    return (precomputed, default!);
}

internal static (ж<rsaꓸPublicKey>, error) fipsPublicKey(ref PublicKey pub) {
    var (N, err) = bigmod.NewModulus(pub.N.Bytes());
    if (err != default!) {
        return (default!, err);
    }
    return (Ꮡ(new rsaꓸPublicKey(N: N, E: pub.E)), default!);
}

internal static (ж<rsa.PrivateKey>, error) fipsPrivateKey(ж<PrivateKey> Ꮡpriv) {
    ref var priv = ref Ꮡpriv.DerefOrNull();

    if (priv.Precomputed.fips != nil) {
        return (priv.Precomputed.fips, default!);
    }
    var (precomputed, err) = priv.precompute();
    if (err != default!) {
        return (default!, err);
    }
    return (precomputed.fips, default!);
}

} // end rsa_package
