// Symbols.cs - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// Use of this source code is governed by an MIT-style license
// that can be found in the LICENSE file.

// THIS FILE IS AUTO-GENERATED by gensymbols from the canonical go2cs symbol table
// src/core/go2cs/symbols.json (its Go projection is src/go2cs/symbols.go). DO NOT EDIT
// this file directly - edit symbols.json and regenerate both projections with
// `go generate .` from src/go2cs, or run src/check-symbol-sync.ps1.

namespace go2cs;

public static class Symbols
{
    public const string PackageSuffix = "_package";

    // Extended Unicode characters are being used to help avoid conflicts with Go identifiers for
    // symbols, markers, intermediate and temporary variables. These characters have to be valid
    // C# identifiers, i.e., Unicode letter characters, decimal digit characters, connecting
    // characters, combining characters, or formatting characters. Some character variants will
    // be better suited to different fonts or display environments. Defaults have been chosen
    // based on better appearance with common Visual Studio code fonts, e.g., "Cascadia Mono".
    public const string PointerPrefix = "ж";
    // BoxConstructPrefix is the spelling of the STANDARD-KIND box class at CONSTRUCTION
    // positions - the B1 role split (docs/phase4/DESIGN-zh-box-b1.md §6, OQ-1): a DECLARED
    // pointer type renders PointerPrefix (the polymorphic base under the per-kind split) and
    // never changes; a CONSTRUCTED box must name the concrete standard-kind class once the base
    // goes abstract. Equal to PointerPrefix until B2-I3 flips it, so introducing the role is
    // byte-inert (CNR-proven at B2-I2).
    // 
    // The 67-site audit this constant closes (B2-I2): every other PointerPrefix use in the
    // converter is a DECLARED type render (convStarExpr, iifeOperations,
    // constraintOperations:1053, typeNameResolution:1474, visitFuncDecl, and the heap()
    // out-parameter declarations - the out var's type remains the base; golib's heap mints the
    // concrete kind internally), an ADAPTER-NAME component (adapterNameCollisions,
    // interfaceConversion, constraintOperations:1408 - the glyph inside adapter class names, a
    // naming convention, not a box type), a string PARSE (the CutPrefix/HasPrefix family -
    // declared types keep their spelling, so parsers are unchanged), or the
    // identifier-sanitization list. The ONE construction-position emitter is
    // globalAddressOperations.go's package-level `= new(...)` (target-typed today, so nothing
    // renders here yet); the corpus's other explicit-new occurrences are 304 array-ELEMENT-type
    // positions (declared role, unchanged forever) and ~40 golib/hand-own/generator
    // constructions edited by hand at I3.
    public const string BoxConstructPrefix = "StandardBox";
    public const string AddressPrefix = "Ꮡ";
    public const string ShadowVarMarker = "Δ";
    public const string TypeAliasDot = "ꓸ";
    public const string EllipsisOperator = "ꓸꓸꓸ";
    public const string CapturedVarMarker = "ʗ";
    public const string TempVarMarker = "ᴛ";
    // Suffixes the name of a hoisted string-literal field (`trueˢ`) - the one-per-package
    // `static readonly` @string a Go RODATA literal is materialized into (see Tier C of
    // docs/phase4/DESIGN-string-literal-allocation.md).
    public const string HoistedLiteralMarker = "ˢ";
    // Composes VALUE-form foreign interface adapter class names ({Struct}ᴠ{Iface}) - the
    // value sibling of the ж-composed pointer adapters (wraps a COPY, Go value semantics).
    public const string ValueAdapterInfix = "ᴠ";
    // Channel operator method names - the Go-visual send/receive member forms the converter
    // emits ("ch.ᐸꟷ(val)" for "ch <- val", "ch.ꟷᐳ(out val)" for "val := <-ch"); the named
    // channel wrapper template forwards these to its underlying channel<T>.
    public const string ChannelLeftOp = "ᐸꟷ";
    public const string ChannelRightOp = "ꟷᐳ";
    // NilDeferringDerefAccessor is the golib ж<T> extension method used in place of `.Value`
    // for EVERY direct-ж pointer entry deref alias - a RECEIVER and a PARAMETER alike, in the
    // converter's own preamble, in the pointer-reassignment re-alias, and in the RecvGenerator
    // bridge that reaches a `ref T` receiver through a box. Go's nil rule does not distinguish
    // the two: a nil `*T` may be passed to a function exactly as it may be the receiver of a
    // method, the body RUNS, and the panic happens only where the body actually dereferences
    // the pointee, so the alias must not deref at ENTRY. This binds a NULL ref: legal to hold,
    // and the first read/write through it raises the nil-pointer panic with Go's own message,
    // at Go's own point - after any side effect the body performed first. That is what makes
    // it unconditional and analysis-FREE, where each accessor it replaced needed a proof the
    // converter could not have: `.Value` needed "this pointer is never nil", and the retired
    // nil-SAFE accessor (a shared default(T) slot, which made a deref Go says must panic read
    // a silent zero instead) needed "this body provably guards". Includes `()` as it is a
    // method call.
    public const string NilDeferringDerefAccessor = "DerefOrNull()";
    // The -tests package-init hook: the erasable classic-partial method a production
    // package_init.cs static ctor ends with when converting under -tests, IMPLEMENTED by the
    // internal test variant's relocated-initializer file (go2cs initOrderOperations.go /
    // writeTestVariantInitFile). The PartialStubGenerator must never stub it - an
    // unimplemented hook is erased by C# by design (the production assembly excludes the
    // *_test.cs implementation), and a throwing stub would detonate the package class's
    // static ctor for every consumer of the production assembly. The doubled marker keeps
    // the name out of the relocated-var method space ("init" + marker + <var name>).
    public const string PackageTestInitHookMethod = "initᴛᴛtests";

    // ValueCloneMethod is the generated deep-copy method on a converted Go STRUCT that carries
    // fixed-size ARRAY fields (see GoValueCloneAttribute): a plain C# struct copy would leave those
    // arrays aliased, so every Go by-value copy site calls this instead. Deliberately NOT named
    // `Clone` — a Go type may declare its own `Clone` method (vendored x/crypto/sha3's `state`), which
    // converts to an extension method on the package class, and an instance member of the same name
    // SHADOWS it (the recv-overload forwarder then bound to the wrong return type). The Δ prefix is
    // the same collision-avoidance marker the promoted-accessor rename uses. Arrays keep golib's own
    // `Clone()` — see valueCloneSuffix.
    public const string ValueCloneMethod = "ΔClone";

    // RangeSnapshotMethod is the COPY a `for i, v := range a` over an array VALUE iterates. Go
    // evaluates a range expression once, so the loop reads a snapshot and a write to the container
    // inside the body is invisible to later iterations; the emitted array is a struct over a shared
    // T[], so the operand has to be copied. It is deliberately NOT the `Clone()` every other Go array
    // value-copy site takes: a copy that cannot outlive the loop is Go's INLINE, stack-resident copy,
    // which costs zero mallocs and zero TotalAlloc, and charging it through golib's allocation counter
    // would make the counter disagree with the runtime.MemStats.Mallocs it mirrors. golib's
    // array<T>.ΔRangeSnapshot() therefore rents a pooled buffer and returns it when the loop ends. The
    // Δ prefix is the same collision-avoidance marker ValueCloneMethod carries, and for the same
    // reason — a Go type may declare a method of any name.
    public const string RangeSnapshotMethod = "ΔRangeSnapshot";
}
