#!/usr/bin/env bash
# Writes RegBulk.cs: one method registering N distinct u8 literals, the shape a generated module
# initializer would take for the corpus's largest module (net/http's tests: 3,805 distinct literals
# at 47e088d3d7). Lengths cycle 1..40 bytes. Regenerate with: bash gen-regbulk.sh 3805 > RegBulk.cs
n=${1:-3805}
echo '// GENERATED by gen-regbulk.sh -- the module-initializer shape for §8.1.x, timed by --regcost.'
echo 'static class RegBulk'
echo '{'
echo '    public const int Count = '"$n"';'
echo '    public static void Run()'
echo '    {'
awk -v n="$n" 'BEGIN { pad = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN";
  for (i = 0; i < n; i++) { len = 1 + (i % 40); k = sprintf("%x.", i); s = k substr(pad, 1, len > length(k) ? len - length(k) : 0);
    printf "        Lit2.Register(\"%s\"u8);\n", s } }'
echo '    }'
echo '}'
